//! `Dl4jModelReader`: a word2vec model as Deeplearning4j saves it -- a zip
//! whose `syn0*` entry is text: a `dictionarySize vectorDimension` header,
//! then one line per term, `term v1 v2 ...` separated by single spaces, the
//! term either raw or `B64:<base64>` (decided by the first term line).
//!
//! The zip is read the way `java.util.zip.ZipInputStream` reads it, entry
//! by entry from the front: local headers, stored or deflated data, a data
//! descriptor after a deflated entry whose sizes were not known up front.
//! Lines are `BufferedReader.readLine`'s (`\n`, `\r` or `\r\n`), fields are
//! `String.split(" ")`'s (trailing empty fields dropped), numbers are
//! `Integer.parseInt` and `Float.parseFloat` (decimal forms; a hexadecimal
//! float is refused), base64 is `Base64.getDecoder()`'s.

use super::model::Word2VecModel;
use crate::{Error, Result};

/// `Dl4jModelReader.MODEL_FILE_NAME_PREFIX`.
const MODEL_FILE_NAME_PREFIX: &str = "syn0";

fn bad(msg: impl Into<String>) -> Error {
    Error::IllegalArgument(msg.into())
}

/// `new Dl4jModelReader(stream).read()` over the zip's bytes.
///
/// # Errors
/// `IllegalArgument` for a zip without a `syn0` entry (Java's message), a
/// malformed zip or model text (Java's `ZipException`, `IOException`,
/// `NumberFormatException` or `RuntimeException`), or a vector of the wrong
/// size (Java's message).
pub fn read_dl4j_model(zip: &[u8]) -> Result<Word2VecModel> {
    let mut at = 0;
    while let Some((name, data, next)) = next_entry(zip, at)? {
        if name.starts_with(MODEL_FILE_NAME_PREFIX) {
            return parse_model(&String::from_utf8_lossy(&data));
        }
        at = next;
    }
    Err(bad(format!(
        "Cannot read Dl4j word2vec model - '{p}' file is missing in the zip. '{p}' is a \
         mandatory file containing the mapping between terms and vectors generated by the DL4j \
         library.",
        p = MODEL_FILE_NAME_PREFIX
    )))
}

fn u16_at(b: &[u8], i: usize) -> Result<usize> {
    b.get(i..i + 2)
        .map(|s| usize::from(u16::from_le_bytes([s[0], s[1]])))
        .ok_or_else(|| bad("truncated zip"))
}

fn u32_at(b: &[u8], i: usize) -> Result<usize> {
    b.get(i..i + 4)
        .map(|s| u32::from_le_bytes([s[0], s[1], s[2], s[3]]) as usize)
        .ok_or_else(|| bad("truncated zip"))
}

/// The zip entry whose local header starts at `at`: its name, its
/// uncompressed bytes and where the next header starts; `None` at the
/// central directory (or the end).
fn next_entry(z: &[u8], at: usize) -> Result<Option<(String, Vec<u8>, usize)>> {
    if z.len() < at + 4 || u32_at(z, at)? != 0x0403_4B50 {
        return Ok(None);
    }
    let flags = u16_at(z, at + 6)?;
    let method = u16_at(z, at + 8)?;
    let compressed = u32_at(z, at + 18)?;
    let name_len = u16_at(z, at + 26)?;
    let extra_len = u16_at(z, at + 28)?;
    let start = at + 30 + name_len + extra_len;
    let name = z
        .get(at + 30..at + 30 + name_len)
        .map(|n| String::from_utf8_lossy(n).into_owned())
        .ok_or_else(|| bad("truncated zip"))?;
    let rest = z.get(start..).ok_or_else(|| bad("truncated zip"))?;
    let descriptor = flags & 8 != 0;
    let (data, used) = match method {
        0 if !descriptor => (
            rest.get(..compressed)
                .ok_or_else(|| bad("truncated zip"))?
                .to_vec(),
            compressed,
        ),
        8 => {
            let mut state =
                miniz_oxide::inflate::stream::InflateState::new(miniz_oxide::DataFormat::Raw);
            let mut out = Vec::new();
            let mut buf = vec![0u8; 64 * 1024];
            let mut used = 0;
            loop {
                let r = miniz_oxide::inflate::stream::inflate(
                    &mut state,
                    &rest[used..],
                    &mut buf,
                    miniz_oxide::MZFlush::None,
                );
                used += r.bytes_consumed;
                out.extend_from_slice(&buf[..r.bytes_written]);
                match r.status {
                    Ok(miniz_oxide::MZStatus::StreamEnd) => break,
                    Ok(_) if r.bytes_consumed > 0 || r.bytes_written > 0 => {}
                    _ => return Err(bad(format!("invalid deflated data in zip entry {name}"))),
                }
            }
            (out, used)
        }
        _ => {
            return Err(bad(format!(
                "unsupported zip entry {name}: compression method {method}"
            )))
        }
    };
    let mut next = start + used;
    if descriptor {
        // An optional signature, then CRC-32 and the two sizes.
        next += if u32_at(z, next)? == 0x0807_4B50 {
            16
        } else {
            12
        };
    }
    Ok(Some((name, data, next)))
}

/// `BufferedReader.readLine` over the whole text.
fn read_lines(text: &str) -> Vec<&str> {
    let mut lines = Vec::new();
    let b = text.as_bytes();
    let (mut start, mut i) = (0, 0);
    while i < b.len() {
        if b[i] == b'\n' || b[i] == b'\r' {
            lines.push(&text[start..i]);
            if b[i] == b'\r' && b.get(i + 1) == Some(&b'\n') {
                i += 1;
            }
            start = i + 1;
        }
        i += 1;
    }
    if start < b.len() {
        lines.push(&text[start..]);
    }
    lines
}

/// `String.split(" ")`: trailing empty strings removed.
fn split_space(line: &str) -> Vec<&str> {
    let mut parts: Vec<&str> = line.split(' ').collect();
    while parts.last() == Some(&"") {
        parts.pop();
    }
    parts
}

fn parse_model(text: &str) -> Result<Word2VecModel> {
    let lines = read_lines(text);
    let header = split_space(lines.first().copied().unwrap_or(""));
    let int = |s: Option<&&str>| -> Result<usize> {
        let s = s.copied().unwrap_or("");
        java_parse_int(s)
            .and_then(|v| usize::try_from(v).ok())
            .ok_or_else(|| bad(format!("For input string: \"{s}\"")))
    };
    let dictionary_size = int(header.first())?;
    let vector_dimension = int(header.get(1))?;
    let mut model = Word2VecModel::new(dictionary_size, vector_dimension);
    let mut b64 = false;
    for (i, line) in lines.iter().enumerate().skip(1) {
        let tokens = split_space(line);
        let first = tokens.first().copied().unwrap_or("");
        if i == 1 {
            // `tokens[0].substring(0, 3).toLowerCase(Locale.ROOT)`.
            let prefix: Vec<u16> = first.encode_utf16().take(3).collect();
            if prefix.len() < 3 {
                return Err(bad(format!("begin 0, end 3, length {}", prefix.len())));
            }
            b64 = String::from_utf16_lossy(&prefix).eq_ignore_ascii_case("b64");
        }
        let term = if b64 {
            decode_b64_term(first)?
        } else {
            first.as_bytes().to_vec()
        };
        let found = tokens.len().saturating_sub(1);
        if found != vector_dimension {
            return Err(bad(format!(
                "Word2Vec model file corrupted. Declared vectors of size {vector_dimension} but \
                 found vector of size {found} for word {first} ({})",
                String::from_utf8_lossy(&term)
            )));
        }
        let vector = tokens[1..]
            .iter()
            .map(|t| java_parse_float(t).ok_or_else(|| bad(format!("For input string: \"{t}\""))))
            .collect::<Result<Vec<f32>>>()?;
        model.add_term_and_vector(term, vector)?;
    }
    Ok(model)
}

/// `Integer.parseInt`: optional sign, ASCII digits, in `i32` range.
fn java_parse_int(s: &str) -> Option<i32> {
    let digits = s.strip_prefix(['+', '-']).unwrap_or(s);
    if digits.is_empty() || !digits.bytes().all(|b| b.is_ascii_digit()) {
        return None;
    }
    s.parse().ok()
}

/// `Float.parseFloat` of a decimal string: Java's `trim()`, then an
/// optional sign and `NaN`, `Infinity` or digits with an optional point and
/// exponent, then an optional `f`/`F`/`d`/`D`. Correctly rounded, as Java's.
pub(super) fn java_parse_float(s: &str) -> Option<f32> {
    let s = s.trim_matches(|c: char| c <= ' ');
    let (neg, body) = match s.as_bytes().first() {
        Some(b'-') => (true, &s[1..]),
        Some(b'+') => (false, &s[1..]),
        _ => (false, s),
    };
    let v = match body {
        "NaN" => f32::NAN,
        "Infinity" => f32::INFINITY,
        _ => {
            let num = body.strip_suffix(['f', 'F', 'd', 'D']).unwrap_or(body);
            let b = num.as_bytes();
            let mantissa = b
                .iter()
                .take_while(|c| c.is_ascii_digit() || **c == b'.')
                .count();
            let m = &b[..mantissa];
            let points = m.iter().filter(|&&c| c == b'.').count();
            if points > 1 || m.iter().all(|&c| c == b'.') {
                return None;
            }
            let exp = &b[mantissa..];
            if !exp.is_empty() {
                let e = exp.strip_prefix(b"e").or_else(|| exp.strip_prefix(b"E"))?;
                let e = e
                    .strip_prefix(b"+")
                    .or_else(|| e.strip_prefix(b"-"))
                    .unwrap_or(e);
                if e.is_empty() || !e.iter().all(u8::is_ascii_digit) {
                    return None;
                }
            }
            num.parse::<f32>().ok()?
        }
    };
    Some(if neg { -v } else { v })
}

/// `Dl4jModelReader.decodeB64Term`: `Base64.getDecoder().decode(term.substring(4))`.
fn decode_b64_term(term: &str) -> Result<Vec<u8>> {
    let units: Vec<u16> = term.encode_utf16().collect();
    let rest = units
        .get(4..)
        .ok_or_else(|| bad(format!("begin 4, end {0}, length {0}", units.len())))?;
    base64_decode(rest).ok_or_else(|| bad(format!("Illegal base64 term: {term}")))
}

/// `Base64.getDecoder().decode`: the RFC 4648 alphabet, `=` padding
/// optional but ending the data, a lone final character refused.
fn base64_decode(s: &[u16]) -> Option<Vec<u8>> {
    let val = |c: u16| -> Option<u32> {
        Some(match u8::try_from(c).ok()? {
            c @ b'A'..=b'Z' => u32::from(c - b'A'),
            c @ b'a'..=b'z' => u32::from(c - b'a') + 26,
            c @ b'0'..=b'9' => u32::from(c - b'0') + 52,
            b'+' => 62,
            b'/' => 63,
            _ => return None,
        })
    };
    let pad = s.iter().position(|&c| c == u16::from(b'='));
    let data = &s[..pad.unwrap_or(s.len())];
    if let Some(p) = pad {
        // Padding completes the last quantum exactly, and nothing follows it.
        let n = s.len() - p;
        let need = match data.len() % 4 {
            2 => 2,
            3 => 1,
            _ => return None,
        };
        if n != need || s[p..].iter().any(|&c| c != u16::from(b'=')) {
            return None;
        }
    }
    if data.len() % 4 == 1 {
        return None;
    }
    let mut out = Vec::with_capacity(data.len() * 3 / 4);
    for chunk in data.chunks(4) {
        let mut acc = 0u32;
        for &c in chunk {
            acc = (acc << 6) | val(c)?;
        }
        acc <<= 6 * (4 - chunk.len() as u32);
        let bytes = acc.to_be_bytes();
        out.extend_from_slice(&bytes[1..chunk.len()]);
    }
    Some(out)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn u(s: &str) -> Vec<u16> {
        s.encode_utf16().collect()
    }

    #[test]
    fn base64_as_java_decodes_it() {
        assert_eq!(base64_decode(&u("aGVsbG8=")), Some(b"hello".to_vec()));
        assert_eq!(base64_decode(&u("aGVsbG8")), Some(b"hello".to_vec()));
        assert_eq!(base64_decode(&u("aGk=")).as_deref(), Some(&b"hi"[..]));
        assert_eq!(base64_decode(&u("aGk")).as_deref(), Some(&b"hi"[..]));
        assert_eq!(base64_decode(&u("")), Some(Vec::new()));
        assert_eq!(base64_decode(&u("a")), None);
        assert_eq!(base64_decode(&u("aGk==")), None);
        assert_eq!(base64_decode(&u("aGVs=")), None);
        assert_eq!(base64_decode(&u("aG=k")), None);
        assert_eq!(base64_decode(&u("a-b_")), None);
        assert_eq!(base64_decode(&u("+/+/")), Some(vec![0xFB, 0xFF, 0xBF]));
        assert_eq!(base64_decode(&[0x41, 0x100, 0x41, 0x41]), None);
    }

    #[test]
    fn floats_and_ints_as_java_parses_them() {
        assert_eq!(java_parse_float(" 1.5 "), Some(1.5));
        assert_eq!(java_parse_float("-2e3f"), Some(-2000.0));
        assert_eq!(java_parse_float(".5D"), Some(0.5));
        assert_eq!(java_parse_float("5."), Some(5.0));
        assert_eq!(java_parse_float("1E+2"), Some(100.0));
        assert!(java_parse_float("NaN").unwrap().is_nan());
        assert_eq!(java_parse_float("-Infinity"), Some(f32::NEG_INFINITY));
        for bad in [
            "", ".", "1..2", "inf", "nan", "1e", "1e+", "0x1p3", "1f2", "--1", "1 2",
        ] {
            assert_eq!(java_parse_float(bad), None, "{bad}");
        }
        assert_eq!(java_parse_int("-12"), Some(-12));
        assert_eq!(java_parse_int("+7"), Some(7));
        for bad in ["", "-", "1.0", "99999999999", " 1"] {
            assert_eq!(java_parse_int(bad), None, "{bad}");
        }
    }

    #[test]
    fn lines_and_fields_as_java_splits_them() {
        assert_eq!(read_lines("a\nb\r\nc\rd"), ["a", "b", "c", "d"]);
        assert_eq!(read_lines("a\n\n"), ["a", ""]);
        assert_eq!(split_space("a b  "), ["a", "b"]);
        assert_eq!(split_space(" a"), ["", "a"]);
        assert!(split_space("").is_empty());
    }

    #[test]
    fn malformed_models_are_refused() {
        let err = |t: &str| parse_model(t).unwrap_err().to_string();
        assert!(err("x 2\n").contains("\"x\""));
        assert!(err("1\n").contains("\"\""));
        assert!(err("1 2\nab 1 2\n").contains("begin 0, end 3, length 2"));
        assert!(err("1 2\nB64 1 2\n").contains("begin 4, end 3"));
        assert!(err("1 2\nB64:!! 1 2\n").contains("Illegal base64"));
        assert!(
            err("1 2\nabc 1\n").contains("Declared vectors of size 2 but found vector of size 1")
        );
        assert!(err("1 2\nabc 1 x\n").contains("\"x\""));
        let m = parse_model("2 2\nb64:YQ== 1 0\nB64:Yg 0 1\n").unwrap();
        assert_eq!((m.term(0), m.term(1)), (&b"a"[..], &b"b"[..]));
        let m = parse_model("1 1\nword 2\n").unwrap();
        assert_eq!((m.term(0), m.vector(0)), (&b"word"[..], &[1.0f32][..]));
    }

    #[test]
    fn zips_without_a_model_or_malformed() {
        let missing = read_dl4j_model(&[]).unwrap_err().to_string();
        assert!(missing.contains("'syn0' file is missing"), "{missing}");
        // A stored entry named `other`, then the end.
        let mut z = vec![0x50, 0x4B, 3, 4, 20, 0, 0, 0, 0, 0];
        z.extend_from_slice(&[0; 8]);
        z.extend_from_slice(&1u32.to_le_bytes());
        z.extend_from_slice(&1u32.to_le_bytes());
        z.extend_from_slice(&5u16.to_le_bytes());
        z.extend_from_slice(&0u16.to_le_bytes());
        z.extend_from_slice(b"otherX");
        assert!(read_dl4j_model(&z)
            .unwrap_err()
            .to_string()
            .contains("missing"));
        let mut lzma = z.clone();
        lzma[8] = 14;
        assert!(read_dl4j_model(&lzma)
            .unwrap_err()
            .to_string()
            .contains("method 14"));
        let mut deflate = z.clone();
        deflate[8] = 8;
        assert!(read_dl4j_model(&deflate)
            .unwrap_err()
            .to_string()
            .contains("invalid deflated"));
        assert!(read_dl4j_model(&z[..29])
            .unwrap_err()
            .to_string()
            .contains("truncated"));
        let mut long = z.clone();
        long[18] = 9;
        assert!(read_dl4j_model(&long)
            .unwrap_err()
            .to_string()
            .contains("truncated"));
        let mut name = z.clone();
        name[26] = 200;
        assert!(read_dl4j_model(&name)
            .unwrap_err()
            .to_string()
            .contains("truncated"));
    }
}
