//! Differential test: `search_boolean_query` against the same real
//! `IndexWriter`-produced segment `term_query_fixtures.rs` already validates at the
//! single-`TermQuery` layer (`fixtures/data/blocktree_index/`, generated by
//! `fixtures/src/GenBlockTree.java`) -- this test proves the boolean-combination
//! layer built on top of that produces exactly the doc IDs real Lucene's own
//! `IndexSearcher.search(new BooleanQuery.Builder()..., collector)` would return,
//! computed here from the *same* real `PostingsEnum.nextDoc()`-derived doc sets
//! `manifest.properties` records (not hand-picked doc IDs), then combined with plain
//! set arithmetic (intersection/union/difference) matching real `BooleanQuery`
//! semantics -- see `lib.rs`'s `search_boolean_query` doc comment for the exact rule
//! this asserts against (`must` present => `should` is non-filtering; pure
//! `must_not` => matches nothing; etc).
//!
//! `body`'s three terms (`docFreq == 2` each, `DOCS_AND_FREQS`) give three known,
//! overlapping doc sets straight from the real fixture: `cat={0,2}`, `dog={0,1}`,
//! `bird={1,4}` -- enough to exercise conjunction, disjunction, and exclusion without
//! needing a new fixture (per the task's own preference for reusing existing fixture
//! data).

use lucene_codecs::blocktree;
use lucene_codecs::field_infos;
use lucene_codecs::postings::DocInput;
use lucene_search::{search_boolean_query, BooleanQuery, TermQuery, VecCollector};
use std::collections::BTreeSet;

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/blocktree_index/"
    )
    .to_string()
}

struct Manifest {
    kv: Vec<(String, String)>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenBlockTree)");
        let kv = text
            .lines()
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        Manifest { kv }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }

    /// The real `PostingsEnum`-derived doc set for `field.<field>.term.<term>`, as a
    /// `BTreeSet` so this test can compute expected boolean combinations with plain
    /// set arithmetic instead of re-deriving the merge algorithms under test.
    fn doc_set(&self, field: &str, term: &str) -> BTreeSet<i32> {
        self.get(&format!("field.{field}.term.{term}.postingsDocs"))
            .split(',')
            .map(|s| s.parse().unwrap())
            .collect()
    }
}

fn id_from_hex(hex: &str) -> [u8; 16] {
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

fn read_raw(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{}.raw", dir(), name)).unwrap_or_else(|_| panic!("missing {name}.raw"))
}

fn open_segment() -> (
    blocktree::BlockTreeFields,
    Vec<u8>,
    [u8; 16],
    String,
    Manifest,
) {
    let m = Manifest::load();
    let id = id_from_hex(m.get("id_hex"));
    let suffix = m.get("segment_suffix").to_string();
    let max_doc: i32 = m.get("max_doc").parse().unwrap();

    let fnm = read_raw(m.get("fnm_file_name"));
    let field_infos = field_infos::parse(&fnm, &id, "").expect("parse .fnm");

    let tim = read_raw(m.get("tim_file_name"));
    let tip = read_raw(m.get("tip_file_name"));
    let tmd = read_raw(m.get("tmd_file_name"));
    let fields = blocktree::open(&tim, &tip, &tmd, &field_infos, &id, &suffix, max_doc)
        .expect("open blocktree");

    let doc = read_raw(m.get("doc_file_name"));
    (fields, doc, id, suffix, m)
}

fn sorted_vec(set: BTreeSet<i32>) -> Vec<i32> {
    set.into_iter().collect()
}

#[test]
fn must_conjunction_matches_real_lucene_intersection() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected: BTreeSet<i32> = m
        .doc_set("body", "cat")
        .intersection(&m.doc_set("body", "dog"))
        .copied()
        .collect();
    assert_eq!(expected, BTreeSet::from([0]), "fixture sanity");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new()
        .with_must([TermQuery::new("body", "cat"), TermQuery::new("body", "dog")]);
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert_eq!(collector.docs, sorted_vec(expected));
}

#[test]
fn should_disjunction_matches_real_lucene_union() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected: BTreeSet<i32> = m
        .doc_set("body", "cat")
        .union(&m.doc_set("body", "bird"))
        .copied()
        .collect();
    assert_eq!(expected, BTreeSet::from([0, 1, 2, 4]), "fixture sanity");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new().with_should([
        TermQuery::new("body", "cat"),
        TermQuery::new("body", "bird"),
    ]);
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert_eq!(collector.docs, sorted_vec(expected));
}

#[test]
fn must_not_subtracts_from_the_must_conjunction() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected: BTreeSet<i32> = m
        .doc_set("body", "cat")
        .difference(&m.doc_set("body", "dog"))
        .copied()
        .collect();
    assert_eq!(expected, BTreeSet::from([2]), "fixture sanity");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new()
        .with_must([TermQuery::new("body", "cat")])
        .with_must_not([TermQuery::new("body", "dog")]);
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert_eq!(collector.docs, sorted_vec(expected));
}

#[test]
fn must_with_should_present_ignores_should_for_matching() {
    // Real BooleanQuery: once a MUST clause exists, SHOULD clauses are score-only
    // (no minimumNumberShouldMatch here) -- the matched set is `must`'s conjunction
    // alone, regardless of what `should` contains.
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected = m.doc_set("body", "cat"); // must=[cat] alone => {0,2}
    assert_eq!(expected, BTreeSet::from([0, 2]), "fixture sanity");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new()
        .with_must([TermQuery::new("body", "cat")])
        .with_should([TermQuery::new("body", "bird")]); // would add doc 1/4 if it mattered
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert_eq!(collector.docs, sorted_vec(expected));
}

#[test]
fn pure_must_not_query_matches_nothing() {
    // Real BooleanQuery.rewrite(): a query with only MUST_NOT clauses rewrites to
    // MatchNoDocsQuery ("pure negative BooleanQuery"), not "every doc except the
    // excluded ones".
    let (fields, doc, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new().with_must_not([TermQuery::new("body", "dog")]);
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert!(collector.docs.is_empty());
}

#[test]
fn empty_boolean_query_matches_nothing() {
    let (fields, doc, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new();
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert!(collector.docs.is_empty());
}

#[test]
fn must_across_multi_block_and_singleton_fields() {
    // Combines the multi-doc-block "big" field (docFreq 300) with the
    // singleton-in-term-dictionary "id" field to exercise the conjunction merge
    // across two structurally different postings representations. "big"'s
    // "everywhere" term covers docs 5..=304; "id2" is doc 2 alone, so they never
    // overlap.
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected: BTreeSet<i32> = m
        .doc_set("big", "everywhere")
        .intersection(&m.doc_set("id", "id2"))
        .copied()
        .collect();
    assert!(expected.is_empty(), "fixture sanity: disjoint doc sets");

    let mut collector = VecCollector::default();
    let query = BooleanQuery::new().with_must([
        TermQuery::new("big", "everywhere"),
        TermQuery::new("id", "id2"),
    ]);
    search_boolean_query(&fields, Some(&doc_in), None, &query, &mut collector).unwrap();
    assert!(collector.docs.is_empty());
}
