//! Differential test: `search_phrase_query` against the same real
//! `IndexWriter`-produced segment `crates/lucene-codecs/tests/
//! blocktree_fixtures.rs`'s `pos_field_positions_match_real_lucene_postings_enum`
//! test already validates at the positions-decode layer
//! (`fixtures/data/blocktree_index/`, `pos`/`.pos`/`.pay` files, generated by
//! `fixtures/src/GenBlockTree.java`) -- this test proves the *query layer* built on
//! top of that decode returns exactly the doc IDs a real
//! `IndexSearcher.search(new PhraseQuery(...), collector)` would for the same
//! phrase against the same segment.
//!
//! The exact-match (`slop == 0`) tests below reuse the existing `pos` field
//! (`IndexOptions.DOCS_AND_FREQS_AND_POSITIONS_AND_OFFSETS`) without extending the
//! generator: from `manifest.properties`, `alpha` occurs in doc 8555 at position 0
//! and in doc 8556 at positions 0 and 1; `beta` occurs only in doc 8555, at
//! position 1. That is already exactly the shape an exact phrase-query
//! differential test needs (an adjacent pair in one doc, a non-adjacent/absent
//! pair in another) -- see the `differential-testing` skill's "prefer reuse where
//! a fixture already fits" stance.
//!
//! The sloppy (`slop > 0`) test further down *does* extend `GenBlockTree.java`:
//! it adds one more doc (doc7, `alpha`@0 / `beta`@3, a real non-adjacent gap of
//! 2 "moves") plus a `field.pos.sloppyGap.realLuceneSlopResults` manifest key
//! recorded by *actually running* `IndexSearcher.search` with a real
//! `PhraseQuery.setSlop(n)` against that doc at generation time -- closing a
//! previously-flagged gap where the sloppy-matching formula had only been
//! checked against itself (hand-computed unit tests), never against real
//! Lucene's actual slop semantics for a known non-adjacent gap.

use lucene_codecs::blocktree;
use lucene_codecs::field_infos;
use lucene_codecs::postings::{DocInput, PayInput, PosInput};
use lucene_search::collector::TopDocsCollector;
use lucene_search::{search_phrase_query, search_phrase_query_scored, PhraseQuery, VecCollector};

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/blocktree_index/"
    )
    .to_string()
}

struct Manifest {
    kv: Vec<(String, String)>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenBlockTree)");
        let kv = text
            .lines()
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        Manifest { kv }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }
}

/// Independently derives, from `manifest.properties`' own
/// `field.pos.term.{term}.postingsDocs`/`.postingsFreqs`/`.occurrences` entries
/// (real `PostingsEnum` output, not anything this crate's implementation
/// produced), the set of doc IDs where `terms` occur at consecutive positions
/// in order -- i.e. the same expectation [`search_phrase_query`] is being
/// checked against, computed a second, independent way so a transcription
/// error in this test can't just mirror a bug in the implementation under
/// test.
///
/// `occurrences` is a flat list with no doc ID of its own: it's every
/// occurrence across every doc in `postingsDocs` order, `postingsFreqs[i]`
/// occurrences per doc `i` (matching how the generator/reader also chunk it;
/// see `blocktree_fixtures.rs`'s `pos_field_positions_match_real_lucene_postings_enum`
/// for the same chunking).
fn per_term_doc_positions(m: &Manifest, field: &str, term: &str) -> Vec<(i32, Vec<i32>)> {
    let docs: Vec<i32> = m
        .get(&format!("field.{field}.term.{term}.postingsDocs"))
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    let freqs: Vec<usize> = m
        .get(&format!("field.{field}.term.{term}.postingsFreqs"))
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    let occurrences: Vec<i32> = m
        .get(&format!("field.{field}.term.{term}.occurrences"))
        .split(';')
        .map(|occ| occ.split_once(',').unwrap().0.parse().unwrap())
        .collect();

    let mut result = Vec::with_capacity(docs.len());
    let mut idx = 0;
    for (doc, freq) in docs.into_iter().zip(freqs) {
        result.push((doc, occurrences[idx..idx + freq].to_vec()));
        idx += freq;
    }
    result
}

fn expected_phrase_docs(m: &Manifest, field: &str, terms: &[&str]) -> Vec<i32> {
    let per_term: Vec<Vec<(i32, Vec<i32>)>> = terms
        .iter()
        .map(|term| per_term_doc_positions(m, field, term))
        .collect();

    let mut by_doc: std::collections::BTreeMap<i32, Vec<Vec<i32>>> =
        std::collections::BTreeMap::new();
    for (term_index, term_docs) in per_term.iter().enumerate() {
        for (doc, positions) in term_docs {
            let entry = by_doc
                .entry(*doc)
                .or_insert_with(|| vec![Vec::new(); terms.len()]);
            entry[term_index] = positions.clone();
        }
    }

    by_doc
        .into_iter()
        .filter(|(_, per_term_positions)| {
            if per_term_positions.iter().any(Vec::is_empty) {
                return false;
            }
            per_term_positions[0].iter().any(|&base| {
                per_term_positions
                    .iter()
                    .enumerate()
                    .all(|(i, positions)| positions.contains(&(base + i as i32)))
            })
        })
        .map(|(doc, _)| doc)
        .collect()
}

fn id_from_hex(hex: &str) -> [u8; 16] {
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

fn read_raw(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{}.raw", dir(), name)).unwrap_or_else(|_| panic!("missing {name}.raw"))
}

/// Opens the fixture segment's term dictionary plus `.doc`/`.pos`/`.pay` files,
/// mirroring `term_query_fixtures.rs::open_segment` (no shared crate to hang a
/// common test helper off; `lucene-codecs` and `lucene-search` are separate
/// crates' test binaries).
type SegmentFixture = (
    blocktree::BlockTreeFields,
    Vec<u8>,
    Vec<u8>,
    Vec<u8>,
    [u8; 16],
    String,
    Manifest,
);

fn open_segment() -> SegmentFixture {
    let m = Manifest::load();
    let id = id_from_hex(m.get("id_hex"));
    let suffix = m.get("segment_suffix").to_string();
    let max_doc: i32 = m.get("max_doc").parse().unwrap();

    let fnm = read_raw(m.get("fnm_file_name"));
    let field_infos = field_infos::parse(&fnm, &id, "").expect("parse .fnm");

    let tim = read_raw(m.get("tim_file_name"));
    let tip = read_raw(m.get("tip_file_name"));
    let tmd = read_raw(m.get("tmd_file_name"));
    let fields = blocktree::open(&tim, &tip, &tmd, &field_infos, &id, &suffix, max_doc)
        .expect("open blocktree");

    let doc = read_raw(m.get("doc_file_name"));
    let pos = read_raw(m.get("pos_file_name"));
    let pay = read_raw(m.get("pay_file_name"));
    (fields, doc, pos, pay, id, suffix, m)
}

/// `"alpha beta"` on the `pos` field: real Lucene's `PhraseQuery` (via
/// `ExactPhraseScorer`) matches doc 8555 (alpha@0, beta@1 -- adjacent) but not doc
/// 8556 (alpha@0 and alpha@1, no "beta" at all in that doc).
#[test]
fn two_term_phrase_matches_real_lucenes_exact_phrase_scorer_doc_set() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &PhraseQuery::new("pos", ["alpha", "beta"]),
        &mut collector,
    )
    .unwrap_or_else(|e| panic!("search_phrase_query(pos, \"alpha beta\") failed: {e}"));

    let expected = expected_phrase_docs(&m, "pos", &["alpha", "beta"]);
    assert_eq!(
        expected,
        vec![8555],
        "sanity: manifest-derived expectation itself"
    );
    assert_eq!(collector.docs, expected);
}

/// Differential/consistency test for `search_phrase_query_scored` (task #29):
/// the phrase's BM25 score for doc 8555 must equal `idf(alpha) + idf(beta)`
/// (real `BM25Similarity`'s combined-term-statistics idf, see
/// `search_phrase_query_scored`'s doc comment) times `tfNorm(phraseFreq=1, ...)`
/// -- hand-derived independently from `manifest.properties`' real `docFreq`
/// values, not by trusting `similarity::score`/`idf`'s own already-separately-
/// tested unit tests, and cross-checked against the field's real `doc_count`
/// read from the opened segment.
#[test]
fn two_term_phrase_scored_matches_hand_computed_bm25_score() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut top = TopDocsCollector::new(10);
    search_phrase_query_scored(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &PhraseQuery::new("pos", ["alpha", "beta"]),
        None,
        &mut top,
    )
    .unwrap_or_else(|e| panic!("search_phrase_query_scored(pos, \"alpha beta\") failed: {e}"));

    let hits = top.top_docs();
    assert_eq!(
        hits.len(),
        1,
        "sanity: matches only doc 8555, see the matching test above"
    );
    assert_eq!(hits[0].doc_id, 8555);

    let doc_count = fields.field("pos").unwrap().doc_count as i64;
    let alpha_doc_freq: i64 = m.get("field.pos.term.alpha.docFreq").parse().unwrap();
    let beta_doc_freq: i64 = m.get("field.pos.term.beta.docFreq").parse().unwrap();
    assert_eq!(alpha_doc_freq, 3, "sanity: manifest-derived docFreq");
    assert_eq!(beta_doc_freq, 2, "sanity: manifest-derived docFreq");

    let idf = |doc_freq: i64| -> f64 {
        (1.0 + (doc_count as f64 - doc_freq as f64 + 0.5) / (doc_freq as f64 + 0.5)).ln()
    };
    let idf_sum = idf(alpha_doc_freq) + idf(beta_doc_freq);
    // phraseFreq == 1 (one alignment: alpha@0, beta@1), unnormed field length
    // fallback (no norms opened for `pos` in this test): k1=1.2, b=0.75.
    let k1 = 1.2_f64;
    let b = 0.75_f64;
    let tf_norm = 1.0 * (k1 + 1.0) / (1.0 + k1 * (1.0 - b + b));
    let expected = (idf_sum * tf_norm) as f32;

    assert!(
        (hits[0].score - expected).abs() < 1e-4,
        "got={} expected={}",
        hits[0].score,
        expected
    );
}

/// A single-term "phrase" degenerates to a plain term match: every doc containing
/// "alpha" (8555 and 8556), no position alignment needed at all.
#[test]
fn single_term_phrase_matches_every_doc_containing_the_term() {
    let (fields, doc, _pos, _pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        None,
        None,
        None,
        &PhraseQuery::new("pos", ["alpha"]),
        &mut collector,
    )
    .unwrap();

    let expected: Vec<i32> = m
        .get("field.pos.term.alpha.postingsDocs")
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    assert_eq!(
        expected,
        vec![8555, 8556, 8557],
        "sanity: manifest-derived expectation itself"
    );
    assert_eq!(collector.docs, expected);
}

/// A phrase term absent from the field entirely: no matches, not an error --
/// matches `PhraseQuery`'s real `null`-`Scorer` "term not found" outcome.
#[test]
fn phrase_with_a_missing_term_matches_nothing() {
    let (fields, doc, pos, pay, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &PhraseQuery::new("pos", ["alpha", "zzz-missing"]),
        &mut collector,
    )
    .unwrap();

    assert!(collector.docs.is_empty());
}

/// Cross-engine differential test for sloppy phrase matching, closing the gap
/// flagged in code review: the `phrase_matches_in_doc_sloppy` unit tests in
/// `lib.rs` only checked this port's own formula for self-consistency (hand-
/// computed "moves needed" arithmetic), never against real Lucene's actual
/// `PhraseQuery.setSlop(n)` behavior. `GenBlockTree.java`'s doc7 (`"pos"`
/// field: `alpha`@0, `beta`@3, a real, non-adjacent, manifest-recorded gap)
/// plus its own `field.pos.sloppyGap.realLuceneSlopResults` manifest key
/// (written by *actually running* `IndexSearcher.search` with a real
/// `PhraseQuery.Builder().add(alpha).add(beta).setSlop(n)` against this exact
/// fixture segment at generation time -- see `GenBlockTree.java`'s "Sloppy
/// PhraseQuery cross-engine ground truth" section) is the ground truth this
/// test checks `search_phrase_query`'s sloppy path against, not a value this
/// test derives independently. Real Lucene's recorded results for this gap
/// (`(3-0)-(2-1) = 2` moves needed): slop 0 and 1 do NOT match, slop 2, 3, 5
/// DO match -- i.e. the exact "below/exactly/above the required moves" shape
/// the review asked for.
#[test]
fn sloppy_phrase_gap_matches_real_lucenes_phrase_query_set_slop_at_every_tested_value() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let gap_doc: i32 = m.get("field.pos.sloppyGapDoc").parse().unwrap();
    assert_eq!(gap_doc, 8557, "sanity: manifest-recorded gap doc ID");
    let moves_needed: u32 = m.get("field.pos.sloppyGap.movesNeeded").parse().unwrap();
    assert_eq!(moves_needed, 2, "sanity: manifest-recorded gap size");

    // Parse "0:false,1:false,2:true,3:true,5:true" -- real Lucene's own
    // PhraseQuery.setSlop(n) match/no-match verdicts for this exact fixture,
    // recorded at fixture-generation time by GenBlockTree.java.
    let real_lucene: Vec<(u32, bool)> = m
        .get("field.pos.sloppyGap.realLuceneSlopResults")
        .split(',')
        .map(|pair| {
            let (slop, matched) = pair.split_once(':').unwrap();
            (slop.parse().unwrap(), matched.parse().unwrap())
        })
        .collect();
    assert_eq!(
        real_lucene,
        vec![(0, false), (1, false), (2, true), (3, true), (5, true)],
        "sanity: manifest-derived real-Lucene expectation itself"
    );

    for (slop, expect_match) in real_lucene {
        let mut collector = VecCollector::default();
        search_phrase_query(
            &fields,
            Some(&doc_in),
            Some(&pos_in),
            Some(&pay_in),
            None,
            &PhraseQuery::new("pos", ["alpha", "beta"]).with_slop(slop),
            &mut collector,
        )
        .unwrap_or_else(|e| {
            panic!("search_phrase_query(pos, \"alpha beta\", slop={slop}) failed: {e}")
        });

        let matched = collector.docs.contains(&gap_doc);
        assert_eq!(
            matched, expect_match,
            "slop={slop}: this port's sloppy match result disagrees with real Lucene's \
             PhraseQuery.setSlop({slop}) for doc {gap_doc} (alpha@0, beta@3)"
        );
    }
}
