//! Differential test: `search_phrase_query` against the same real
//! `IndexWriter`-produced segment `crates/lucene-codecs/tests/
//! blocktree_fixtures.rs`'s `pos_field_positions_match_real_lucene_postings_enum`
//! test already validates at the positions-decode layer
//! (`fixtures/data/blocktree_index/`, `pos`/`.pos`/`.pay` files, generated by
//! `fixtures/src/GenBlockTree.java`) -- this test proves the *query layer* built on
//! top of that decode returns exactly the doc IDs a real
//! `IndexSearcher.search(new PhraseQuery(...), collector)` would for the same
//! phrase against the same segment.
//!
//! No new fixture generator was added for this: the existing `pos` field
//! (`IndexOptions.DOCS_AND_FREQS_AND_POSITIONS_AND_OFFSETS`) already has real,
//! manifest-recorded per-occurrence positions for two terms -- from
//! `manifest.properties`: `alpha` occurs in doc 8555 at position 0 and in doc 8556
//! at positions 0 and 1; `beta` occurs only in doc 8555, at position 1. That is
//! already exactly the shape a phrase-query differential test needs (an adjacent
//! pair in one doc, a non-adjacent/absent pair in another), so this test reuses it
//! rather than extending the generator -- see the `differential-testing` skill's
//! "prefer reuse where a fixture already fits" stance.

use lucene_codecs::blocktree;
use lucene_codecs::field_infos;
use lucene_codecs::postings::{DocInput, PayInput, PosInput};
use lucene_search::{search_phrase_query, PhraseQuery, VecCollector};

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/blocktree_index/"
    )
    .to_string()
}

struct Manifest {
    kv: Vec<(String, String)>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenBlockTree)");
        let kv = text
            .lines()
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        Manifest { kv }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }
}

/// Independently derives, from `manifest.properties`' own
/// `field.pos.term.{term}.postingsDocs`/`.postingsFreqs`/`.occurrences` entries
/// (real `PostingsEnum` output, not anything this crate's implementation
/// produced), the set of doc IDs where `terms` occur at consecutive positions
/// in order -- i.e. the same expectation [`search_phrase_query`] is being
/// checked against, computed a second, independent way so a transcription
/// error in this test can't just mirror a bug in the implementation under
/// test.
///
/// `occurrences` is a flat list with no doc ID of its own: it's every
/// occurrence across every doc in `postingsDocs` order, `postingsFreqs[i]`
/// occurrences per doc `i` (matching how the generator/reader also chunk it;
/// see `blocktree_fixtures.rs`'s `pos_field_positions_match_real_lucene_postings_enum`
/// for the same chunking).
fn per_term_doc_positions(m: &Manifest, field: &str, term: &str) -> Vec<(i32, Vec<i32>)> {
    let docs: Vec<i32> = m
        .get(&format!("field.{field}.term.{term}.postingsDocs"))
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    let freqs: Vec<usize> = m
        .get(&format!("field.{field}.term.{term}.postingsFreqs"))
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    let occurrences: Vec<i32> = m
        .get(&format!("field.{field}.term.{term}.occurrences"))
        .split(';')
        .map(|occ| occ.split_once(',').unwrap().0.parse().unwrap())
        .collect();

    let mut result = Vec::with_capacity(docs.len());
    let mut idx = 0;
    for (doc, freq) in docs.into_iter().zip(freqs) {
        result.push((doc, occurrences[idx..idx + freq].to_vec()));
        idx += freq;
    }
    result
}

fn expected_phrase_docs(m: &Manifest, field: &str, terms: &[&str]) -> Vec<i32> {
    let per_term: Vec<Vec<(i32, Vec<i32>)>> = terms
        .iter()
        .map(|term| per_term_doc_positions(m, field, term))
        .collect();

    let mut by_doc: std::collections::BTreeMap<i32, Vec<Vec<i32>>> =
        std::collections::BTreeMap::new();
    for (term_index, term_docs) in per_term.iter().enumerate() {
        for (doc, positions) in term_docs {
            let entry = by_doc
                .entry(*doc)
                .or_insert_with(|| vec![Vec::new(); terms.len()]);
            entry[term_index] = positions.clone();
        }
    }

    by_doc
        .into_iter()
        .filter(|(_, per_term_positions)| {
            if per_term_positions.iter().any(Vec::is_empty) {
                return false;
            }
            per_term_positions[0].iter().any(|&base| {
                per_term_positions
                    .iter()
                    .enumerate()
                    .all(|(i, positions)| positions.contains(&(base + i as i32)))
            })
        })
        .map(|(doc, _)| doc)
        .collect()
}

fn id_from_hex(hex: &str) -> [u8; 16] {
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

fn read_raw(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{}.raw", dir(), name)).unwrap_or_else(|_| panic!("missing {name}.raw"))
}

/// Opens the fixture segment's term dictionary plus `.doc`/`.pos`/`.pay` files,
/// mirroring `term_query_fixtures.rs::open_segment` (no shared crate to hang a
/// common test helper off; `lucene-codecs` and `lucene-search` are separate
/// crates' test binaries).
type SegmentFixture = (
    blocktree::BlockTreeFields,
    Vec<u8>,
    Vec<u8>,
    Vec<u8>,
    [u8; 16],
    String,
    Manifest,
);

fn open_segment() -> SegmentFixture {
    let m = Manifest::load();
    let id = id_from_hex(m.get("id_hex"));
    let suffix = m.get("segment_suffix").to_string();
    let max_doc: i32 = m.get("max_doc").parse().unwrap();

    let fnm = read_raw(m.get("fnm_file_name"));
    let field_infos = field_infos::parse(&fnm, &id, "").expect("parse .fnm");

    let tim = read_raw(m.get("tim_file_name"));
    let tip = read_raw(m.get("tip_file_name"));
    let tmd = read_raw(m.get("tmd_file_name"));
    let fields = blocktree::open(&tim, &tip, &tmd, &field_infos, &id, &suffix, max_doc)
        .expect("open blocktree");

    let doc = read_raw(m.get("doc_file_name"));
    let pos = read_raw(m.get("pos_file_name"));
    let pay = read_raw(m.get("pay_file_name"));
    (fields, doc, pos, pay, id, suffix, m)
}

/// `"alpha beta"` on the `pos` field: real Lucene's `PhraseQuery` (via
/// `ExactPhraseScorer`) matches doc 8555 (alpha@0, beta@1 -- adjacent) but not doc
/// 8556 (alpha@0 and alpha@1, no "beta" at all in that doc).
#[test]
fn two_term_phrase_matches_real_lucenes_exact_phrase_scorer_doc_set() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &PhraseQuery::new("pos", ["alpha", "beta"]),
        &mut collector,
    )
    .unwrap_or_else(|e| panic!("search_phrase_query(pos, \"alpha beta\") failed: {e}"));

    let expected = expected_phrase_docs(&m, "pos", &["alpha", "beta"]);
    assert_eq!(
        expected,
        vec![8555],
        "sanity: manifest-derived expectation itself"
    );
    assert_eq!(collector.docs, expected);
}

/// A single-term "phrase" degenerates to a plain term match: every doc containing
/// "alpha" (8555 and 8556), no position alignment needed at all.
#[test]
fn single_term_phrase_matches_every_doc_containing_the_term() {
    let (fields, doc, _pos, _pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        None,
        None,
        None,
        &PhraseQuery::new("pos", ["alpha"]),
        &mut collector,
    )
    .unwrap();

    let expected: Vec<i32> = m
        .get("field.pos.term.alpha.postingsDocs")
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    assert_eq!(
        expected,
        vec![8555, 8556],
        "sanity: manifest-derived expectation itself"
    );
    assert_eq!(collector.docs, expected);
}

/// A phrase term absent from the field entirely: no matches, not an error --
/// matches `PhraseQuery`'s real `null`-`Scorer` "term not found" outcome.
#[test]
fn phrase_with_a_missing_term_matches_nothing() {
    let (fields, doc, pos, pay, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut collector = VecCollector::default();
    search_phrase_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &PhraseQuery::new("pos", ["alpha", "zzz-missing"]),
        &mut collector,
    )
    .unwrap();

    assert!(collector.docs.is_empty());
}
