//! Differential test: `search_span_query` against the same real
//! `IndexWriter`-produced segment `phrase_query_fixtures.rs` already uses
//! (`fixtures/data/blocktree_index/`, generated by
//! `fixtures/src/GenBlockTree.java`) -- this test proves task #55's
//! `SpanTermQuery`/`SpanNearQuery`/`SpanOrQuery` port agrees with real
//! `org.apache.lucene.queries.spans.SpanNearQuery`/`SpanOrQuery`, especially
//! the `in_order == false` any-order case, the property most likely to be
//! subtly wrong if hand-derived without checking real Lucene (see this
//! task's own scoping notes and `SpanQuery`'s doc comment).
//!
//! `GenBlockTree.java`'s doc8 (`"pos"` field: `"delta"@0`, `"gamma"@1` --
//! occurrence order DELIBERATELY REVERSED relative to a `SpanNearQuery` built
//! with clauses in `[gamma, delta]` order) plus its own
//! `field.pos.span.*` manifest keys (written by *actually running*
//! `IndexSearcher.search` with real `SpanNearQuery`/`SpanOrQuery` instances
//! against this exact fixture segment at generation time) is the ground
//! truth this test checks `search_span_query`/`span_matches_in_doc` against,
//! not a value this test derives independently.

use lucene_codecs::blocktree;
use lucene_codecs::field_infos;
use lucene_codecs::postings::{DocInput, PayInput, PosInput};
use lucene_search::{search_span_query, SpanQuery, VecCollector};

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/blocktree_index/"
    )
    .to_string()
}

struct Manifest {
    kv: Vec<(String, String)>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenBlockTree)");
        let kv = text
            .lines()
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        Manifest { kv }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }
}

fn id_from_hex(hex: &str) -> [u8; 16] {
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

fn read_raw(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{}.raw", dir(), name)).unwrap_or_else(|_| panic!("missing {name}.raw"))
}

type SegmentFixture = (
    blocktree::BlockTreeFields,
    Vec<u8>,
    Vec<u8>,
    Vec<u8>,
    [u8; 16],
    String,
    Manifest,
);

fn open_segment() -> SegmentFixture {
    let m = Manifest::load();
    let id = id_from_hex(m.get("id_hex"));
    let suffix = m.get("segment_suffix").to_string();
    let max_doc: i32 = m.get("max_doc").parse().unwrap();

    let fnm = read_raw(m.get("fnm_file_name"));
    let field_infos = field_infos::parse(&fnm, &id, "").expect("parse .fnm");

    let tim = read_raw(m.get("tim_file_name"));
    let tip = read_raw(m.get("tip_file_name"));
    let tmd = read_raw(m.get("tmd_file_name"));
    let fields = blocktree::open(&tim, &tip, &tmd, &field_infos, &id, &suffix, max_doc)
        .expect("open blocktree");

    let doc = read_raw(m.get("doc_file_name"));
    let pos = read_raw(m.get("pos_file_name"));
    let pay = read_raw(m.get("pay_file_name"));
    (fields, doc, pos, pay, id, suffix, m)
}

/// `SpanTermQuery`-equivalent sanity: "gamma" occurs exactly once, at doc8 --
/// same doc `field.pos.span.doc` names.
#[test]
fn span_term_matches_the_single_doc_containing_the_term() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let expected_doc: i32 = m.get("field.pos.span.doc").parse().unwrap();

    let mut collector = VecCollector::default();
    search_span_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &SpanQuery::span_term("pos", "gamma"),
        &mut collector,
    )
    .unwrap_or_else(|e| panic!("search_span_query(SpanTerm(pos, gamma)) failed: {e}"));

    assert_eq!(collector.docs, vec![expected_doc]);
}

/// Cross-engine differential test for `SpanNearQuery`'s `in_order`/`slop`
/// semantics: doc8 has "delta"@0, "gamma"@1 -- occurrence order reversed
/// relative to query clause order `[gamma, delta]`. Real
/// `SpanNearQuery([gamma, delta], slop=0, inOrder=true)` does NOT match this
/// doc (recorded ground truth); `inOrder=false` DOES match -- the key
/// differentiator from `PhraseQuery`'s in-order-only sloppy matching.
#[test]
fn span_near_in_order_and_out_of_order_agree_with_real_lucene() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let expected_doc: i32 = m.get("field.pos.span.doc").parse().unwrap();
    let real_in_order: bool = m
        .get("field.pos.span.nearInOrderSlop0Matches")
        .parse()
        .unwrap();
    let real_out_of_order: bool = m
        .get("field.pos.span.nearOutOfOrderSlop0Matches")
        .parse()
        .unwrap();
    assert!(
        !real_in_order && real_out_of_order,
        "sanity: manifest-derived real-Lucene expectations themselves \
         (in_order should NOT match, out-of-order SHOULD match)"
    );

    let query = |in_order: bool| {
        SpanQuery::span_near(
            [
                SpanQuery::span_term("pos", "gamma"),
                SpanQuery::span_term("pos", "delta"),
            ],
            0,
            in_order,
        )
    };

    let mut in_order_collector = VecCollector::default();
    search_span_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &query(true),
        &mut in_order_collector,
    )
    .unwrap_or_else(|e| panic!("search_span_query(SpanNear(in_order=true)) failed: {e}"));
    assert_eq!(
        in_order_collector.docs.contains(&expected_doc),
        real_in_order,
        "in_order=true: this port's span match result disagrees with real \
         Lucene's SpanNearQuery(slop=0, inOrder=true) for doc {expected_doc}"
    );

    let mut out_of_order_collector = VecCollector::default();
    search_span_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &query(false),
        &mut out_of_order_collector,
    )
    .unwrap_or_else(|e| panic!("search_span_query(SpanNear(in_order=false)) failed: {e}"));
    assert_eq!(
        out_of_order_collector.docs.contains(&expected_doc),
        real_out_of_order,
        "in_order=false: this port's span match result disagrees with real \
         Lucene's SpanNearQuery(slop=0, inOrder=false) for doc {expected_doc}"
    );
}

/// Cross-engine differential test for `SpanOrQuery`: the union of "gamma"'s
/// and "delta"'s own spans must match doc8, agreeing with real
/// `SpanOrQuery`'s recorded verdict.
#[test]
fn span_or_matches_real_lucenes_span_or_query() {
    let (fields, doc, pos, pay, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let expected_doc: i32 = m.get("field.pos.span.doc").parse().unwrap();
    let real_or_matches: bool = m.get("field.pos.span.orMatches").parse().unwrap();
    assert!(
        real_or_matches,
        "sanity: manifest-derived expectation itself"
    );

    let query = SpanQuery::span_or([
        SpanQuery::span_term("pos", "gamma"),
        SpanQuery::span_term("pos", "delta"),
    ]);

    let mut collector = VecCollector::default();
    search_span_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &query,
        &mut collector,
    )
    .unwrap_or_else(|e| panic!("search_span_query(SpanOr(gamma, delta)) failed: {e}"));

    assert_eq!(
        collector.docs.contains(&expected_doc),
        real_or_matches,
        "this port's SpanOr match result disagrees with real Lucene's \
         SpanOrQuery for doc {expected_doc}"
    );
}

/// A `SpanTermQuery` for a term absent from the field entirely: no matches,
/// not an error -- same convention `search_phrase_query`/`search_term_query`
/// already follow.
#[test]
fn span_term_with_a_missing_term_matches_nothing() {
    let (fields, doc, pos, pay, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");
    let pos_in = PosInput::open(&pos, &id, &suffix).expect("open .pos");
    let pay_in = PayInput::open(&pay, &id, &suffix).expect("open .pay");

    let mut collector = VecCollector::default();
    search_span_query(
        &fields,
        Some(&doc_in),
        Some(&pos_in),
        Some(&pay_in),
        None,
        &SpanQuery::span_term("pos", "zzz-missing"),
        &mut collector,
    )
    .unwrap();

    assert!(collector.docs.is_empty());
}
