//! Differential test: `search_term_query` against the same real
//! `IndexWriter`-produced `.tim`/`.tip`/`.tmd`/`.doc` segment
//! `crates/lucene-codecs/tests/blocktree_fixtures.rs` already validates at
//! the term-dictionary/postings layer (`fixtures/data/blocktree_index/`,
//! generated by `fixtures/src/GenBlockTree.java`) -- this test proves the
//! *query layer* built on top of that decode returns exactly the doc IDs
//! real Lucene's own `IndexSearcher.search(new TermQuery(...), collector)`
//! would return for the same term against the same segment, not just that
//! the lower-level postings decode is correct in isolation.
//!
//! `manifest.properties`' `field.<field>.term.<term>.postingsDocs` entries
//! are themselves real `PostingsEnum.nextDoc()` output dumped by
//! `GenBlockTree.java` from the real Lucene reader -- i.e. exactly the doc
//! set real `IndexSearcher` would collect for a `TermQuery` on that term
//! (`docFreq` equals the live doc count here since this fixture segment has
//! no deletions -- no `.liv` file is generated -- so every postingsDocs
//! entry is also the *live* doc set `TermQuery` would return).

use lucene_codecs::blocktree;
use lucene_codecs::field_infos;
use lucene_codecs::postings::DocInput;
use lucene_search::{search_term_query, CountCollector, TermQuery, VecCollector};

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/blocktree_index/"
    )
    .to_string()
}

struct Manifest {
    kv: Vec<(String, String)>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenBlockTree)");
        let kv = text
            .lines()
            .filter_map(|l| l.split_once('='))
            .map(|(k, v)| (k.to_string(), v.to_string()))
            .collect();
        Manifest { kv }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .iter()
            .find(|(k, _)| k == key)
            .map(|(_, v)| v.as_str())
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }
}

fn id_from_hex(hex: &str) -> [u8; 16] {
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

fn read_raw(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{}.raw", dir(), name)).unwrap_or_else(|_| panic!("missing {name}.raw"))
}

/// Opens the fixture segment's term dictionary and `.doc` file exactly the
/// way `blocktree_fixtures.rs` does -- see that test file's own `open_*`
/// helpers, which this mirrors (no shared crate to hang a common test helper
/// off; `lucene-codecs` and `lucene-search` are separate crates' test
/// binaries).
fn open_segment() -> (
    blocktree::BlockTreeFields,
    Vec<u8>,
    [u8; 16],
    String,
    Manifest,
) {
    let m = Manifest::load();
    let id = id_from_hex(m.get("id_hex"));
    let suffix = m.get("segment_suffix").to_string();
    let max_doc: i32 = m.get("max_doc").parse().unwrap();

    let fnm = read_raw(m.get("fnm_file_name"));
    let field_infos = field_infos::parse(&fnm, &id, "").expect("parse .fnm");

    let tim = read_raw(m.get("tim_file_name"));
    let tip = read_raw(m.get("tip_file_name"));
    let tmd = read_raw(m.get("tmd_file_name"));
    let fields = blocktree::open(&tim, &tip, &tmd, &field_infos, &id, &suffix, max_doc)
        .expect("open blocktree");

    let doc = read_raw(m.get("doc_file_name"));
    (fields, doc, id, suffix, m)
}

/// `body` (`IndexOptions.DOCS_AND_FREQS`, `docFreq == 2` for every term):
/// exercises the multi-doc `.doc`-backed path end to end through the query
/// layer, for every one of the field's three terms.
#[test]
fn body_field_term_query_matches_real_lucene_postings_enum_doc_set() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    for term in ["cat", "dog", "bird"] {
        let expected_docs: Vec<i32> = m
            .get(&format!("field.body.term.{term}.postingsDocs"))
            .split(',')
            .map(|s| s.parse().unwrap())
            .collect();

        let mut collector = VecCollector::default();
        search_term_query(
            &fields,
            Some(&doc_in),
            None,
            &TermQuery::new("body", term),
            &mut collector,
        )
        .unwrap_or_else(|e| panic!("search_term_query(body, {term:?}) failed: {e}"));

        assert_eq!(collector.docs, expected_docs, "term={term:?}");
    }
}

/// `id` (`IndexOptions.DOCS`, `docFreq == 1` singletons pulsed into the term
/// dictionary): exercises the no-`.doc`-file-needed path -- passing `None`
/// for `doc_in` must still find every doc.
#[test]
fn id_field_term_query_matches_real_lucene_without_opening_doc_file() {
    let (fields, _doc, _id, _suffix, m) = open_segment();

    for i in 0..5 {
        let term = format!("id{i}");
        let expected_docs: Vec<i32> = m
            .get(&format!("field.id.term.{term}.postingsDocs"))
            .split(',')
            .map(|s| s.parse().unwrap())
            .collect();

        let mut collector = VecCollector::default();
        search_term_query(
            &fields,
            None,
            None,
            &TermQuery::new("id", term.clone()),
            &mut collector,
        )
        .unwrap_or_else(|e| panic!("search_term_query(id, {term:?}) failed: {e}"));

        assert_eq!(collector.docs, expected_docs, "term={term:?}");
    }
}

/// `big` (`IndexOptions.DOCS_AND_FREQS`, `docFreq == 300`): exercises the
/// multi-block `.doc` decode path through the query layer -- the same
/// fixture `blocktree_fixtures.rs` uses for its own multi-block postings
/// coverage, now proving the query layer collects all 300 doc IDs correctly
/// too, not just that `FieldTerms::postings` decodes them.
#[test]
fn big_field_term_query_matches_real_lucene_across_multiple_doc_blocks() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected_docs: Vec<i32> = m
        .get("field.big.term.everywhere.postingsDocs")
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    assert_eq!(expected_docs.len(), 300, "fixture sanity: docFreq 300");

    let mut collector = VecCollector::default();
    search_term_query(
        &fields,
        Some(&doc_in),
        None,
        &TermQuery::new("big", "everywhere"),
        &mut collector,
    )
    .unwrap();
    assert_eq!(collector.docs, expected_docs);

    let mut count = CountCollector::default();
    search_term_query(
        &fields,
        Some(&doc_in),
        None,
        &TermQuery::new("big", "everywhere"),
        &mut count,
    )
    .unwrap();
    assert_eq!(count.count as usize, expected_docs.len());
}

/// A field that exists in the segment but doesn't contain the queried term,
/// and a field name absent from the segment entirely: both must yield zero
/// matches, not an error -- matches `TermQuery.createWeight`'s `null`-Scorer
/// "no such term" outcome, which real `IndexSearcher.search` reports as zero
/// hits, not a failure.
#[test]
fn unknown_field_and_unknown_term_yield_zero_hits_not_an_error() {
    let (fields, doc, id, suffix, _m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let mut collector = VecCollector::default();
    search_term_query(
        &fields,
        Some(&doc_in),
        None,
        &TermQuery::new("body", "zzz-missing"),
        &mut collector,
    )
    .unwrap();
    assert!(collector.docs.is_empty());

    let mut collector = VecCollector::default();
    search_term_query(
        &fields,
        Some(&doc_in),
        None,
        &TermQuery::new("no-such-field", "cat"),
        &mut collector,
    )
    .unwrap();
    assert!(collector.docs.is_empty());
}

/// `l1` (`docFreq == 8250 > LEVEL1_NUM_DOCS`): exercises the query layer
/// against the level-1-skip-structured `.doc` encoding -- the largest
/// doc-count term any fixture in this port produces -- proving
/// `search_term_query`'s eager-postings path handles it identically to
/// `blocktree_fixtures.rs`'s own direct `FieldTerms::postings` coverage.
#[test]
fn l1_field_term_query_matches_real_lucene_across_level1_skip_structure() {
    let (fields, doc, id, suffix, m) = open_segment();
    let doc_in = DocInput::open(&doc, &id, &suffix).expect("open .doc");

    let expected_docs: Vec<i32> = m
        .get("field.l1.term.l1term.postingsDocs")
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    assert_eq!(expected_docs.len(), 8250, "fixture sanity: docFreq 8250");

    let mut collector = VecCollector::default();
    search_term_query(
        &fields,
        Some(&doc_in),
        None,
        &TermQuery::new("l1", "l1term"),
        &mut collector,
    )
    .unwrap();
    assert_eq!(collector.docs, expected_docs);
}
