//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 109] = &[
    Among(&[105, 100, 101, 97], -1, 1, None), // "idea"
    Among(&[98, 105, 100, 101, 97], 0, 1, None), // "bidea"
    Among(&[107, 105, 100, 101, 97], 0, 1, None), // "kidea"
    Among(&[112, 105, 100, 101, 97], 0, 1, None), // "pidea"
    Among(&[107, 117, 110, 100, 101, 97], -1, 1, None), // "kundea"
    Among(&[103, 97, 108, 101, 97], -1, 1, None), // "galea"
    Among(&[116, 97, 105, 108, 101, 97], -1, 1, None), // "tailea"
    Among(&[116, 122, 97, 105, 108, 101, 97], -1, 1, None), // "tzailea"
    Among(&[103, 117, 110, 101, 97], -1, 1, None), // "gunea"
    Among(&[107, 117, 110, 101, 97], -1, 1, None), // "kunea"
    Among(&[116, 122, 97, 103, 97], -1, 1, None), // "tzaga"
    Among(&[103, 97, 105, 97], -1, 1, None), // "gaia"
    Among(&[97, 108, 100, 105, 97], -1, 1, None), // "aldia"
    Among(&[116, 97, 108, 100, 105, 97], 12, 1, None), // "taldia"
    Among(&[107, 97, 114, 105, 97], -1, 1, None), // "karia"
    Among(&[103, 97, 114, 114, 105, 97], -1, 2, None), // "garria"
    Among(&[107, 97, 114, 114, 105, 97], -1, 1, None), // "karria"
    Among(&[107, 97], -1, 1, None), // "ka"
    Among(&[116, 122, 97, 107, 97], 17, 1, None), // "tzaka"
    Among(&[108, 97], -1, 1, None), // "la"
    Among(&[109, 101, 110, 97], -1, 1, None), // "mena"
    Among(&[112, 101, 110, 97], -1, 1, None), // "pena"
    Among(&[107, 105, 110, 97], -1, 1, None), // "kina"
    Among(&[101, 122, 105, 110, 97], -1, 1, None), // "ezina"
    Among(&[116, 101, 122, 105, 110, 97], 23, 1, None), // "tezina"
    Among(&[107, 117, 110, 97], -1, 1, None), // "kuna"
    Among(&[116, 117, 110, 97], -1, 1, None), // "tuna"
    Among(&[107, 105, 122, 117, 110, 97], -1, 1, None), // "kizuna"
    Among(&[101, 114, 97], -1, 1, None), // "era"
    Among(&[98, 101, 114, 97], 28, 1, None), // "bera"
    Among(&[97, 114, 97, 98, 101, 114, 97], 29, 4, None), // "arabera"
    Among(&[107, 101, 114, 97], 28, 1, None), // "kera"
    Among(&[112, 101, 114, 97], 28, 1, None), // "pera"
    Among(&[111, 114, 114, 97], -1, 1, None), // "orra"
    Among(&[107, 111, 114, 114, 97], 33, 1, None), // "korra"
    Among(&[100, 117, 114, 97], -1, 1, None), // "dura"
    Among(&[103, 117, 114, 97], -1, 1, None), // "gura"
    Among(&[107, 117, 114, 97], -1, 1, None), // "kura"
    Among(&[116, 117, 114, 97], -1, 1, None), // "tura"
    Among(&[101, 116, 97], -1, 1, None), // "eta"
    Among(&[107, 101, 116, 97], 39, 1, None), // "keta"
    Among(&[103, 97, 105, 108, 117, 97], -1, 1, None), // "gailua"
    Among(&[101, 122, 97], -1, 1, None), // "eza"
    Among(&[101, 114, 114, 101, 122, 97], 42, 1, None), // "erreza"
    Among(&[116, 122, 97], -1, 2, None), // "tza"
    Among(&[103, 97, 105, 116, 122, 97], 44, 1, None), // "gaitza"
    Among(&[107, 97, 105, 116, 122, 97], 44, 1, None), // "kaitza"
    Among(&[107, 117, 110, 116, 122, 97], 44, 1, None), // "kuntza"
    Among(&[105, 100, 101], -1, 1, None), // "ide"
    Among(&[98, 105, 100, 101], 48, 1, None), // "bide"
    Among(&[107, 105, 100, 101], 48, 1, None), // "kide"
    Among(&[112, 105, 100, 101], 48, 1, None), // "pide"
    Among(&[107, 117, 110, 100, 101], -1, 1, None), // "kunde"
    Among(&[116, 122, 97, 107, 101], -1, 1, None), // "tzake"
    Among(&[116, 122, 101, 107, 101], -1, 1, None), // "tzeke"
    Among(&[108, 101], -1, 1, None), // "le"
    Among(&[103, 97, 108, 101], 55, 1, None), // "gale"
    Among(&[116, 97, 105, 108, 101], 55, 1, None), // "taile"
    Among(&[116, 122, 97, 105, 108, 101], 55, 1, None), // "tzaile"
    Among(&[103, 117, 110, 101], -1, 1, None), // "gune"
    Among(&[107, 117, 110, 101], -1, 1, None), // "kune"
    Among(&[116, 122, 101], -1, 1, None), // "tze"
    Among(&[97, 116, 122, 101], 61, 1, None), // "atze"
    Among(&[103, 97, 105], -1, 1, None), // "gai"
    Among(&[97, 108, 100, 105], -1, 1, None), // "aldi"
    Among(&[116, 97, 108, 100, 105], 64, 1, None), // "taldi"
    Among(&[107, 105], -1, 1, None), // "ki"
    Among(&[97, 114, 105], -1, 1, None), // "ari"
    Among(&[107, 97, 114, 105], 67, 1, None), // "kari"
    Among(&[108, 97, 114, 105], 67, 1, None), // "lari"
    Among(&[116, 97, 114, 105], 67, 1, None), // "tari"
    Among(&[101, 116, 97, 114, 105], 70, 1, None), // "etari"
    Among(&[103, 97, 114, 114, 105], -1, 2, None), // "garri"
    Among(&[107, 97, 114, 114, 105], -1, 1, None), // "karri"
    Among(&[97, 114, 97, 122, 105], -1, 1, None), // "arazi"
    Among(&[116, 97, 114, 97, 122, 105], 74, 1, None), // "tarazi"
    Among(&[97, 110], -1, 1, None), // "an"
    Among(&[101, 97, 110], 76, 1, None), // "ean"
    Among(&[114, 101, 97, 110], 77, 1, None), // "rean"
    Among(&[107, 97, 110], 76, 1, None), // "kan"
    Among(&[101, 116, 97, 110], 76, 1, None), // "etan"
    Among(&[97, 116, 115, 101, 100, 101, 110], -1, 3, None), // "atseden"
    Among(&[109, 101, 110], -1, 1, None), // "men"
    Among(&[112, 101, 110], -1, 1, None), // "pen"
    Among(&[107, 105, 110], -1, 1, None), // "kin"
    Among(&[114, 101, 107, 105, 110], 84, 1, None), // "rekin"
    Among(&[101, 122, 105, 110], -1, 1, None), // "ezin"
    Among(&[116, 101, 122, 105, 110], 86, 1, None), // "tezin"
    Among(&[116, 117, 110], -1, 1, None), // "tun"
    Among(&[107, 105, 122, 117, 110], -1, 1, None), // "kizun"
    Among(&[103, 111], -1, 1, None), // "go"
    Among(&[97, 103, 111], 90, 1, None), // "ago"
    Among(&[116, 105, 111], -1, 1, None), // "tio"
    Among(&[100, 97, 107, 111], -1, 1, None), // "dako"
    Among(&[111, 114], -1, 1, None), // "or"
    Among(&[107, 111, 114], 94, 1, None), // "kor"
    Among(&[116, 122, 97, 116], -1, 1, None), // "tzat"
    Among(&[100, 117], -1, 1, None), // "du"
    Among(&[103, 97, 105, 108, 117], -1, 1, None), // "gailu"
    Among(&[116, 117], -1, 1, None), // "tu"
    Among(&[97, 116, 117], 99, 1, None), // "atu"
    Among(&[97, 108, 100, 97, 116, 117], 100, 1, None), // "aldatu"
    Among(&[116, 97, 116, 117], 100, 1, None), // "tatu"
    Among(&[98, 97, 100, 105, 116, 117], 99, 5, None), // "baditu"
    Among(&[101, 122], -1, 1, None), // "ez"
    Among(&[101, 114, 114, 101, 122], 104, 1, None), // "errez"
    Among(&[116, 122, 101, 122], 104, 1, None), // "tzez"
    Among(&[103, 97, 105, 116, 122], -1, 1, None), // "gaitz"
    Among(&[107, 97, 105, 116, 122], -1, 1, None), // "kaitz"
];

static A_1: &'static [Among<Context>; 295] = &[
    Among(&[97, 100, 97], -1, 1, None), // "ada"
    Among(&[107, 97, 100, 97], 0, 1, None), // "kada"
    Among(&[97, 110, 100, 97], -1, 1, None), // "anda"
    Among(&[100, 101, 110, 100, 97], -1, 1, None), // "denda"
    Among(&[103, 97, 98, 101, 97], -1, 1, None), // "gabea"
    Among(&[107, 97, 98, 101, 97], -1, 1, None), // "kabea"
    Among(&[97, 108, 100, 101, 97], -1, 1, None), // "aldea"
    Among(&[107, 97, 108, 100, 101, 97], 6, 1, None), // "kaldea"
    Among(&[116, 97, 108, 100, 101, 97], 6, 1, None), // "taldea"
    Among(&[111, 114, 100, 101, 97], -1, 1, None), // "ordea"
    Among(&[122, 97, 108, 101, 97], -1, 1, None), // "zalea"
    Among(&[116, 122, 97, 108, 101, 97], 10, 1, None), // "tzalea"
    Among(&[103, 105, 108, 101, 97], -1, 1, None), // "gilea"
    Among(&[101, 109, 101, 97], -1, 1, None), // "emea"
    Among(&[107, 117, 109, 101, 97], -1, 1, None), // "kumea"
    Among(&[110, 101, 97], -1, 1, None), // "nea"
    Among(&[101, 110, 101, 97], 15, 1, None), // "enea"
    Among(&[122, 105, 111, 110, 101, 97], 15, 1, None), // "zionea"
    Among(&[117, 110, 101, 97], 15, 1, None), // "unea"
    Among(&[103, 117, 110, 101, 97], 18, 1, None), // "gunea"
    Among(&[112, 101, 97], -1, 1, None), // "pea"
    Among(&[97, 117, 114, 114, 101, 97], -1, 1, None), // "aurrea"
    Among(&[116, 101, 97], -1, 1, None), // "tea"
    Among(&[107, 111, 116, 101, 97], 22, 1, None), // "kotea"
    Among(&[97, 114, 116, 101, 97], 22, 1, None), // "artea"
    Among(&[111, 115, 116, 101, 97], 22, 1, None), // "ostea"
    Among(&[101, 116, 120, 101, 97], -1, 1, None), // "etxea"
    Among(&[103, 97], -1, 1, None), // "ga"
    Among(&[97, 110, 103, 97], 27, 1, None), // "anga"
    Among(&[103, 97, 105, 97], -1, 1, None), // "gaia"
    Among(&[97, 108, 100, 105, 97], -1, 1, None), // "aldia"
    Among(&[116, 97, 108, 100, 105, 97], 30, 1, None), // "taldia"
    Among(&[104, 97, 110, 100, 105, 97], -1, 1, None), // "handia"
    Among(&[109, 101, 110, 100, 105, 97], -1, 1, None), // "mendia"
    Among(&[103, 101, 105, 97], -1, 1, None), // "geia"
    Among(&[101, 103, 105, 97], -1, 1, None), // "egia"
    Among(&[100, 101, 103, 105, 97], 35, 1, None), // "degia"
    Among(&[116, 101, 103, 105, 97], 35, 1, None), // "tegia"
    Among(&[110, 97, 104, 105, 97], -1, 1, None), // "nahia"
    Among(&[111, 104, 105, 97], -1, 1, None), // "ohia"
    Among(&[107, 105, 97], -1, 1, None), // "kia"
    Among(&[116, 111, 107, 105, 97], 40, 1, None), // "tokia"
    Among(&[111, 105, 97], -1, 1, None), // "oia"
    Among(&[107, 111, 105, 97], 42, 1, None), // "koia"
    Among(&[97, 114, 105, 97], -1, 1, None), // "aria"
    Among(&[107, 97, 114, 105, 97], 44, 1, None), // "karia"
    Among(&[108, 97, 114, 105, 97], 44, 1, None), // "laria"
    Among(&[116, 97, 114, 105, 97], 44, 1, None), // "taria"
    Among(&[101, 114, 105, 97], -1, 1, None), // "eria"
    Among(&[107, 101, 114, 105, 97], 48, 1, None), // "keria"
    Among(&[116, 101, 114, 105, 97], 48, 1, None), // "teria"
    Among(&[103, 97, 114, 114, 105, 97], -1, 2, None), // "garria"
    Among(&[108, 97, 114, 114, 105, 97], -1, 1, None), // "larria"
    Among(&[107, 105, 114, 114, 105, 97], -1, 1, None), // "kirria"
    Among(&[100, 117, 114, 105, 97], -1, 1, None), // "duria"
    Among(&[97, 115, 105, 97], -1, 1, None), // "asia"
    Among(&[116, 105, 97], -1, 1, None), // "tia"
    Among(&[101, 122, 105, 97], -1, 1, None), // "ezia"
    Among(&[98, 105, 122, 105, 97], -1, 1, None), // "bizia"
    Among(&[111, 110, 116, 122, 105, 97], -1, 1, None), // "ontzia"
    Among(&[107, 97], -1, 1, None), // "ka"
    Among(&[106, 111, 107, 97], 60, 3, None), // "joka"
    Among(&[97, 117, 114, 107, 97], 60, 10, None), // "aurka"
    Among(&[115, 107, 97], 60, 1, None), // "ska"
    Among(&[120, 107, 97], 60, 1, None), // "xka"
    Among(&[122, 107, 97], 60, 1, None), // "zka"
    Among(&[103, 105, 98, 101, 108, 97], -1, 1, None), // "gibela"
    Among(&[103, 101, 108, 97], -1, 1, None), // "gela"
    Among(&[107, 97, 105, 108, 97], -1, 1, None), // "kaila"
    Among(&[115, 107, 105, 108, 97], -1, 1, None), // "skila"
    Among(&[116, 105, 108, 97], -1, 1, None), // "tila"
    Among(&[111, 108, 97], -1, 1, None), // "ola"
    Among(&[110, 97], -1, 1, None), // "na"
    Among(&[107, 97, 110, 97], 72, 1, None), // "kana"
    Among(&[101, 110, 97], 72, 1, None), // "ena"
    Among(&[103, 97, 114, 114, 101, 110, 97], 74, 1, None), // "garrena"
    Among(&[103, 101, 114, 114, 101, 110, 97], 74, 1, None), // "gerrena"
    Among(&[117, 114, 114, 101, 110, 97], 74, 1, None), // "urrena"
    Among(&[122, 97, 105, 110, 97], 72, 1, None), // "zaina"
    Among(&[116, 122, 97, 105, 110, 97], 78, 1, None), // "tzaina"
    Among(&[107, 105, 110, 97], 72, 1, None), // "kina"
    Among(&[109, 105, 110, 97], 72, 1, None), // "mina"
    Among(&[103, 97, 114, 110, 97], 72, 1, None), // "garna"
    Among(&[117, 110, 97], 72, 1, None), // "una"
    Among(&[100, 117, 110, 97], 83, 1, None), // "duna"
    Among(&[97, 115, 117, 110, 97], 83, 1, None), // "asuna"
    Among(&[116, 97, 115, 117, 110, 97], 85, 1, None), // "tasuna"
    Among(&[111, 110, 100, 111, 97], -1, 1, None), // "ondoa"
    Among(&[107, 111, 110, 100, 111, 97], 87, 1, None), // "kondoa"
    Among(&[110, 103, 111, 97], -1, 1, None), // "ngoa"
    Among(&[122, 105, 111, 97], -1, 1, None), // "zioa"
    Among(&[107, 111, 97], -1, 1, None), // "koa"
    Among(&[116, 97, 107, 111, 97], 91, 1, None), // "takoa"
    Among(&[122, 107, 111, 97], 91, 1, None), // "zkoa"
    Among(&[110, 111, 97], -1, 1, None), // "noa"
    Among(&[122, 105, 110, 111, 97], 94, 1, None), // "zinoa"
    Among(&[97, 114, 111, 97], -1, 1, None), // "aroa"
    Among(&[116, 97, 114, 111, 97], 96, 1, None), // "taroa"
    Among(&[122, 97, 114, 111, 97], 96, 1, None), // "zaroa"
    Among(&[101, 114, 111, 97], -1, 1, None), // "eroa"
    Among(&[111, 114, 111, 97], -1, 1, None), // "oroa"
    Among(&[111, 115, 111, 97], -1, 1, None), // "osoa"
    Among(&[116, 111, 97], -1, 1, None), // "toa"
    Among(&[116, 116, 111, 97], 102, 1, None), // "ttoa"
    Among(&[122, 116, 111, 97], 102, 1, None), // "ztoa"
    Among(&[116, 120, 111, 97], -1, 1, None), // "txoa"
    Among(&[116, 122, 111, 97], -1, 1, None), // "tzoa"
    Among(&[241, 111, 97], -1, 1, None), // "\u{00F1}oa"
    Among(&[114, 97], -1, 1, None), // "ra"
    Among(&[97, 114, 97], 108, 1, None), // "ara"
    Among(&[100, 97, 114, 97], 109, 1, None), // "dara"
    Among(&[108, 105, 97, 114, 97], 109, 1, None), // "liara"
    Among(&[116, 105, 97, 114, 97], 109, 1, None), // "tiara"
    Among(&[116, 97, 114, 97], 109, 1, None), // "tara"
    Among(&[101, 116, 97, 114, 97], 113, 1, None), // "etara"
    Among(&[116, 122, 97, 114, 97], 109, 1, None), // "tzara"
    Among(&[98, 101, 114, 97], 108, 1, None), // "bera"
    Among(&[107, 101, 114, 97], 108, 1, None), // "kera"
    Among(&[112, 101, 114, 97], 108, 1, None), // "pera"
    Among(&[111, 114, 97], 108, 2, None), // "ora"
    Among(&[116, 122, 97, 114, 114, 97], 108, 1, None), // "tzarra"
    Among(&[107, 111, 114, 114, 97], 108, 1, None), // "korra"
    Among(&[116, 114, 97], 108, 1, None), // "tra"
    Among(&[115, 97], -1, 1, None), // "sa"
    Among(&[111, 115, 97], 123, 1, None), // "osa"
    Among(&[116, 97], -1, 1, None), // "ta"
    Among(&[101, 116, 97], 125, 1, None), // "eta"
    Among(&[107, 101, 116, 97], 126, 1, None), // "keta"
    Among(&[115, 116, 97], 125, 1, None), // "sta"
    Among(&[100, 117, 97], -1, 1, None), // "dua"
    Among(&[109, 101, 110, 100, 117, 97], 129, 1, None), // "mendua"
    Among(&[111, 114, 100, 117, 97], 129, 1, None), // "ordua"
    Among(&[108, 101, 107, 117, 97], -1, 1, None), // "lekua"
    Among(&[98, 117, 114, 117, 97], -1, 1, None), // "burua"
    Among(&[100, 117, 114, 117, 97], -1, 1, None), // "durua"
    Among(&[116, 115, 117, 97], -1, 1, None), // "tsua"
    Among(&[116, 117, 97], -1, 1, None), // "tua"
    Among(&[109, 101, 110, 116, 117, 97], 136, 1, None), // "mentua"
    Among(&[101, 115, 116, 117, 97], 136, 1, None), // "estua"
    Among(&[116, 120, 117, 97], -1, 1, None), // "txua"
    Among(&[122, 117, 97], -1, 1, None), // "zua"
    Among(&[116, 122, 117, 97], 140, 1, None), // "tzua"
    Among(&[122, 97], -1, 1, None), // "za"
    Among(&[101, 122, 97], 142, 1, None), // "eza"
    Among(&[101, 114, 111, 122, 97], 142, 1, None), // "eroza"
    Among(&[116, 122, 97], 142, 2, None), // "tza"
    Among(&[107, 111, 105, 116, 122, 97], 145, 1, None), // "koitza"
    Among(&[97, 110, 116, 122, 97], 145, 1, None), // "antza"
    Among(&[103, 105, 110, 116, 122, 97], 145, 1, None), // "gintza"
    Among(&[107, 105, 110, 116, 122, 97], 145, 1, None), // "kintza"
    Among(&[107, 117, 110, 116, 122, 97], 145, 1, None), // "kuntza"
    Among(&[103, 97, 98, 101], -1, 1, None), // "gabe"
    Among(&[107, 97, 98, 101], -1, 1, None), // "kabe"
    Among(&[107, 105, 100, 101], -1, 1, None), // "kide"
    Among(&[97, 108, 100, 101], -1, 1, None), // "alde"
    Among(&[107, 97, 108, 100, 101], 154, 1, None), // "kalde"
    Among(&[116, 97, 108, 100, 101], 154, 1, None), // "talde"
    Among(&[111, 114, 100, 101], -1, 1, None), // "orde"
    Among(&[103, 101], -1, 1, None), // "ge"
    Among(&[122, 97, 108, 101], -1, 1, None), // "zale"
    Among(&[116, 122, 97, 108, 101], 159, 1, None), // "tzale"
    Among(&[103, 105, 108, 101], -1, 1, None), // "gile"
    Among(&[101, 109, 101], -1, 1, None), // "eme"
    Among(&[107, 117, 109, 101], -1, 1, None), // "kume"
    Among(&[110, 101], -1, 1, None), // "ne"
    Among(&[122, 105, 111, 110, 101], 164, 1, None), // "zione"
    Among(&[117, 110, 101], 164, 1, None), // "une"
    Among(&[103, 117, 110, 101], 166, 1, None), // "gune"
    Among(&[112, 101], -1, 1, None), // "pe"
    Among(&[97, 117, 114, 114, 101], -1, 1, None), // "aurre"
    Among(&[116, 101], -1, 1, None), // "te"
    Among(&[107, 111, 116, 101], 170, 1, None), // "kote"
    Among(&[97, 114, 116, 101], 170, 1, None), // "arte"
    Among(&[111, 115, 116, 101], 170, 1, None), // "oste"
    Among(&[101, 116, 120, 101], -1, 1, None), // "etxe"
    Among(&[103, 97, 105], -1, 1, None), // "gai"
    Among(&[100, 105], -1, 1, None), // "di"
    Among(&[97, 108, 100, 105], 176, 1, None), // "aldi"
    Among(&[116, 97, 108, 100, 105], 177, 1, None), // "taldi"
    Among(&[103, 101, 108, 100, 105], 176, 8, None), // "geldi"
    Among(&[104, 97, 110, 100, 105], 176, 1, None), // "handi"
    Among(&[109, 101, 110, 100, 105], 176, 1, None), // "mendi"
    Among(&[103, 101, 105], -1, 1, None), // "gei"
    Among(&[101, 103, 105], -1, 1, None), // "egi"
    Among(&[100, 101, 103, 105], 183, 1, None), // "degi"
    Among(&[116, 101, 103, 105], 183, 1, None), // "tegi"
    Among(&[110, 97, 104, 105], -1, 1, None), // "nahi"
    Among(&[111, 104, 105], -1, 1, None), // "ohi"
    Among(&[107, 105], -1, 1, None), // "ki"
    Among(&[116, 111, 107, 105], 188, 1, None), // "toki"
    Among(&[111, 105], -1, 1, None), // "oi"
    Among(&[103, 111, 105], 190, 1, None), // "goi"
    Among(&[107, 111, 105], 190, 1, None), // "koi"
    Among(&[97, 114, 105], -1, 1, None), // "ari"
    Among(&[107, 97, 114, 105], 193, 1, None), // "kari"
    Among(&[108, 97, 114, 105], 193, 1, None), // "lari"
    Among(&[116, 97, 114, 105], 193, 1, None), // "tari"
    Among(&[103, 97, 114, 114, 105], -1, 2, None), // "garri"
    Among(&[108, 97, 114, 114, 105], -1, 1, None), // "larri"
    Among(&[107, 105, 114, 114, 105], -1, 1, None), // "kirri"
    Among(&[100, 117, 114, 105], -1, 1, None), // "duri"
    Among(&[97, 115, 105], -1, 1, None), // "asi"
    Among(&[116, 105], -1, 1, None), // "ti"
    Among(&[111, 110, 116, 122, 105], -1, 1, None), // "ontzi"
    Among(&[241, 105], -1, 1, None), // "\u{00F1}i"
    Among(&[97, 107], -1, 1, None), // "ak"
    Among(&[101, 107], -1, 1, None), // "ek"
    Among(&[116, 97, 114, 105, 107], -1, 1, None), // "tarik"
    Among(&[103, 105, 98, 101, 108], -1, 1, None), // "gibel"
    Among(&[97, 105, 108], -1, 1, None), // "ail"
    Among(&[107, 97, 105, 108], 209, 1, None), // "kail"
    Among(&[107, 97, 110], -1, 1, None), // "kan"
    Among(&[116, 97, 110], -1, 1, None), // "tan"
    Among(&[101, 116, 97, 110], 212, 1, None), // "etan"
    Among(&[101, 110], -1, 4, None), // "en"
    Among(&[114, 101, 110], 214, 2, None), // "ren"
    Among(&[103, 97, 114, 114, 101, 110], 215, 1, None), // "garren"
    Among(&[103, 101, 114, 114, 101, 110], 215, 1, None), // "gerren"
    Among(&[117, 114, 114, 101, 110], 215, 1, None), // "urren"
    Among(&[116, 101, 110], 214, 4, None), // "ten"
    Among(&[116, 122, 101, 110], 214, 4, None), // "tzen"
    Among(&[122, 97, 105, 110], -1, 1, None), // "zain"
    Among(&[116, 122, 97, 105, 110], 221, 1, None), // "tzain"
    Among(&[107, 105, 110], -1, 1, None), // "kin"
    Among(&[109, 105, 110], -1, 1, None), // "min"
    Among(&[100, 117, 110], -1, 1, None), // "dun"
    Among(&[97, 115, 117, 110], -1, 1, None), // "asun"
    Among(&[116, 97, 115, 117, 110], 226, 1, None), // "tasun"
    Among(&[97, 105, 122, 117, 110], -1, 1, None), // "aizun"
    Among(&[111, 110, 100, 111], -1, 1, None), // "ondo"
    Among(&[107, 111, 110, 100, 111], 229, 1, None), // "kondo"
    Among(&[103, 111], -1, 1, None), // "go"
    Among(&[110, 103, 111], 231, 1, None), // "ngo"
    Among(&[122, 105, 111], -1, 1, None), // "zio"
    Among(&[107, 111], -1, 1, None), // "ko"
    Among(&[116, 114, 97, 107, 111], 234, 5, None), // "trako"
    Among(&[116, 97, 107, 111], 234, 1, None), // "tako"
    Among(&[101, 116, 97, 107, 111], 236, 1, None), // "etako"
    Among(&[101, 107, 111], 234, 1, None), // "eko"
    Among(&[116, 97, 114, 105, 107, 111], 234, 1, None), // "tariko"
    Among(&[115, 107, 111], 234, 1, None), // "sko"
    Among(&[116, 117, 107, 111], 234, 1, None), // "tuko"
    Among(&[109, 105, 110, 117, 116, 117, 107, 111], 241, 6, None), // "minutuko"
    Among(&[122, 107, 111], 234, 1, None), // "zko"
    Among(&[110, 111], -1, 1, None), // "no"
    Among(&[122, 105, 110, 111], 244, 1, None), // "zino"
    Among(&[114, 111], -1, 1, None), // "ro"
    Among(&[97, 114, 111], 246, 1, None), // "aro"
    Among(&[105, 103, 97, 114, 111], 247, 9, None), // "igaro"
    Among(&[116, 97, 114, 111], 247, 1, None), // "taro"
    Among(&[122, 97, 114, 111], 247, 1, None), // "zaro"
    Among(&[101, 114, 111], 246, 1, None), // "ero"
    Among(&[103, 105, 114, 111], 246, 1, None), // "giro"
    Among(&[111, 114, 111], 246, 1, None), // "oro"
    Among(&[111, 115, 111], -1, 1, None), // "oso"
    Among(&[116, 111], -1, 1, None), // "to"
    Among(&[116, 116, 111], 255, 1, None), // "tto"
    Among(&[122, 116, 111], 255, 1, None), // "zto"
    Among(&[116, 120, 111], -1, 1, None), // "txo"
    Among(&[116, 122, 111], -1, 1, None), // "tzo"
    Among(&[103, 105, 110, 116, 122, 111], 259, 1, None), // "gintzo"
    Among(&[241, 111], -1, 1, None), // "\u{00F1}o"
    Among(&[122, 112], -1, 1, None), // "zp"
    Among(&[97, 114], -1, 1, None), // "ar"
    Among(&[100, 97, 114], 263, 1, None), // "dar"
    Among(&[98, 101, 104, 97, 114], 263, 1, None), // "behar"
    Among(&[122, 101, 104, 97, 114], 263, 7, None), // "zehar"
    Among(&[108, 105, 97, 114], 263, 1, None), // "liar"
    Among(&[116, 105, 97, 114], 263, 1, None), // "tiar"
    Among(&[116, 97, 114], 263, 1, None), // "tar"
    Among(&[116, 122, 97, 114], 263, 1, None), // "tzar"
    Among(&[111, 114], -1, 2, None), // "or"
    Among(&[107, 111, 114], 271, 1, None), // "kor"
    Among(&[111, 115], -1, 1, None), // "os"
    Among(&[107, 101, 116], -1, 1, None), // "ket"
    Among(&[100, 117], -1, 1, None), // "du"
    Among(&[109, 101, 110, 100, 117], 275, 1, None), // "mendu"
    Among(&[111, 114, 100, 117], 275, 1, None), // "ordu"
    Among(&[108, 101, 107, 117], -1, 1, None), // "leku"
    Among(&[98, 117, 114, 117], -1, 2, None), // "buru"
    Among(&[100, 117, 114, 117], -1, 1, None), // "duru"
    Among(&[116, 115, 117], -1, 1, None), // "tsu"
    Among(&[116, 117], -1, 1, None), // "tu"
    Among(&[116, 97, 116, 117], 282, 4, None), // "tatu"
    Among(&[109, 101, 110, 116, 117], 282, 1, None), // "mentu"
    Among(&[101, 115, 116, 117], 282, 1, None), // "estu"
    Among(&[116, 120, 117], -1, 1, None), // "txu"
    Among(&[122, 117], -1, 1, None), // "zu"
    Among(&[116, 122, 117], 287, 1, None), // "tzu"
    Among(&[103, 105, 110, 116, 122, 117], 288, 1, None), // "gintzu"
    Among(&[122], -1, 1, None), // "z"
    Among(&[101, 122], 290, 1, None), // "ez"
    Among(&[101, 114, 111, 122], 290, 1, None), // "eroz"
    Among(&[116, 122], 290, 1, None), // "tz"
    Among(&[107, 111, 105, 116, 122], 293, 1, None), // "koitz"
];

static A_2: &'static [Among<Context>; 19] = &[
    Among(&[122, 108, 101, 97], -1, 2, None), // "zlea"
    Among(&[107, 101, 114, 105, 97], -1, 1, None), // "keria"
    Among(&[108, 97], -1, 1, None), // "la"
    Among(&[101, 114, 97], -1, 1, None), // "era"
    Among(&[100, 97, 100, 101], -1, 1, None), // "dade"
    Among(&[116, 97, 100, 101], -1, 1, None), // "tade"
    Among(&[100, 97, 116, 101], -1, 1, None), // "date"
    Among(&[116, 97, 116, 101], -1, 1, None), // "tate"
    Among(&[103, 105], -1, 1, None), // "gi"
    Among(&[107, 105], -1, 1, None), // "ki"
    Among(&[105, 107], -1, 1, None), // "ik"
    Among(&[108, 97, 110, 105, 107], 10, 1, None), // "lanik"
    Among(&[114, 105, 107], 10, 1, None), // "rik"
    Among(&[108, 97, 114, 105, 107], 12, 1, None), // "larik"
    Among(&[122, 116, 105, 107], 10, 1, None), // "ztik"
    Among(&[103, 111], -1, 1, None), // "go"
    Among(&[114, 111], -1, 1, None), // "ro"
    Among(&[101, 114, 111], 16, 1, None), // "ero"
    Among(&[116, 111], -1, 1, None), // "to"
];

static G_v: &'static [u8; 3] = &[17, 65, 16];

#[derive(Clone)]
struct Context {
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 117) {
                    break 'lab2;
                }
                'lab3: loop {
                    let v_3 = env.cursor;
                    'lab4: loop {
                        if !env.out_grouping(G_v, 97, 117) {
                            break 'lab4;
                        }
                        'golab5: loop {
                            'lab6: loop {
                                if !env.in_grouping(G_v, 97, 117) {
                                    break 'lab6;
                                }
                                break 'golab5;
                            }
                            if env.cursor >= env.limit {
                                break 'lab4;
                            }
                            env.next_char();
                        }
                        break 'lab3;
                    }
                    env.cursor = v_3;
                    if !env.in_grouping(G_v, 97, 117) {
                        break 'lab2;
                    }
                    'golab7: loop {
                        'lab8: loop {
                            if !env.out_grouping(G_v, 97, 117) {
                                break 'lab8;
                            }
                            break 'golab7;
                        }
                        if env.cursor >= env.limit {
                            break 'lab2;
                        }
                        env.next_char();
                    }
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if !env.out_grouping(G_v, 97, 117) {
                break 'lab0;
            }
            'lab9: loop {
                let v_6 = env.cursor;
                'lab10: loop {
                    if !env.out_grouping(G_v, 97, 117) {
                        break 'lab10;
                    }
                    'golab11: loop {
                        'lab12: loop {
                            if !env.in_grouping(G_v, 97, 117) {
                                break 'lab12;
                            }
                            break 'golab11;
                        }
                        if env.cursor >= env.limit {
                            break 'lab10;
                        }
                        env.next_char();
                    }
                    break 'lab9;
                }
                env.cursor = v_6;
                if !env.in_grouping(G_v, 97, 117) {
                    break 'lab0;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
                break 'lab9;
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_8 = env.cursor;
    'lab13: loop {
        'golab14: loop {
            'lab15: loop {
                if !env.in_grouping(G_v, 97, 117) {
                    break 'lab15;
                }
                break 'golab14;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab16: loop {
            'lab17: loop {
                if !env.out_grouping(G_v, 97, 117) {
                    break 'lab17;
                }
                break 'golab16;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab18: loop {
            'lab19: loop {
                if !env.in_grouping(G_v, 97, 117) {
                    break 'lab19;
                }
                break 'golab18;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab20: loop {
            'lab21: loop {
                if !env.out_grouping(G_v, 97, 117) {
                    break 'lab21;
                }
                break 'golab20;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab13;
    }
    env.cursor = v_8;
    return true
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_pV <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_aditzak(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_0, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        3 => {
            env.slice_from(&[97, 116, 115, 101, 100, 101, 110]);
        }
        4 => {
            env.slice_from(&[97, 114, 97, 98, 101, 114, 97]);
        }
        5 => {
            env.slice_from(&[98, 97, 100, 105, 116, 117]);
        }
        _ => ()
    }
    return true
}

fn r_izenak(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_1, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        3 => {
            env.slice_from(&[106, 111, 107]);
        }
        4 => {
            if !r_R1(env, context) {
                return false;
            }
            env.slice_del();
        }
        5 => {
            env.slice_from(&[116, 114, 97]);
        }
        6 => {
            env.slice_from(&[109, 105, 110, 117, 116, 117]);
        }
        7 => {
            env.slice_from(&[122, 101, 104, 97, 114]);
        }
        8 => {
            env.slice_from(&[103, 101, 108, 100, 105]);
        }
        9 => {
            env.slice_from(&[105, 103, 97, 114, 111]);
        }
        10 => {
            env.slice_from(&[97, 117, 114, 107, 97]);
        }
        _ => ()
    }
    return true
}

fn r_adjetiboak(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            env.slice_from(&[122]);
        }
        _ => ()
    }
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    r_mark_regions(env, context);
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    'replab0: loop{
        let v_2 = env.limit - env.cursor;
        'lab1: for _ in 0..1 {
            if !r_aditzak(env, context) {
                break 'lab1;
            }
            continue 'replab0;
        }
        env.cursor = env.limit - v_2;
        break 'replab0;
    }
    'replab2: loop{
        let v_3 = env.limit - env.cursor;
        'lab3: for _ in 0..1 {
            if !r_izenak(env, context) {
                break 'lab3;
            }
            continue 'replab2;
        }
        env.cursor = env.limit - v_3;
        break 'replab2;
    }
    let v_4 = env.limit - env.cursor;
    r_adjetiboak(env, context);
    env.cursor = env.limit - v_4;
    env.cursor = env.limit_backward;
    return true
}
