//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 3] = &[
    Among(&[97, 114, 115, 101, 110], -1, -1, None), // "arsen"
    Among(&[99, 111, 109, 109, 117, 110], -1, -1, None), // "commun"
    Among(&[103, 101, 110, 101, 114], -1, -1, None), // "gener"
];

static A_1: &'static [Among<Context>; 3] = &[
    Among(&[39], -1, 1, None), // "'"
    Among(&[39, 115, 39], 0, 1, None), // "'s'"
    Among(&[39, 115], -1, 1, None), // "'s"
];

static A_2: &'static [Among<Context>; 6] = &[
    Among(&[105, 101, 100], -1, 2, None), // "ied"
    Among(&[115], -1, 3, None), // "s"
    Among(&[105, 101, 115], 1, 2, None), // "ies"
    Among(&[115, 115, 101, 115], 1, 1, None), // "sses"
    Among(&[115, 115], 1, -1, None), // "ss"
    Among(&[117, 115], 1, -1, None), // "us"
];

static A_3: &'static [Among<Context>; 13] = &[
    Among(&[], -1, 3, None), // ""
    Among(&[98, 98], 0, 2, None), // "bb"
    Among(&[100, 100], 0, 2, None), // "dd"
    Among(&[102, 102], 0, 2, None), // "ff"
    Among(&[103, 103], 0, 2, None), // "gg"
    Among(&[98, 108], 0, 1, None), // "bl"
    Among(&[109, 109], 0, 2, None), // "mm"
    Among(&[110, 110], 0, 2, None), // "nn"
    Among(&[112, 112], 0, 2, None), // "pp"
    Among(&[114, 114], 0, 2, None), // "rr"
    Among(&[97, 116], 0, 1, None), // "at"
    Among(&[116, 116], 0, 2, None), // "tt"
    Among(&[105, 122], 0, 1, None), // "iz"
];

static A_4: &'static [Among<Context>; 6] = &[
    Among(&[101, 100], -1, 2, None), // "ed"
    Among(&[101, 101, 100], 0, 1, None), // "eed"
    Among(&[105, 110, 103], -1, 2, None), // "ing"
    Among(&[101, 100, 108, 121], -1, 2, None), // "edly"
    Among(&[101, 101, 100, 108, 121], 3, 1, None), // "eedly"
    Among(&[105, 110, 103, 108, 121], -1, 2, None), // "ingly"
];

static A_5: &'static [Among<Context>; 24] = &[
    Among(&[97, 110, 99, 105], -1, 3, None), // "anci"
    Among(&[101, 110, 99, 105], -1, 2, None), // "enci"
    Among(&[111, 103, 105], -1, 13, None), // "ogi"
    Among(&[108, 105], -1, 15, None), // "li"
    Among(&[98, 108, 105], 3, 12, None), // "bli"
    Among(&[97, 98, 108, 105], 4, 4, None), // "abli"
    Among(&[97, 108, 108, 105], 3, 8, None), // "alli"
    Among(&[102, 117, 108, 108, 105], 3, 9, None), // "fulli"
    Among(&[108, 101, 115, 115, 108, 105], 3, 14, None), // "lessli"
    Among(&[111, 117, 115, 108, 105], 3, 10, None), // "ousli"
    Among(&[101, 110, 116, 108, 105], 3, 5, None), // "entli"
    Among(&[97, 108, 105, 116, 105], -1, 8, None), // "aliti"
    Among(&[98, 105, 108, 105, 116, 105], -1, 12, None), // "biliti"
    Among(&[105, 118, 105, 116, 105], -1, 11, None), // "iviti"
    Among(&[116, 105, 111, 110, 97, 108], -1, 1, None), // "tional"
    Among(&[97, 116, 105, 111, 110, 97, 108], 14, 7, None), // "ational"
    Among(&[97, 108, 105, 115, 109], -1, 8, None), // "alism"
    Among(&[97, 116, 105, 111, 110], -1, 7, None), // "ation"
    Among(&[105, 122, 97, 116, 105, 111, 110], 17, 6, None), // "ization"
    Among(&[105, 122, 101, 114], -1, 6, None), // "izer"
    Among(&[97, 116, 111, 114], -1, 7, None), // "ator"
    Among(&[105, 118, 101, 110, 101, 115, 115], -1, 11, None), // "iveness"
    Among(&[102, 117, 108, 110, 101, 115, 115], -1, 9, None), // "fulness"
    Among(&[111, 117, 115, 110, 101, 115, 115], -1, 10, None), // "ousness"
];

static A_6: &'static [Among<Context>; 9] = &[
    Among(&[105, 99, 97, 116, 101], -1, 4, None), // "icate"
    Among(&[97, 116, 105, 118, 101], -1, 6, None), // "ative"
    Among(&[97, 108, 105, 122, 101], -1, 3, None), // "alize"
    Among(&[105, 99, 105, 116, 105], -1, 4, None), // "iciti"
    Among(&[105, 99, 97, 108], -1, 4, None), // "ical"
    Among(&[116, 105, 111, 110, 97, 108], -1, 1, None), // "tional"
    Among(&[97, 116, 105, 111, 110, 97, 108], 5, 2, None), // "ational"
    Among(&[102, 117, 108], -1, 5, None), // "ful"
    Among(&[110, 101, 115, 115], -1, 5, None), // "ness"
];

static A_7: &'static [Among<Context>; 18] = &[
    Among(&[105, 99], -1, 1, None), // "ic"
    Among(&[97, 110, 99, 101], -1, 1, None), // "ance"
    Among(&[101, 110, 99, 101], -1, 1, None), // "ence"
    Among(&[97, 98, 108, 101], -1, 1, None), // "able"
    Among(&[105, 98, 108, 101], -1, 1, None), // "ible"
    Among(&[97, 116, 101], -1, 1, None), // "ate"
    Among(&[105, 118, 101], -1, 1, None), // "ive"
    Among(&[105, 122, 101], -1, 1, None), // "ize"
    Among(&[105, 116, 105], -1, 1, None), // "iti"
    Among(&[97, 108], -1, 1, None), // "al"
    Among(&[105, 115, 109], -1, 1, None), // "ism"
    Among(&[105, 111, 110], -1, 2, None), // "ion"
    Among(&[101, 114], -1, 1, None), // "er"
    Among(&[111, 117, 115], -1, 1, None), // "ous"
    Among(&[97, 110, 116], -1, 1, None), // "ant"
    Among(&[101, 110, 116], -1, 1, None), // "ent"
    Among(&[109, 101, 110, 116], 15, 1, None), // "ment"
    Among(&[101, 109, 101, 110, 116], 16, 1, None), // "ement"
];

static A_8: &'static [Among<Context>; 2] = &[
    Among(&[101], -1, 1, None), // "e"
    Among(&[108], -1, 2, None), // "l"
];

static A_9: &'static [Among<Context>; 8] = &[
    Among(&[115, 117, 99, 99, 101, 101, 100], -1, -1, None), // "succeed"
    Among(&[112, 114, 111, 99, 101, 101, 100], -1, -1, None), // "proceed"
    Among(&[101, 120, 99, 101, 101, 100], -1, -1, None), // "exceed"
    Among(&[99, 97, 110, 110, 105, 110, 103], -1, -1, None), // "canning"
    Among(&[105, 110, 110, 105, 110, 103], -1, -1, None), // "inning"
    Among(&[101, 97, 114, 114, 105, 110, 103], -1, -1, None), // "earring"
    Among(&[104, 101, 114, 114, 105, 110, 103], -1, -1, None), // "herring"
    Among(&[111, 117, 116, 105, 110, 103], -1, -1, None), // "outing"
];

static A_10: &'static [Among<Context>; 18] = &[
    Among(&[97, 110, 100, 101, 115], -1, -1, None), // "andes"
    Among(&[97, 116, 108, 97, 115], -1, -1, None), // "atlas"
    Among(&[98, 105, 97, 115], -1, -1, None), // "bias"
    Among(&[99, 111, 115, 109, 111, 115], -1, -1, None), // "cosmos"
    Among(&[100, 121, 105, 110, 103], -1, 3, None), // "dying"
    Among(&[101, 97, 114, 108, 121], -1, 9, None), // "early"
    Among(&[103, 101, 110, 116, 108, 121], -1, 7, None), // "gently"
    Among(&[104, 111, 119, 101], -1, -1, None), // "howe"
    Among(&[105, 100, 108, 121], -1, 6, None), // "idly"
    Among(&[108, 121, 105, 110, 103], -1, 4, None), // "lying"
    Among(&[110, 101, 119, 115], -1, -1, None), // "news"
    Among(&[111, 110, 108, 121], -1, 10, None), // "only"
    Among(&[115, 105, 110, 103, 108, 121], -1, 11, None), // "singly"
    Among(&[115, 107, 105, 101, 115], -1, 2, None), // "skies"
    Among(&[115, 107, 105, 115], -1, 1, None), // "skis"
    Among(&[115, 107, 121], -1, -1, None), // "sky"
    Among(&[116, 121, 105, 110, 103], -1, 5, None), // "tying"
    Among(&[117, 103, 108, 121], -1, 8, None), // "ugly"
];

static G_aeo: &'static [u8; 2] = &[17, 64];

static G_v: &'static [u8; 4] = &[17, 65, 16, 1];

static G_v_WXY: &'static [u8; 5] = &[1, 17, 65, 208, 1];

static G_valid_LI: &'static [u8; 3] = &[55, 141, 2];

#[derive(Clone)]
struct Context {
    b_Y_found: bool,
    i_p2: i32,
    i_p1: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.b_Y_found = false;
    let v_1 = env.cursor;
    'lab0: loop {
        env.bra = env.cursor;
        if !env.eq_s(&[39]) {
            break 'lab0;
        }
        env.ket = env.cursor;
        env.slice_del();
        break 'lab0;
    }
    env.cursor = v_1;
    let v_2 = env.cursor;
    'lab1: loop {
        env.bra = env.cursor;
        if !env.eq_s(&[121]) {
            break 'lab1;
        }
        env.ket = env.cursor;
        env.slice_from(&[89]);
        context.b_Y_found = true;
        break 'lab1;
    }
    env.cursor = v_2;
    let v_3 = env.cursor;
    'lab2: loop {
        'replab3: loop{
            let v_4 = env.cursor;
            'lab4: for _ in 0..1 {
                'golab5: loop {
                    let v_5 = env.cursor;
                    'lab6: loop {
                        if !env.in_grouping(G_v, 97, 121) {
                            break 'lab6;
                        }
                        env.bra = env.cursor;
                        if !env.eq_s(&[121]) {
                            break 'lab6;
                        }
                        env.ket = env.cursor;
                        env.cursor = v_5;
                        break 'golab5;
                    }
                    env.cursor = v_5;
                    if env.cursor >= env.limit {
                        break 'lab4;
                    }
                    env.next_char();
                }
                env.slice_from(&[89]);
                context.b_Y_found = true;
                continue 'replab3;
            }
            env.cursor = v_4;
            break 'replab3;
        }
        break 'lab2;
    }
    env.cursor = v_3;
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if env.find_among(A_0, context) == 0 {
                    break 'lab2;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            'golab3: loop {
                'lab4: loop {
                    if !env.in_grouping(G_v, 97, 121) {
                        break 'lab4;
                    }
                    break 'golab3;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
            }
            'golab5: loop {
                'lab6: loop {
                    if !env.out_grouping(G_v, 97, 121) {
                        break 'lab6;
                    }
                    break 'golab5;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
            }
            break 'lab1;
        }
        context.i_p1 = env.cursor;
        'golab7: loop {
            'lab8: loop {
                if !env.in_grouping(G_v, 97, 121) {
                    break 'lab8;
                }
                break 'golab7;
            }
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
        }
        'golab9: loop {
            'lab10: loop {
                if !env.out_grouping(G_v, 97, 121) {
                    break 'lab10;
                }
                break 'golab9;
            }
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    return true
}

fn r_shortv(env: &mut SnowballEnv, context: &mut Context) -> bool {
    'lab0: loop {
        let v_1 = env.limit - env.cursor;
        'lab1: loop {
            if !env.out_grouping_b(G_v_WXY, 89, 121) {
                break 'lab1;
            }
            if !env.in_grouping_b(G_v, 97, 121) {
                break 'lab1;
            }
            if !env.out_grouping_b(G_v, 97, 121) {
                break 'lab1;
            }
            break 'lab0;
        }
        env.cursor = env.limit - v_1;
        if !env.out_grouping_b(G_v, 97, 121) {
            return false;
        }
        if !env.in_grouping_b(G_v, 97, 121) {
            return false;
        }
        if env.cursor > env.limit_backward {
            return false;
        }
        break 'lab0;
    }
    return true
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_Step_1a(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        if env.find_among_b(A_1, context) == 0 {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.bra = env.cursor;
        env.slice_del();
        break 'lab0;
    }
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            env.slice_from(&[115, 115]);
        }
        2 => {
            'lab1: loop {
                let v_2 = env.limit - env.cursor;
                'lab2: loop {
                    if !env.hop_back(2) {
                        break 'lab2;
                    }
                    env.slice_from(&[105]);
                    break 'lab1;
                }
                env.cursor = env.limit - v_2;
                env.slice_from(&[105, 101]);
                break 'lab1;
            }
        }
        3 => {
            if env.cursor <= env.limit_backward {
                return false;
            }
            env.previous_char();
            'golab3: loop {
                'lab4: loop {
                    if !env.in_grouping_b(G_v, 97, 121) {
                        break 'lab4;
                    }
                    break 'golab3;
                }
                if env.cursor <= env.limit_backward {
                    return false;
                }
                env.previous_char();
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_Step_1b(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_4, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R1(env, context) {
                return false;
            }
            env.slice_from(&[101, 101]);
        }
        2 => {
            let v_1 = env.limit - env.cursor;
            'golab0: loop {
                'lab1: loop {
                    if !env.in_grouping_b(G_v, 97, 121) {
                        break 'lab1;
                    }
                    break 'golab0;
                }
                if env.cursor <= env.limit_backward {
                    return false;
                }
                env.previous_char();
            }
            env.cursor = env.limit - v_1;
            env.slice_del();
            env.ket = env.cursor;
            env.bra = env.cursor;
            let v_3 = env.limit - env.cursor;
            among_var = env.find_among_b(A_3, context);
            match among_var {
                1 => {
                    env.slice_from(&[101]);
                    return false;
                }
                2 => {
                    let v_4 = env.limit - env.cursor;
                    'lab2: loop {
                        if !env.in_grouping_b(G_aeo, 97, 111) {
                            break 'lab2;
                        }
                        if env.cursor > env.limit_backward {
                            break 'lab2;
                        }
                        return false;
                    }
                    env.cursor = env.limit - v_4;
                }
                3 => {
                    if env.cursor != context.i_p1 {
                        return false;
                    }
                    let v_5 = env.limit - env.cursor;
                    if !r_shortv(env, context) {
                        return false;
                    }
                    env.cursor = env.limit - v_5;
                    env.slice_from(&[101]);
                    return false;
                }
                _ => ()
            }
            env.cursor = env.limit - v_3;
            env.ket = env.cursor;
            if env.cursor <= env.limit_backward {
                return false;
            }
            env.previous_char();
            env.bra = env.cursor;
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_Step_1c(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    'lab0: loop {
        let v_1 = env.limit - env.cursor;
        'lab1: loop {
            if !env.eq_s_b(&[121]) {
                break 'lab1;
            }
            break 'lab0;
        }
        env.cursor = env.limit - v_1;
        if !env.eq_s_b(&[89]) {
            return false;
        }
        break 'lab0;
    }
    env.bra = env.cursor;
    if !env.out_grouping_b(G_v, 97, 121) {
        return false;
    }
    'lab2: loop {
        if env.cursor > env.limit_backward {
            break 'lab2;
        }
        return false;
    }
    env.slice_from(&[105]);
    return true
}

fn r_Step_2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_5, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R1(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_from(&[116, 105, 111, 110]);
        }
        2 => {
            env.slice_from(&[101, 110, 99, 101]);
        }
        3 => {
            env.slice_from(&[97, 110, 99, 101]);
        }
        4 => {
            env.slice_from(&[97, 98, 108, 101]);
        }
        5 => {
            env.slice_from(&[101, 110, 116]);
        }
        6 => {
            env.slice_from(&[105, 122, 101]);
        }
        7 => {
            env.slice_from(&[97, 116, 101]);
        }
        8 => {
            env.slice_from(&[97, 108]);
        }
        9 => {
            env.slice_from(&[102, 117, 108]);
        }
        10 => {
            env.slice_from(&[111, 117, 115]);
        }
        11 => {
            env.slice_from(&[105, 118, 101]);
        }
        12 => {
            env.slice_from(&[98, 108, 101]);
        }
        13 => {
            if !env.eq_s_b(&[108]) {
                return false;
            }
            env.slice_from(&[111, 103]);
        }
        14 => {
            env.slice_from(&[108, 101, 115, 115]);
        }
        15 => {
            if !env.in_grouping_b(G_valid_LI, 99, 116) {
                return false;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_Step_3(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_6, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R1(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_from(&[116, 105, 111, 110]);
        }
        2 => {
            env.slice_from(&[97, 116, 101]);
        }
        3 => {
            env.slice_from(&[97, 108]);
        }
        4 => {
            env.slice_from(&[105, 99]);
        }
        5 => {
            env.slice_del();
        }
        6 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_Step_4(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_7, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R2(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.eq_s_b(&[115]) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                if !env.eq_s_b(&[116]) {
                    return false;
                }
                break 'lab0;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_Step_5(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_8, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    if !r_R2(env, context) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                if !r_R1(env, context) {
                    return false;
                }
                let v_2 = env.limit - env.cursor;
                'lab2: loop {
                    if !r_shortv(env, context) {
                        break 'lab2;
                    }
                    return false;
                }
                env.cursor = env.limit - v_2;
                break 'lab0;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            if !env.eq_s_b(&[108]) {
                return false;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_exception2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_9, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    if env.cursor > env.limit_backward {
        return false;
    }
    return true
}

fn r_exception1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.bra = env.cursor;
    among_var = env.find_among(A_10, context);
    if among_var == 0 {
        return false;
    }
    env.ket = env.cursor;
    if env.cursor < env.limit {
        return false;
    }
    match among_var {
        1 => {
            env.slice_from(&[115, 107, 105]);
        }
        2 => {
            env.slice_from(&[115, 107, 121]);
        }
        3 => {
            env.slice_from(&[100, 105, 101]);
        }
        4 => {
            env.slice_from(&[108, 105, 101]);
        }
        5 => {
            env.slice_from(&[116, 105, 101]);
        }
        6 => {
            env.slice_from(&[105, 100, 108]);
        }
        7 => {
            env.slice_from(&[103, 101, 110, 116, 108]);
        }
        8 => {
            env.slice_from(&[117, 103, 108, 105]);
        }
        9 => {
            env.slice_from(&[101, 97, 114, 108, 105]);
        }
        10 => {
            env.slice_from(&[111, 110, 108, 105]);
        }
        11 => {
            env.slice_from(&[115, 105, 110, 103, 108]);
        }
        _ => ()
    }
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !context.b_Y_found {
        return false;
    }
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            'golab2: loop {
                let v_2 = env.cursor;
                'lab3: loop {
                    env.bra = env.cursor;
                    if !env.eq_s(&[89]) {
                        break 'lab3;
                    }
                    env.ket = env.cursor;
                    env.cursor = v_2;
                    break 'golab2;
                }
                env.cursor = v_2;
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            env.slice_from(&[121]);
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        b_Y_found: false,
        i_p2: 0,
        i_p1: 0,
    };
    'lab0: loop {
        let v_1 = env.cursor;
        'lab1: loop {
            if !r_exception1(env, context) {
                break 'lab1;
            }
            break 'lab0;
        }
        env.cursor = v_1;
        'lab2: loop {
            let v_2 = env.cursor;
            'lab3: loop {
                if !env.hop(3) {
                    break 'lab3;
                }
                break 'lab2;
            }
            env.cursor = v_2;
            break 'lab0;
        }
        env.cursor = v_1;
        r_prelude(env, context);
        r_mark_regions(env, context);
        env.limit_backward = env.cursor;
        env.cursor = env.limit;
        let v_5 = env.limit - env.cursor;
        r_Step_1a(env, context);
        env.cursor = env.limit - v_5;
        'lab4: loop {
            let v_6 = env.limit - env.cursor;
            'lab5: loop {
                if !r_exception2(env, context) {
                    break 'lab5;
                }
                break 'lab4;
            }
            env.cursor = env.limit - v_6;
            let v_7 = env.limit - env.cursor;
            r_Step_1b(env, context);
            env.cursor = env.limit - v_7;
            let v_8 = env.limit - env.cursor;
            r_Step_1c(env, context);
            env.cursor = env.limit - v_8;
            let v_9 = env.limit - env.cursor;
            r_Step_2(env, context);
            env.cursor = env.limit - v_9;
            let v_10 = env.limit - env.cursor;
            r_Step_3(env, context);
            env.cursor = env.limit - v_10;
            let v_11 = env.limit - env.cursor;
            r_Step_4(env, context);
            env.cursor = env.limit - v_11;
            let v_12 = env.limit - env.cursor;
            r_Step_5(env, context);
            env.cursor = env.limit - v_12;
            break 'lab4;
        }
        env.cursor = env.limit_backward;
        let v_13 = env.cursor;
        r_postlude(env, context);
        env.cursor = v_13;
        break 'lab0;
    }
    return true
}
