//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 3] = &[
    Among(&[99, 111, 108], -1, -1, None), // "col"
    Among(&[112, 97, 114], -1, -1, None), // "par"
    Among(&[116, 97, 112], -1, -1, None), // "tap"
];

static A_1: &'static [Among<Context>; 7] = &[
    Among(&[], -1, 7, None), // ""
    Among(&[72], 0, 6, None), // "H"
    Among(&[72, 101], 1, 4, None), // "He"
    Among(&[72, 105], 1, 5, None), // "Hi"
    Among(&[73], 0, 1, None), // "I"
    Among(&[85], 0, 2, None), // "U"
    Among(&[89], 0, 3, None), // "Y"
];

static A_2: &'static [Among<Context>; 6] = &[
    Among(&[105, 113, 85], -1, 3, None), // "iqU"
    Among(&[97, 98, 108], -1, 3, None), // "abl"
    Among(&[73, 232, 114], -1, 4, None), // "I\u{00E8}r"
    Among(&[105, 232, 114], -1, 4, None), // "i\u{00E8}r"
    Among(&[101, 117, 115], -1, 2, None), // "eus"
    Among(&[105, 118], -1, 1, None), // "iv"
];

static A_3: &'static [Among<Context>; 3] = &[
    Among(&[105, 99], -1, 2, None), // "ic"
    Among(&[97, 98, 105, 108], -1, 1, None), // "abil"
    Among(&[105, 118], -1, 3, None), // "iv"
];

static A_4: &'static [Among<Context>; 43] = &[
    Among(&[105, 113, 85, 101], -1, 1, None), // "iqUe"
    Among(&[97, 116, 114, 105, 99, 101], -1, 2, None), // "atrice"
    Among(&[97, 110, 99, 101], -1, 1, None), // "ance"
    Among(&[101, 110, 99, 101], -1, 5, None), // "ence"
    Among(&[108, 111, 103, 105, 101], -1, 3, None), // "logie"
    Among(&[97, 98, 108, 101], -1, 1, None), // "able"
    Among(&[105, 115, 109, 101], -1, 1, None), // "isme"
    Among(&[101, 117, 115, 101], -1, 11, None), // "euse"
    Among(&[105, 115, 116, 101], -1, 1, None), // "iste"
    Among(&[105, 118, 101], -1, 8, None), // "ive"
    Among(&[105, 102], -1, 8, None), // "if"
    Among(&[117, 115, 105, 111, 110], -1, 4, None), // "usion"
    Among(&[97, 116, 105, 111, 110], -1, 2, None), // "ation"
    Among(&[117, 116, 105, 111, 110], -1, 4, None), // "ution"
    Among(&[97, 116, 101, 117, 114], -1, 2, None), // "ateur"
    Among(&[105, 113, 85, 101, 115], -1, 1, None), // "iqUes"
    Among(&[97, 116, 114, 105, 99, 101, 115], -1, 2, None), // "atrices"
    Among(&[97, 110, 99, 101, 115], -1, 1, None), // "ances"
    Among(&[101, 110, 99, 101, 115], -1, 5, None), // "ences"
    Among(&[108, 111, 103, 105, 101, 115], -1, 3, None), // "logies"
    Among(&[97, 98, 108, 101, 115], -1, 1, None), // "ables"
    Among(&[105, 115, 109, 101, 115], -1, 1, None), // "ismes"
    Among(&[101, 117, 115, 101, 115], -1, 11, None), // "euses"
    Among(&[105, 115, 116, 101, 115], -1, 1, None), // "istes"
    Among(&[105, 118, 101, 115], -1, 8, None), // "ives"
    Among(&[105, 102, 115], -1, 8, None), // "ifs"
    Among(&[117, 115, 105, 111, 110, 115], -1, 4, None), // "usions"
    Among(&[97, 116, 105, 111, 110, 115], -1, 2, None), // "ations"
    Among(&[117, 116, 105, 111, 110, 115], -1, 4, None), // "utions"
    Among(&[97, 116, 101, 117, 114, 115], -1, 2, None), // "ateurs"
    Among(&[109, 101, 110, 116, 115], -1, 15, None), // "ments"
    Among(&[101, 109, 101, 110, 116, 115], 30, 6, None), // "ements"
    Among(&[105, 115, 115, 101, 109, 101, 110, 116, 115], 31, 12, None), // "issements"
    Among(&[105, 116, 233, 115], -1, 7, None), // "it\u{00E9}s"
    Among(&[109, 101, 110, 116], -1, 15, None), // "ment"
    Among(&[101, 109, 101, 110, 116], 34, 6, None), // "ement"
    Among(&[105, 115, 115, 101, 109, 101, 110, 116], 35, 12, None), // "issement"
    Among(&[97, 109, 109, 101, 110, 116], 34, 13, None), // "amment"
    Among(&[101, 109, 109, 101, 110, 116], 34, 14, None), // "emment"
    Among(&[97, 117, 120], -1, 10, None), // "aux"
    Among(&[101, 97, 117, 120], 39, 9, None), // "eaux"
    Among(&[101, 117, 120], -1, 1, None), // "eux"
    Among(&[105, 116, 233], -1, 7, None), // "it\u{00E9}"
];

static A_5: &'static [Among<Context>; 35] = &[
    Among(&[105, 114, 97], -1, 1, None), // "ira"
    Among(&[105, 101], -1, 1, None), // "ie"
    Among(&[105, 115, 115, 101], -1, 1, None), // "isse"
    Among(&[105, 115, 115, 97, 110, 116, 101], -1, 1, None), // "issante"
    Among(&[105], -1, 1, None), // "i"
    Among(&[105, 114, 97, 105], 4, 1, None), // "irai"
    Among(&[105, 114], -1, 1, None), // "ir"
    Among(&[105, 114, 97, 115], -1, 1, None), // "iras"
    Among(&[105, 101, 115], -1, 1, None), // "ies"
    Among(&[238, 109, 101, 115], -1, 1, None), // "\u{00EE}mes"
    Among(&[105, 115, 115, 101, 115], -1, 1, None), // "isses"
    Among(&[105, 115, 115, 97, 110, 116, 101, 115], -1, 1, None), // "issantes"
    Among(&[238, 116, 101, 115], -1, 1, None), // "\u{00EE}tes"
    Among(&[105, 115], -1, 1, None), // "is"
    Among(&[105, 114, 97, 105, 115], 13, 1, None), // "irais"
    Among(&[105, 115, 115, 97, 105, 115], 13, 1, None), // "issais"
    Among(&[105, 114, 105, 111, 110, 115], -1, 1, None), // "irions"
    Among(&[105, 115, 115, 105, 111, 110, 115], -1, 1, None), // "issions"
    Among(&[105, 114, 111, 110, 115], -1, 1, None), // "irons"
    Among(&[105, 115, 115, 111, 110, 115], -1, 1, None), // "issons"
    Among(&[105, 115, 115, 97, 110, 116, 115], -1, 1, None), // "issants"
    Among(&[105, 116], -1, 1, None), // "it"
    Among(&[105, 114, 97, 105, 116], 21, 1, None), // "irait"
    Among(&[105, 115, 115, 97, 105, 116], 21, 1, None), // "issait"
    Among(&[105, 115, 115, 97, 110, 116], -1, 1, None), // "issant"
    Among(&[105, 114, 97, 73, 101, 110, 116], -1, 1, None), // "iraIent"
    Among(&[105, 115, 115, 97, 73, 101, 110, 116], -1, 1, None), // "issaIent"
    Among(&[105, 114, 101, 110, 116], -1, 1, None), // "irent"
    Among(&[105, 115, 115, 101, 110, 116], -1, 1, None), // "issent"
    Among(&[105, 114, 111, 110, 116], -1, 1, None), // "iront"
    Among(&[238, 116], -1, 1, None), // "\u{00EE}t"
    Among(&[105, 114, 105, 101, 122], -1, 1, None), // "iriez"
    Among(&[105, 115, 115, 105, 101, 122], -1, 1, None), // "issiez"
    Among(&[105, 114, 101, 122], -1, 1, None), // "irez"
    Among(&[105, 115, 115, 101, 122], -1, 1, None), // "issez"
];

static A_6: &'static [Among<Context>; 38] = &[
    Among(&[97], -1, 3, None), // "a"
    Among(&[101, 114, 97], 0, 2, None), // "era"
    Among(&[97, 115, 115, 101], -1, 3, None), // "asse"
    Among(&[97, 110, 116, 101], -1, 3, None), // "ante"
    Among(&[233, 101], -1, 2, None), // "\u{00E9}e"
    Among(&[97, 105], -1, 3, None), // "ai"
    Among(&[101, 114, 97, 105], 5, 2, None), // "erai"
    Among(&[101, 114], -1, 2, None), // "er"
    Among(&[97, 115], -1, 3, None), // "as"
    Among(&[101, 114, 97, 115], 8, 2, None), // "eras"
    Among(&[226, 109, 101, 115], -1, 3, None), // "\u{00E2}mes"
    Among(&[97, 115, 115, 101, 115], -1, 3, None), // "asses"
    Among(&[97, 110, 116, 101, 115], -1, 3, None), // "antes"
    Among(&[226, 116, 101, 115], -1, 3, None), // "\u{00E2}tes"
    Among(&[233, 101, 115], -1, 2, None), // "\u{00E9}es"
    Among(&[97, 105, 115], -1, 3, None), // "ais"
    Among(&[101, 114, 97, 105, 115], 15, 2, None), // "erais"
    Among(&[105, 111, 110, 115], -1, 1, None), // "ions"
    Among(&[101, 114, 105, 111, 110, 115], 17, 2, None), // "erions"
    Among(&[97, 115, 115, 105, 111, 110, 115], 17, 3, None), // "assions"
    Among(&[101, 114, 111, 110, 115], -1, 2, None), // "erons"
    Among(&[97, 110, 116, 115], -1, 3, None), // "ants"
    Among(&[233, 115], -1, 2, None), // "\u{00E9}s"
    Among(&[97, 105, 116], -1, 3, None), // "ait"
    Among(&[101, 114, 97, 105, 116], 23, 2, None), // "erait"
    Among(&[97, 110, 116], -1, 3, None), // "ant"
    Among(&[97, 73, 101, 110, 116], -1, 3, None), // "aIent"
    Among(&[101, 114, 97, 73, 101, 110, 116], 26, 2, None), // "eraIent"
    Among(&[232, 114, 101, 110, 116], -1, 2, None), // "\u{00E8}rent"
    Among(&[97, 115, 115, 101, 110, 116], -1, 3, None), // "assent"
    Among(&[101, 114, 111, 110, 116], -1, 2, None), // "eront"
    Among(&[226, 116], -1, 3, None), // "\u{00E2}t"
    Among(&[101, 122], -1, 2, None), // "ez"
    Among(&[105, 101, 122], 32, 2, None), // "iez"
    Among(&[101, 114, 105, 101, 122], 33, 2, None), // "eriez"
    Among(&[97, 115, 115, 105, 101, 122], 33, 3, None), // "assiez"
    Among(&[101, 114, 101, 122], 32, 2, None), // "erez"
    Among(&[233], -1, 2, None), // "\u{00E9}"
];

static A_7: &'static [Among<Context>; 6] = &[
    Among(&[101], -1, 3, None), // "e"
    Among(&[73, 232, 114, 101], 0, 2, None), // "I\u{00E8}re"
    Among(&[105, 232, 114, 101], 0, 2, None), // "i\u{00E8}re"
    Among(&[105, 111, 110], -1, 1, None), // "ion"
    Among(&[73, 101, 114], -1, 2, None), // "Ier"
    Among(&[105, 101, 114], -1, 2, None), // "ier"
];

static A_8: &'static [Among<Context>; 5] = &[
    Among(&[101, 108, 108], -1, -1, None), // "ell"
    Among(&[101, 105, 108, 108], -1, -1, None), // "eill"
    Among(&[101, 110, 110], -1, -1, None), // "enn"
    Among(&[111, 110, 110], -1, -1, None), // "onn"
    Among(&[101, 116, 116], -1, -1, None), // "ett"
];

static G_v: &'static [u8; 20] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 130, 103, 8, 5];

static G_keep_with_s: &'static [u8; 17] = &[1, 65, 20, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128];

#[derive(Clone)]
struct Context {
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            'golab2: loop {
                let v_2 = env.cursor;
                'lab3: loop {
                    'lab4: loop {
                        let v_3 = env.cursor;
                        'lab5: loop {
                            if !env.in_grouping(G_v, 97, 251) {
                                break 'lab5;
                            }
                            env.bra = env.cursor;
                            'lab6: loop {
                                let v_4 = env.cursor;
                                'lab7: loop {
                                    if !env.eq_s(&[117]) {
                                        break 'lab7;
                                    }
                                    env.ket = env.cursor;
                                    if !env.in_grouping(G_v, 97, 251) {
                                        break 'lab7;
                                    }
                                    env.slice_from(&[85]);
                                    break 'lab6;
                                }
                                env.cursor = v_4;
                                'lab8: loop {
                                    if !env.eq_s(&[105]) {
                                        break 'lab8;
                                    }
                                    env.ket = env.cursor;
                                    if !env.in_grouping(G_v, 97, 251) {
                                        break 'lab8;
                                    }
                                    env.slice_from(&[73]);
                                    break 'lab6;
                                }
                                env.cursor = v_4;
                                if !env.eq_s(&[121]) {
                                    break 'lab5;
                                }
                                env.ket = env.cursor;
                                env.slice_from(&[89]);
                                break 'lab6;
                            }
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab9: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&[235]) {
                                break 'lab9;
                            }
                            env.ket = env.cursor;
                            env.slice_from(&[72, 101]);
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab10: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&[239]) {
                                break 'lab10;
                            }
                            env.ket = env.cursor;
                            env.slice_from(&[72, 105]);
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        'lab11: loop {
                            env.bra = env.cursor;
                            if !env.eq_s(&[121]) {
                                break 'lab11;
                            }
                            env.ket = env.cursor;
                            if !env.in_grouping(G_v, 97, 251) {
                                break 'lab11;
                            }
                            env.slice_from(&[89]);
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        if !env.eq_s(&[113]) {
                            break 'lab3;
                        }
                        env.bra = env.cursor;
                        if !env.eq_s(&[117]) {
                            break 'lab3;
                        }
                        env.ket = env.cursor;
                        env.slice_from(&[85]);
                        break 'lab4;
                    }
                    env.cursor = v_2;
                    break 'golab2;
                }
                env.cursor = v_2;
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab2;
                }
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab2;
                }
                if env.cursor >= env.limit {
                    break 'lab2;
                }
                env.next_char();
                break 'lab1;
            }
            env.cursor = v_2;
            'lab3: loop {
                if env.find_among(A_0, context) == 0 {
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
            'golab4: loop {
                'lab5: loop {
                    if !env.in_grouping(G_v, 97, 251) {
                        break 'lab5;
                    }
                    break 'golab4;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_4 = env.cursor;
    'lab6: loop {
        'golab7: loop {
            'lab8: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab8;
                }
                break 'golab7;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        'golab9: loop {
            'lab10: loop {
                if !env.out_grouping(G_v, 97, 251) {
                    break 'lab10;
                }
                break 'golab9;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab11: loop {
            'lab12: loop {
                if !env.in_grouping(G_v, 97, 251) {
                    break 'lab12;
                }
                break 'golab11;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        'golab13: loop {
            'lab14: loop {
                if !env.out_grouping(G_v, 97, 251) {
                    break 'lab14;
                }
                break 'golab13;
            }
            if env.cursor >= env.limit {
                break 'lab6;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab6;
    }
    env.cursor = v_4;
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[105]);
                }
                2 => {
                    env.slice_from(&[117]);
                }
                3 => {
                    env.slice_from(&[121]);
                }
                4 => {
                    env.slice_from(&[235]);
                }
                5 => {
                    env.slice_from(&[239]);
                }
                6 => {
                    env.slice_del();
                }
                7 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_pV <= env.cursor
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_4, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_1 = env.limit - env.cursor;
            'lab0: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[105, 99]) {
                    env.cursor = env.limit - v_1;
                    break 'lab0;
                }
                env.bra = env.cursor;
                'lab1: loop {
                    let v_2 = env.limit - env.cursor;
                    'lab2: loop {
                        if !r_R2(env, context) {
                            break 'lab2;
                        }
                        env.slice_del();
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_2;
                    env.slice_from(&[105, 113, 85]);
                    break 'lab1;
                }
                break 'lab0;
            }
        }
        3 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[108, 111, 103]);
        }
        4 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[117]);
        }
        5 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[101, 110, 116]);
        }
        6 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
            let v_3 = env.limit - env.cursor;
            'lab3: loop {
                env.ket = env.cursor;
                among_var = env.find_among_b(A_2, context);
                if among_var == 0 {
                    env.cursor = env.limit - v_3;
                    break 'lab3;
                }
                env.bra = env.cursor;
                match among_var {
                    1 => {
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_3;
                            break 'lab3;
                        }
                        env.slice_del();
                        env.ket = env.cursor;
                        if !env.eq_s_b(&[97, 116]) {
                            env.cursor = env.limit - v_3;
                            break 'lab3;
                        }
                        env.bra = env.cursor;
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_3;
                            break 'lab3;
                        }
                        env.slice_del();
                    }
                    2 => {
                        'lab4: loop {
                            let v_4 = env.limit - env.cursor;
                            'lab5: loop {
                                if !r_R2(env, context) {
                                    break 'lab5;
                                }
                                env.slice_del();
                                break 'lab4;
                            }
                            env.cursor = env.limit - v_4;
                            if !r_R1(env, context) {
                                env.cursor = env.limit - v_3;
                                break 'lab3;
                            }
                            env.slice_from(&[101, 117, 120]);
                            break 'lab4;
                        }
                    }
                    3 => {
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_3;
                            break 'lab3;
                        }
                        env.slice_del();
                    }
                    4 => {
                        if !r_RV(env, context) {
                            env.cursor = env.limit - v_3;
                            break 'lab3;
                        }
                        env.slice_from(&[105]);
                    }
                    _ => ()
                }
                break 'lab3;
            }
        }
        7 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_5 = env.limit - env.cursor;
            'lab6: loop {
                env.ket = env.cursor;
                among_var = env.find_among_b(A_3, context);
                if among_var == 0 {
                    env.cursor = env.limit - v_5;
                    break 'lab6;
                }
                env.bra = env.cursor;
                match among_var {
                    1 => {
                        'lab7: loop {
                            let v_6 = env.limit - env.cursor;
                            'lab8: loop {
                                if !r_R2(env, context) {
                                    break 'lab8;
                                }
                                env.slice_del();
                                break 'lab7;
                            }
                            env.cursor = env.limit - v_6;
                            env.slice_from(&[97, 98, 108]);
                            break 'lab7;
                        }
                    }
                    2 => {
                        'lab9: loop {
                            let v_7 = env.limit - env.cursor;
                            'lab10: loop {
                                if !r_R2(env, context) {
                                    break 'lab10;
                                }
                                env.slice_del();
                                break 'lab9;
                            }
                            env.cursor = env.limit - v_7;
                            env.slice_from(&[105, 113, 85]);
                            break 'lab9;
                        }
                    }
                    3 => {
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_5;
                            break 'lab6;
                        }
                        env.slice_del();
                    }
                    _ => ()
                }
                break 'lab6;
            }
        }
        8 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_8 = env.limit - env.cursor;
            'lab11: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[97, 116]) {
                    env.cursor = env.limit - v_8;
                    break 'lab11;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_8;
                    break 'lab11;
                }
                env.slice_del();
                env.ket = env.cursor;
                if !env.eq_s_b(&[105, 99]) {
                    env.cursor = env.limit - v_8;
                    break 'lab11;
                }
                env.bra = env.cursor;
                'lab12: loop {
                    let v_9 = env.limit - env.cursor;
                    'lab13: loop {
                        if !r_R2(env, context) {
                            break 'lab13;
                        }
                        env.slice_del();
                        break 'lab12;
                    }
                    env.cursor = env.limit - v_9;
                    env.slice_from(&[105, 113, 85]);
                    break 'lab12;
                }
                break 'lab11;
            }
        }
        9 => {
            env.slice_from(&[101, 97, 117]);
        }
        10 => {
            if !r_R1(env, context) {
                return false;
            }
            env.slice_from(&[97, 108]);
        }
        11 => {
            'lab14: loop {
                let v_10 = env.limit - env.cursor;
                'lab15: loop {
                    if !r_R2(env, context) {
                        break 'lab15;
                    }
                    env.slice_del();
                    break 'lab14;
                }
                env.cursor = env.limit - v_10;
                if !r_R1(env, context) {
                    return false;
                }
                env.slice_from(&[101, 117, 120]);
                break 'lab14;
            }
        }
        12 => {
            if !r_R1(env, context) {
                return false;
            }
            if !env.out_grouping_b(G_v, 97, 251) {
                return false;
            }
            env.slice_del();
        }
        13 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_from(&[97, 110, 116]);
            return false;
        }
        14 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_from(&[101, 110, 116]);
            return false;
        }
        15 => {
            let v_11 = env.limit - env.cursor;
            if !env.in_grouping_b(G_v, 97, 251) {
                return false;
            }
            if !r_RV(env, context) {
                return false;
            }
            env.cursor = env.limit - v_11;
            env.slice_del();
            return false;
        }
        _ => ()
    }
    return true
}

fn r_i_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    if env.find_among_b(A_5, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    let v_3 = env.limit - env.cursor;
    'lab0: loop {
        if !env.eq_s_b(&[72]) {
            break 'lab0;
        }
        env.limit_backward = v_2;
        return false;
    }
    env.cursor = env.limit - v_3;
    if !env.out_grouping_b(G_v, 97, 251) {
        env.limit_backward = v_2;
        return false;
    }
    env.slice_del();
    env.limit_backward = v_2;
    return true
}

fn r_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_6, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R2(env, context) {
                env.limit_backward = v_2;
                return false;
            }
            env.slice_del();
        }
        2 => {
            env.slice_del();
        }
        3 => {
            env.slice_del();
            let v_3 = env.limit - env.cursor;
            'lab0: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[101]) {
                    env.cursor = env.limit - v_3;
                    break 'lab0;
                }
                env.bra = env.cursor;
                env.slice_del();
                break 'lab0;
            }
        }
        _ => ()
    }
    env.limit_backward = v_2;
    return true
}

fn r_residual_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        if !env.eq_s_b(&[115]) {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.bra = env.cursor;
        let v_2 = env.limit - env.cursor;
        'lab1: loop {
            let v_3 = env.limit - env.cursor;
            'lab2: loop {
                if !env.eq_s_b(&[72, 105]) {
                    break 'lab2;
                }
                break 'lab1;
            }
            env.cursor = env.limit - v_3;
            if !env.out_grouping_b(G_keep_with_s, 97, 232) {
                env.cursor = env.limit - v_1;
                break 'lab0;
            }
            break 'lab1;
        }
        env.cursor = env.limit - v_2;
        env.slice_del();
        break 'lab0;
    }
    if env.cursor < context.i_pV {
        return false;
    }
    let v_5 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_7, context);
    if among_var == 0 {
        env.limit_backward = v_5;
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R2(env, context) {
                env.limit_backward = v_5;
                return false;
            }
            'lab3: loop {
                let v_6 = env.limit - env.cursor;
                'lab4: loop {
                    if !env.eq_s_b(&[115]) {
                        break 'lab4;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_6;
                if !env.eq_s_b(&[116]) {
                    env.limit_backward = v_5;
                    return false;
                }
                break 'lab3;
            }
            env.slice_del();
        }
        2 => {
            env.slice_from(&[105]);
        }
        3 => {
            env.slice_del();
        }
        _ => ()
    }
    env.limit_backward = v_5;
    return true
}

fn r_un_double(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.limit - env.cursor;
    if env.find_among_b(A_8, context) == 0 {
        return false;
    }
    env.cursor = env.limit - v_1;
    env.ket = env.cursor;
    if env.cursor <= env.limit_backward {
        return false;
    }
    env.previous_char();
    env.bra = env.cursor;
    env.slice_del();
    return true
}

fn r_un_accent(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut v_1 = 1;
    'replab0: loop{
        'lab1: for _ in 0..1 {
            if !env.out_grouping_b(G_v, 97, 251) {
                break 'lab1;
            }
            v_1 -= 1;
            continue 'replab0;
        }
        break 'replab0;
    }
    if v_1 > 0 {
        return false;
    }
    env.ket = env.cursor;
    'lab2: loop {
        let v_3 = env.limit - env.cursor;
        'lab3: loop {
            if !env.eq_s_b(&[233]) {
                break 'lab3;
            }
            break 'lab2;
        }
        env.cursor = env.limit - v_3;
        if !env.eq_s_b(&[232]) {
            return false;
        }
        break 'lab2;
    }
    env.bra = env.cursor;
    env.slice_from(&[101]);
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    let v_1 = env.cursor;
    r_prelude(env, context);
    env.cursor = v_1;
    r_mark_regions(env, context);
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_3 = env.limit - env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_4 = env.limit - env.cursor;
            'lab2: loop {
                let v_5 = env.limit - env.cursor;
                'lab3: loop {
                    let v_6 = env.limit - env.cursor;
                    'lab4: loop {
                        if !r_standard_suffix(env, context) {
                            break 'lab4;
                        }
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_6;
                    'lab5: loop {
                        if !r_i_verb_suffix(env, context) {
                            break 'lab5;
                        }
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_6;
                    if !r_verb_suffix(env, context) {
                        break 'lab2;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_5;
                let v_7 = env.limit - env.cursor;
                'lab6: loop {
                    env.ket = env.cursor;
                    'lab7: loop {
                        let v_8 = env.limit - env.cursor;
                        'lab8: loop {
                            if !env.eq_s_b(&[89]) {
                                break 'lab8;
                            }
                            env.bra = env.cursor;
                            env.slice_from(&[105]);
                            break 'lab7;
                        }
                        env.cursor = env.limit - v_8;
                        if !env.eq_s_b(&[231]) {
                            env.cursor = env.limit - v_7;
                            break 'lab6;
                        }
                        env.bra = env.cursor;
                        env.slice_from(&[99]);
                        break 'lab7;
                    }
                    break 'lab6;
                }
                break 'lab1;
            }
            env.cursor = env.limit - v_4;
            if !r_residual_suffix(env, context) {
                break 'lab0;
            }
            break 'lab1;
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_3;
    let v_9 = env.limit - env.cursor;
    r_un_double(env, context);
    env.cursor = env.limit - v_9;
    let v_10 = env.limit - env.cursor;
    r_un_accent(env, context);
    env.cursor = env.limit - v_10;
    env.cursor = env.limit_backward;
    let v_11 = env.cursor;
    r_postlude(env, context);
    env.cursor = v_11;
    return true
}
