//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 6] = &[
    Among(&[], -1, 5, None), // ""
    Among(&[97, 101], 0, 2, None), // "ae"
    Among(&[111, 101], 0, 3, None), // "oe"
    Among(&[113, 117], 0, -1, None), // "qu"
    Among(&[117, 101], 0, 4, None), // "ue"
    Among(&[223], 0, 1, None), // "\u{00DF}"
];

static A_1: &'static [Among<Context>; 6] = &[
    Among(&[], -1, 5, None), // ""
    Among(&[85], 0, 2, None), // "U"
    Among(&[89], 0, 1, None), // "Y"
    Among(&[228], 0, 3, None), // "\u{00E4}"
    Among(&[246], 0, 4, None), // "\u{00F6}"
    Among(&[252], 0, 2, None), // "\u{00FC}"
];

static A_2: &'static [Among<Context>; 7] = &[
    Among(&[101], -1, 3, None), // "e"
    Among(&[101, 109], -1, 1, None), // "em"
    Among(&[101, 110], -1, 3, None), // "en"
    Among(&[101, 114, 110], -1, 2, None), // "ern"
    Among(&[101, 114], -1, 2, None), // "er"
    Among(&[115], -1, 4, None), // "s"
    Among(&[101, 115], 5, 3, None), // "es"
];

static A_3: &'static [Among<Context>; 4] = &[
    Among(&[101, 110], -1, 1, None), // "en"
    Among(&[101, 114], -1, 1, None), // "er"
    Among(&[115, 116], -1, 2, None), // "st"
    Among(&[101, 115, 116], 2, 1, None), // "est"
];

static A_4: &'static [Among<Context>; 2] = &[
    Among(&[105, 103], -1, 1, None), // "ig"
    Among(&[108, 105, 99, 104], -1, 1, None), // "lich"
];

static A_5: &'static [Among<Context>; 8] = &[
    Among(&[101, 110, 100], -1, 1, None), // "end"
    Among(&[105, 103], -1, 2, None), // "ig"
    Among(&[117, 110, 103], -1, 1, None), // "ung"
    Among(&[108, 105, 99, 104], -1, 3, None), // "lich"
    Among(&[105, 115, 99, 104], -1, 2, None), // "isch"
    Among(&[105, 107], -1, 2, None), // "ik"
    Among(&[104, 101, 105, 116], -1, 3, None), // "heit"
    Among(&[107, 101, 105, 116], -1, 4, None), // "keit"
];

static G_v: &'static [u8; 20] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0, 32, 8];

static G_s_ending: &'static [u8; 3] = &[117, 30, 5];

static G_st_ending: &'static [u8; 3] = &[117, 30, 4];

#[derive(Clone)]
struct Context {
    i_x: i32,
    i_p2: i32,
    i_p1: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.cursor;
    'replab0: loop{
        let v_2 = env.cursor;
        'lab1: for _ in 0..1 {
            'golab2: loop {
                let v_3 = env.cursor;
                'lab3: loop {
                    if !env.in_grouping(G_v, 97, 252) {
                        break 'lab3;
                    }
                    env.bra = env.cursor;
                    'lab4: loop {
                        let v_4 = env.cursor;
                        'lab5: loop {
                            if !env.eq_s(&[117]) {
                                break 'lab5;
                            }
                            env.ket = env.cursor;
                            if !env.in_grouping(G_v, 97, 252) {
                                break 'lab5;
                            }
                            env.slice_from(&[85]);
                            break 'lab4;
                        }
                        env.cursor = v_4;
                        if !env.eq_s(&[121]) {
                            break 'lab3;
                        }
                        env.ket = env.cursor;
                        if !env.in_grouping(G_v, 97, 252) {
                            break 'lab3;
                        }
                        env.slice_from(&[89]);
                        break 'lab4;
                    }
                    env.cursor = v_3;
                    break 'golab2;
                }
                env.cursor = v_3;
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            continue 'replab0;
        }
        env.cursor = v_2;
        break 'replab0;
    }
    env.cursor = v_1;
    'replab6: loop{
        let v_5 = env.cursor;
        'lab7: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_0, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[115, 115]);
                }
                2 => {
                    env.slice_from(&[228]);
                }
                3 => {
                    env.slice_from(&[246]);
                }
                4 => {
                    env.slice_from(&[252]);
                }
                5 => {
                    if env.cursor >= env.limit {
                        break 'lab7;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab6;
        }
        env.cursor = v_5;
        break 'replab6;
    }
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    if !env.hop(3) {
        return false;
    }
    context.i_x = env.cursor;
    env.cursor = v_1;
    'golab0: loop {
        'lab1: loop {
            if !env.in_grouping(G_v, 97, 252) {
                break 'lab1;
            }
            break 'golab0;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    'golab2: loop {
        'lab3: loop {
            if !env.out_grouping(G_v, 97, 252) {
                break 'lab3;
            }
            break 'golab2;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    context.i_p1 = env.cursor;
    'lab4: loop {
        if context.i_p1 >= context.i_x{
            break 'lab4;
        }
        context.i_p1 = context.i_x;
        break 'lab4;
    }
    'golab5: loop {
        'lab6: loop {
            if !env.in_grouping(G_v, 97, 252) {
                break 'lab6;
            }
            break 'golab5;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    'golab7: loop {
        'lab8: loop {
            if !env.out_grouping(G_v, 97, 252) {
                break 'lab8;
            }
            break 'golab7;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    context.i_p2 = env.cursor;
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[121]);
                }
                2 => {
                    env.slice_from(&[117]);
                }
                3 => {
                    env.slice_from(&[97]);
                }
                4 => {
                    env.slice_from(&[111]);
                }
                5 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        among_var = env.find_among_b(A_2, context);
        if among_var == 0 {
            break 'lab0;
        }
        env.bra = env.cursor;
        if !r_R1(env, context) {
            break 'lab0;
        }
        match among_var {
            1 => {
                let v_2 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.eq_s_b(&[115, 121, 115, 116]) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_2;
                env.slice_del();
            }
            2 => {
                env.slice_del();
            }
            3 => {
                env.slice_del();
                let v_3 = env.limit - env.cursor;
                'lab2: loop {
                    env.ket = env.cursor;
                    if !env.eq_s_b(&[115]) {
                        env.cursor = env.limit - v_3;
                        break 'lab2;
                    }
                    env.bra = env.cursor;
                    if !env.eq_s_b(&[110, 105, 115]) {
                        env.cursor = env.limit - v_3;
                        break 'lab2;
                    }
                    env.slice_del();
                    break 'lab2;
                }
            }
            4 => {
                if !env.in_grouping_b(G_s_ending, 98, 116) {
                    break 'lab0;
                }
                env.slice_del();
            }
            _ => ()
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_1;
    let v_4 = env.limit - env.cursor;
    'lab3: loop {
        env.ket = env.cursor;
        among_var = env.find_among_b(A_3, context);
        if among_var == 0 {
            break 'lab3;
        }
        env.bra = env.cursor;
        if !r_R1(env, context) {
            break 'lab3;
        }
        match among_var {
            1 => {
                env.slice_del();
            }
            2 => {
                if !env.in_grouping_b(G_st_ending, 98, 116) {
                    break 'lab3;
                }
                if !env.hop_back(3) {
                    break 'lab3;
                }
                env.slice_del();
            }
            _ => ()
        }
        break 'lab3;
    }
    env.cursor = env.limit - v_4;
    let v_5 = env.limit - env.cursor;
    'lab4: loop {
        env.ket = env.cursor;
        among_var = env.find_among_b(A_5, context);
        if among_var == 0 {
            break 'lab4;
        }
        env.bra = env.cursor;
        if !r_R2(env, context) {
            break 'lab4;
        }
        match among_var {
            1 => {
                env.slice_del();
                let v_6 = env.limit - env.cursor;
                'lab5: loop {
                    env.ket = env.cursor;
                    if !env.eq_s_b(&[105, 103]) {
                        env.cursor = env.limit - v_6;
                        break 'lab5;
                    }
                    env.bra = env.cursor;
                    let v_7 = env.limit - env.cursor;
                    'lab6: loop {
                        if !env.eq_s_b(&[101]) {
                            break 'lab6;
                        }
                        env.cursor = env.limit - v_6;
                        break 'lab5;
                    }
                    env.cursor = env.limit - v_7;
                    if !r_R2(env, context) {
                        env.cursor = env.limit - v_6;
                        break 'lab5;
                    }
                    env.slice_del();
                    break 'lab5;
                }
            }
            2 => {
                let v_8 = env.limit - env.cursor;
                'lab7: loop {
                    if !env.eq_s_b(&[101]) {
                        break 'lab7;
                    }
                    break 'lab4;
                }
                env.cursor = env.limit - v_8;
                env.slice_del();
            }
            3 => {
                env.slice_del();
                let v_9 = env.limit - env.cursor;
                'lab8: loop {
                    env.ket = env.cursor;
                    'lab9: loop {
                        let v_10 = env.limit - env.cursor;
                        'lab10: loop {
                            if !env.eq_s_b(&[101, 114]) {
                                break 'lab10;
                            }
                            break 'lab9;
                        }
                        env.cursor = env.limit - v_10;
                        if !env.eq_s_b(&[101, 110]) {
                            env.cursor = env.limit - v_9;
                            break 'lab8;
                        }
                        break 'lab9;
                    }
                    env.bra = env.cursor;
                    if !r_R1(env, context) {
                        env.cursor = env.limit - v_9;
                        break 'lab8;
                    }
                    env.slice_del();
                    break 'lab8;
                }
            }
            4 => {
                env.slice_del();
                let v_11 = env.limit - env.cursor;
                'lab11: loop {
                    env.ket = env.cursor;
                    if env.find_among_b(A_4, context) == 0 {
                        env.cursor = env.limit - v_11;
                        break 'lab11;
                    }
                    env.bra = env.cursor;
                    if !r_R2(env, context) {
                        env.cursor = env.limit - v_11;
                        break 'lab11;
                    }
                    env.slice_del();
                    break 'lab11;
                }
            }
            _ => ()
        }
        break 'lab4;
    }
    env.cursor = env.limit - v_5;
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_x: 0,
        i_p2: 0,
        i_p1: 0,
    };
    let v_1 = env.cursor;
    r_prelude(env, context);
    env.cursor = v_1;
    let v_2 = env.cursor;
    r_mark_regions(env, context);
    env.cursor = v_2;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    r_standard_suffix(env, context);
    env.cursor = env.limit_backward;
    let v_4 = env.cursor;
    r_postlude(env, context);
    env.cursor = v_4;
    return true
}
