//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 7] = &[
    Among(&[], -1, 7, None), // ""
    Among(&[113, 117], 0, 6, None), // "qu"
    Among(&[225], 0, 1, None), // "\u{00E1}"
    Among(&[233], 0, 2, None), // "\u{00E9}"
    Among(&[237], 0, 3, None), // "\u{00ED}"
    Among(&[243], 0, 4, None), // "\u{00F3}"
    Among(&[250], 0, 5, None), // "\u{00FA}"
];

static A_1: &'static [Among<Context>; 3] = &[
    Among(&[], -1, 3, None), // ""
    Among(&[73], 0, 1, None), // "I"
    Among(&[85], 0, 2, None), // "U"
];

static A_2: &'static [Among<Context>; 37] = &[
    Among(&[108, 97], -1, -1, None), // "la"
    Among(&[99, 101, 108, 97], 0, -1, None), // "cela"
    Among(&[103, 108, 105, 101, 108, 97], 0, -1, None), // "gliela"
    Among(&[109, 101, 108, 97], 0, -1, None), // "mela"
    Among(&[116, 101, 108, 97], 0, -1, None), // "tela"
    Among(&[118, 101, 108, 97], 0, -1, None), // "vela"
    Among(&[108, 101], -1, -1, None), // "le"
    Among(&[99, 101, 108, 101], 6, -1, None), // "cele"
    Among(&[103, 108, 105, 101, 108, 101], 6, -1, None), // "gliele"
    Among(&[109, 101, 108, 101], 6, -1, None), // "mele"
    Among(&[116, 101, 108, 101], 6, -1, None), // "tele"
    Among(&[118, 101, 108, 101], 6, -1, None), // "vele"
    Among(&[110, 101], -1, -1, None), // "ne"
    Among(&[99, 101, 110, 101], 12, -1, None), // "cene"
    Among(&[103, 108, 105, 101, 110, 101], 12, -1, None), // "gliene"
    Among(&[109, 101, 110, 101], 12, -1, None), // "mene"
    Among(&[115, 101, 110, 101], 12, -1, None), // "sene"
    Among(&[116, 101, 110, 101], 12, -1, None), // "tene"
    Among(&[118, 101, 110, 101], 12, -1, None), // "vene"
    Among(&[99, 105], -1, -1, None), // "ci"
    Among(&[108, 105], -1, -1, None), // "li"
    Among(&[99, 101, 108, 105], 20, -1, None), // "celi"
    Among(&[103, 108, 105, 101, 108, 105], 20, -1, None), // "glieli"
    Among(&[109, 101, 108, 105], 20, -1, None), // "meli"
    Among(&[116, 101, 108, 105], 20, -1, None), // "teli"
    Among(&[118, 101, 108, 105], 20, -1, None), // "veli"
    Among(&[103, 108, 105], 20, -1, None), // "gli"
    Among(&[109, 105], -1, -1, None), // "mi"
    Among(&[115, 105], -1, -1, None), // "si"
    Among(&[116, 105], -1, -1, None), // "ti"
    Among(&[118, 105], -1, -1, None), // "vi"
    Among(&[108, 111], -1, -1, None), // "lo"
    Among(&[99, 101, 108, 111], 31, -1, None), // "celo"
    Among(&[103, 108, 105, 101, 108, 111], 31, -1, None), // "glielo"
    Among(&[109, 101, 108, 111], 31, -1, None), // "melo"
    Among(&[116, 101, 108, 111], 31, -1, None), // "telo"
    Among(&[118, 101, 108, 111], 31, -1, None), // "velo"
];

static A_3: &'static [Among<Context>; 5] = &[
    Among(&[97, 110, 100, 111], -1, 1, None), // "ando"
    Among(&[101, 110, 100, 111], -1, 1, None), // "endo"
    Among(&[97, 114], -1, 2, None), // "ar"
    Among(&[101, 114], -1, 2, None), // "er"
    Among(&[105, 114], -1, 2, None), // "ir"
];

static A_4: &'static [Among<Context>; 4] = &[
    Among(&[105, 99], -1, -1, None), // "ic"
    Among(&[97, 98, 105, 108], -1, -1, None), // "abil"
    Among(&[111, 115], -1, -1, None), // "os"
    Among(&[105, 118], -1, 1, None), // "iv"
];

static A_5: &'static [Among<Context>; 3] = &[
    Among(&[105, 99], -1, 1, None), // "ic"
    Among(&[97, 98, 105, 108], -1, 1, None), // "abil"
    Among(&[105, 118], -1, 1, None), // "iv"
];

static A_6: &'static [Among<Context>; 51] = &[
    Among(&[105, 99, 97], -1, 1, None), // "ica"
    Among(&[108, 111, 103, 105, 97], -1, 3, None), // "logia"
    Among(&[111, 115, 97], -1, 1, None), // "osa"
    Among(&[105, 115, 116, 97], -1, 1, None), // "ista"
    Among(&[105, 118, 97], -1, 9, None), // "iva"
    Among(&[97, 110, 122, 97], -1, 1, None), // "anza"
    Among(&[101, 110, 122, 97], -1, 5, None), // "enza"
    Among(&[105, 99, 101], -1, 1, None), // "ice"
    Among(&[97, 116, 114, 105, 99, 101], 7, 1, None), // "atrice"
    Among(&[105, 99, 104, 101], -1, 1, None), // "iche"
    Among(&[108, 111, 103, 105, 101], -1, 3, None), // "logie"
    Among(&[97, 98, 105, 108, 101], -1, 1, None), // "abile"
    Among(&[105, 98, 105, 108, 101], -1, 1, None), // "ibile"
    Among(&[117, 115, 105, 111, 110, 101], -1, 4, None), // "usione"
    Among(&[97, 122, 105, 111, 110, 101], -1, 2, None), // "azione"
    Among(&[117, 122, 105, 111, 110, 101], -1, 4, None), // "uzione"
    Among(&[97, 116, 111, 114, 101], -1, 2, None), // "atore"
    Among(&[111, 115, 101], -1, 1, None), // "ose"
    Among(&[97, 110, 116, 101], -1, 1, None), // "ante"
    Among(&[109, 101, 110, 116, 101], -1, 1, None), // "mente"
    Among(&[97, 109, 101, 110, 116, 101], 19, 7, None), // "amente"
    Among(&[105, 115, 116, 101], -1, 1, None), // "iste"
    Among(&[105, 118, 101], -1, 9, None), // "ive"
    Among(&[97, 110, 122, 101], -1, 1, None), // "anze"
    Among(&[101, 110, 122, 101], -1, 5, None), // "enze"
    Among(&[105, 99, 105], -1, 1, None), // "ici"
    Among(&[97, 116, 114, 105, 99, 105], 25, 1, None), // "atrici"
    Among(&[105, 99, 104, 105], -1, 1, None), // "ichi"
    Among(&[97, 98, 105, 108, 105], -1, 1, None), // "abili"
    Among(&[105, 98, 105, 108, 105], -1, 1, None), // "ibili"
    Among(&[105, 115, 109, 105], -1, 1, None), // "ismi"
    Among(&[117, 115, 105, 111, 110, 105], -1, 4, None), // "usioni"
    Among(&[97, 122, 105, 111, 110, 105], -1, 2, None), // "azioni"
    Among(&[117, 122, 105, 111, 110, 105], -1, 4, None), // "uzioni"
    Among(&[97, 116, 111, 114, 105], -1, 2, None), // "atori"
    Among(&[111, 115, 105], -1, 1, None), // "osi"
    Among(&[97, 110, 116, 105], -1, 1, None), // "anti"
    Among(&[97, 109, 101, 110, 116, 105], -1, 6, None), // "amenti"
    Among(&[105, 109, 101, 110, 116, 105], -1, 6, None), // "imenti"
    Among(&[105, 115, 116, 105], -1, 1, None), // "isti"
    Among(&[105, 118, 105], -1, 9, None), // "ivi"
    Among(&[105, 99, 111], -1, 1, None), // "ico"
    Among(&[105, 115, 109, 111], -1, 1, None), // "ismo"
    Among(&[111, 115, 111], -1, 1, None), // "oso"
    Among(&[97, 109, 101, 110, 116, 111], -1, 6, None), // "amento"
    Among(&[105, 109, 101, 110, 116, 111], -1, 6, None), // "imento"
    Among(&[105, 118, 111], -1, 9, None), // "ivo"
    Among(&[105, 116, 224], -1, 8, None), // "it\u{00E0}"
    Among(&[105, 115, 116, 224], -1, 1, None), // "ist\u{00E0}"
    Among(&[105, 115, 116, 232], -1, 1, None), // "ist\u{00E8}"
    Among(&[105, 115, 116, 236], -1, 1, None), // "ist\u{00EC}"
];

static A_7: &'static [Among<Context>; 87] = &[
    Among(&[105, 115, 99, 97], -1, 1, None), // "isca"
    Among(&[101, 110, 100, 97], -1, 1, None), // "enda"
    Among(&[97, 116, 97], -1, 1, None), // "ata"
    Among(&[105, 116, 97], -1, 1, None), // "ita"
    Among(&[117, 116, 97], -1, 1, None), // "uta"
    Among(&[97, 118, 97], -1, 1, None), // "ava"
    Among(&[101, 118, 97], -1, 1, None), // "eva"
    Among(&[105, 118, 97], -1, 1, None), // "iva"
    Among(&[101, 114, 101, 98, 98, 101], -1, 1, None), // "erebbe"
    Among(&[105, 114, 101, 98, 98, 101], -1, 1, None), // "irebbe"
    Among(&[105, 115, 99, 101], -1, 1, None), // "isce"
    Among(&[101, 110, 100, 101], -1, 1, None), // "ende"
    Among(&[97, 114, 101], -1, 1, None), // "are"
    Among(&[101, 114, 101], -1, 1, None), // "ere"
    Among(&[105, 114, 101], -1, 1, None), // "ire"
    Among(&[97, 115, 115, 101], -1, 1, None), // "asse"
    Among(&[97, 116, 101], -1, 1, None), // "ate"
    Among(&[97, 118, 97, 116, 101], 16, 1, None), // "avate"
    Among(&[101, 118, 97, 116, 101], 16, 1, None), // "evate"
    Among(&[105, 118, 97, 116, 101], 16, 1, None), // "ivate"
    Among(&[101, 116, 101], -1, 1, None), // "ete"
    Among(&[101, 114, 101, 116, 101], 20, 1, None), // "erete"
    Among(&[105, 114, 101, 116, 101], 20, 1, None), // "irete"
    Among(&[105, 116, 101], -1, 1, None), // "ite"
    Among(&[101, 114, 101, 115, 116, 101], -1, 1, None), // "ereste"
    Among(&[105, 114, 101, 115, 116, 101], -1, 1, None), // "ireste"
    Among(&[117, 116, 101], -1, 1, None), // "ute"
    Among(&[101, 114, 97, 105], -1, 1, None), // "erai"
    Among(&[105, 114, 97, 105], -1, 1, None), // "irai"
    Among(&[105, 115, 99, 105], -1, 1, None), // "isci"
    Among(&[101, 110, 100, 105], -1, 1, None), // "endi"
    Among(&[101, 114, 101, 105], -1, 1, None), // "erei"
    Among(&[105, 114, 101, 105], -1, 1, None), // "irei"
    Among(&[97, 115, 115, 105], -1, 1, None), // "assi"
    Among(&[97, 116, 105], -1, 1, None), // "ati"
    Among(&[105, 116, 105], -1, 1, None), // "iti"
    Among(&[101, 114, 101, 115, 116, 105], -1, 1, None), // "eresti"
    Among(&[105, 114, 101, 115, 116, 105], -1, 1, None), // "iresti"
    Among(&[117, 116, 105], -1, 1, None), // "uti"
    Among(&[97, 118, 105], -1, 1, None), // "avi"
    Among(&[101, 118, 105], -1, 1, None), // "evi"
    Among(&[105, 118, 105], -1, 1, None), // "ivi"
    Among(&[105, 115, 99, 111], -1, 1, None), // "isco"
    Among(&[97, 110, 100, 111], -1, 1, None), // "ando"
    Among(&[101, 110, 100, 111], -1, 1, None), // "endo"
    Among(&[89, 97, 109, 111], -1, 1, None), // "Yamo"
    Among(&[105, 97, 109, 111], -1, 1, None), // "iamo"
    Among(&[97, 118, 97, 109, 111], -1, 1, None), // "avamo"
    Among(&[101, 118, 97, 109, 111], -1, 1, None), // "evamo"
    Among(&[105, 118, 97, 109, 111], -1, 1, None), // "ivamo"
    Among(&[101, 114, 101, 109, 111], -1, 1, None), // "eremo"
    Among(&[105, 114, 101, 109, 111], -1, 1, None), // "iremo"
    Among(&[97, 115, 115, 105, 109, 111], -1, 1, None), // "assimo"
    Among(&[97, 109, 109, 111], -1, 1, None), // "ammo"
    Among(&[101, 109, 109, 111], -1, 1, None), // "emmo"
    Among(&[101, 114, 101, 109, 109, 111], 54, 1, None), // "eremmo"
    Among(&[105, 114, 101, 109, 109, 111], 54, 1, None), // "iremmo"
    Among(&[105, 109, 109, 111], -1, 1, None), // "immo"
    Among(&[97, 110, 111], -1, 1, None), // "ano"
    Among(&[105, 115, 99, 97, 110, 111], 58, 1, None), // "iscano"
    Among(&[97, 118, 97, 110, 111], 58, 1, None), // "avano"
    Among(&[101, 118, 97, 110, 111], 58, 1, None), // "evano"
    Among(&[105, 118, 97, 110, 111], 58, 1, None), // "ivano"
    Among(&[101, 114, 97, 110, 110, 111], -1, 1, None), // "eranno"
    Among(&[105, 114, 97, 110, 110, 111], -1, 1, None), // "iranno"
    Among(&[111, 110, 111], -1, 1, None), // "ono"
    Among(&[105, 115, 99, 111, 110, 111], 65, 1, None), // "iscono"
    Among(&[97, 114, 111, 110, 111], 65, 1, None), // "arono"
    Among(&[101, 114, 111, 110, 111], 65, 1, None), // "erono"
    Among(&[105, 114, 111, 110, 111], 65, 1, None), // "irono"
    Among(&[101, 114, 101, 98, 98, 101, 114, 111], -1, 1, None), // "erebbero"
    Among(&[105, 114, 101, 98, 98, 101, 114, 111], -1, 1, None), // "irebbero"
    Among(&[97, 115, 115, 101, 114, 111], -1, 1, None), // "assero"
    Among(&[101, 115, 115, 101, 114, 111], -1, 1, None), // "essero"
    Among(&[105, 115, 115, 101, 114, 111], -1, 1, None), // "issero"
    Among(&[97, 116, 111], -1, 1, None), // "ato"
    Among(&[105, 116, 111], -1, 1, None), // "ito"
    Among(&[117, 116, 111], -1, 1, None), // "uto"
    Among(&[97, 118, 111], -1, 1, None), // "avo"
    Among(&[101, 118, 111], -1, 1, None), // "evo"
    Among(&[105, 118, 111], -1, 1, None), // "ivo"
    Among(&[97, 114], -1, 1, None), // "ar"
    Among(&[105, 114], -1, 1, None), // "ir"
    Among(&[101, 114, 224], -1, 1, None), // "er\u{00E0}"
    Among(&[105, 114, 224], -1, 1, None), // "ir\u{00E0}"
    Among(&[101, 114, 242], -1, 1, None), // "er\u{00F2}"
    Among(&[105, 114, 242], -1, 1, None), // "ir\u{00F2}"
];

static G_v: &'static [u8; 20] = &[17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2, 1];

static G_AEIO: &'static [u8; 19] = &[17, 65, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 128, 128, 8, 2];

static G_CG: &'static [u8; 1] = &[17];

#[derive(Clone)]
struct Context {
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.cursor;
    'replab0: loop{
        let v_2 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_0, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[224]);
                }
                2 => {
                    env.slice_from(&[232]);
                }
                3 => {
                    env.slice_from(&[236]);
                }
                4 => {
                    env.slice_from(&[242]);
                }
                5 => {
                    env.slice_from(&[249]);
                }
                6 => {
                    env.slice_from(&[113, 85]);
                }
                7 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_2;
        break 'replab0;
    }
    env.cursor = v_1;
    'replab2: loop{
        let v_3 = env.cursor;
        'lab3: for _ in 0..1 {
            'golab4: loop {
                let v_4 = env.cursor;
                'lab5: loop {
                    if !env.in_grouping(G_v, 97, 249) {
                        break 'lab5;
                    }
                    env.bra = env.cursor;
                    'lab6: loop {
                        let v_5 = env.cursor;
                        'lab7: loop {
                            if !env.eq_s(&[117]) {
                                break 'lab7;
                            }
                            env.ket = env.cursor;
                            if !env.in_grouping(G_v, 97, 249) {
                                break 'lab7;
                            }
                            env.slice_from(&[85]);
                            break 'lab6;
                        }
                        env.cursor = v_5;
                        if !env.eq_s(&[105]) {
                            break 'lab5;
                        }
                        env.ket = env.cursor;
                        if !env.in_grouping(G_v, 97, 249) {
                            break 'lab5;
                        }
                        env.slice_from(&[73]);
                        break 'lab6;
                    }
                    env.cursor = v_4;
                    break 'golab4;
                }
                env.cursor = v_4;
                if env.cursor >= env.limit {
                    break 'lab3;
                }
                env.next_char();
            }
            continue 'replab2;
        }
        env.cursor = v_3;
        break 'replab2;
    }
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 249) {
                    break 'lab2;
                }
                'lab3: loop {
                    let v_3 = env.cursor;
                    'lab4: loop {
                        if !env.out_grouping(G_v, 97, 249) {
                            break 'lab4;
                        }
                        'golab5: loop {
                            'lab6: loop {
                                if !env.in_grouping(G_v, 97, 249) {
                                    break 'lab6;
                                }
                                break 'golab5;
                            }
                            if env.cursor >= env.limit {
                                break 'lab4;
                            }
                            env.next_char();
                        }
                        break 'lab3;
                    }
                    env.cursor = v_3;
                    if !env.in_grouping(G_v, 97, 249) {
                        break 'lab2;
                    }
                    'golab7: loop {
                        'lab8: loop {
                            if !env.out_grouping(G_v, 97, 249) {
                                break 'lab8;
                            }
                            break 'golab7;
                        }
                        if env.cursor >= env.limit {
                            break 'lab2;
                        }
                        env.next_char();
                    }
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if !env.out_grouping(G_v, 97, 249) {
                break 'lab0;
            }
            'lab9: loop {
                let v_6 = env.cursor;
                'lab10: loop {
                    if !env.out_grouping(G_v, 97, 249) {
                        break 'lab10;
                    }
                    'golab11: loop {
                        'lab12: loop {
                            if !env.in_grouping(G_v, 97, 249) {
                                break 'lab12;
                            }
                            break 'golab11;
                        }
                        if env.cursor >= env.limit {
                            break 'lab10;
                        }
                        env.next_char();
                    }
                    break 'lab9;
                }
                env.cursor = v_6;
                if !env.in_grouping(G_v, 97, 249) {
                    break 'lab0;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
                break 'lab9;
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_8 = env.cursor;
    'lab13: loop {
        'golab14: loop {
            'lab15: loop {
                if !env.in_grouping(G_v, 97, 249) {
                    break 'lab15;
                }
                break 'golab14;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab16: loop {
            'lab17: loop {
                if !env.out_grouping(G_v, 97, 249) {
                    break 'lab17;
                }
                break 'golab16;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab18: loop {
            'lab19: loop {
                if !env.in_grouping(G_v, 97, 249) {
                    break 'lab19;
                }
                break 'golab18;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab20: loop {
            'lab21: loop {
                if !env.out_grouping(G_v, 97, 249) {
                    break 'lab21;
                }
                break 'golab20;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab13;
    }
    env.cursor = v_8;
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[105]);
                }
                2 => {
                    env.slice_from(&[117]);
                }
                3 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_pV <= env.cursor
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_attached_pronoun(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    if env.find_among_b(A_2, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    among_var = env.find_among_b(A_3, context);
    if among_var == 0 {
        return false;
    }
    if !r_RV(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            env.slice_from(&[101]);
        }
        _ => ()
    }
    return true
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_6, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_1 = env.limit - env.cursor;
            'lab0: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[105, 99]) {
                    env.cursor = env.limit - v_1;
                    break 'lab0;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_1;
                    break 'lab0;
                }
                env.slice_del();
                break 'lab0;
            }
        }
        3 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[108, 111, 103]);
        }
        4 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[117]);
        }
        5 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[101, 110, 116, 101]);
        }
        6 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
        }
        7 => {
            if !r_R1(env, context) {
                return false;
            }
            env.slice_del();
            let v_2 = env.limit - env.cursor;
            'lab1: loop {
                env.ket = env.cursor;
                among_var = env.find_among_b(A_4, context);
                if among_var == 0 {
                    env.cursor = env.limit - v_2;
                    break 'lab1;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_2;
                    break 'lab1;
                }
                env.slice_del();
                match among_var {
                    1 => {
                        env.ket = env.cursor;
                        if !env.eq_s_b(&[97, 116]) {
                            env.cursor = env.limit - v_2;
                            break 'lab1;
                        }
                        env.bra = env.cursor;
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_2;
                            break 'lab1;
                        }
                        env.slice_del();
                    }
                    _ => ()
                }
                break 'lab1;
            }
        }
        8 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_3 = env.limit - env.cursor;
            'lab2: loop {
                env.ket = env.cursor;
                if env.find_among_b(A_5, context) == 0 {
                    env.cursor = env.limit - v_3;
                    break 'lab2;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab2;
                }
                env.slice_del();
                break 'lab2;
            }
        }
        9 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_4 = env.limit - env.cursor;
            'lab3: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[97, 116]) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.slice_del();
                env.ket = env.cursor;
                if !env.eq_s_b(&[105, 99]) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.slice_del();
                break 'lab3;
            }
        }
        _ => ()
    }
    return true
}

fn r_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    if env.find_among_b(A_7, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.slice_del();
    env.limit_backward = v_2;
    return true
}

fn r_vowel_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        if !env.in_grouping_b(G_AEIO, 97, 242) {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.bra = env.cursor;
        if !r_RV(env, context) {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.slice_del();
        env.ket = env.cursor;
        if !env.eq_s_b(&[105]) {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.bra = env.cursor;
        if !r_RV(env, context) {
            env.cursor = env.limit - v_1;
            break 'lab0;
        }
        env.slice_del();
        break 'lab0;
    }
    let v_2 = env.limit - env.cursor;
    'lab1: loop {
        env.ket = env.cursor;
        if !env.eq_s_b(&[104]) {
            env.cursor = env.limit - v_2;
            break 'lab1;
        }
        env.bra = env.cursor;
        if !env.in_grouping_b(G_CG, 99, 103) {
            env.cursor = env.limit - v_2;
            break 'lab1;
        }
        if !r_RV(env, context) {
            env.cursor = env.limit - v_2;
            break 'lab1;
        }
        env.slice_del();
        break 'lab1;
    }
    return true
}

fn r_exceptions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.bra = env.cursor;
    if !env.eq_s(&[100, 105, 118, 97, 110, 111]) {
        return false;
    }
    if env.cursor < env.limit {
        return false;
    }
    env.ket = env.cursor;
    env.slice_from(&[100, 105, 118, 97, 110]);
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    'lab0: loop {
        let v_1 = env.cursor;
        'lab1: loop {
            if !r_exceptions(env, context) {
                break 'lab1;
            }
            break 'lab0;
        }
        env.cursor = v_1;
        let v_2 = env.cursor;
        r_prelude(env, context);
        env.cursor = v_2;
        r_mark_regions(env, context);
        env.limit_backward = env.cursor;
        env.cursor = env.limit;
        let v_4 = env.limit - env.cursor;
        r_attached_pronoun(env, context);
        env.cursor = env.limit - v_4;
        let v_5 = env.limit - env.cursor;
        'lab2: loop {
            'lab3: loop {
                let v_6 = env.limit - env.cursor;
                'lab4: loop {
                    if !r_standard_suffix(env, context) {
                        break 'lab4;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_6;
                if !r_verb_suffix(env, context) {
                    break 'lab2;
                }
                break 'lab3;
            }
            break 'lab2;
        }
        env.cursor = env.limit - v_5;
        let v_7 = env.limit - env.cursor;
        r_vowel_suffix(env, context);
        env.cursor = env.limit - v_7;
        env.cursor = env.limit_backward;
        let v_8 = env.cursor;
        r_postlude(env, context);
        env.cursor = v_8;
        break 'lab0;
    }
    return true
}
