//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 204] = &[
    Among(&[97], -1, -1, None), // "a"
    Among(&[105, 97], 0, -1, None), // "ia"
    Among(&[101, 114, 105, 97], 1, -1, None), // "eria"
    Among(&[111, 115, 110, 97], 0, -1, None), // "osna"
    Among(&[105, 111, 115, 110, 97], 3, -1, None), // "iosna"
    Among(&[117, 111, 115, 110, 97], 3, -1, None), // "uosna"
    Among(&[105, 117, 111, 115, 110, 97], 5, -1, None), // "iuosna"
    Among(&[121, 115, 110, 97], 0, -1, None), // "ysna"
    Among(&[279, 115, 110, 97], 0, -1, None), // "\u{0117}sna"
    Among(&[101], -1, -1, None), // "e"
    Among(&[105, 101], 9, -1, None), // "ie"
    Among(&[101, 110, 105, 101], 10, -1, None), // "enie"
    Among(&[101, 114, 105, 101], 10, -1, None), // "erie"
    Among(&[111, 106, 101], 9, -1, None), // "oje"
    Among(&[105, 111, 106, 101], 13, -1, None), // "ioje"
    Among(&[117, 106, 101], 9, -1, None), // "uje"
    Among(&[105, 117, 106, 101], 15, -1, None), // "iuje"
    Among(&[121, 106, 101], 9, -1, None), // "yje"
    Among(&[101, 110, 121, 106, 101], 17, -1, None), // "enyje"
    Among(&[101, 114, 121, 106, 101], 17, -1, None), // "eryje"
    Among(&[279, 106, 101], 9, -1, None), // "\u{0117}je"
    Among(&[97, 109, 101], 9, -1, None), // "ame"
    Among(&[105, 97, 109, 101], 21, -1, None), // "iame"
    Among(&[115, 105, 109, 101], 9, -1, None), // "sime"
    Among(&[111, 109, 101], 9, -1, None), // "ome"
    Among(&[279, 109, 101], 9, -1, None), // "\u{0117}me"
    Among(&[116, 117, 109, 279, 109, 101], 25, -1, None), // "tum\u{0117}me"
    Among(&[111, 115, 101], 9, -1, None), // "ose"
    Among(&[105, 111, 115, 101], 27, -1, None), // "iose"
    Among(&[117, 111, 115, 101], 27, -1, None), // "uose"
    Among(&[105, 117, 111, 115, 101], 29, -1, None), // "iuose"
    Among(&[121, 115, 101], 9, -1, None), // "yse"
    Among(&[101, 110, 121, 115, 101], 31, -1, None), // "enyse"
    Among(&[101, 114, 121, 115, 101], 31, -1, None), // "eryse"
    Among(&[279, 115, 101], 9, -1, None), // "\u{0117}se"
    Among(&[97, 116, 101], 9, -1, None), // "ate"
    Among(&[105, 97, 116, 101], 35, -1, None), // "iate"
    Among(&[105, 116, 101], 9, -1, None), // "ite"
    Among(&[107, 105, 116, 101], 37, -1, None), // "kite"
    Among(&[115, 105, 116, 101], 37, -1, None), // "site"
    Among(&[111, 116, 101], 9, -1, None), // "ote"
    Among(&[116, 117, 116, 101], 9, -1, None), // "tute"
    Among(&[279, 116, 101], 9, -1, None), // "\u{0117}te"
    Among(&[116, 117, 109, 279, 116, 101], 42, -1, None), // "tum\u{0117}te"
    Among(&[105], -1, -1, None), // "i"
    Among(&[97, 105], 44, -1, None), // "ai"
    Among(&[105, 97, 105], 45, -1, None), // "iai"
    Among(&[101, 114, 105, 97, 105], 46, -1, None), // "eriai"
    Among(&[101, 105], 44, -1, None), // "ei"
    Among(&[116, 117, 109, 101, 105], 48, -1, None), // "tumei"
    Among(&[107, 105], 44, -1, None), // "ki"
    Among(&[105, 109, 105], 44, -1, None), // "imi"
    Among(&[101, 114, 105, 109, 105], 51, -1, None), // "erimi"
    Among(&[117, 109, 105], 44, -1, None), // "umi"
    Among(&[105, 117, 109, 105], 53, -1, None), // "iumi"
    Among(&[115, 105], 44, -1, None), // "si"
    Among(&[97, 115, 105], 55, -1, None), // "asi"
    Among(&[105, 97, 115, 105], 56, -1, None), // "iasi"
    Among(&[101, 115, 105], 55, -1, None), // "esi"
    Among(&[105, 101, 115, 105], 58, -1, None), // "iesi"
    Among(&[115, 105, 101, 115, 105], 59, -1, None), // "siesi"
    Among(&[105, 115, 105], 55, -1, None), // "isi"
    Among(&[97, 105, 115, 105], 61, -1, None), // "aisi"
    Among(&[101, 105, 115, 105], 61, -1, None), // "eisi"
    Among(&[116, 117, 109, 101, 105, 115, 105], 63, -1, None), // "tumeisi"
    Among(&[117, 105, 115, 105], 61, -1, None), // "uisi"
    Among(&[111, 115, 105], 55, -1, None), // "osi"
    Among(&[279, 106, 111, 115, 105], 66, -1, None), // "\u{0117}josi"
    Among(&[117, 111, 115, 105], 66, -1, None), // "uosi"
    Among(&[105, 117, 111, 115, 105], 68, -1, None), // "iuosi"
    Among(&[115, 105, 117, 111, 115, 105], 69, -1, None), // "siuosi"
    Among(&[117, 115, 105], 55, -1, None), // "usi"
    Among(&[97, 117, 115, 105], 71, -1, None), // "ausi"
    Among(&[269, 105, 97, 117, 115, 105], 72, -1, None), // "\u{010D}iausi"
    Among(&[261, 115, 105], 55, -1, None), // "\u{0105}si"
    Among(&[279, 115, 105], 55, -1, None), // "\u{0117}si"
    Among(&[371, 115, 105], 55, -1, None), // "\u{0173}si"
    Among(&[116, 371, 115, 105], 76, -1, None), // "t\u{0173}si"
    Among(&[116, 105], 44, -1, None), // "ti"
    Among(&[101, 110, 116, 105], 78, -1, None), // "enti"
    Among(&[105, 110, 116, 105], 78, -1, None), // "inti"
    Among(&[111, 116, 105], 78, -1, None), // "oti"
    Among(&[105, 111, 116, 105], 81, -1, None), // "ioti"
    Among(&[117, 111, 116, 105], 81, -1, None), // "uoti"
    Among(&[105, 117, 111, 116, 105], 83, -1, None), // "iuoti"
    Among(&[97, 117, 116, 105], 78, -1, None), // "auti"
    Among(&[105, 97, 117, 116, 105], 85, -1, None), // "iauti"
    Among(&[121, 116, 105], 78, -1, None), // "yti"
    Among(&[279, 116, 105], 78, -1, None), // "\u{0117}ti"
    Among(&[116, 101, 108, 279, 116, 105], 88, -1, None), // "tel\u{0117}ti"
    Among(&[105, 110, 279, 116, 105], 88, -1, None), // "in\u{0117}ti"
    Among(&[116, 101, 114, 279, 116, 105], 88, -1, None), // "ter\u{0117}ti"
    Among(&[117, 105], 44, -1, None), // "ui"
    Among(&[105, 117, 105], 92, -1, None), // "iui"
    Among(&[101, 110, 105, 117, 105], 93, -1, None), // "eniui"
    Among(&[111, 106], -1, -1, None), // "oj"
    Among(&[279, 106], -1, -1, None), // "\u{0117}j"
    Among(&[107], -1, -1, None), // "k"
    Among(&[97, 109], -1, -1, None), // "am"
    Among(&[105, 97, 109], 98, -1, None), // "iam"
    Among(&[105, 101, 109], -1, -1, None), // "iem"
    Among(&[105, 109], -1, -1, None), // "im"
    Among(&[115, 105, 109], 101, -1, None), // "sim"
    Among(&[111, 109], -1, -1, None), // "om"
    Among(&[116, 117, 109], -1, -1, None), // "tum"
    Among(&[279, 109], -1, -1, None), // "\u{0117}m"
    Among(&[116, 117, 109, 279, 109], 105, -1, None), // "tum\u{0117}m"
    Among(&[97, 110], -1, -1, None), // "an"
    Among(&[111, 110], -1, -1, None), // "on"
    Among(&[105, 111, 110], 108, -1, None), // "ion"
    Among(&[117, 110], -1, -1, None), // "un"
    Among(&[105, 117, 110], 110, -1, None), // "iun"
    Among(&[279, 110], -1, -1, None), // "\u{0117}n"
    Among(&[111], -1, -1, None), // "o"
    Among(&[105, 111], 113, -1, None), // "io"
    Among(&[101, 110, 105, 111], 114, -1, None), // "enio"
    Among(&[279, 106, 111], 113, -1, None), // "\u{0117}jo"
    Among(&[117, 111], 113, -1, None), // "uo"
    Among(&[115], -1, -1, None), // "s"
    Among(&[97, 115], 118, -1, None), // "as"
    Among(&[105, 97, 115], 119, -1, None), // "ias"
    Among(&[101, 115], 118, -1, None), // "es"
    Among(&[105, 101, 115], 121, -1, None), // "ies"
    Among(&[105, 115], 118, -1, None), // "is"
    Among(&[97, 105, 115], 123, -1, None), // "ais"
    Among(&[105, 97, 105, 115], 124, -1, None), // "iais"
    Among(&[116, 117, 109, 101, 105, 115], 123, -1, None), // "tumeis"
    Among(&[105, 109, 105, 115], 123, -1, None), // "imis"
    Among(&[101, 110, 105, 109, 105, 115], 127, -1, None), // "enimis"
    Among(&[111, 109, 105, 115], 123, -1, None), // "omis"
    Among(&[105, 111, 109, 105, 115], 129, -1, None), // "iomis"
    Among(&[117, 109, 105, 115], 123, -1, None), // "umis"
    Among(&[279, 109, 105, 115], 123, -1, None), // "\u{0117}mis"
    Among(&[101, 110, 105, 115], 123, -1, None), // "enis"
    Among(&[97, 115, 105, 115], 123, -1, None), // "asis"
    Among(&[121, 115, 105, 115], 123, -1, None), // "ysis"
    Among(&[97, 109, 115], 118, -1, None), // "ams"
    Among(&[105, 97, 109, 115], 136, -1, None), // "iams"
    Among(&[105, 101, 109, 115], 118, -1, None), // "iems"
    Among(&[105, 109, 115], 118, -1, None), // "ims"
    Among(&[101, 110, 105, 109, 115], 139, -1, None), // "enims"
    Among(&[101, 114, 105, 109, 115], 139, -1, None), // "erims"
    Among(&[111, 109, 115], 118, -1, None), // "oms"
    Among(&[105, 111, 109, 115], 142, -1, None), // "ioms"
    Among(&[117, 109, 115], 118, -1, None), // "ums"
    Among(&[279, 109, 115], 118, -1, None), // "\u{0117}ms"
    Among(&[101, 110, 115], 118, -1, None), // "ens"
    Among(&[111, 115], 118, -1, None), // "os"
    Among(&[105, 111, 115], 147, -1, None), // "ios"
    Among(&[117, 111, 115], 147, -1, None), // "uos"
    Among(&[105, 117, 111, 115], 149, -1, None), // "iuos"
    Among(&[101, 114, 115], 118, -1, None), // "ers"
    Among(&[117, 115], 118, -1, None), // "us"
    Among(&[97, 117, 115], 152, -1, None), // "aus"
    Among(&[105, 97, 117, 115], 153, -1, None), // "iaus"
    Among(&[105, 117, 115], 152, -1, None), // "ius"
    Among(&[121, 115], 118, -1, None), // "ys"
    Among(&[101, 110, 121, 115], 156, -1, None), // "enys"
    Among(&[101, 114, 121, 115], 156, -1, None), // "erys"
    Among(&[261, 115], 118, -1, None), // "\u{0105}s"
    Among(&[105, 261, 115], 159, -1, None), // "i\u{0105}s"
    Among(&[279, 115], 118, -1, None), // "\u{0117}s"
    Among(&[97, 109, 279, 115], 161, -1, None), // "am\u{0117}s"
    Among(&[105, 97, 109, 279, 115], 162, -1, None), // "iam\u{0117}s"
    Among(&[105, 109, 279, 115], 161, -1, None), // "im\u{0117}s"
    Among(&[107, 105, 109, 279, 115], 164, -1, None), // "kim\u{0117}s"
    Among(&[115, 105, 109, 279, 115], 164, -1, None), // "sim\u{0117}s"
    Among(&[111, 109, 279, 115], 161, -1, None), // "om\u{0117}s"
    Among(&[279, 109, 279, 115], 161, -1, None), // "\u{0117}m\u{0117}s"
    Among(&[116, 117, 109, 279, 109, 279, 115], 168, -1, None), // "tum\u{0117}m\u{0117}s"
    Among(&[97, 116, 279, 115], 161, -1, None), // "at\u{0117}s"
    Among(&[105, 97, 116, 279, 115], 170, -1, None), // "iat\u{0117}s"
    Among(&[115, 105, 116, 279, 115], 161, -1, None), // "sit\u{0117}s"
    Among(&[111, 116, 279, 115], 161, -1, None), // "ot\u{0117}s"
    Among(&[279, 116, 279, 115], 161, -1, None), // "\u{0117}t\u{0117}s"
    Among(&[116, 117, 109, 279, 116, 279, 115], 174, -1, None), // "tum\u{0117}t\u{0117}s"
    Among(&[303, 115], 118, -1, None), // "\u{012F}s"
    Among(&[363, 115], 118, -1, None), // "\u{016B}s"
    Among(&[116, 371, 115], 118, -1, None), // "t\u{0173}s"
    Among(&[97, 116], -1, -1, None), // "at"
    Among(&[105, 97, 116], 179, -1, None), // "iat"
    Among(&[105, 116], -1, -1, None), // "it"
    Among(&[115, 105, 116], 181, -1, None), // "sit"
    Among(&[111, 116], -1, -1, None), // "ot"
    Among(&[279, 116], -1, -1, None), // "\u{0117}t"
    Among(&[116, 117, 109, 279, 116], 184, -1, None), // "tum\u{0117}t"
    Among(&[117], -1, -1, None), // "u"
    Among(&[97, 117], 186, -1, None), // "au"
    Among(&[105, 97, 117], 187, -1, None), // "iau"
    Among(&[269, 105, 97, 117], 188, -1, None), // "\u{010D}iau"
    Among(&[105, 117], 186, -1, None), // "iu"
    Among(&[101, 110, 105, 117], 190, -1, None), // "eniu"
    Among(&[115, 105, 117], 190, -1, None), // "siu"
    Among(&[121], -1, -1, None), // "y"
    Among(&[261], -1, -1, None), // "\u{0105}"
    Among(&[105, 261], 194, -1, None), // "i\u{0105}"
    Among(&[279], -1, -1, None), // "\u{0117}"
    Among(&[281], -1, -1, None), // "\u{0119}"
    Among(&[303], -1, -1, None), // "\u{012F}"
    Among(&[101, 110, 303], 198, -1, None), // "en\u{012F}"
    Among(&[101, 114, 303], 198, -1, None), // "er\u{012F}"
    Among(&[371], -1, -1, None), // "\u{0173}"
    Among(&[105, 371], 201, -1, None), // "i\u{0173}"
    Among(&[101, 114, 371], 201, -1, None), // "er\u{0173}"
];

static A_1: &'static [Among<Context>; 62] = &[
    Among(&[105, 110, 103], -1, -1, None), // "ing"
    Among(&[97, 106], -1, -1, None), // "aj"
    Among(&[105, 97, 106], 1, -1, None), // "iaj"
    Among(&[105, 101, 106], -1, -1, None), // "iej"
    Among(&[111, 106], -1, -1, None), // "oj"
    Among(&[105, 111, 106], 4, -1, None), // "ioj"
    Among(&[117, 111, 106], 4, -1, None), // "uoj"
    Among(&[105, 117, 111, 106], 6, -1, None), // "iuoj"
    Among(&[97, 117, 106], -1, -1, None), // "auj"
    Among(&[261, 106], -1, -1, None), // "\u{0105}j"
    Among(&[105, 261, 106], 9, -1, None), // "i\u{0105}j"
    Among(&[279, 106], -1, -1, None), // "\u{0117}j"
    Among(&[371, 106], -1, -1, None), // "\u{0173}j"
    Among(&[105, 371, 106], 12, -1, None), // "i\u{0173}j"
    Among(&[111, 107], -1, -1, None), // "ok"
    Among(&[105, 111, 107], 14, -1, None), // "iok"
    Among(&[105, 117, 107], -1, -1, None), // "iuk"
    Among(&[117, 108, 105, 117, 107], 16, -1, None), // "uliuk"
    Among(&[117, 269, 105, 117, 107], 16, -1, None), // "u\u{010D}iuk"
    Among(&[105, 353, 107], -1, -1, None), // "i\u{0161}k"
    Among(&[105, 117, 108], -1, -1, None), // "iul"
    Among(&[121, 108], -1, -1, None), // "yl"
    Among(&[279, 108], -1, -1, None), // "\u{0117}l"
    Among(&[97, 109], -1, -1, None), // "am"
    Among(&[100, 97, 109], 23, -1, None), // "dam"
    Among(&[106, 97, 109], 23, -1, None), // "jam"
    Among(&[122, 103, 97, 110], -1, -1, None), // "zgan"
    Among(&[97, 105, 110], -1, -1, None), // "ain"
    Among(&[101, 115, 110], -1, -1, None), // "esn"
    Among(&[111, 112], -1, -1, None), // "op"
    Among(&[105, 111, 112], 29, -1, None), // "iop"
    Among(&[105, 97, 115], -1, -1, None), // "ias"
    Among(&[105, 101, 115], -1, -1, None), // "ies"
    Among(&[97, 105, 115], -1, -1, None), // "ais"
    Among(&[105, 97, 105, 115], 33, -1, None), // "iais"
    Among(&[111, 115], -1, -1, None), // "os"
    Among(&[105, 111, 115], 35, -1, None), // "ios"
    Among(&[117, 111, 115], 35, -1, None), // "uos"
    Among(&[105, 117, 111, 115], 37, -1, None), // "iuos"
    Among(&[97, 117, 115], -1, -1, None), // "aus"
    Among(&[105, 97, 117, 115], 39, -1, None), // "iaus"
    Among(&[261, 115], -1, -1, None), // "\u{0105}s"
    Among(&[105, 261, 115], 41, -1, None), // "i\u{0105}s"
    Among(&[281, 115], -1, -1, None), // "\u{0119}s"
    Among(&[117, 116, 279, 97, 105, 116], -1, -1, None), // "ut\u{0117}ait"
    Among(&[97, 110, 116], -1, -1, None), // "ant"
    Among(&[105, 97, 110, 116], 45, -1, None), // "iant"
    Among(&[115, 105, 97, 110, 116], 46, -1, None), // "siant"
    Among(&[105, 110, 116], -1, -1, None), // "int"
    Among(&[111, 116], -1, -1, None), // "ot"
    Among(&[117, 111, 116], 49, -1, None), // "uot"
    Among(&[105, 117, 111, 116], 50, -1, None), // "iuot"
    Among(&[121, 116], -1, -1, None), // "yt"
    Among(&[279, 116], -1, -1, None), // "\u{0117}t"
    Among(&[121, 107, 353, 116], -1, -1, None), // "yk\u{0161}t"
    Among(&[105, 97, 117], -1, -1, None), // "iau"
    Among(&[100, 97, 118], -1, -1, None), // "dav"
    Among(&[115, 118], -1, -1, None), // "sv"
    Among(&[353, 118], -1, -1, None), // "\u{0161}v"
    Among(&[121, 107, 353, 269], -1, -1, None), // "yk\u{0161}\u{010D}"
    Among(&[281], -1, -1, None), // "\u{0119}"
    Among(&[279, 106, 281], 60, -1, None), // "\u{0117}j\u{0119}"
];

static A_2: &'static [Among<Context>; 11] = &[
    Among(&[111, 106, 105, 109, 101], -1, 7, None), // "ojime"
    Among(&[279, 106, 105, 109, 101], -1, 3, None), // "\u{0117}jime"
    Among(&[97, 118, 105, 109, 101], -1, 6, None), // "avime"
    Among(&[111, 107, 97, 116, 101], -1, 8, None), // "okate"
    Among(&[97, 105, 116, 101], -1, 1, None), // "aite"
    Among(&[117, 111, 116, 101], -1, 2, None), // "uote"
    Among(&[97, 115, 105, 117, 115], -1, 5, None), // "asius"
    Among(&[111, 107, 97, 116, 279, 115], -1, 8, None), // "okat\u{0117}s"
    Among(&[97, 105, 116, 279, 115], -1, 1, None), // "ait\u{0117}s"
    Among(&[117, 111, 116, 279, 115], -1, 2, None), // "uot\u{0117}s"
    Among(&[101, 115, 105, 117], -1, 4, None), // "esiu"
];

static A_3: &'static [Among<Context>; 2] = &[
    Among(&[269], -1, 1, None), // "\u{010D}"
    Among(&[100, 382], -1, 2, None), // "d\u{017E}"
];

static A_4: &'static [Among<Context>; 1] = &[
    Among(&[103, 100], -1, 1, None), // "gd"
];

static G_v: &'static [u8; 35] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 16, 0, 64, 1, 0, 64, 0, 0, 0, 0, 0, 0, 0, 4, 4];

#[derive(Clone)]
struct Context {
    i_p1: i32,
}

fn r_step1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    if env.find_among_b(A_0, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    env.slice_del();
    return true
}

fn r_step2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    'replab0: loop{
        let v_1 = env.limit - env.cursor;
        'lab1: for _ in 0..1 {
            if env.cursor < context.i_p1 {
                break 'lab1;
            }
            let v_3 = env.limit_backward;
            env.limit_backward = context.i_p1;
            env.ket = env.cursor;
            if env.find_among_b(A_1, context) == 0 {
                env.limit_backward = v_3;
                break 'lab1;
            }
            env.bra = env.cursor;
            env.limit_backward = v_3;
            env.slice_del();
            continue 'replab0;
        }
        env.cursor = env.limit - v_1;
        break 'replab0;
    }
    return true
}

fn r_fix_conflicts(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            env.slice_from(&[97, 105, 116, 279]);
        }
        2 => {
            env.slice_from(&[117, 111, 116, 279]);
        }
        3 => {
            env.slice_from(&[279, 106, 105, 109, 97, 115]);
        }
        4 => {
            env.slice_from(&[101, 115, 121, 115]);
        }
        5 => {
            env.slice_from(&[97, 115, 121, 115]);
        }
        6 => {
            env.slice_from(&[97, 118, 105, 109, 97, 115]);
        }
        7 => {
            env.slice_from(&[111, 106, 105, 109, 97, 115]);
        }
        8 => {
            env.slice_from(&[111, 107, 97, 116, 279]);
        }
        _ => ()
    }
    return true
}

fn r_fix_chdz(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_3, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            env.slice_from(&[116]);
        }
        2 => {
            env.slice_from(&[100]);
        }
        _ => ()
    }
    return true
}

fn r_fix_gd(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_4, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    env.slice_from(&[103]);
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p1: 0,
    };
    context.i_p1 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        let v_2 = env.cursor;
        'lab1: loop {
            let v_3 = env.cursor;
            if !env.eq_s(&[97]) {
                env.cursor = v_2;
                break 'lab1;
            }
            env.cursor = v_3;
            if env.length <= 6{
                env.cursor = v_2;
                break 'lab1;
            }
            if !env.hop(1) {
                env.cursor = v_2;
                break 'lab1;
            }
            break 'lab1;
        }
        'golab2: loop {
            'lab3: loop {
                if !env.in_grouping(G_v, 97, 371) {
                    break 'lab3;
                }
                break 'golab2;
            }
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
        }
        'golab4: loop {
            'lab5: loop {
                if !env.out_grouping(G_v, 97, 371) {
                    break 'lab5;
                }
                break 'golab4;
            }
            if env.cursor >= env.limit {
                break 'lab0;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_6 = env.limit - env.cursor;
    r_fix_conflicts(env, context);
    env.cursor = env.limit - v_6;
    let v_7 = env.limit - env.cursor;
    r_step1(env, context);
    env.cursor = env.limit - v_7;
    let v_8 = env.limit - env.cursor;
    r_fix_chdz(env, context);
    env.cursor = env.limit - v_8;
    let v_9 = env.limit - env.cursor;
    r_step2(env, context);
    env.cursor = env.limit - v_9;
    let v_10 = env.limit - env.cursor;
    r_fix_chdz(env, context);
    env.cursor = env.limit - v_10;
    let v_11 = env.limit - env.cursor;
    r_fix_gd(env, context);
    env.cursor = env.limit - v_11;
    env.cursor = env.limit_backward;
    return true
}
