//! The Snowball compiler's Rust output for every stemmer Lucene 10.5.0
//! ships (`org.tartarus.snowball.ext.*Stemmer`), generated by
//! `tools/gen_snowball.sh` from Snowball commit
//! `34f3612e5e8c48975243bc2e87561abdac5aa9bb`. Do not edit.

#![allow(clippy::all, clippy::pedantic, unused_labels, unreachable_code, rustdoc::bare_urls)]

pub mod arabic;
pub mod armenian;
pub mod basque;
pub mod catalan;
pub mod danish;
pub mod dutch;
pub mod english;
pub mod estonian;
pub mod finnish;
pub mod french;
pub mod german;
pub mod greek;
pub mod hindi;
pub mod hungarian;
pub mod indonesian;
pub mod irish;
pub mod italian;
pub mod lithuanian;
pub mod nepali;
pub mod norwegian;
pub mod porter;
pub mod portuguese;
pub mod romanian;
pub mod russian;
pub mod serbian;
pub mod spanish;
pub mod swedish;
pub mod tamil;
pub mod turkish;
pub mod yiddish;

/// `(Java class name without `Stemmer`, the generated `stem`)`, in
/// `languages.txt` order.
pub static STEMMERS: [(&str, fn(&mut super::program::SnowballEnv) -> bool); 30] = [
    ("Arabic", arabic::stem),
    ("Armenian", armenian::stem),
    ("Basque", basque::stem),
    ("Catalan", catalan::stem),
    ("Danish", danish::stem),
    ("Dutch", dutch::stem),
    ("English", english::stem),
    ("Estonian", estonian::stem),
    ("Finnish", finnish::stem),
    ("French", french::stem),
    ("German", german::stem),
    ("Greek", greek::stem),
    ("Hindi", hindi::stem),
    ("Hungarian", hungarian::stem),
    ("Indonesian", indonesian::stem),
    ("Irish", irish::stem),
    ("Italian", italian::stem),
    ("Lithuanian", lithuanian::stem),
    ("Nepali", nepali::stem),
    ("Norwegian", norwegian::stem),
    ("Porter", porter::stem),
    ("Portuguese", portuguese::stem),
    ("Romanian", romanian::stem),
    ("Russian", russian::stem),
    ("Serbian", serbian::stem),
    ("Spanish", spanish::stem),
    ("Swedish", swedish::stem),
    ("Tamil", tamil::stem),
    ("Turkish", turkish::stem),
    ("Yiddish", yiddish::stem),
];
