//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 17] = &[
    Among(&[2354, 2366, 2311], -1, 1, None), // "\u{0932}\u{093E}\u{0907}"
    Among(&[2354, 2366, 2312], -1, 1, None), // "\u{0932}\u{093E}\u{0908}"
    Among(&[2360, 2305, 2327], -1, 1, None), // "\u{0938}\u{0901}\u{0917}"
    Among(&[2360, 2306, 2327], -1, 1, None), // "\u{0938}\u{0902}\u{0917}"
    Among(&[2350, 2366, 2352, 2381, 2347, 2340], -1, 1, None), // "\u{092E}\u{093E}\u{0930}\u{094D}\u{092B}\u{0924}"
    Among(&[2352, 2340], -1, 1, None), // "\u{0930}\u{0924}"
    Among(&[2325, 2366], -1, 2, None), // "\u{0915}\u{093E}"
    Among(&[2350, 2366], -1, 1, None), // "\u{092E}\u{093E}"
    Among(&[2342, 2381, 2357, 2366, 2352, 2366], -1, 1, None), // "\u{0926}\u{094D}\u{0935}\u{093E}\u{0930}\u{093E}"
    Among(&[2325, 2367], -1, 2, None), // "\u{0915}\u{093F}"
    Among(&[2346, 2331, 2367], -1, 1, None), // "\u{092A}\u{091B}\u{093F}"
    Among(&[2325, 2368], -1, 2, None), // "\u{0915}\u{0940}"
    Among(&[2354, 2375], -1, 1, None), // "\u{0932}\u{0947}"
    Among(&[2325, 2376], -1, 2, None), // "\u{0915}\u{0948}"
    Among(&[2360, 2305, 2327, 2376], -1, 1, None), // "\u{0938}\u{0901}\u{0917}\u{0948}"
    Among(&[2350, 2376], -1, 1, None), // "\u{092E}\u{0948}"
    Among(&[2325, 2379], -1, 2, None), // "\u{0915}\u{094B}"
];

static A_1: &'static [Among<Context>; 3] = &[
    Among(&[2305], -1, -1, None), // "\u{0901}"
    Among(&[2306], -1, -1, None), // "\u{0902}"
    Among(&[2376], -1, -1, None), // "\u{0948}"
];

static A_2: &'static [Among<Context>; 3] = &[
    Among(&[2305], -1, 1, None), // "\u{0901}"
    Among(&[2306], -1, 1, None), // "\u{0902}"
    Among(&[2376], -1, 2, None), // "\u{0948}"
];

static A_3: &'static [Among<Context>; 91] = &[
    Among(&[2341, 2367, 2319], -1, 1, None), // "\u{0925}\u{093F}\u{090F}"
    Among(&[2331], -1, 1, None), // "\u{091B}"
    Among(&[2311, 2331], 1, 1, None), // "\u{0907}\u{091B}"
    Among(&[2319, 2331], 1, 1, None), // "\u{090F}\u{091B}"
    Among(&[2367, 2331], 1, 1, None), // "\u{093F}\u{091B}"
    Among(&[2375, 2331], 1, 1, None), // "\u{0947}\u{091B}"
    Among(&[2344, 2375, 2331], 5, 1, None), // "\u{0928}\u{0947}\u{091B}"
    Among(&[2361, 2369, 2344, 2375, 2331], 6, 1, None), // "\u{0939}\u{0941}\u{0928}\u{0947}\u{091B}"
    Among(&[2311, 2344, 2381, 2331], 1, 1, None), // "\u{0907}\u{0928}\u{094D}\u{091B}"
    Among(&[2367, 2344, 2381, 2331], 1, 1, None), // "\u{093F}\u{0928}\u{094D}\u{091B}"
    Among(&[2361, 2369, 2344, 2381, 2331], 1, 1, None), // "\u{0939}\u{0941}\u{0928}\u{094D}\u{091B}"
    Among(&[2319, 2325, 2366], -1, 1, None), // "\u{090F}\u{0915}\u{093E}"
    Among(&[2311, 2319, 2325, 2366], 11, 1, None), // "\u{0907}\u{090F}\u{0915}\u{093E}"
    Among(&[2367, 2319, 2325, 2366], 11, 1, None), // "\u{093F}\u{090F}\u{0915}\u{093E}"
    Among(&[2375, 2325, 2366], -1, 1, None), // "\u{0947}\u{0915}\u{093E}"
    Among(&[2344, 2375, 2325, 2366], 14, 1, None), // "\u{0928}\u{0947}\u{0915}\u{093E}"
    Among(&[2342, 2366], -1, 1, None), // "\u{0926}\u{093E}"
    Among(&[2311, 2342, 2366], 16, 1, None), // "\u{0907}\u{0926}\u{093E}"
    Among(&[2367, 2342, 2366], 16, 1, None), // "\u{093F}\u{0926}\u{093E}"
    Among(&[2342, 2375, 2326, 2367], -1, 1, None), // "\u{0926}\u{0947}\u{0916}\u{093F}"
    Among(&[2350, 2366, 2341, 2367], -1, 1, None), // "\u{092E}\u{093E}\u{0925}\u{093F}"
    Among(&[2319, 2325, 2368], -1, 1, None), // "\u{090F}\u{0915}\u{0940}"
    Among(&[2311, 2319, 2325, 2368], 21, 1, None), // "\u{0907}\u{090F}\u{0915}\u{0940}"
    Among(&[2367, 2319, 2325, 2368], 21, 1, None), // "\u{093F}\u{090F}\u{0915}\u{0940}"
    Among(&[2375, 2325, 2368], -1, 1, None), // "\u{0947}\u{0915}\u{0940}"
    Among(&[2342, 2375, 2326, 2368], -1, 1, None), // "\u{0926}\u{0947}\u{0916}\u{0940}"
    Among(&[2341, 2368], -1, 1, None), // "\u{0925}\u{0940}"
    Among(&[2342, 2368], -1, 1, None), // "\u{0926}\u{0940}"
    Among(&[2331, 2369], -1, 1, None), // "\u{091B}\u{0941}"
    Among(&[2319, 2331, 2369], 28, 1, None), // "\u{090F}\u{091B}\u{0941}"
    Among(&[2375, 2331, 2369], 28, 1, None), // "\u{0947}\u{091B}\u{0941}"
    Among(&[2344, 2375, 2331, 2369], 30, 1, None), // "\u{0928}\u{0947}\u{091B}\u{0941}"
    Among(&[2344, 2369], -1, 1, None), // "\u{0928}\u{0941}"
    Among(&[2361, 2352, 2369], -1, 1, None), // "\u{0939}\u{0930}\u{0941}"
    Among(&[2361, 2352, 2370], -1, 1, None), // "\u{0939}\u{0930}\u{0942}"
    Among(&[2331, 2375], -1, 1, None), // "\u{091B}\u{0947}"
    Among(&[2341, 2375], -1, 1, None), // "\u{0925}\u{0947}"
    Among(&[2344, 2375], -1, 1, None), // "\u{0928}\u{0947}"
    Among(&[2319, 2325, 2376], -1, 1, None), // "\u{090F}\u{0915}\u{0948}"
    Among(&[2375, 2325, 2376], -1, 1, None), // "\u{0947}\u{0915}\u{0948}"
    Among(&[2344, 2375, 2325, 2376], 39, 1, None), // "\u{0928}\u{0947}\u{0915}\u{0948}"
    Among(&[2342, 2376], -1, 1, None), // "\u{0926}\u{0948}"
    Among(&[2311, 2342, 2376], 41, 1, None), // "\u{0907}\u{0926}\u{0948}"
    Among(&[2367, 2342, 2376], 41, 1, None), // "\u{093F}\u{0926}\u{0948}"
    Among(&[2319, 2325, 2379], -1, 1, None), // "\u{090F}\u{0915}\u{094B}"
    Among(&[2311, 2319, 2325, 2379], 44, 1, None), // "\u{0907}\u{090F}\u{0915}\u{094B}"
    Among(&[2367, 2319, 2325, 2379], 44, 1, None), // "\u{093F}\u{090F}\u{0915}\u{094B}"
    Among(&[2375, 2325, 2379], -1, 1, None), // "\u{0947}\u{0915}\u{094B}"
    Among(&[2344, 2375, 2325, 2379], 47, 1, None), // "\u{0928}\u{0947}\u{0915}\u{094B}"
    Among(&[2342, 2379], -1, 1, None), // "\u{0926}\u{094B}"
    Among(&[2311, 2342, 2379], 49, 1, None), // "\u{0907}\u{0926}\u{094B}"
    Among(&[2367, 2342, 2379], 49, 1, None), // "\u{093F}\u{0926}\u{094B}"
    Among(&[2351, 2379], -1, 1, None), // "\u{092F}\u{094B}"
    Among(&[2311, 2351, 2379], 52, 1, None), // "\u{0907}\u{092F}\u{094B}"
    Among(&[2349, 2351, 2379], 52, 1, None), // "\u{092D}\u{092F}\u{094B}"
    Among(&[2367, 2351, 2379], 52, 1, None), // "\u{093F}\u{092F}\u{094B}"
    Among(&[2341, 2367, 2351, 2379], 55, 1, None), // "\u{0925}\u{093F}\u{092F}\u{094B}"
    Among(&[2342, 2367, 2351, 2379], 55, 1, None), // "\u{0926}\u{093F}\u{092F}\u{094B}"
    Among(&[2341, 2381, 2351, 2379], 52, 1, None), // "\u{0925}\u{094D}\u{092F}\u{094B}"
    Among(&[2331, 2380], -1, 1, None), // "\u{091B}\u{094C}"
    Among(&[2311, 2331, 2380], 59, 1, None), // "\u{0907}\u{091B}\u{094C}"
    Among(&[2319, 2331, 2380], 59, 1, None), // "\u{090F}\u{091B}\u{094C}"
    Among(&[2367, 2331, 2380], 59, 1, None), // "\u{093F}\u{091B}\u{094C}"
    Among(&[2375, 2331, 2380], 59, 1, None), // "\u{0947}\u{091B}\u{094C}"
    Among(&[2344, 2375, 2331, 2380], 63, 1, None), // "\u{0928}\u{0947}\u{091B}\u{094C}"
    Among(&[2351, 2380], -1, 1, None), // "\u{092F}\u{094C}"
    Among(&[2341, 2367, 2351, 2380], 65, 1, None), // "\u{0925}\u{093F}\u{092F}\u{094C}"
    Among(&[2331, 2381, 2351, 2380], 65, 1, None), // "\u{091B}\u{094D}\u{092F}\u{094C}"
    Among(&[2341, 2381, 2351, 2380], 65, 1, None), // "\u{0925}\u{094D}\u{092F}\u{094C}"
    Among(&[2331, 2344, 2381], -1, 1, None), // "\u{091B}\u{0928}\u{094D}"
    Among(&[2311, 2331, 2344, 2381], 69, 1, None), // "\u{0907}\u{091B}\u{0928}\u{094D}"
    Among(&[2319, 2331, 2344, 2381], 69, 1, None), // "\u{090F}\u{091B}\u{0928}\u{094D}"
    Among(&[2367, 2331, 2344, 2381], 69, 1, None), // "\u{093F}\u{091B}\u{0928}\u{094D}"
    Among(&[2375, 2331, 2344, 2381], 69, 1, None), // "\u{0947}\u{091B}\u{0928}\u{094D}"
    Among(&[2344, 2375, 2331, 2344, 2381], 73, 1, None), // "\u{0928}\u{0947}\u{091B}\u{0928}\u{094D}"
    Among(&[2354, 2366, 2344, 2381], -1, 1, None), // "\u{0932}\u{093E}\u{0928}\u{094D}"
    Among(&[2331, 2367, 2344, 2381], -1, 1, None), // "\u{091B}\u{093F}\u{0928}\u{094D}"
    Among(&[2341, 2367, 2344, 2381], -1, 1, None), // "\u{0925}\u{093F}\u{0928}\u{094D}"
    Among(&[2346, 2352, 2381], -1, 1, None), // "\u{092A}\u{0930}\u{094D}"
    Among(&[2311, 2360, 2381], -1, 1, None), // "\u{0907}\u{0938}\u{094D}"
    Among(&[2341, 2367, 2311, 2360, 2381], 79, 1, None), // "\u{0925}\u{093F}\u{0907}\u{0938}\u{094D}"
    Among(&[2331, 2360, 2381], -1, 1, None), // "\u{091B}\u{0938}\u{094D}"
    Among(&[2311, 2331, 2360, 2381], 81, 1, None), // "\u{0907}\u{091B}\u{0938}\u{094D}"
    Among(&[2319, 2331, 2360, 2381], 81, 1, None), // "\u{090F}\u{091B}\u{0938}\u{094D}"
    Among(&[2367, 2331, 2360, 2381], 81, 1, None), // "\u{093F}\u{091B}\u{0938}\u{094D}"
    Among(&[2375, 2331, 2360, 2381], 81, 1, None), // "\u{0947}\u{091B}\u{0938}\u{094D}"
    Among(&[2344, 2375, 2331, 2360, 2381], 85, 1, None), // "\u{0928}\u{0947}\u{091B}\u{0938}\u{094D}"
    Among(&[2367, 2360, 2381], -1, 1, None), // "\u{093F}\u{0938}\u{094D}"
    Among(&[2341, 2367, 2360, 2381], 87, 1, None), // "\u{0925}\u{093F}\u{0938}\u{094D}"
    Among(&[2331, 2375, 2360, 2381], -1, 1, None), // "\u{091B}\u{0947}\u{0938}\u{094D}"
    Among(&[2361, 2379, 2360, 2381], -1, 1, None), // "\u{0939}\u{094B}\u{0938}\u{094D}"
];

#[derive(Clone)]
struct Context {
}

fn r_remove_category_1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_0, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    'lab2: loop {
                        let v_2 = env.limit - env.cursor;
                        'lab3: loop {
                            if !env.eq_s_b(&[2319]) {
                                break 'lab3;
                            }
                            break 'lab2;
                        }
                        env.cursor = env.limit - v_2;
                        if !env.eq_s_b(&[2375]) {
                            break 'lab1;
                        }
                        break 'lab2;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                env.slice_del();
                break 'lab0;
            }
        }
        _ => ()
    }
    return true
}

fn r_check_category_2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_1, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    return true
}

fn r_remove_category_2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.eq_s_b(&[2351, 2380]) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                'lab2: loop {
                    if !env.eq_s_b(&[2331, 2380]) {
                        break 'lab2;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                'lab3: loop {
                    if !env.eq_s_b(&[2344, 2380]) {
                        break 'lab3;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                if !env.eq_s_b(&[2341, 2375]) {
                    return false;
                }
                break 'lab0;
            }
            env.slice_del();
        }
        2 => {
            if !env.eq_s_b(&[2340, 2381, 2352]) {
                return false;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_remove_category_3(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_3, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    env.slice_del();
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
    };
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_1 = env.limit - env.cursor;
    r_remove_category_1(env, context);
    env.cursor = env.limit - v_1;
    let v_2 = env.limit - env.cursor;
    'lab0: loop {
        'replab1: loop{
            let v_3 = env.limit - env.cursor;
            'lab2: for _ in 0..1 {
                let v_4 = env.limit - env.cursor;
                'lab3: loop {
                    let v_5 = env.limit - env.cursor;
                    if !r_check_category_2(env, context) {
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_5;
                    if !r_remove_category_2(env, context) {
                        break 'lab3;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_4;
                if !r_remove_category_3(env, context) {
                    break 'lab2;
                }
                continue 'replab1;
            }
            env.cursor = env.limit - v_3;
            break 'replab1;
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_2;
    env.cursor = env.limit_backward;
    return true
}
