//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 29] = &[
    Among(&[97], -1, 1, None), // "a"
    Among(&[101], -1, 1, None), // "e"
    Among(&[101, 100, 101], 1, 1, None), // "ede"
    Among(&[97, 110, 100, 101], 1, 1, None), // "ande"
    Among(&[101, 110, 100, 101], 1, 1, None), // "ende"
    Among(&[97, 110, 101], 1, 1, None), // "ane"
    Among(&[101, 110, 101], 1, 1, None), // "ene"
    Among(&[104, 101, 116, 101, 110, 101], 6, 1, None), // "hetene"
    Among(&[101, 114, 116, 101], 1, 3, None), // "erte"
    Among(&[101, 110], -1, 1, None), // "en"
    Among(&[104, 101, 116, 101, 110], 9, 1, None), // "heten"
    Among(&[97, 114], -1, 1, None), // "ar"
    Among(&[101, 114], -1, 1, None), // "er"
    Among(&[104, 101, 116, 101, 114], 12, 1, None), // "heter"
    Among(&[115], -1, 2, None), // "s"
    Among(&[97, 115], 14, 1, None), // "as"
    Among(&[101, 115], 14, 1, None), // "es"
    Among(&[101, 100, 101, 115], 16, 1, None), // "edes"
    Among(&[101, 110, 100, 101, 115], 16, 1, None), // "endes"
    Among(&[101, 110, 101, 115], 16, 1, None), // "enes"
    Among(&[104, 101, 116, 101, 110, 101, 115], 19, 1, None), // "hetenes"
    Among(&[101, 110, 115], 14, 1, None), // "ens"
    Among(&[104, 101, 116, 101, 110, 115], 21, 1, None), // "hetens"
    Among(&[101, 114, 115], 14, 1, None), // "ers"
    Among(&[101, 116, 115], 14, 1, None), // "ets"
    Among(&[101, 116], -1, 1, None), // "et"
    Among(&[104, 101, 116], 25, 1, None), // "het"
    Among(&[101, 114, 116], -1, 3, None), // "ert"
    Among(&[97, 115, 116], -1, 1, None), // "ast"
];

static A_1: &'static [Among<Context>; 2] = &[
    Among(&[100, 116], -1, -1, None), // "dt"
    Among(&[118, 116], -1, -1, None), // "vt"
];

static A_2: &'static [Among<Context>; 11] = &[
    Among(&[108, 101, 103], -1, 1, None), // "leg"
    Among(&[101, 108, 101, 103], 0, 1, None), // "eleg"
    Among(&[105, 103], -1, 1, None), // "ig"
    Among(&[101, 105, 103], 2, 1, None), // "eig"
    Among(&[108, 105, 103], 2, 1, None), // "lig"
    Among(&[101, 108, 105, 103], 4, 1, None), // "elig"
    Among(&[101, 108, 115], -1, 1, None), // "els"
    Among(&[108, 111, 118], -1, 1, None), // "lov"
    Among(&[101, 108, 111, 118], 7, 1, None), // "elov"
    Among(&[115, 108, 111, 118], 7, 1, None), // "slov"
    Among(&[104, 101, 116, 115, 108, 111, 118], 9, 1, None), // "hetslov"
];

static G_v: &'static [u8; 19] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 0, 128];

static G_s_ending: &'static [u8; 4] = &[119, 125, 149, 1];

#[derive(Clone)]
struct Context {
    i_x: i32,
    i_p1: i32,
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_p1 = env.limit;
    let v_1 = env.cursor;
    if !env.hop(3) {
        return false;
    }
    context.i_x = env.cursor;
    env.cursor = v_1;
    'golab0: loop {
        let v_2 = env.cursor;
        'lab1: loop {
            if !env.in_grouping(G_v, 97, 248) {
                break 'lab1;
            }
            env.cursor = v_2;
            break 'golab0;
        }
        env.cursor = v_2;
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    'golab2: loop {
        'lab3: loop {
            if !env.out_grouping(G_v, 97, 248) {
                break 'lab3;
            }
            break 'golab2;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    context.i_p1 = env.cursor;
    'lab4: loop {
        if context.i_p1 >= context.i_x{
            break 'lab4;
        }
        context.i_p1 = context.i_x;
        break 'lab4;
    }
    return true
}

fn r_main_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_0, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            'lab0: loop {
                let v_3 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.in_grouping_b(G_s_ending, 98, 122) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_3;
                if !env.eq_s_b(&[107]) {
                    return false;
                }
                if !env.out_grouping_b(G_v, 97, 248) {
                    return false;
                }
                break 'lab0;
            }
            env.slice_del();
        }
        3 => {
            env.slice_from(&[101, 114]);
        }
        _ => ()
    }
    return true
}

fn r_consonant_pair(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.limit - env.cursor;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_3 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    if env.find_among_b(A_1, context) == 0 {
        env.limit_backward = v_3;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_3;
    env.cursor = env.limit - v_1;
    if env.cursor <= env.limit_backward {
        return false;
    }
    env.previous_char();
    env.bra = env.cursor;
    env.slice_del();
    return true
}

fn r_other_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    if env.find_among_b(A_2, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    env.slice_del();
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_x: 0,
        i_p1: 0,
    };
    let v_1 = env.cursor;
    r_mark_regions(env, context);
    env.cursor = v_1;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_2 = env.limit - env.cursor;
    r_main_suffix(env, context);
    env.cursor = env.limit - v_2;
    let v_3 = env.limit - env.cursor;
    r_consonant_pair(env, context);
    env.cursor = env.limit - v_3;
    let v_4 = env.limit - env.cursor;
    r_other_suffix(env, context);
    env.cursor = env.limit - v_4;
    env.cursor = env.limit_backward;
    return true
}
