//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 3] = &[
    Among(&[], -1, 3, None), // ""
    Among(&[227], 0, 1, None), // "\u{00E3}"
    Among(&[245], 0, 2, None), // "\u{00F5}"
];

static A_1: &'static [Among<Context>; 3] = &[
    Among(&[], -1, 3, None), // ""
    Among(&[97, 126], 0, 1, None), // "a~"
    Among(&[111, 126], 0, 2, None), // "o~"
];

static A_2: &'static [Among<Context>; 4] = &[
    Among(&[105, 99], -1, -1, None), // "ic"
    Among(&[97, 100], -1, -1, None), // "ad"
    Among(&[111, 115], -1, -1, None), // "os"
    Among(&[105, 118], -1, 1, None), // "iv"
];

static A_3: &'static [Among<Context>; 3] = &[
    Among(&[97, 110, 116, 101], -1, 1, None), // "ante"
    Among(&[97, 118, 101, 108], -1, 1, None), // "avel"
    Among(&[237, 118, 101, 108], -1, 1, None), // "\u{00ED}vel"
];

static A_4: &'static [Among<Context>; 3] = &[
    Among(&[105, 99], -1, 1, None), // "ic"
    Among(&[97, 98, 105, 108], -1, 1, None), // "abil"
    Among(&[105, 118], -1, 1, None), // "iv"
];

static A_5: &'static [Among<Context>; 45] = &[
    Among(&[105, 99, 97], -1, 1, None), // "ica"
    Among(&[226, 110, 99, 105, 97], -1, 1, None), // "\u{00E2}ncia"
    Among(&[234, 110, 99, 105, 97], -1, 4, None), // "\u{00EA}ncia"
    Among(&[108, 111, 103, 105, 97], -1, 2, None), // "logia"
    Among(&[105, 114, 97], -1, 9, None), // "ira"
    Among(&[97, 100, 111, 114, 97], -1, 1, None), // "adora"
    Among(&[111, 115, 97], -1, 1, None), // "osa"
    Among(&[105, 115, 116, 97], -1, 1, None), // "ista"
    Among(&[105, 118, 97], -1, 8, None), // "iva"
    Among(&[101, 122, 97], -1, 1, None), // "eza"
    Among(&[105, 100, 97, 100, 101], -1, 7, None), // "idade"
    Among(&[97, 110, 116, 101], -1, 1, None), // "ante"
    Among(&[109, 101, 110, 116, 101], -1, 6, None), // "mente"
    Among(&[97, 109, 101, 110, 116, 101], 12, 5, None), // "amente"
    Among(&[225, 118, 101, 108], -1, 1, None), // "\u{00E1}vel"
    Among(&[237, 118, 101, 108], -1, 1, None), // "\u{00ED}vel"
    Among(&[105, 99, 111], -1, 1, None), // "ico"
    Among(&[105, 115, 109, 111], -1, 1, None), // "ismo"
    Among(&[111, 115, 111], -1, 1, None), // "oso"
    Among(&[97, 109, 101, 110, 116, 111], -1, 1, None), // "amento"
    Among(&[105, 109, 101, 110, 116, 111], -1, 1, None), // "imento"
    Among(&[105, 118, 111], -1, 8, None), // "ivo"
    Among(&[97, 231, 97, 126, 111], -1, 1, None), // "a\u{00E7}a~o"
    Among(&[117, 231, 97, 126, 111], -1, 3, None), // "u\u{00E7}a~o"
    Among(&[97, 100, 111, 114], -1, 1, None), // "ador"
    Among(&[105, 99, 97, 115], -1, 1, None), // "icas"
    Among(&[234, 110, 99, 105, 97, 115], -1, 4, None), // "\u{00EA}ncias"
    Among(&[108, 111, 103, 105, 97, 115], -1, 2, None), // "logias"
    Among(&[105, 114, 97, 115], -1, 9, None), // "iras"
    Among(&[97, 100, 111, 114, 97, 115], -1, 1, None), // "adoras"
    Among(&[111, 115, 97, 115], -1, 1, None), // "osas"
    Among(&[105, 115, 116, 97, 115], -1, 1, None), // "istas"
    Among(&[105, 118, 97, 115], -1, 8, None), // "ivas"
    Among(&[101, 122, 97, 115], -1, 1, None), // "ezas"
    Among(&[105, 100, 97, 100, 101, 115], -1, 7, None), // "idades"
    Among(&[97, 100, 111, 114, 101, 115], -1, 1, None), // "adores"
    Among(&[97, 110, 116, 101, 115], -1, 1, None), // "antes"
    Among(&[97, 231, 111, 126, 101, 115], -1, 1, None), // "a\u{00E7}o~es"
    Among(&[117, 231, 111, 126, 101, 115], -1, 3, None), // "u\u{00E7}o~es"
    Among(&[105, 99, 111, 115], -1, 1, None), // "icos"
    Among(&[105, 115, 109, 111, 115], -1, 1, None), // "ismos"
    Among(&[111, 115, 111, 115], -1, 1, None), // "osos"
    Among(&[97, 109, 101, 110, 116, 111, 115], -1, 1, None), // "amentos"
    Among(&[105, 109, 101, 110, 116, 111, 115], -1, 1, None), // "imentos"
    Among(&[105, 118, 111, 115], -1, 8, None), // "ivos"
];

static A_6: &'static [Among<Context>; 120] = &[
    Among(&[97, 100, 97], -1, 1, None), // "ada"
    Among(&[105, 100, 97], -1, 1, None), // "ida"
    Among(&[105, 97], -1, 1, None), // "ia"
    Among(&[97, 114, 105, 97], 2, 1, None), // "aria"
    Among(&[101, 114, 105, 97], 2, 1, None), // "eria"
    Among(&[105, 114, 105, 97], 2, 1, None), // "iria"
    Among(&[97, 114, 97], -1, 1, None), // "ara"
    Among(&[101, 114, 97], -1, 1, None), // "era"
    Among(&[105, 114, 97], -1, 1, None), // "ira"
    Among(&[97, 118, 97], -1, 1, None), // "ava"
    Among(&[97, 115, 115, 101], -1, 1, None), // "asse"
    Among(&[101, 115, 115, 101], -1, 1, None), // "esse"
    Among(&[105, 115, 115, 101], -1, 1, None), // "isse"
    Among(&[97, 115, 116, 101], -1, 1, None), // "aste"
    Among(&[101, 115, 116, 101], -1, 1, None), // "este"
    Among(&[105, 115, 116, 101], -1, 1, None), // "iste"
    Among(&[101, 105], -1, 1, None), // "ei"
    Among(&[97, 114, 101, 105], 16, 1, None), // "arei"
    Among(&[101, 114, 101, 105], 16, 1, None), // "erei"
    Among(&[105, 114, 101, 105], 16, 1, None), // "irei"
    Among(&[97, 109], -1, 1, None), // "am"
    Among(&[105, 97, 109], 20, 1, None), // "iam"
    Among(&[97, 114, 105, 97, 109], 21, 1, None), // "ariam"
    Among(&[101, 114, 105, 97, 109], 21, 1, None), // "eriam"
    Among(&[105, 114, 105, 97, 109], 21, 1, None), // "iriam"
    Among(&[97, 114, 97, 109], 20, 1, None), // "aram"
    Among(&[101, 114, 97, 109], 20, 1, None), // "eram"
    Among(&[105, 114, 97, 109], 20, 1, None), // "iram"
    Among(&[97, 118, 97, 109], 20, 1, None), // "avam"
    Among(&[101, 109], -1, 1, None), // "em"
    Among(&[97, 114, 101, 109], 29, 1, None), // "arem"
    Among(&[101, 114, 101, 109], 29, 1, None), // "erem"
    Among(&[105, 114, 101, 109], 29, 1, None), // "irem"
    Among(&[97, 115, 115, 101, 109], 29, 1, None), // "assem"
    Among(&[101, 115, 115, 101, 109], 29, 1, None), // "essem"
    Among(&[105, 115, 115, 101, 109], 29, 1, None), // "issem"
    Among(&[97, 100, 111], -1, 1, None), // "ado"
    Among(&[105, 100, 111], -1, 1, None), // "ido"
    Among(&[97, 110, 100, 111], -1, 1, None), // "ando"
    Among(&[101, 110, 100, 111], -1, 1, None), // "endo"
    Among(&[105, 110, 100, 111], -1, 1, None), // "indo"
    Among(&[97, 114, 97, 126, 111], -1, 1, None), // "ara~o"
    Among(&[101, 114, 97, 126, 111], -1, 1, None), // "era~o"
    Among(&[105, 114, 97, 126, 111], -1, 1, None), // "ira~o"
    Among(&[97, 114], -1, 1, None), // "ar"
    Among(&[101, 114], -1, 1, None), // "er"
    Among(&[105, 114], -1, 1, None), // "ir"
    Among(&[97, 115], -1, 1, None), // "as"
    Among(&[97, 100, 97, 115], 47, 1, None), // "adas"
    Among(&[105, 100, 97, 115], 47, 1, None), // "idas"
    Among(&[105, 97, 115], 47, 1, None), // "ias"
    Among(&[97, 114, 105, 97, 115], 50, 1, None), // "arias"
    Among(&[101, 114, 105, 97, 115], 50, 1, None), // "erias"
    Among(&[105, 114, 105, 97, 115], 50, 1, None), // "irias"
    Among(&[97, 114, 97, 115], 47, 1, None), // "aras"
    Among(&[101, 114, 97, 115], 47, 1, None), // "eras"
    Among(&[105, 114, 97, 115], 47, 1, None), // "iras"
    Among(&[97, 118, 97, 115], 47, 1, None), // "avas"
    Among(&[101, 115], -1, 1, None), // "es"
    Among(&[97, 114, 100, 101, 115], 58, 1, None), // "ardes"
    Among(&[101, 114, 100, 101, 115], 58, 1, None), // "erdes"
    Among(&[105, 114, 100, 101, 115], 58, 1, None), // "irdes"
    Among(&[97, 114, 101, 115], 58, 1, None), // "ares"
    Among(&[101, 114, 101, 115], 58, 1, None), // "eres"
    Among(&[105, 114, 101, 115], 58, 1, None), // "ires"
    Among(&[97, 115, 115, 101, 115], 58, 1, None), // "asses"
    Among(&[101, 115, 115, 101, 115], 58, 1, None), // "esses"
    Among(&[105, 115, 115, 101, 115], 58, 1, None), // "isses"
    Among(&[97, 115, 116, 101, 115], 58, 1, None), // "astes"
    Among(&[101, 115, 116, 101, 115], 58, 1, None), // "estes"
    Among(&[105, 115, 116, 101, 115], 58, 1, None), // "istes"
    Among(&[105, 115], -1, 1, None), // "is"
    Among(&[97, 105, 115], 71, 1, None), // "ais"
    Among(&[101, 105, 115], 71, 1, None), // "eis"
    Among(&[97, 114, 101, 105, 115], 73, 1, None), // "areis"
    Among(&[101, 114, 101, 105, 115], 73, 1, None), // "ereis"
    Among(&[105, 114, 101, 105, 115], 73, 1, None), // "ireis"
    Among(&[225, 114, 101, 105, 115], 73, 1, None), // "\u{00E1}reis"
    Among(&[233, 114, 101, 105, 115], 73, 1, None), // "\u{00E9}reis"
    Among(&[237, 114, 101, 105, 115], 73, 1, None), // "\u{00ED}reis"
    Among(&[225, 115, 115, 101, 105, 115], 73, 1, None), // "\u{00E1}sseis"
    Among(&[233, 115, 115, 101, 105, 115], 73, 1, None), // "\u{00E9}sseis"
    Among(&[237, 115, 115, 101, 105, 115], 73, 1, None), // "\u{00ED}sseis"
    Among(&[225, 118, 101, 105, 115], 73, 1, None), // "\u{00E1}veis"
    Among(&[237, 101, 105, 115], 73, 1, None), // "\u{00ED}eis"
    Among(&[97, 114, 237, 101, 105, 115], 84, 1, None), // "ar\u{00ED}eis"
    Among(&[101, 114, 237, 101, 105, 115], 84, 1, None), // "er\u{00ED}eis"
    Among(&[105, 114, 237, 101, 105, 115], 84, 1, None), // "ir\u{00ED}eis"
    Among(&[97, 100, 111, 115], -1, 1, None), // "ados"
    Among(&[105, 100, 111, 115], -1, 1, None), // "idos"
    Among(&[97, 109, 111, 115], -1, 1, None), // "amos"
    Among(&[225, 114, 97, 109, 111, 115], 90, 1, None), // "\u{00E1}ramos"
    Among(&[233, 114, 97, 109, 111, 115], 90, 1, None), // "\u{00E9}ramos"
    Among(&[237, 114, 97, 109, 111, 115], 90, 1, None), // "\u{00ED}ramos"
    Among(&[225, 118, 97, 109, 111, 115], 90, 1, None), // "\u{00E1}vamos"
    Among(&[237, 97, 109, 111, 115], 90, 1, None), // "\u{00ED}amos"
    Among(&[97, 114, 237, 97, 109, 111, 115], 95, 1, None), // "ar\u{00ED}amos"
    Among(&[101, 114, 237, 97, 109, 111, 115], 95, 1, None), // "er\u{00ED}amos"
    Among(&[105, 114, 237, 97, 109, 111, 115], 95, 1, None), // "ir\u{00ED}amos"
    Among(&[101, 109, 111, 115], -1, 1, None), // "emos"
    Among(&[97, 114, 101, 109, 111, 115], 99, 1, None), // "aremos"
    Among(&[101, 114, 101, 109, 111, 115], 99, 1, None), // "eremos"
    Among(&[105, 114, 101, 109, 111, 115], 99, 1, None), // "iremos"
    Among(&[225, 115, 115, 101, 109, 111, 115], 99, 1, None), // "\u{00E1}ssemos"
    Among(&[234, 115, 115, 101, 109, 111, 115], 99, 1, None), // "\u{00EA}ssemos"
    Among(&[237, 115, 115, 101, 109, 111, 115], 99, 1, None), // "\u{00ED}ssemos"
    Among(&[105, 109, 111, 115], -1, 1, None), // "imos"
    Among(&[97, 114, 109, 111, 115], -1, 1, None), // "armos"
    Among(&[101, 114, 109, 111, 115], -1, 1, None), // "ermos"
    Among(&[105, 114, 109, 111, 115], -1, 1, None), // "irmos"
    Among(&[225, 109, 111, 115], -1, 1, None), // "\u{00E1}mos"
    Among(&[97, 114, 225, 115], -1, 1, None), // "ar\u{00E1}s"
    Among(&[101, 114, 225, 115], -1, 1, None), // "er\u{00E1}s"
    Among(&[105, 114, 225, 115], -1, 1, None), // "ir\u{00E1}s"
    Among(&[101, 117], -1, 1, None), // "eu"
    Among(&[105, 117], -1, 1, None), // "iu"
    Among(&[111, 117], -1, 1, None), // "ou"
    Among(&[97, 114, 225], -1, 1, None), // "ar\u{00E1}"
    Among(&[101, 114, 225], -1, 1, None), // "er\u{00E1}"
    Among(&[105, 114, 225], -1, 1, None), // "ir\u{00E1}"
];

static A_7: &'static [Among<Context>; 7] = &[
    Among(&[97], -1, 1, None), // "a"
    Among(&[105], -1, 1, None), // "i"
    Among(&[111], -1, 1, None), // "o"
    Among(&[111, 115], -1, 1, None), // "os"
    Among(&[225], -1, 1, None), // "\u{00E1}"
    Among(&[237], -1, 1, None), // "\u{00ED}"
    Among(&[243], -1, 1, None), // "\u{00F3}"
];

static A_8: &'static [Among<Context>; 4] = &[
    Among(&[101], -1, 1, None), // "e"
    Among(&[231], -1, 2, None), // "\u{00E7}"
    Among(&[233], -1, 1, None), // "\u{00E9}"
    Among(&[234], -1, 1, None), // "\u{00EA}"
];

static G_v: &'static [u8; 20] = &[17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 3, 19, 12, 2];

#[derive(Clone)]
struct Context {
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_0, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[97, 126]);
                }
                2 => {
                    env.slice_from(&[111, 126]);
                }
                3 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 250) {
                    break 'lab2;
                }
                'lab3: loop {
                    let v_3 = env.cursor;
                    'lab4: loop {
                        if !env.out_grouping(G_v, 97, 250) {
                            break 'lab4;
                        }
                        'golab5: loop {
                            'lab6: loop {
                                if !env.in_grouping(G_v, 97, 250) {
                                    break 'lab6;
                                }
                                break 'golab5;
                            }
                            if env.cursor >= env.limit {
                                break 'lab4;
                            }
                            env.next_char();
                        }
                        break 'lab3;
                    }
                    env.cursor = v_3;
                    if !env.in_grouping(G_v, 97, 250) {
                        break 'lab2;
                    }
                    'golab7: loop {
                        'lab8: loop {
                            if !env.out_grouping(G_v, 97, 250) {
                                break 'lab8;
                            }
                            break 'golab7;
                        }
                        if env.cursor >= env.limit {
                            break 'lab2;
                        }
                        env.next_char();
                    }
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if !env.out_grouping(G_v, 97, 250) {
                break 'lab0;
            }
            'lab9: loop {
                let v_6 = env.cursor;
                'lab10: loop {
                    if !env.out_grouping(G_v, 97, 250) {
                        break 'lab10;
                    }
                    'golab11: loop {
                        'lab12: loop {
                            if !env.in_grouping(G_v, 97, 250) {
                                break 'lab12;
                            }
                            break 'golab11;
                        }
                        if env.cursor >= env.limit {
                            break 'lab10;
                        }
                        env.next_char();
                    }
                    break 'lab9;
                }
                env.cursor = v_6;
                if !env.in_grouping(G_v, 97, 250) {
                    break 'lab0;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
                break 'lab9;
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_8 = env.cursor;
    'lab13: loop {
        'golab14: loop {
            'lab15: loop {
                if !env.in_grouping(G_v, 97, 250) {
                    break 'lab15;
                }
                break 'golab14;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab16: loop {
            'lab17: loop {
                if !env.out_grouping(G_v, 97, 250) {
                    break 'lab17;
                }
                break 'golab16;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab18: loop {
            'lab19: loop {
                if !env.in_grouping(G_v, 97, 250) {
                    break 'lab19;
                }
                break 'golab18;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab20: loop {
            'lab21: loop {
                if !env.out_grouping(G_v, 97, 250) {
                    break 'lab21;
                }
                break 'golab20;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab13;
    }
    env.cursor = v_8;
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[227]);
                }
                2 => {
                    env.slice_from(&[245]);
                }
                3 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_pV <= env.cursor
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_5, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[108, 111, 103]);
        }
        3 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[117]);
        }
        4 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_from(&[101, 110, 116, 101]);
        }
        5 => {
            if !r_R1(env, context) {
                return false;
            }
            env.slice_del();
            let v_1 = env.limit - env.cursor;
            'lab0: loop {
                env.ket = env.cursor;
                among_var = env.find_among_b(A_2, context);
                if among_var == 0 {
                    env.cursor = env.limit - v_1;
                    break 'lab0;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_1;
                    break 'lab0;
                }
                env.slice_del();
                match among_var {
                    1 => {
                        env.ket = env.cursor;
                        if !env.eq_s_b(&[97, 116]) {
                            env.cursor = env.limit - v_1;
                            break 'lab0;
                        }
                        env.bra = env.cursor;
                        if !r_R2(env, context) {
                            env.cursor = env.limit - v_1;
                            break 'lab0;
                        }
                        env.slice_del();
                    }
                    _ => ()
                }
                break 'lab0;
            }
        }
        6 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_2 = env.limit - env.cursor;
            'lab1: loop {
                env.ket = env.cursor;
                if env.find_among_b(A_3, context) == 0 {
                    env.cursor = env.limit - v_2;
                    break 'lab1;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_2;
                    break 'lab1;
                }
                env.slice_del();
                break 'lab1;
            }
        }
        7 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_3 = env.limit - env.cursor;
            'lab2: loop {
                env.ket = env.cursor;
                if env.find_among_b(A_4, context) == 0 {
                    env.cursor = env.limit - v_3;
                    break 'lab2;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_3;
                    break 'lab2;
                }
                env.slice_del();
                break 'lab2;
            }
        }
        8 => {
            if !r_R2(env, context) {
                return false;
            }
            env.slice_del();
            let v_4 = env.limit - env.cursor;
            'lab3: loop {
                env.ket = env.cursor;
                if !env.eq_s_b(&[97, 116]) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.bra = env.cursor;
                if !r_R2(env, context) {
                    env.cursor = env.limit - v_4;
                    break 'lab3;
                }
                env.slice_del();
                break 'lab3;
            }
        }
        9 => {
            if !r_RV(env, context) {
                return false;
            }
            if !env.eq_s_b(&[101]) {
                return false;
            }
            env.slice_from(&[105, 114]);
        }
        _ => ()
    }
    return true
}

fn r_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    if env.find_among_b(A_6, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.slice_del();
    env.limit_backward = v_2;
    return true
}

fn r_residual_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_7, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_RV(env, context) {
        return false;
    }
    env.slice_del();
    return true
}

fn r_residual_form(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_8, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
            env.ket = env.cursor;
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.eq_s_b(&[117]) {
                        break 'lab1;
                    }
                    env.bra = env.cursor;
                    let v_2 = env.limit - env.cursor;
                    if !env.eq_s_b(&[103]) {
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_2;
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                if !env.eq_s_b(&[105]) {
                    return false;
                }
                env.bra = env.cursor;
                let v_3 = env.limit - env.cursor;
                if !env.eq_s_b(&[99]) {
                    return false;
                }
                env.cursor = env.limit - v_3;
                break 'lab0;
            }
            if !r_RV(env, context) {
                return false;
            }
            env.slice_del();
        }
        2 => {
            env.slice_from(&[99]);
        }
        _ => ()
    }
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    let v_1 = env.cursor;
    r_prelude(env, context);
    env.cursor = v_1;
    r_mark_regions(env, context);
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_3 = env.limit - env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_4 = env.limit - env.cursor;
            'lab2: loop {
                let v_5 = env.limit - env.cursor;
                'lab3: loop {
                    let v_6 = env.limit - env.cursor;
                    'lab4: loop {
                        if !r_standard_suffix(env, context) {
                            break 'lab4;
                        }
                        break 'lab3;
                    }
                    env.cursor = env.limit - v_6;
                    if !r_verb_suffix(env, context) {
                        break 'lab2;
                    }
                    break 'lab3;
                }
                env.cursor = env.limit - v_5;
                let v_7 = env.limit - env.cursor;
                'lab5: loop {
                    env.ket = env.cursor;
                    if !env.eq_s_b(&[105]) {
                        break 'lab5;
                    }
                    env.bra = env.cursor;
                    let v_8 = env.limit - env.cursor;
                    if !env.eq_s_b(&[99]) {
                        break 'lab5;
                    }
                    env.cursor = env.limit - v_8;
                    if !r_RV(env, context) {
                        break 'lab5;
                    }
                    env.slice_del();
                    break 'lab5;
                }
                env.cursor = env.limit - v_7;
                break 'lab1;
            }
            env.cursor = env.limit - v_4;
            if !r_residual_suffix(env, context) {
                break 'lab0;
            }
            break 'lab1;
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_3;
    let v_9 = env.limit - env.cursor;
    r_residual_form(env, context);
    env.cursor = env.limit - v_9;
    env.cursor = env.limit_backward;
    let v_10 = env.cursor;
    r_postlude(env, context);
    env.cursor = v_10;
    return true
}
