//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 2] = &[
    Among(&[351], -1, 1, None), // "\u{015F}"
    Among(&[355], -1, 2, None), // "\u{0163}"
];

static A_1: &'static [Among<Context>; 3] = &[
    Among(&[], -1, 3, None), // ""
    Among(&[73], 0, 1, None), // "I"
    Among(&[85], 0, 2, None), // "U"
];

static A_2: &'static [Among<Context>; 16] = &[
    Among(&[101, 97], -1, 3, None), // "ea"
    Among(&[97, 539, 105, 97], -1, 7, None), // "a\u{021B}ia"
    Among(&[97, 117, 97], -1, 2, None), // "aua"
    Among(&[105, 117, 97], -1, 4, None), // "iua"
    Among(&[97, 539, 105, 101], -1, 7, None), // "a\u{021B}ie"
    Among(&[101, 108, 101], -1, 3, None), // "ele"
    Among(&[105, 108, 101], -1, 5, None), // "ile"
    Among(&[105, 105, 108, 101], 6, 4, None), // "iile"
    Among(&[105, 101, 105], -1, 4, None), // "iei"
    Among(&[97, 116, 101, 105], -1, 6, None), // "atei"
    Among(&[105, 105], -1, 4, None), // "ii"
    Among(&[117, 108, 117, 105], -1, 1, None), // "ului"
    Among(&[117, 108], -1, 1, None), // "ul"
    Among(&[101, 108, 111, 114], -1, 3, None), // "elor"
    Among(&[105, 108, 111, 114], -1, 4, None), // "ilor"
    Among(&[105, 105, 108, 111, 114], 14, 4, None), // "iilor"
];

static A_3: &'static [Among<Context>; 46] = &[
    Among(&[105, 99, 97, 108, 97], -1, 4, None), // "icala"
    Among(&[105, 99, 105, 118, 97], -1, 4, None), // "iciva"
    Among(&[97, 116, 105, 118, 97], -1, 5, None), // "ativa"
    Among(&[105, 116, 105, 118, 97], -1, 6, None), // "itiva"
    Among(&[105, 99, 97, 108, 101], -1, 4, None), // "icale"
    Among(&[97, 539, 105, 117, 110, 101], -1, 5, None), // "a\u{021B}iune"
    Among(&[105, 539, 105, 117, 110, 101], -1, 6, None), // "i\u{021B}iune"
    Among(&[97, 116, 111, 97, 114, 101], -1, 5, None), // "atoare"
    Among(&[105, 116, 111, 97, 114, 101], -1, 6, None), // "itoare"
    Among(&[259, 116, 111, 97, 114, 101], -1, 5, None), // "\u{0103}toare"
    Among(&[105, 99, 105, 116, 97, 116, 101], -1, 4, None), // "icitate"
    Among(&[97, 98, 105, 108, 105, 116, 97, 116, 101], -1, 1, None), // "abilitate"
    Among(&[105, 98, 105, 108, 105, 116, 97, 116, 101], -1, 2, None), // "ibilitate"
    Among(&[105, 118, 105, 116, 97, 116, 101], -1, 3, None), // "ivitate"
    Among(&[105, 99, 105, 118, 101], -1, 4, None), // "icive"
    Among(&[97, 116, 105, 118, 101], -1, 5, None), // "ative"
    Among(&[105, 116, 105, 118, 101], -1, 6, None), // "itive"
    Among(&[105, 99, 97, 108, 105], -1, 4, None), // "icali"
    Among(&[97, 116, 111, 114, 105], -1, 5, None), // "atori"
    Among(&[105, 99, 97, 116, 111, 114, 105], 18, 4, None), // "icatori"
    Among(&[105, 116, 111, 114, 105], -1, 6, None), // "itori"
    Among(&[259, 116, 111, 114, 105], -1, 5, None), // "\u{0103}tori"
    Among(&[105, 99, 105, 116, 97, 116, 105], -1, 4, None), // "icitati"
    Among(&[97, 98, 105, 108, 105, 116, 97, 116, 105], -1, 1, None), // "abilitati"
    Among(&[105, 118, 105, 116, 97, 116, 105], -1, 3, None), // "ivitati"
    Among(&[105, 99, 105, 118, 105], -1, 4, None), // "icivi"
    Among(&[97, 116, 105, 118, 105], -1, 5, None), // "ativi"
    Among(&[105, 116, 105, 118, 105], -1, 6, None), // "itivi"
    Among(&[105, 99, 105, 116, 259, 105], -1, 4, None), // "icit\u{0103}i"
    Among(&[97, 98, 105, 108, 105, 116, 259, 105], -1, 1, None), // "abilit\u{0103}i"
    Among(&[105, 118, 105, 116, 259, 105], -1, 3, None), // "ivit\u{0103}i"
    Among(&[105, 99, 105, 116, 259, 539, 105], -1, 4, None), // "icit\u{0103}\u{021B}i"
    Among(&[97, 98, 105, 108, 105, 116, 259, 539, 105], -1, 1, None), // "abilit\u{0103}\u{021B}i"
    Among(&[105, 118, 105, 116, 259, 539, 105], -1, 3, None), // "ivit\u{0103}\u{021B}i"
    Among(&[105, 99, 97, 108], -1, 4, None), // "ical"
    Among(&[97, 116, 111, 114], -1, 5, None), // "ator"
    Among(&[105, 99, 97, 116, 111, 114], 35, 4, None), // "icator"
    Among(&[105, 116, 111, 114], -1, 6, None), // "itor"
    Among(&[259, 116, 111, 114], -1, 5, None), // "\u{0103}tor"
    Among(&[105, 99, 105, 118], -1, 4, None), // "iciv"
    Among(&[97, 116, 105, 118], -1, 5, None), // "ativ"
    Among(&[105, 116, 105, 118], -1, 6, None), // "itiv"
    Among(&[105, 99, 97, 108, 259], -1, 4, None), // "ical\u{0103}"
    Among(&[105, 99, 105, 118, 259], -1, 4, None), // "iciv\u{0103}"
    Among(&[97, 116, 105, 118, 259], -1, 5, None), // "ativ\u{0103}"
    Among(&[105, 116, 105, 118, 259], -1, 6, None), // "itiv\u{0103}"
];

static A_4: &'static [Among<Context>; 62] = &[
    Among(&[105, 99, 97], -1, 1, None), // "ica"
    Among(&[97, 98, 105, 108, 97], -1, 1, None), // "abila"
    Among(&[105, 98, 105, 108, 97], -1, 1, None), // "ibila"
    Among(&[111, 97, 115, 97], -1, 1, None), // "oasa"
    Among(&[97, 116, 97], -1, 1, None), // "ata"
    Among(&[105, 116, 97], -1, 1, None), // "ita"
    Among(&[97, 110, 116, 97], -1, 1, None), // "anta"
    Among(&[105, 115, 116, 97], -1, 3, None), // "ista"
    Among(&[117, 116, 97], -1, 1, None), // "uta"
    Among(&[105, 118, 97], -1, 1, None), // "iva"
    Among(&[105, 99], -1, 1, None), // "ic"
    Among(&[105, 99, 101], -1, 1, None), // "ice"
    Among(&[97, 98, 105, 108, 101], -1, 1, None), // "abile"
    Among(&[105, 98, 105, 108, 101], -1, 1, None), // "ibile"
    Among(&[105, 115, 109, 101], -1, 3, None), // "isme"
    Among(&[105, 117, 110, 101], -1, 2, None), // "iune"
    Among(&[111, 97, 115, 101], -1, 1, None), // "oase"
    Among(&[97, 116, 101], -1, 1, None), // "ate"
    Among(&[105, 116, 97, 116, 101], 17, 1, None), // "itate"
    Among(&[105, 116, 101], -1, 1, None), // "ite"
    Among(&[97, 110, 116, 101], -1, 1, None), // "ante"
    Among(&[105, 115, 116, 101], -1, 3, None), // "iste"
    Among(&[117, 116, 101], -1, 1, None), // "ute"
    Among(&[105, 118, 101], -1, 1, None), // "ive"
    Among(&[105, 99, 105], -1, 1, None), // "ici"
    Among(&[97, 98, 105, 108, 105], -1, 1, None), // "abili"
    Among(&[105, 98, 105, 108, 105], -1, 1, None), // "ibili"
    Among(&[105, 117, 110, 105], -1, 2, None), // "iuni"
    Among(&[97, 116, 111, 114, 105], -1, 1, None), // "atori"
    Among(&[111, 115, 105], -1, 1, None), // "osi"
    Among(&[97, 116, 105], -1, 1, None), // "ati"
    Among(&[105, 116, 97, 116, 105], 30, 1, None), // "itati"
    Among(&[105, 116, 105], -1, 1, None), // "iti"
    Among(&[97, 110, 116, 105], -1, 1, None), // "anti"
    Among(&[105, 115, 116, 105], -1, 3, None), // "isti"
    Among(&[117, 116, 105], -1, 1, None), // "uti"
    Among(&[105, 537, 116, 105], -1, 3, None), // "i\u{0219}ti"
    Among(&[105, 118, 105], -1, 1, None), // "ivi"
    Among(&[105, 116, 259, 105], -1, 1, None), // "it\u{0103}i"
    Among(&[111, 537, 105], -1, 1, None), // "o\u{0219}i"
    Among(&[105, 116, 259, 539, 105], -1, 1, None), // "it\u{0103}\u{021B}i"
    Among(&[97, 98, 105, 108], -1, 1, None), // "abil"
    Among(&[105, 98, 105, 108], -1, 1, None), // "ibil"
    Among(&[105, 115, 109], -1, 3, None), // "ism"
    Among(&[97, 116, 111, 114], -1, 1, None), // "ator"
    Among(&[111, 115], -1, 1, None), // "os"
    Among(&[97, 116], -1, 1, None), // "at"
    Among(&[105, 116], -1, 1, None), // "it"
    Among(&[97, 110, 116], -1, 1, None), // "ant"
    Among(&[105, 115, 116], -1, 3, None), // "ist"
    Among(&[117, 116], -1, 1, None), // "ut"
    Among(&[105, 118], -1, 1, None), // "iv"
    Among(&[105, 99, 259], -1, 1, None), // "ic\u{0103}"
    Among(&[97, 98, 105, 108, 259], -1, 1, None), // "abil\u{0103}"
    Among(&[105, 98, 105, 108, 259], -1, 1, None), // "ibil\u{0103}"
    Among(&[111, 97, 115, 259], -1, 1, None), // "oas\u{0103}"
    Among(&[97, 116, 259], -1, 1, None), // "at\u{0103}"
    Among(&[105, 116, 259], -1, 1, None), // "it\u{0103}"
    Among(&[97, 110, 116, 259], -1, 1, None), // "ant\u{0103}"
    Among(&[105, 115, 116, 259], -1, 3, None), // "ist\u{0103}"
    Among(&[117, 116, 259], -1, 1, None), // "ut\u{0103}"
    Among(&[105, 118, 259], -1, 1, None), // "iv\u{0103}"
];

static A_5: &'static [Among<Context>; 94] = &[
    Among(&[101, 97], -1, 1, None), // "ea"
    Among(&[105, 97], -1, 1, None), // "ia"
    Among(&[101, 115, 99], -1, 1, None), // "esc"
    Among(&[259, 115, 99], -1, 1, None), // "\u{0103}sc"
    Among(&[105, 110, 100], -1, 1, None), // "ind"
    Among(&[226, 110, 100], -1, 1, None), // "\u{00E2}nd"
    Among(&[97, 114, 101], -1, 1, None), // "are"
    Among(&[101, 114, 101], -1, 1, None), // "ere"
    Among(&[105, 114, 101], -1, 1, None), // "ire"
    Among(&[226, 114, 101], -1, 1, None), // "\u{00E2}re"
    Among(&[115, 101], -1, 2, None), // "se"
    Among(&[97, 115, 101], 10, 1, None), // "ase"
    Among(&[115, 101, 115, 101], 10, 2, None), // "sese"
    Among(&[105, 115, 101], 10, 1, None), // "ise"
    Among(&[117, 115, 101], 10, 1, None), // "use"
    Among(&[226, 115, 101], 10, 1, None), // "\u{00E2}se"
    Among(&[101, 537, 116, 101], -1, 1, None), // "e\u{0219}te"
    Among(&[259, 537, 116, 101], -1, 1, None), // "\u{0103}\u{0219}te"
    Among(&[101, 122, 101], -1, 1, None), // "eze"
    Among(&[97, 105], -1, 1, None), // "ai"
    Among(&[101, 97, 105], 19, 1, None), // "eai"
    Among(&[105, 97, 105], 19, 1, None), // "iai"
    Among(&[115, 101, 105], -1, 2, None), // "sei"
    Among(&[101, 537, 116, 105], -1, 1, None), // "e\u{0219}ti"
    Among(&[259, 537, 116, 105], -1, 1, None), // "\u{0103}\u{0219}ti"
    Among(&[117, 105], -1, 1, None), // "ui"
    Among(&[101, 122, 105], -1, 1, None), // "ezi"
    Among(&[226, 105], -1, 1, None), // "\u{00E2}i"
    Among(&[97, 537, 105], -1, 1, None), // "a\u{0219}i"
    Among(&[115, 101, 537, 105], -1, 2, None), // "se\u{0219}i"
    Among(&[97, 115, 101, 537, 105], 29, 1, None), // "ase\u{0219}i"
    Among(&[115, 101, 115, 101, 537, 105], 29, 2, None), // "sese\u{0219}i"
    Among(&[105, 115, 101, 537, 105], 29, 1, None), // "ise\u{0219}i"
    Among(&[117, 115, 101, 537, 105], 29, 1, None), // "use\u{0219}i"
    Among(&[226, 115, 101, 537, 105], 29, 1, None), // "\u{00E2}se\u{0219}i"
    Among(&[105, 537, 105], -1, 1, None), // "i\u{0219}i"
    Among(&[117, 537, 105], -1, 1, None), // "u\u{0219}i"
    Among(&[226, 537, 105], -1, 1, None), // "\u{00E2}\u{0219}i"
    Among(&[97, 539, 105], -1, 2, None), // "a\u{021B}i"
    Among(&[101, 97, 539, 105], 38, 1, None), // "ea\u{021B}i"
    Among(&[105, 97, 539, 105], 38, 1, None), // "ia\u{021B}i"
    Among(&[101, 539, 105], -1, 2, None), // "e\u{021B}i"
    Among(&[105, 539, 105], -1, 2, None), // "i\u{021B}i"
    Among(&[226, 539, 105], -1, 2, None), // "\u{00E2}\u{021B}i"
    Among(&[97, 114, 259, 539, 105], -1, 1, None), // "ar\u{0103}\u{021B}i"
    Among(&[115, 101, 114, 259, 539, 105], -1, 2, None), // "ser\u{0103}\u{021B}i"
    Among(&[97, 115, 101, 114, 259, 539, 105], 45, 1, None), // "aser\u{0103}\u{021B}i"
    Among(&[115, 101, 115, 101, 114, 259, 539, 105], 45, 2, None), // "seser\u{0103}\u{021B}i"
    Among(&[105, 115, 101, 114, 259, 539, 105], 45, 1, None), // "iser\u{0103}\u{021B}i"
    Among(&[117, 115, 101, 114, 259, 539, 105], 45, 1, None), // "user\u{0103}\u{021B}i"
    Among(&[226, 115, 101, 114, 259, 539, 105], 45, 1, None), // "\u{00E2}ser\u{0103}\u{021B}i"
    Among(&[105, 114, 259, 539, 105], -1, 1, None), // "ir\u{0103}\u{021B}i"
    Among(&[117, 114, 259, 539, 105], -1, 1, None), // "ur\u{0103}\u{021B}i"
    Among(&[226, 114, 259, 539, 105], -1, 1, None), // "\u{00E2}r\u{0103}\u{021B}i"
    Among(&[97, 109], -1, 1, None), // "am"
    Among(&[101, 97, 109], 54, 1, None), // "eam"
    Among(&[105, 97, 109], 54, 1, None), // "iam"
    Among(&[101, 109], -1, 2, None), // "em"
    Among(&[97, 115, 101, 109], 57, 1, None), // "asem"
    Among(&[115, 101, 115, 101, 109], 57, 2, None), // "sesem"
    Among(&[105, 115, 101, 109], 57, 1, None), // "isem"
    Among(&[117, 115, 101, 109], 57, 1, None), // "usem"
    Among(&[226, 115, 101, 109], 57, 1, None), // "\u{00E2}sem"
    Among(&[105, 109], -1, 2, None), // "im"
    Among(&[226, 109], -1, 2, None), // "\u{00E2}m"
    Among(&[259, 109], -1, 2, None), // "\u{0103}m"
    Among(&[97, 114, 259, 109], 65, 1, None), // "ar\u{0103}m"
    Among(&[115, 101, 114, 259, 109], 65, 2, None), // "ser\u{0103}m"
    Among(&[97, 115, 101, 114, 259, 109], 67, 1, None), // "aser\u{0103}m"
    Among(&[115, 101, 115, 101, 114, 259, 109], 67, 2, None), // "seser\u{0103}m"
    Among(&[105, 115, 101, 114, 259, 109], 67, 1, None), // "iser\u{0103}m"
    Among(&[117, 115, 101, 114, 259, 109], 67, 1, None), // "user\u{0103}m"
    Among(&[226, 115, 101, 114, 259, 109], 67, 1, None), // "\u{00E2}ser\u{0103}m"
    Among(&[105, 114, 259, 109], 65, 1, None), // "ir\u{0103}m"
    Among(&[117, 114, 259, 109], 65, 1, None), // "ur\u{0103}m"
    Among(&[226, 114, 259, 109], 65, 1, None), // "\u{00E2}r\u{0103}m"
    Among(&[97, 117], -1, 1, None), // "au"
    Among(&[101, 97, 117], 76, 1, None), // "eau"
    Among(&[105, 97, 117], 76, 1, None), // "iau"
    Among(&[105, 110, 100, 117], -1, 1, None), // "indu"
    Among(&[226, 110, 100, 117], -1, 1, None), // "\u{00E2}ndu"
    Among(&[101, 122], -1, 1, None), // "ez"
    Among(&[101, 97, 115, 99, 259], -1, 1, None), // "easc\u{0103}"
    Among(&[97, 114, 259], -1, 1, None), // "ar\u{0103}"
    Among(&[115, 101, 114, 259], -1, 2, None), // "ser\u{0103}"
    Among(&[97, 115, 101, 114, 259], 84, 1, None), // "aser\u{0103}"
    Among(&[115, 101, 115, 101, 114, 259], 84, 2, None), // "seser\u{0103}"
    Among(&[105, 115, 101, 114, 259], 84, 1, None), // "iser\u{0103}"
    Among(&[117, 115, 101, 114, 259], 84, 1, None), // "user\u{0103}"
    Among(&[226, 115, 101, 114, 259], 84, 1, None), // "\u{00E2}ser\u{0103}"
    Among(&[105, 114, 259], -1, 1, None), // "ir\u{0103}"
    Among(&[117, 114, 259], -1, 1, None), // "ur\u{0103}"
    Among(&[226, 114, 259], -1, 1, None), // "\u{00E2}r\u{0103}"
    Among(&[101, 97, 122, 259], -1, 1, None), // "eaz\u{0103}"
];

static A_6: &'static [Among<Context>; 5] = &[
    Among(&[97], -1, 1, None), // "a"
    Among(&[101], -1, 1, None), // "e"
    Among(&[105, 101], 1, 1, None), // "ie"
    Among(&[105], -1, 1, None), // "i"
    Among(&[259], -1, 1, None), // "\u{0103}"
];

static G_v: &'static [u8; 21] = &[17, 65, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2, 32, 0, 0, 4];

#[derive(Clone)]
struct Context {
    b_standard_suffix_removed: bool,
    i_p2: i32,
    i_p1: i32,
    i_pV: i32,
}

fn r_norm(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.cursor;
    'lab0: loop {
        'replab1: loop{
            let v_2 = env.cursor;
            'lab2: for _ in 0..1 {
                'golab3: loop {
                    let v_3 = env.cursor;
                    'lab4: loop {
                        env.bra = env.cursor;
                        among_var = env.find_among(A_0, context);
                        if among_var == 0 {
                            break 'lab4;
                        }
                        env.ket = env.cursor;
                        match among_var {
                            1 => {
                                env.slice_from(&[537]);
                            }
                            2 => {
                                env.slice_from(&[539]);
                            }
                            _ => ()
                        }
                        env.cursor = v_3;
                        break 'golab3;
                    }
                    env.cursor = v_3;
                    if env.cursor >= env.limit {
                        break 'lab2;
                    }
                    env.next_char();
                }
                continue 'replab1;
            }
            env.cursor = v_2;
            break 'replab1;
        }
        break 'lab0;
    }
    env.cursor = v_1;
    return true
}

fn r_prelude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            'golab2: loop {
                let v_2 = env.cursor;
                'lab3: loop {
                    if !env.in_grouping(G_v, 97, 259) {
                        break 'lab3;
                    }
                    env.bra = env.cursor;
                    'lab4: loop {
                        let v_3 = env.cursor;
                        'lab5: loop {
                            if !env.eq_s(&[117]) {
                                break 'lab5;
                            }
                            env.ket = env.cursor;
                            if !env.in_grouping(G_v, 97, 259) {
                                break 'lab5;
                            }
                            env.slice_from(&[85]);
                            break 'lab4;
                        }
                        env.cursor = v_3;
                        if !env.eq_s(&[105]) {
                            break 'lab3;
                        }
                        env.ket = env.cursor;
                        if !env.in_grouping(G_v, 97, 259) {
                            break 'lab3;
                        }
                        env.slice_from(&[73]);
                        break 'lab4;
                    }
                    env.cursor = v_2;
                    break 'golab2;
                }
                env.cursor = v_2;
                if env.cursor >= env.limit {
                    break 'lab1;
                }
                env.next_char();
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_pV = env.limit;
    context.i_p1 = env.limit;
    context.i_p2 = env.limit;
    let v_1 = env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_2 = env.cursor;
            'lab2: loop {
                if !env.in_grouping(G_v, 97, 259) {
                    break 'lab2;
                }
                'lab3: loop {
                    let v_3 = env.cursor;
                    'lab4: loop {
                        if !env.out_grouping(G_v, 97, 259) {
                            break 'lab4;
                        }
                        'golab5: loop {
                            'lab6: loop {
                                if !env.in_grouping(G_v, 97, 259) {
                                    break 'lab6;
                                }
                                break 'golab5;
                            }
                            if env.cursor >= env.limit {
                                break 'lab4;
                            }
                            env.next_char();
                        }
                        break 'lab3;
                    }
                    env.cursor = v_3;
                    if !env.in_grouping(G_v, 97, 259) {
                        break 'lab2;
                    }
                    'golab7: loop {
                        'lab8: loop {
                            if !env.out_grouping(G_v, 97, 259) {
                                break 'lab8;
                            }
                            break 'golab7;
                        }
                        if env.cursor >= env.limit {
                            break 'lab2;
                        }
                        env.next_char();
                    }
                    break 'lab3;
                }
                break 'lab1;
            }
            env.cursor = v_2;
            if !env.out_grouping(G_v, 97, 259) {
                break 'lab0;
            }
            'lab9: loop {
                let v_6 = env.cursor;
                'lab10: loop {
                    if !env.out_grouping(G_v, 97, 259) {
                        break 'lab10;
                    }
                    'golab11: loop {
                        'lab12: loop {
                            if !env.in_grouping(G_v, 97, 259) {
                                break 'lab12;
                            }
                            break 'golab11;
                        }
                        if env.cursor >= env.limit {
                            break 'lab10;
                        }
                        env.next_char();
                    }
                    break 'lab9;
                }
                env.cursor = v_6;
                if !env.in_grouping(G_v, 97, 259) {
                    break 'lab0;
                }
                if env.cursor >= env.limit {
                    break 'lab0;
                }
                env.next_char();
                break 'lab9;
            }
            break 'lab1;
        }
        context.i_pV = env.cursor;
        break 'lab0;
    }
    env.cursor = v_1;
    let v_8 = env.cursor;
    'lab13: loop {
        'golab14: loop {
            'lab15: loop {
                if !env.in_grouping(G_v, 97, 259) {
                    break 'lab15;
                }
                break 'golab14;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab16: loop {
            'lab17: loop {
                if !env.out_grouping(G_v, 97, 259) {
                    break 'lab17;
                }
                break 'golab16;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p1 = env.cursor;
        'golab18: loop {
            'lab19: loop {
                if !env.in_grouping(G_v, 97, 259) {
                    break 'lab19;
                }
                break 'golab18;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        'golab20: loop {
            'lab21: loop {
                if !env.out_grouping(G_v, 97, 259) {
                    break 'lab21;
                }
                break 'golab20;
            }
            if env.cursor >= env.limit {
                break 'lab13;
            }
            env.next_char();
        }
        context.i_p2 = env.cursor;
        break 'lab13;
    }
    env.cursor = v_8;
    return true
}

fn r_postlude(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            env.bra = env.cursor;
            among_var = env.find_among(A_1, context);
            env.ket = env.cursor;
            match among_var {
                1 => {
                    env.slice_from(&[105]);
                }
                2 => {
                    env.slice_from(&[117]);
                }
                3 => {
                    if env.cursor >= env.limit {
                        break 'lab1;
                    }
                    env.next_char();
                }
                _ => ()
            }
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_RV(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_pV <= env.cursor
}

fn r_R1(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p1 <= env.cursor
}

fn r_R2(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return context.i_p2 <= env.cursor
}

fn r_step_0(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R1(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            env.slice_from(&[97]);
        }
        3 => {
            env.slice_from(&[101]);
        }
        4 => {
            env.slice_from(&[105]);
        }
        5 => {
            let v_1 = env.limit - env.cursor;
            'lab0: loop {
                if !env.eq_s_b(&[97, 98]) {
                    break 'lab0;
                }
                return false;
            }
            env.cursor = env.limit - v_1;
            env.slice_from(&[105]);
        }
        6 => {
            env.slice_from(&[97, 116]);
        }
        7 => {
            env.slice_from(&[97, 539, 105]);
        }
        _ => ()
    }
    return true
}

fn r_combo_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    let v_1 = env.limit - env.cursor;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_3, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R1(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_from(&[97, 98, 105, 108]);
        }
        2 => {
            env.slice_from(&[105, 98, 105, 108]);
        }
        3 => {
            env.slice_from(&[105, 118]);
        }
        4 => {
            env.slice_from(&[105, 99]);
        }
        5 => {
            env.slice_from(&[97, 116]);
        }
        6 => {
            env.slice_from(&[105, 116]);
        }
        _ => ()
    }
    context.b_standard_suffix_removed = true;
    env.cursor = env.limit - v_1;
    return true
}

fn r_standard_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    context.b_standard_suffix_removed = false;
    'replab0: loop{
        let v_1 = env.limit - env.cursor;
        'lab1: for _ in 0..1 {
            if !r_combo_suffix(env, context) {
                break 'lab1;
            }
            continue 'replab0;
        }
        env.cursor = env.limit - v_1;
        break 'replab0;
    }
    env.ket = env.cursor;
    among_var = env.find_among_b(A_4, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_R2(env, context) {
        return false;
    }
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            if !env.eq_s_b(&[539]) {
                return false;
            }
            env.bra = env.cursor;
            env.slice_from(&[116]);
        }
        3 => {
            env.slice_from(&[105, 115, 116]);
        }
        _ => ()
    }
    context.b_standard_suffix_removed = true;
    return true
}

fn r_verb_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_pV {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_pV;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_5, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            'lab0: loop {
                let v_3 = env.limit - env.cursor;
                'lab1: loop {
                    if !env.out_grouping_b(G_v, 97, 259) {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_3;
                if !env.eq_s_b(&[117]) {
                    env.limit_backward = v_2;
                    return false;
                }
                break 'lab0;
            }
            env.slice_del();
        }
        2 => {
            env.slice_del();
        }
        _ => ()
    }
    env.limit_backward = v_2;
    return true
}

fn r_vowel_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.ket = env.cursor;
    if env.find_among_b(A_6, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    if !r_RV(env, context) {
        return false;
    }
    env.slice_del();
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        b_standard_suffix_removed: false,
        i_p2: 0,
        i_p1: 0,
        i_pV: 0,
    };
    r_norm(env, context);
    let v_2 = env.cursor;
    r_prelude(env, context);
    env.cursor = v_2;
    r_mark_regions(env, context);
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_4 = env.limit - env.cursor;
    r_step_0(env, context);
    env.cursor = env.limit - v_4;
    let v_5 = env.limit - env.cursor;
    r_standard_suffix(env, context);
    env.cursor = env.limit - v_5;
    let v_6 = env.limit - env.cursor;
    'lab0: loop {
        'lab1: loop {
            let v_7 = env.limit - env.cursor;
            'lab2: loop {
                if !context.b_standard_suffix_removed {
                    break 'lab2;
                }
                break 'lab1;
            }
            env.cursor = env.limit - v_7;
            if !r_verb_suffix(env, context) {
                break 'lab0;
            }
            break 'lab1;
        }
        break 'lab0;
    }
    env.cursor = env.limit - v_6;
    let v_8 = env.limit - env.cursor;
    r_vowel_suffix(env, context);
    env.cursor = env.limit - v_8;
    env.cursor = env.limit_backward;
    let v_9 = env.cursor;
    r_postlude(env, context);
    env.cursor = v_9;
    return true
}
