//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 37] = &[
    Among(&[97], -1, 1, None), // "a"
    Among(&[97, 114, 110, 97], 0, 1, None), // "arna"
    Among(&[101, 114, 110, 97], 0, 1, None), // "erna"
    Among(&[104, 101, 116, 101, 114, 110, 97], 2, 1, None), // "heterna"
    Among(&[111, 114, 110, 97], 0, 1, None), // "orna"
    Among(&[97, 100], -1, 1, None), // "ad"
    Among(&[101], -1, 1, None), // "e"
    Among(&[97, 100, 101], 6, 1, None), // "ade"
    Among(&[97, 110, 100, 101], 6, 1, None), // "ande"
    Among(&[97, 114, 110, 101], 6, 1, None), // "arne"
    Among(&[97, 114, 101], 6, 1, None), // "are"
    Among(&[97, 115, 116, 101], 6, 1, None), // "aste"
    Among(&[101, 110], -1, 1, None), // "en"
    Among(&[97, 110, 100, 101, 110], 12, 1, None), // "anden"
    Among(&[97, 114, 101, 110], 12, 1, None), // "aren"
    Among(&[104, 101, 116, 101, 110], 12, 1, None), // "heten"
    Among(&[101, 114, 110], -1, 1, None), // "ern"
    Among(&[97, 114], -1, 1, None), // "ar"
    Among(&[101, 114], -1, 1, None), // "er"
    Among(&[104, 101, 116, 101, 114], 18, 1, None), // "heter"
    Among(&[111, 114], -1, 1, None), // "or"
    Among(&[115], -1, 2, None), // "s"
    Among(&[97, 115], 21, 1, None), // "as"
    Among(&[97, 114, 110, 97, 115], 22, 1, None), // "arnas"
    Among(&[101, 114, 110, 97, 115], 22, 1, None), // "ernas"
    Among(&[111, 114, 110, 97, 115], 22, 1, None), // "ornas"
    Among(&[101, 115], 21, 1, None), // "es"
    Among(&[97, 100, 101, 115], 26, 1, None), // "ades"
    Among(&[97, 110, 100, 101, 115], 26, 1, None), // "andes"
    Among(&[101, 110, 115], 21, 1, None), // "ens"
    Among(&[97, 114, 101, 110, 115], 29, 1, None), // "arens"
    Among(&[104, 101, 116, 101, 110, 115], 29, 1, None), // "hetens"
    Among(&[101, 114, 110, 115], 21, 1, None), // "erns"
    Among(&[97, 116], -1, 1, None), // "at"
    Among(&[97, 110, 100, 101, 116], -1, 1, None), // "andet"
    Among(&[104, 101, 116], -1, 1, None), // "het"
    Among(&[97, 115, 116], -1, 1, None), // "ast"
];

static A_1: &'static [Among<Context>; 7] = &[
    Among(&[100, 100], -1, -1, None), // "dd"
    Among(&[103, 100], -1, -1, None), // "gd"
    Among(&[110, 110], -1, -1, None), // "nn"
    Among(&[100, 116], -1, -1, None), // "dt"
    Among(&[103, 116], -1, -1, None), // "gt"
    Among(&[107, 116], -1, -1, None), // "kt"
    Among(&[116, 116], -1, -1, None), // "tt"
];

static A_2: &'static [Among<Context>; 5] = &[
    Among(&[105, 103], -1, 1, None), // "ig"
    Among(&[108, 105, 103], 0, 1, None), // "lig"
    Among(&[101, 108, 115], -1, 1, None), // "els"
    Among(&[102, 117, 108, 108, 116], -1, 3, None), // "fullt"
    Among(&[246, 115, 116], -1, 2, None), // "\u{00F6}st"
];

static G_v: &'static [u8; 19] = &[17, 65, 16, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 24, 0, 32];

static G_s_ending: &'static [u8; 3] = &[119, 127, 149];

static G_ost_ending: &'static [u8; 2] = &[173, 58];

#[derive(Clone)]
struct Context {
    i_x: i32,
    i_p1: i32,
}

fn r_mark_regions(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.i_p1 = env.limit;
    let v_1 = env.cursor;
    if !env.hop(3) {
        return false;
    }
    context.i_x = env.cursor;
    env.cursor = v_1;
    'golab0: loop {
        let v_2 = env.cursor;
        'lab1: loop {
            if !env.in_grouping(G_v, 97, 246) {
                break 'lab1;
            }
            env.cursor = v_2;
            break 'golab0;
        }
        env.cursor = v_2;
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    'golab2: loop {
        'lab3: loop {
            if !env.out_grouping(G_v, 97, 246) {
                break 'lab3;
            }
            break 'golab2;
        }
        if env.cursor >= env.limit {
            return false;
        }
        env.next_char();
    }
    context.i_p1 = env.cursor;
    'lab4: loop {
        if context.i_p1 >= context.i_x{
            break 'lab4;
        }
        context.i_p1 = context.i_x;
        break 'lab4;
    }
    return true
}

fn r_main_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_0, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            if !env.in_grouping_b(G_s_ending, 98, 121) {
                return false;
            }
            env.slice_del();
        }
        _ => ()
    }
    return true
}

fn r_consonant_pair(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    let v_3 = env.limit - env.cursor;
    if env.find_among_b(A_1, context) == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.cursor = env.limit - v_3;
    env.ket = env.cursor;
    if env.cursor <= env.limit_backward {
        env.limit_backward = v_2;
        return false;
    }
    env.previous_char();
    env.bra = env.cursor;
    env.slice_del();
    env.limit_backward = v_2;
    return true
}

fn r_other_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.cursor < context.i_p1 {
        return false;
    }
    let v_2 = env.limit_backward;
    env.limit_backward = context.i_p1;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_2, context);
    if among_var == 0 {
        env.limit_backward = v_2;
        return false;
    }
    env.bra = env.cursor;
    env.limit_backward = v_2;
    match among_var {
        1 => {
            env.slice_del();
        }
        2 => {
            if !env.in_grouping_b(G_ost_ending, 105, 118) {
                return false;
            }
            env.slice_from(&[246, 115]);
        }
        3 => {
            env.slice_from(&[102, 117, 108, 108]);
        }
        _ => ()
    }
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        i_x: 0,
        i_p1: 0,
    };
    let v_1 = env.cursor;
    r_mark_regions(env, context);
    env.cursor = v_1;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_2 = env.limit - env.cursor;
    r_main_suffix(env, context);
    env.cursor = env.limit - v_2;
    let v_3 = env.limit - env.cursor;
    r_consonant_pair(env, context);
    env.cursor = env.limit - v_3;
    let v_4 = env.limit - env.cursor;
    r_other_suffix(env, context);
    env.cursor = env.limit - v_4;
    env.cursor = env.limit_backward;
    return true
}
