//! Generated by Snowball 2.2.0 - https://snowballstem.org/

#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(unused_mut)]
#![allow(unused_parens)]
#![allow(unused_variables)]
use super::super::program::SnowballEnv;
use super::super::program::Among;

static A_0: &'static [Among<Context>; 4] = &[
    Among(&[2997, 3009], -1, 3, None), // "\u{0BB5}\u{0BC1}"
    Among(&[2997, 3010], -1, 4, None), // "\u{0BB5}\u{0BC2}"
    Among(&[2997, 3018], -1, 2, None), // "\u{0BB5}\u{0BCA}"
    Among(&[2997, 3019], -1, 1, None), // "\u{0BB5}\u{0BCB}"
];

static A_1: &'static [Among<Context>; 10] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2969], -1, -1, None), // "\u{0B99}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2974], -1, -1, None), // "\u{0B9E}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2984], -1, -1, None), // "\u{0BA8}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2990], -1, -1, None), // "\u{0BAE}"
    Among(&[2991], -1, -1, None), // "\u{0BAF}"
    Among(&[2997], -1, -1, None), // "\u{0BB5}"
];

static A_2: &'static [Among<Context>; 3] = &[
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_3: &'static [Among<Context>; 8] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_4: &'static [Among<Context>; 3] = &[
    Among(&[], -1, 2, None), // ""
    Among(&[3016], 0, 1, None), // "\u{0BC8}"
    Among(&[3021], 0, 1, None), // "\u{0BCD}"
];

static A_5: &'static [Among<Context>; 17] = &[
    Among(&[2984, 3021, 2980], -1, 1, None), // "\u{0BA8}\u{0BCD}\u{0BA4}"
    Among(&[2991], -1, 1, None), // "\u{0BAF}"
    Among(&[2997], -1, 1, None), // "\u{0BB5}"
    Among(&[2985, 3009], -1, 8, None), // "\u{0BA9}\u{0BC1}"
    Among(&[3009, 2965, 3021], -1, 7, None), // "\u{0BC1}\u{0B95}\u{0BCD}"
    Among(&[3009, 2965, 3021, 2965, 3021], -1, 7, None), // "\u{0BC1}\u{0B95}\u{0BCD}\u{0B95}\u{0BCD}"
    Among(&[2975, 3021, 2965, 3021], -1, 3, None), // "\u{0B9F}\u{0BCD}\u{0B95}\u{0BCD}"
    Among(&[2993, 3021, 2965, 3021], -1, 4, None), // "\u{0BB1}\u{0BCD}\u{0B95}\u{0BCD}"
    Among(&[2969, 3021], -1, 9, None), // "\u{0B99}\u{0BCD}"
    Among(&[2975, 3021, 2975, 3021], -1, 5, None), // "\u{0B9F}\u{0BCD}\u{0B9F}\u{0BCD}"
    Among(&[2980, 3021, 2980, 3021], -1, 6, None), // "\u{0BA4}\u{0BCD}\u{0BA4}\u{0BCD}"
    Among(&[2984, 3021, 2980, 3021], -1, 1, None), // "\u{0BA8}\u{0BCD}\u{0BA4}\u{0BCD}"
    Among(&[2984, 3021], -1, 1, None), // "\u{0BA8}\u{0BCD}"
    Among(&[2975, 3021, 2986, 3021], -1, 3, None), // "\u{0B9F}\u{0BCD}\u{0BAA}\u{0BCD}"
    Among(&[2991, 3021], -1, 2, None), // "\u{0BAF}\u{0BCD}"
    Among(&[2985, 3021, 2993, 3021], -1, 4, None), // "\u{0BA9}\u{0BCD}\u{0BB1}\u{0BCD}"
    Among(&[2997, 3021], -1, 1, None), // "\u{0BB5}\u{0BCD}"
];

static A_6: &'static [Among<Context>; 6] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2975], -1, -1, None), // "\u{0B9F}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2993], -1, -1, None), // "\u{0BB1}"
];

static A_7: &'static [Among<Context>; 6] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2975], -1, -1, None), // "\u{0B9F}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2993], -1, -1, None), // "\u{0BB1}"
];

static A_8: &'static [Among<Context>; 11] = &[
    Among(&[2974], -1, -1, None), // "\u{0B9E}"
    Among(&[2979], -1, -1, None), // "\u{0BA3}"
    Among(&[2984], -1, -1, None), // "\u{0BA8}"
    Among(&[2985], -1, -1, None), // "\u{0BA9}"
    Among(&[2990], -1, -1, None), // "\u{0BAE}"
    Among(&[2991], -1, -1, None), // "\u{0BAF}"
    Among(&[2992], -1, -1, None), // "\u{0BB0}"
    Among(&[2994], -1, -1, None), // "\u{0BB2}"
    Among(&[2995], -1, -1, None), // "\u{0BB3}"
    Among(&[2996], -1, -1, None), // "\u{0BB4}"
    Among(&[2997], -1, -1, None), // "\u{0BB5}"
];

static A_9: &'static [Among<Context>; 9] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
    Among(&[3021], -1, -1, None), // "\u{0BCD}"
];

static A_10: &'static [Among<Context>; 3] = &[
    Among(&[2949], -1, -1, None), // "\u{0B85}"
    Among(&[2951], -1, -1, None), // "\u{0B87}"
    Among(&[2953], -1, -1, None), // "\u{0B89}"
];

static A_11: &'static [Among<Context>; 10] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2969], -1, -1, None), // "\u{0B99}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2974], -1, -1, None), // "\u{0B9E}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2984], -1, -1, None), // "\u{0BA8}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2990], -1, -1, None), // "\u{0BAE}"
    Among(&[2991], -1, -1, None), // "\u{0BAF}"
    Among(&[2997], -1, -1, None), // "\u{0BB5}"
];

static A_12: &'static [Among<Context>; 6] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2975], -1, -1, None), // "\u{0B9F}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2993], -1, -1, None), // "\u{0BB1}"
];

static A_13: &'static [Among<Context>; 4] = &[
    Among(&[2965, 2995, 3021], -1, 4, None), // "\u{0B95}\u{0BB3}\u{0BCD}"
    Among(&[3009, 2969, 3021, 2965, 2995, 3021], 0, 1, None), // "\u{0BC1}\u{0B99}\u{0BCD}\u{0B95}\u{0BB3}\u{0BCD}"
    Among(&[2975, 3021, 2965, 2995, 3021], 0, 3, None), // "\u{0B9F}\u{0BCD}\u{0B95}\u{0BB3}\u{0BCD}"
    Among(&[2993, 3021, 2965, 2995, 3021], 0, 2, None), // "\u{0BB1}\u{0BCD}\u{0B95}\u{0BB3}\u{0BCD}"
];

static A_14: &'static [Among<Context>; 3] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3019], -1, -1, None), // "\u{0BCB}"
];

static A_15: &'static [Among<Context>; 2] = &[
    Among(&[2986, 3007], -1, -1, None), // "\u{0BAA}\u{0BBF}"
    Among(&[2997, 3007], -1, -1, None), // "\u{0BB5}\u{0BBF}"
];

static A_16: &'static [Among<Context>; 8] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_17: &'static [Among<Context>; 26] = &[
    Among(&[2986, 2975, 3021, 2975], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BCD}\u{0B9F}"
    Among(&[2986, 2975, 3021, 2975, 2979], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BCD}\u{0B9F}\u{0BA3}"
    Among(&[2980, 3006, 2985], -1, 3, None), // "\u{0BA4}\u{0BBE}\u{0BA9}"
    Among(&[2986, 2975, 3007, 2980, 3006, 2985], 2, 3, None), // "\u{0BAA}\u{0B9F}\u{0BBF}\u{0BA4}\u{0BBE}\u{0BA9}"
    Among(&[3014, 2985], -1, 1, None), // "\u{0BC6}\u{0BA9}"
    Among(&[3006, 2965, 3007, 2991], -1, 1, None), // "\u{0BBE}\u{0B95}\u{0BBF}\u{0BAF}"
    Among(&[2965, 3009, 2992, 3007, 2991], -1, 3, None), // "\u{0B95}\u{0BC1}\u{0BB0}\u{0BBF}\u{0BAF}"
    Among(&[3009, 2975, 3016, 2991], -1, 1, None), // "\u{0BC1}\u{0B9F}\u{0BC8}\u{0BAF}"
    Among(&[2994, 3021, 2994], -1, 2, None), // "\u{0BB2}\u{0BCD}\u{0BB2}"
    Among(&[3009, 2995, 3021, 2995], -1, 1, None), // "\u{0BC1}\u{0BB3}\u{0BCD}\u{0BB3}"
    Among(&[3006, 2965, 3007], -1, 1, None), // "\u{0BBE}\u{0B95}\u{0BBF}"
    Among(&[2986, 2975, 3007], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BBF}"
    Among(&[3007, 2985, 3021, 2993, 3007], -1, 1, None), // "\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}\u{0BBF}"
    Among(&[2986, 2993, 3021, 2993, 3007], -1, 3, None), // "\u{0BAA}\u{0BB1}\u{0BCD}\u{0BB1}\u{0BBF}"
    Among(&[2986, 2975, 3009], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BC1}"
    Among(&[2997, 3007, 2975, 3009], -1, 3, None), // "\u{0BB5}\u{0BBF}\u{0B9F}\u{0BC1}"
    Among(&[2986, 2975, 3021, 2975, 3009], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BCD}\u{0B9F}\u{0BC1}"
    Among(&[2997, 3007, 2975, 3021, 2975, 3009], -1, 3, None), // "\u{0BB5}\u{0BBF}\u{0B9F}\u{0BCD}\u{0B9F}\u{0BC1}"
    Among(&[2986, 2975, 3021, 2975, 2980, 3009], -1, 3, None), // "\u{0BAA}\u{0B9F}\u{0BCD}\u{0B9F}\u{0BA4}\u{0BC1}"
    Among(&[3014, 2985, 3021, 2993, 3009], -1, 1, None), // "\u{0BC6}\u{0BA9}\u{0BCD}\u{0BB1}\u{0BC1}"
    Among(&[3009, 2975, 3016], -1, 1, None), // "\u{0BC1}\u{0B9F}\u{0BC8}"
    Among(&[3007, 2994, 3021, 2994, 3016], -1, 1, None), // "\u{0BBF}\u{0BB2}\u{0BCD}\u{0BB2}\u{0BC8}"
    Among(&[3009, 2975, 2985, 3021], -1, 1, None), // "\u{0BC1}\u{0B9F}\u{0BA9}\u{0BCD}"
    Among(&[3007, 2975, 2990, 3021], -1, 1, None), // "\u{0BBF}\u{0B9F}\u{0BAE}\u{0BCD}"
    Among(&[3014, 2994, 3021, 2994, 3006, 2990, 3021], -1, 3, None), // "\u{0BC6}\u{0BB2}\u{0BCD}\u{0BB2}\u{0BBE}\u{0BAE}\u{0BCD}"
    Among(&[3014, 2985, 3009, 2990, 3021], -1, 1, None), // "\u{0BC6}\u{0BA9}\u{0BC1}\u{0BAE}\u{0BCD}"
];

static A_18: &'static [Among<Context>; 8] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_19: &'static [Among<Context>; 8] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_20: &'static [Among<Context>; 22] = &[
    Among(&[2997, 3007, 2975], -1, 2, None), // "\u{0BB5}\u{0BBF}\u{0B9F}"
    Among(&[3008], -1, 7, None), // "\u{0BC0}"
    Among(&[3018, 2975, 3009], -1, 2, None), // "\u{0BCA}\u{0B9F}\u{0BC1}"
    Among(&[3019, 2975, 3009], -1, 2, None), // "\u{0BCB}\u{0B9F}\u{0BC1}"
    Among(&[2980, 3009], -1, 6, None), // "\u{0BA4}\u{0BC1}"
    Among(&[3007, 2992, 3009, 2984, 3021, 2980, 3009], 4, 2, None), // "\u{0BBF}\u{0BB0}\u{0BC1}\u{0BA8}\u{0BCD}\u{0BA4}\u{0BC1}"
    Among(&[3007, 2985, 3021, 2993, 3009], -1, 2, None), // "\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}\u{0BC1}"
    Among(&[3009, 2975, 3016], -1, 2, None), // "\u{0BC1}\u{0B9F}\u{0BC8}"
    Among(&[2985, 3016], -1, 1, None), // "\u{0BA9}\u{0BC8}"
    Among(&[2965, 2979, 3021], -1, 1, None), // "\u{0B95}\u{0BA3}\u{0BCD}"
    Among(&[3007, 2985, 3021], -1, 3, None), // "\u{0BBF}\u{0BA9}\u{0BCD}"
    Among(&[2990, 3009, 2985, 3021], -1, 1, None), // "\u{0BAE}\u{0BC1}\u{0BA9}\u{0BCD}"
    Among(&[3007, 2975, 2990, 3021], -1, 4, None), // "\u{0BBF}\u{0B9F}\u{0BAE}\u{0BCD}"
    Among(&[3007, 2993, 3021], -1, 2, None), // "\u{0BBF}\u{0BB1}\u{0BCD}"
    Among(&[2990, 3015, 2993, 3021], -1, 1, None), // "\u{0BAE}\u{0BC7}\u{0BB1}\u{0BCD}"
    Among(&[2994, 3021], -1, 5, None), // "\u{0BB2}\u{0BCD}"
    Among(&[3006, 2990, 2994, 3021], 15, 2, None), // "\u{0BBE}\u{0BAE}\u{0BB2}\u{0BCD}"
    Among(&[3006, 2994, 3021], 15, 2, None), // "\u{0BBE}\u{0BB2}\u{0BCD}"
    Among(&[3007, 2994, 3021], 15, 2, None), // "\u{0BBF}\u{0BB2}\u{0BCD}"
    Among(&[2990, 3015, 2994, 3021], 15, 1, None), // "\u{0BAE}\u{0BC7}\u{0BB2}\u{0BCD}"
    Among(&[3009, 2995, 3021], -1, 2, None), // "\u{0BC1}\u{0BB3}\u{0BCD}"
    Among(&[2965, 3008, 2996, 3021], -1, 1, None), // "\u{0B95}\u{0BC0}\u{0BB4}\u{0BCD}"
];

static A_21: &'static [Among<Context>; 6] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2975], -1, -1, None), // "\u{0B9F}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2993], -1, -1, None), // "\u{0BB1}"
];

static A_22: &'static [Among<Context>; 6] = &[
    Among(&[2965], -1, -1, None), // "\u{0B95}"
    Among(&[2970], -1, -1, None), // "\u{0B9A}"
    Among(&[2975], -1, -1, None), // "\u{0B9F}"
    Among(&[2980], -1, -1, None), // "\u{0BA4}"
    Among(&[2986], -1, -1, None), // "\u{0BAA}"
    Among(&[2993], -1, -1, None), // "\u{0BB1}"
];

static A_23: &'static [Among<Context>; 12] = &[
    Among(&[2949], -1, -1, None), // "\u{0B85}"
    Among(&[2950], -1, -1, None), // "\u{0B86}"
    Among(&[2951], -1, -1, None), // "\u{0B87}"
    Among(&[2952], -1, -1, None), // "\u{0B88}"
    Among(&[2953], -1, -1, None), // "\u{0B89}"
    Among(&[2954], -1, -1, None), // "\u{0B8A}"
    Among(&[2958], -1, -1, None), // "\u{0B8E}"
    Among(&[2959], -1, -1, None), // "\u{0B8F}"
    Among(&[2960], -1, -1, None), // "\u{0B90}"
    Among(&[2962], -1, -1, None), // "\u{0B92}"
    Among(&[2963], -1, -1, None), // "\u{0B93}"
    Among(&[2964], -1, -1, None), // "\u{0B94}"
];

static A_24: &'static [Among<Context>; 8] = &[
    Among(&[3006], -1, -1, None), // "\u{0BBE}"
    Among(&[3007], -1, -1, None), // "\u{0BBF}"
    Among(&[3008], -1, -1, None), // "\u{0BC0}"
    Among(&[3009], -1, -1, None), // "\u{0BC1}"
    Among(&[3010], -1, -1, None), // "\u{0BC2}"
    Among(&[3014], -1, -1, None), // "\u{0BC6}"
    Among(&[3015], -1, -1, None), // "\u{0BC7}"
    Among(&[3016], -1, -1, None), // "\u{0BC8}"
];

static A_25: &'static [Among<Context>; 46] = &[
    Among(&[2965], -1, 1, None), // "\u{0B95}"
    Among(&[2980], -1, 1, None), // "\u{0BA4}"
    Among(&[2985], -1, 1, None), // "\u{0BA9}"
    Among(&[2986], -1, 1, None), // "\u{0BAA}"
    Among(&[2991], -1, 1, None), // "\u{0BAF}"
    Among(&[3006], -1, 5, None), // "\u{0BBE}"
    Among(&[2965, 3009], -1, 6, None), // "\u{0B95}\u{0BC1}"
    Among(&[2986, 2975, 3009], -1, 1, None), // "\u{0BAA}\u{0B9F}\u{0BC1}"
    Among(&[2980, 3009], -1, 3, None), // "\u{0BA4}\u{0BC1}"
    Among(&[3007, 2993, 3021, 2993, 3009], -1, 1, None), // "\u{0BBF}\u{0BB1}\u{0BCD}\u{0BB1}\u{0BC1}"
    Among(&[2985, 3016], -1, 1, None), // "\u{0BA9}\u{0BC8}"
    Among(&[2997, 3016], -1, 1, None), // "\u{0BB5}\u{0BC8}"
    Among(&[2985, 2985, 3021], -1, 1, None), // "\u{0BA9}\u{0BA9}\u{0BCD}"
    Among(&[2986, 2985, 3021], -1, 1, None), // "\u{0BAA}\u{0BA9}\u{0BCD}"
    Among(&[2997, 2985, 3021], -1, 2, None), // "\u{0BB5}\u{0BA9}\u{0BCD}"
    Among(&[3006, 2985, 3021], -1, 4, None), // "\u{0BBE}\u{0BA9}\u{0BCD}"
    Among(&[2985, 3006, 2985, 3021], 15, 1, None), // "\u{0BA9}\u{0BBE}\u{0BA9}\u{0BCD}"
    Among(&[2990, 3007, 2985, 3021], -1, 1, None), // "\u{0BAE}\u{0BBF}\u{0BA9}\u{0BCD}"
    Among(&[2985, 3014, 2985, 3021], -1, 1, None), // "\u{0BA9}\u{0BC6}\u{0BA9}\u{0BCD}"
    Among(&[3015, 2985, 3021], -1, 5, None), // "\u{0BC7}\u{0BA9}\u{0BCD}"
    Among(&[2985, 2990, 3021], -1, 1, None), // "\u{0BA9}\u{0BAE}\u{0BCD}"
    Among(&[2986, 2990, 3021], -1, 1, None), // "\u{0BAA}\u{0BAE}\u{0BCD}"
    Among(&[3006, 2990, 3021], -1, 5, None), // "\u{0BBE}\u{0BAE}\u{0BCD}"
    Among(&[2965, 3009, 2990, 3021], -1, 1, None), // "\u{0B95}\u{0BC1}\u{0BAE}\u{0BCD}"
    Among(&[2975, 3009, 2990, 3021], -1, 5, None), // "\u{0B9F}\u{0BC1}\u{0BAE}\u{0BCD}"
    Among(&[2980, 3009, 2990, 3021], -1, 1, None), // "\u{0BA4}\u{0BC1}\u{0BAE}\u{0BCD}"
    Among(&[2993, 3009, 2990, 3021], -1, 1, None), // "\u{0BB1}\u{0BC1}\u{0BAE}\u{0BCD}"
    Among(&[3014, 2990, 3021], -1, 5, None), // "\u{0BC6}\u{0BAE}\u{0BCD}"
    Among(&[3015, 2990, 3021], -1, 5, None), // "\u{0BC7}\u{0BAE}\u{0BCD}"
    Among(&[3019, 2990, 3021], -1, 5, None), // "\u{0BCB}\u{0BAE}\u{0BCD}"
    Among(&[3006, 2991, 3021], -1, 5, None), // "\u{0BBE}\u{0BAF}\u{0BCD}"
    Among(&[2985, 2992, 3021], -1, 1, None), // "\u{0BA9}\u{0BB0}\u{0BCD}"
    Among(&[2986, 2992, 3021], -1, 1, None), // "\u{0BAA}\u{0BB0}\u{0BCD}"
    Among(&[3008, 2991, 2992, 3021], -1, 5, None), // "\u{0BC0}\u{0BAF}\u{0BB0}\u{0BCD}"
    Among(&[2997, 2992, 3021], -1, 1, None), // "\u{0BB5}\u{0BB0}\u{0BCD}"
    Among(&[3006, 2992, 3021], -1, 5, None), // "\u{0BBE}\u{0BB0}\u{0BCD}"
    Among(&[2985, 3006, 2992, 3021], 35, 1, None), // "\u{0BA9}\u{0BBE}\u{0BB0}\u{0BCD}"
    Among(&[2990, 3006, 2992, 3021], 35, 1, None), // "\u{0BAE}\u{0BBE}\u{0BB0}\u{0BCD}"
    Among(&[2965, 3018, 2979, 3021, 2975, 3007, 2992, 3021], -1, 1, None), // "\u{0B95}\u{0BCA}\u{0BA3}\u{0BCD}\u{0B9F}\u{0BBF}\u{0BB0}\u{0BCD}"
    Among(&[2985, 3007, 2992, 3021], -1, 5, None), // "\u{0BA9}\u{0BBF}\u{0BB0}\u{0BCD}"
    Among(&[3008, 2992, 3021], -1, 5, None), // "\u{0BC0}\u{0BB0}\u{0BCD}"
    Among(&[2985, 2995, 3021], -1, 1, None), // "\u{0BA9}\u{0BB3}\u{0BCD}"
    Among(&[2986, 2995, 3021], -1, 1, None), // "\u{0BAA}\u{0BB3}\u{0BCD}"
    Among(&[2997, 2995, 3021], -1, 1, None), // "\u{0BB5}\u{0BB3}\u{0BCD}"
    Among(&[3006, 2995, 3021], -1, 5, None), // "\u{0BBE}\u{0BB3}\u{0BCD}"
    Among(&[2985, 3006, 2995, 3021], 44, 1, None), // "\u{0BA9}\u{0BBE}\u{0BB3}\u{0BCD}"
];

static A_26: &'static [Among<Context>; 6] = &[
    Among(&[2965, 3007, 2993], -1, -1, None), // "\u{0B95}\u{0BBF}\u{0BB1}"
    Among(&[2965, 3007, 2985, 3021, 2993], -1, -1, None), // "\u{0B95}\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}"
    Among(&[3006, 2984, 3007, 2985, 3021, 2993], -1, -1, None), // "\u{0BBE}\u{0BA8}\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}"
    Among(&[2965, 3007, 2993, 3021], -1, -1, None), // "\u{0B95}\u{0BBF}\u{0BB1}\u{0BCD}"
    Among(&[2965, 3007, 2985, 3021, 2993, 3021], -1, -1, None), // "\u{0B95}\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}\u{0BCD}"
    Among(&[3006, 2984, 3007, 2985, 3021, 2993, 3021], -1, -1, None), // "\u{0BBE}\u{0BA8}\u{0BBF}\u{0BA9}\u{0BCD}\u{0BB1}\u{0BCD}"
];

#[derive(Clone)]
struct Context {
    b_found_vetrumai_urupu: bool,
    b_found_a_match: bool,
}

fn r_has_min_length(env: &mut SnowballEnv, context: &mut Context) -> bool {
    return env.length > 4
}

fn r_fix_va_start(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.bra = env.cursor;
    among_var = env.find_among(A_0, context);
    if among_var == 0 {
        return false;
    }
    env.ket = env.cursor;
    match among_var {
        1 => {
            env.slice_from(&[2963]);
        }
        2 => {
            env.slice_from(&[2962]);
        }
        3 => {
            env.slice_from(&[2953]);
        }
        4 => {
            env.slice_from(&[2954]);
        }
        _ => ()
    }
    return true
}

fn r_fix_endings(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let v_1 = env.cursor;
    'lab0: loop {
        'replab1: loop{
            let v_2 = env.cursor;
            'lab2: for _ in 0..1 {
                if !r_fix_ending(env, context) {
                    break 'lab2;
                }
                continue 'replab1;
            }
            env.cursor = v_2;
            break 'replab1;
        }
        break 'lab0;
    }
    env.cursor = v_1;
    return true
}

fn r_remove_question_prefixes(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.bra = env.cursor;
    if !env.eq_s(&[2958]) {
        return false;
    }
    if env.find_among(A_1, context) == 0 {
        return false;
    }
    if !env.eq_s(&[3021]) {
        return false;
    }
    env.ket = env.cursor;
    env.slice_del();
    let v_1 = env.cursor;
    r_fix_va_start(env, context);
    env.cursor = v_1;
    return true
}

fn r_fix_ending(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if env.length <= 3{
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    'lab0: loop {
        let v_1 = env.limit - env.cursor;
        'lab1: loop {
            env.ket = env.cursor;
            among_var = env.find_among_b(A_5, context);
            if among_var == 0 {
                break 'lab1;
            }
            env.bra = env.cursor;
            match among_var {
                1 => {
                    env.slice_del();
                }
                2 => {
                    let v_2 = env.limit - env.cursor;
                    if env.find_among_b(A_2, context) == 0 {
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_2;
                    env.slice_del();
                }
                3 => {
                    env.slice_from(&[2995, 3021]);
                }
                4 => {
                    env.slice_from(&[2994, 3021]);
                }
                5 => {
                    env.slice_from(&[2975, 3009]);
                }
                6 => {
                    if !context.b_found_vetrumai_urupu {
                        break 'lab1;
                    }
                    let v_3 = env.limit - env.cursor;
                    'lab2: loop {
                        if !env.eq_s_b(&[3016]) {
                            break 'lab2;
                        }
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_3;
                    env.slice_from(&[2990, 3021]);
                }
                7 => {
                    env.slice_from(&[3021]);
                }
                8 => {
                    let v_4 = env.limit - env.cursor;
                    'lab3: loop {
                        if env.find_among_b(A_3, context) == 0 {
                            break 'lab3;
                        }
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_4;
                    env.slice_del();
                }
                9 => {
                    among_var = env.find_among_b(A_4, context);
                    match among_var {
                        1 => {
                            env.slice_del();
                        }
                        2 => {
                            env.slice_from(&[2990, 3021]);
                        }
                        _ => ()
                    }
                }
                _ => ()
            }
            break 'lab0;
        }
        env.cursor = env.limit - v_1;
        env.ket = env.cursor;
        if !env.eq_s_b(&[3021]) {
            return false;
        }
        'lab4: loop {
            let v_5 = env.limit - env.cursor;
            'lab5: loop {
                if env.find_among_b(A_6, context) == 0 {
                    break 'lab5;
                }
                let v_6 = env.limit - env.cursor;
                'lab6: loop {
                    if !env.eq_s_b(&[3021]) {
                        env.cursor = env.limit - v_6;
                        break 'lab6;
                    }
                    if env.find_among_b(A_7, context) == 0 {
                        env.cursor = env.limit - v_6;
                        break 'lab6;
                    }
                    break 'lab6;
                }
                env.bra = env.cursor;
                env.slice_del();
                break 'lab4;
            }
            env.cursor = env.limit - v_5;
            'lab7: loop {
                if env.find_among_b(A_8, context) == 0 {
                    break 'lab7;
                }
                env.bra = env.cursor;
                if !env.eq_s_b(&[3021]) {
                    break 'lab7;
                }
                env.slice_del();
                break 'lab4;
            }
            env.cursor = env.limit - v_5;
            let v_7 = env.limit - env.cursor;
            if env.find_among_b(A_9, context) == 0 {
                return false;
            }
            env.cursor = env.limit - v_7;
            env.bra = env.cursor;
            env.slice_del();
            break 'lab4;
        }
        break 'lab0;
    }
    env.cursor = env.limit_backward;
    return true
}

fn r_remove_pronoun_prefixes(env: &mut SnowballEnv, context: &mut Context) -> bool {
    env.bra = env.cursor;
    if env.find_among(A_10, context) == 0 {
        return false;
    }
    if env.find_among(A_11, context) == 0 {
        return false;
    }
    if !env.eq_s(&[3021]) {
        return false;
    }
    env.ket = env.cursor;
    env.slice_del();
    let v_1 = env.cursor;
    r_fix_va_start(env, context);
    env.cursor = v_1;
    return true
}

fn r_remove_plural_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_13, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            'lab0: loop {
                let v_1 = env.limit - env.cursor;
                'lab1: loop {
                    if env.find_among_b(A_12, context) == 0 {
                        break 'lab1;
                    }
                    env.slice_from(&[3009, 2969, 3021]);
                    break 'lab0;
                }
                env.cursor = env.limit - v_1;
                env.slice_from(&[3021]);
                break 'lab0;
            }
        }
        2 => {
            env.slice_from(&[2994, 3021]);
        }
        3 => {
            env.slice_from(&[2995, 3021]);
        }
        4 => {
            env.slice_del();
        }
        _ => ()
    }
    env.cursor = env.limit_backward;
    return true
}

fn r_remove_question_suffixes(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        env.ket = env.cursor;
        if env.find_among_b(A_14, context) == 0 {
            break 'lab0;
        }
        env.bra = env.cursor;
        env.slice_from(&[3021]);
        break 'lab0;
    }
    env.cursor = env.limit - v_1;
    env.cursor = env.limit_backward;
    r_fix_endings(env, context);
    return true
}

fn r_remove_command_suffixes(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    env.ket = env.cursor;
    if env.find_among_b(A_15, context) == 0 {
        return false;
    }
    env.bra = env.cursor;
    env.slice_del();
    env.cursor = env.limit_backward;
    return true
}

fn r_remove_um(env: &mut SnowballEnv, context: &mut Context) -> bool {
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    env.ket = env.cursor;
    if !env.eq_s_b(&[3009, 2990, 3021]) {
        return false;
    }
    env.bra = env.cursor;
    env.slice_from(&[3021]);
    env.cursor = env.limit_backward;
    let v_1 = env.cursor;
    r_fix_ending(env, context);
    env.cursor = v_1;
    return true
}

fn r_remove_common_word_endings(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    env.ket = env.cursor;
    among_var = env.find_among_b(A_17, context);
    if among_var == 0 {
        return false;
    }
    env.bra = env.cursor;
    match among_var {
        1 => {
            env.slice_from(&[3021]);
        }
        2 => {
            let v_1 = env.limit - env.cursor;
            'lab0: loop {
                if env.find_among_b(A_16, context) == 0 {
                    break 'lab0;
                }
                return false;
            }
            env.cursor = env.limit - v_1;
            env.slice_from(&[3021]);
        }
        3 => {
            env.slice_del();
        }
        _ => ()
    }
    env.cursor = env.limit_backward;
    r_fix_endings(env, context);
    return true
}

fn r_remove_vetrumai_urupukal(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    context.b_found_vetrumai_urupu = false;
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    'lab0: loop {
        let v_1 = env.limit - env.cursor;
        'lab1: loop {
            let v_2 = env.limit - env.cursor;
            env.ket = env.cursor;
            among_var = env.find_among_b(A_20, context);
            if among_var == 0 {
                break 'lab1;
            }
            env.bra = env.cursor;
            match among_var {
                1 => {
                    env.slice_del();
                }
                2 => {
                    env.slice_from(&[3021]);
                }
                3 => {
                    let v_3 = env.limit - env.cursor;
                    'lab2: loop {
                        if !env.eq_s_b(&[2990]) {
                            break 'lab2;
                        }
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_3;
                    env.slice_from(&[3021]);
                }
                4 => {
                    if env.length < 7{
                        break 'lab1;
                    }
                    env.slice_from(&[3021]);
                }
                5 => {
                    let v_4 = env.limit - env.cursor;
                    'lab3: loop {
                        if env.find_among_b(A_18, context) == 0 {
                            break 'lab3;
                        }
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_4;
                    env.slice_from(&[3021]);
                }
                6 => {
                    let v_5 = env.limit - env.cursor;
                    'lab4: loop {
                        if env.find_among_b(A_19, context) == 0 {
                            break 'lab4;
                        }
                        break 'lab1;
                    }
                    env.cursor = env.limit - v_5;
                    env.slice_del();
                }
                7 => {
                    env.slice_from(&[3007]);
                }
                _ => ()
            }
            env.cursor = env.limit - v_2;
            break 'lab0;
        }
        env.cursor = env.limit - v_1;
        let v_6 = env.limit - env.cursor;
        env.ket = env.cursor;
        if !env.eq_s_b(&[3016]) {
            return false;
        }
        'lab5: loop {
            let v_7 = env.limit - env.cursor;
            'lab6: loop {
                let v_8 = env.limit - env.cursor;
                'lab7: loop {
                    if env.find_among_b(A_21, context) == 0 {
                        break 'lab7;
                    }
                    break 'lab6;
                }
                env.cursor = env.limit - v_8;
                break 'lab5;
            }
            env.cursor = env.limit - v_7;
            let v_9 = env.limit - env.cursor;
            if env.find_among_b(A_22, context) == 0 {
                return false;
            }
            if !env.eq_s_b(&[3021]) {
                return false;
            }
            env.cursor = env.limit - v_9;
            break 'lab5;
        }
        env.bra = env.cursor;
        env.slice_from(&[3021]);
        env.cursor = env.limit - v_6;
        break 'lab0;
    }
    context.b_found_vetrumai_urupu = true;
    let v_10 = env.limit - env.cursor;
    'lab8: loop {
        env.ket = env.cursor;
        if !env.eq_s_b(&[3007, 2985, 3021]) {
            break 'lab8;
        }
        env.bra = env.cursor;
        env.slice_from(&[3021]);
        break 'lab8;
    }
    env.cursor = env.limit - v_10;
    env.cursor = env.limit_backward;
    r_fix_endings(env, context);
    return true
}

fn r_remove_tense_suffixes(env: &mut SnowballEnv, context: &mut Context) -> bool {
    context.b_found_a_match = true;
    'replab0: loop{
        let v_1 = env.cursor;
        'lab1: for _ in 0..1 {
            if !context.b_found_a_match {
                break 'lab1;
            }
            let v_2 = env.cursor;
            r_remove_tense_suffix(env, context);
            env.cursor = v_2;
            continue 'replab0;
        }
        env.cursor = v_1;
        break 'replab0;
    }
    return true
}

fn r_remove_tense_suffix(env: &mut SnowballEnv, context: &mut Context) -> bool {
    let mut among_var;
    context.b_found_a_match = false;
    if !r_has_min_length(env, context) {
        return false;
    }
    env.limit_backward = env.cursor;
    env.cursor = env.limit;
    let v_1 = env.limit - env.cursor;
    'lab0: loop {
        let v_2 = env.limit - env.cursor;
        env.ket = env.cursor;
        among_var = env.find_among_b(A_25, context);
        if among_var == 0 {
            break 'lab0;
        }
        env.bra = env.cursor;
        match among_var {
            1 => {
                env.slice_del();
            }
            2 => {
                let v_3 = env.limit - env.cursor;
                'lab1: loop {
                    if env.find_among_b(A_23, context) == 0 {
                        break 'lab1;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_3;
                env.slice_del();
            }
            3 => {
                let v_4 = env.limit - env.cursor;
                'lab2: loop {
                    if env.find_among_b(A_24, context) == 0 {
                        break 'lab2;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_4;
                env.slice_del();
            }
            4 => {
                let v_5 = env.limit - env.cursor;
                'lab3: loop {
                    if !env.eq_s_b(&[2970]) {
                        break 'lab3;
                    }
                    break 'lab0;
                }
                env.cursor = env.limit - v_5;
                env.slice_from(&[3021]);
            }
            5 => {
                env.slice_from(&[3021]);
            }
            6 => {
                let v_6 = env.limit - env.cursor;
                if !env.eq_s_b(&[3021]) {
                    break 'lab0;
                }
                env.cursor = env.limit - v_6;
                env.slice_del();
            }
            _ => ()
        }
        context.b_found_a_match = true;
        env.cursor = env.limit - v_2;
        break 'lab0;
    }
    env.cursor = env.limit - v_1;
    let v_7 = env.limit - env.cursor;
    'lab4: loop {
        env.ket = env.cursor;
        if env.find_among_b(A_26, context) == 0 {
            break 'lab4;
        }
        env.bra = env.cursor;
        env.slice_del();
        context.b_found_a_match = true;
        break 'lab4;
    }
    env.cursor = env.limit - v_7;
    env.cursor = env.limit_backward;
    r_fix_endings(env, context);
    return true
}

pub fn stem(env: &mut SnowballEnv) -> bool {
    let mut context = &mut Context {
        b_found_vetrumai_urupu: false,
        b_found_a_match: false,
    };
    context.b_found_vetrumai_urupu = false;
    let v_1 = env.cursor;
    r_fix_ending(env, context);
    env.cursor = v_1;
    if !r_has_min_length(env, context) {
        return false;
    }
    let v_2 = env.cursor;
    r_remove_question_prefixes(env, context);
    env.cursor = v_2;
    let v_3 = env.cursor;
    r_remove_pronoun_prefixes(env, context);
    env.cursor = v_3;
    let v_4 = env.cursor;
    r_remove_question_suffixes(env, context);
    env.cursor = v_4;
    let v_5 = env.cursor;
    r_remove_um(env, context);
    env.cursor = v_5;
    let v_6 = env.cursor;
    r_remove_common_word_endings(env, context);
    env.cursor = v_6;
    let v_7 = env.cursor;
    r_remove_vetrumai_urupukal(env, context);
    env.cursor = v_7;
    let v_8 = env.cursor;
    r_remove_plural_suffix(env, context);
    env.cursor = v_8;
    let v_9 = env.cursor;
    r_remove_command_suffixes(env, context);
    env.cursor = v_9;
    let v_10 = env.cursor;
    r_remove_tense_suffixes(env, context);
    env.cursor = v_10;
    return true
}
