import java.io.PrintStream;
import java.lang.reflect.Field;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Emits {@code crates/lucene-analysis/src/standard/tables.rs}: the unpacked DFA tables of Lucene
 * 10.5.0's JFlex-generated {@code org.apache.lucene.analysis.standard.StandardTokenizerImpl}.
 *
 * <p>JFlex stores the tables as run-length-packed {@code String} constants and unpacks them in the
 * class's static initialiser. Transcribing the packed strings by hand (or re-implementing the four
 * slightly different unpackers) is exactly the kind of byte-level guess this port avoids; instead
 * this reads the already-unpacked {@code private static final int[]} fields of the class Lucene
 * itself ships, by reflection, so the Rust scanner runs over the very arrays Java's does.
 *
 * <p>Run (the jar is what {@code scripts/lib-lucene-jars.sh} resolves):
 *
 * <pre>
 *   javac -d /tmp/x crates/lucene-analysis/tools/ExtractStandardTokenizerTables.java
 *   java -cp /tmp/x:lucene-core-10.5.0.jar ExtractStandardTokenizerTables \
 *       crates/lucene-analysis/src/standard/tables.rs
 * </pre>
 */
public class ExtractStandardTokenizerTables {
  private static final String CLASS = "org.apache.lucene.analysis.standard.StandardTokenizerImpl";

  public static void main(String[] args) throws Exception {
    Class<?> impl = Class.forName(CLASS);
    String version = org.apache.lucene.util.Version.LATEST.toString();
    if (!version.equals("10.5.0")) {
      throw new IllegalStateException("expected Lucene 10.5.0 on the classpath, got " + version);
    }
    StringBuilder out = new StringBuilder();
    out.append("// @generated by crates/lucene-analysis/tools/ExtractStandardTokenizerTables.java\n");
    out.append("// from Lucene ").append(version).append("'s compiled ").append(CLASS).append(":\n");
    out.append("// the private static final int[] tables JFlex 1.8.2 unpacks in the class's static\n");
    out.append("// initialiser, read back by reflection. DO NOT EDIT -- regenerate (see the tool's\n");
    out.append("// javadoc for the command line).\n");
    out.append("//\n");
    out.append("// Element types are the narrowest that hold every value; the tool checks each range.\n\n");
    out.append("#![allow(clippy::unreadable_literal)]\n\n");
    emit(out, impl, "ZZ_LEXSTATE", "u8", 0, 255);
    emit(out, impl, "ZZ_CMAP_TOP", "u16", 0, 65535);
    emit(out, impl, "ZZ_CMAP_BLOCKS", "u8", 0, 255);
    emit(out, impl, "ZZ_ACTION", "u8", 0, 255);
    emit(out, impl, "ZZ_ROWMAP", "u16", 0, 65535);
    emit(out, impl, "ZZ_TRANS", "i16", -1, 32767);
    emit(out, impl, "ZZ_ATTRIBUTE", "u8", 0, 255);
    Files.writeString(Path.of(args[0]), out.toString(), StandardCharsets.UTF_8);
  }

  private static void emit(StringBuilder out, Class<?> impl, String name, String ty, int lo, int hi)
      throws Exception {
    Field f = impl.getDeclaredField(name);
    f.setAccessible(true);
    int[] v = (int[]) f.get(null);
    out.append("pub(crate) static ").append(name).append(": [").append(ty).append("; ");
    out.append(v.length).append("] = [");
    for (int i = 0; i < v.length; i++) {
      if (v[i] < lo || v[i] > hi) {
        throw new IllegalStateException(name + "[" + i + "] = " + v[i] + " does not fit " + ty);
      }
      out.append(i % 16 == 0 ? "\n    " : " ").append(v[i]).append(',');
    }
    out.append("\n];\n\n");
  }
}
