#!/usr/bin/env python3
"""Extract the input strings of Lucene's UAX#29 conformance tests.

Lucene 10.5.0's test framework ships Unicode's word-break and emoji
conformance data as Java tests (`WordBreakTestUnicode_12_1_0.java`,
`EmojiTokenizationTestUnicode_12_1.java`: one `assertAnalyzesTo(analyzer,
"<input>", ...)` per test line). This pulls the *inputs* out of those sources
into `fixtures/src/uax29-inputs.txt` (one `<test>:<n>\t<UTF-8 hex>` line
each). The expected tokens are deliberately not taken from the test files:
`fixtures/src/GenStandardTokenizer.java` runs real `StandardTokenizer` over the
inputs and records what it produces, so the fixture is Lucene's output, not a
transcription.

Usage (the sources jar is Maven Central's
`org.apache.lucene:lucene-test-framework:10.5.0:sources`):

    python3 crates/lucene-analysis/tools/extract_uax29_inputs.py \
        lucene-test-framework-10.5.0-sources.jar fixtures/src/uax29-inputs.txt
"""

import re
import sys
import zipfile

TESTS = {
    "wordbreak": "org/apache/lucene/tests/analysis/standard/WordBreakTestUnicode_12_1_0.java",
    "emoji": "org/apache/lucene/tests/analysis/standard/EmojiTokenizationTestUnicode_12_1.java",
}

CALL = re.compile(r'assertAnalyzesTo\(\s*analyzer,\s*"((?:[^"\\]|\\.)*)"', re.S)
LITERAL = re.compile(r'"((?:[^"\\]|\\.)*)"')
ESCAPES = {"n": "\n", "r": "\r", "t": "\t", "b": "\b", "f": "\f", '"': '"', "'": "'", "\\": "\\"}


def java_unescape(lit: str) -> str:
    """A Java string literal's body as UTF-16 code units, then as a Python str."""
    units = []
    i = 0
    while i < len(lit):
        c = lit[i]
        if c != "\\":
            units.extend(c.encode("utf-16-le"))
            i += 1
            continue
        e = lit[i + 1]
        if e == "u":
            j = i + 1
            while lit[j] == "u":
                j += 1
            units.extend(int(lit[j:j + 4], 16).to_bytes(2, "little"))
            i = j + 4
        elif e in ESCAPES:
            units.extend(ESCAPES[e].encode("utf-16-le"))
            i += 2
        else:
            raise ValueError(f"unhandled escape \\{e}")
    # surrogatepass would keep a lone surrogate; strict refuses one, which is
    # what the Rust side (a `String`) needs.
    return bytes(units).decode("utf-16-le")


def main() -> int:
    jar, out = sys.argv[1], sys.argv[2]
    lines = []
    with zipfile.ZipFile(jar) as z:
        for name, path in TESTS.items():
            src = z.read(path).decode("utf-8")
            if name == "emoji":
                # `TESTS = { "<emoji-test.txt line>", "<the sequence>", ... }`:
                # every second literal is an input.
                body = src[src.index("TESTS =") :]
                inputs = LITERAL.findall(body)[1::2]
            else:
                inputs = [m.group(1) for m in CALL.finditer(src)]
            for n, lit in enumerate(inputs):
                lines.append(f"{name}:{n}\t{java_unescape(lit).encode('utf-8').hex()}")
    with open(out, "w", encoding="utf-8") as f:
        f.write("# generated by crates/lucene-analysis/tools/extract_uax29_inputs.py -- DO NOT EDIT\n")
        f.write("\n".join(lines) + "\n")
    print(f"{len(lines)} inputs", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
