#!/usr/bin/env python3
"""Generate crates/lucene-analysis/src/java_character_tables.rs from the
Unicode Character Database.

`java.lang.Character.getType(int)` is, by its specification, the UCD
`General_Category` of the JDK's Unicode version, and `getNumericValue` of a
`DECIMAL_DIGIT_NUMBER` is its UCD decimal value. So the tables are taken from
the UCD itself -- data under the Unicode licence (Unicode-3.0, allowed by
docs/licences.md) -- not from the JDK: the JDK only ever read the same file.

Source: `unicodedata2==16.0.0` (PyPI; Apache-2.0 code over the UCD 16.0.0
data files), Unicode 16.0 being what JDK 25 implements and what Lucene
10.5.0's `UnicodeProps.UNICODE_VERSION` names. The generated categories and
digit runs were checked identical, code point for code point, to JDK 25's
`Character.getType`/`getNumericValue` when this generator replaced a JDK
extractor.

`White_Space` comes from UCD 16.0.0's `PropList.txt` (transcribed below:
ten ranges, unchanged since Unicode 6.3); it is exactly Lucene 10.5.0's
`UnicodeProps.WHITESPACE`, which Lucene generates from the same file.

Usage:

    pip install --target /tmp/ucd unicodedata2==16.0.0
    PYTHONPATH=/tmp/ucd python3 crates/lucene-analysis/tools/gen_java_character_tables.py \\
        crates/lucene-analysis/src/java_character_tables.rs
"""

import sys

import unicodedata2 as ucd

UNICODE_VERSION = "16.0.0"

# java.lang.Character's general-category constants.
JAVA_TYPE = {
    "Cn": 0, "Lu": 1, "Ll": 2, "Lt": 3, "Lm": 4, "Lo": 5, "Mn": 6, "Me": 7,
    "Mc": 8, "Nd": 9, "Nl": 10, "No": 11, "Zs": 12, "Zl": 13, "Zp": 14,
    "Cc": 15, "Cf": 16, "Co": 18, "Cs": 19, "Pd": 20, "Ps": 21, "Pe": 22,
    "Pc": 23, "Po": 24, "Sm": 25, "Sc": 26, "Sk": 27, "So": 28, "Pi": 29,
    "Pf": 30,
}

# PropList.txt 16.0.0, White_Space.
WHITE_SPACE = [
    (0x0009, 0x000D), (0x0020, 0x0020), (0x0085, 0x0085), (0x00A0, 0x00A0),
    (0x1680, 0x1680), (0x2000, 0x200A), (0x2028, 0x2029), (0x202F, 0x202F),
    (0x205F, 0x205F), (0x3000, 0x3000),
]

MAX_CODE_POINT = 0x10FFFF


def main(path):
    if ucd.unidata_version != UNICODE_VERSION:
        sys.exit(f"need UCD {UNICODE_VERSION}, unicodedata2 has {ucd.unidata_version}")
    out = [
        "// @generated by crates/lucene-analysis/tools/gen_java_character_tables.py",
        f"// from the Unicode Character Database {UNICODE_VERSION} (Unicode licence). DO NOT EDIT --",
        "// regenerate (see the tool's docstring for the command line).",
        "",
    ]
    runs, prev = [], -1
    for cp in range(MAX_CODE_POINT + 1):
        t = JAVA_TYPE[ucd.category(chr(cp))]
        if t != prev:
            runs.append((cp, t))
            prev = t
    out.append("/// `(first code point, Character.getType)` runs, ascending.")
    line = f"pub(crate) static GENERAL_CATEGORY_RUNS: [(u32, u8); {len(runs)}] = ["
    for i, (cp, t) in enumerate(runs):
        if i % 6 == 0:
            out.append(line)
            line = "   "
        line += f" (0x{cp:X}, {t}),"
    out.append(line)
    out.append("];")
    out.append("")

    zeros = []
    for cp in range(MAX_CODE_POINT + 1):
        c = chr(cp)
        if ucd.category(c) != "Nd":
            continue
        v = ucd.decimal(c)
        zero = cp - v
        if not 0 <= v <= 9 or ucd.category(chr(zero)) != "Nd" or ucd.decimal(chr(zero)) != 0:
            sys.exit(f"decimal digit {cp:X} not in a 0..9 run")
        if v == 0:
            zeros.append(cp)
    out.append("/// The zero of every `DECIMAL_DIGIT_NUMBER` run, ascending.")
    line = f"pub(crate) static DECIMAL_DIGIT_ZEROS: [u32; {len(zeros)}] = ["
    for i, z in enumerate(zeros):
        if i % 8 == 0:
            out.append(line)
            line = "   "
        line += f" 0x{z:X},"
    out.append(line)
    out.append("];")
    out.append("")

    out.append(f"/// `UnicodeProps.WHITESPACE`: UCD {UNICODE_VERSION} `White_Space`, as inclusive ranges.")
    out.append(f"pub(crate) static UNICODE_WHITESPACE: [(u32, u32); {len(WHITE_SPACE)}] = [")
    for a, b in WHITE_SPACE:
        out.append(f"    (0x{a:X}, 0x{b:X}),")
    out.append("];")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main(sys.argv[1])
