#!/usr/bin/env python3
"""Generate crates/lucene-analysis/src/en/kstem_data.rs from Lucene's sources.

KStem's dictionary is data in Java source form: the `String[] data` arrays of
`KStemData1..8` (the head-word list) and the `exceptionWords`,
`directConflations`, `countryNationality`, `supplementDict` and `properNouns`
arrays of `KStemmer`. This reads them out of the lucene-analysis-common
10.5.0 sources jar (Maven Central's
`org.apache.lucene:lucene-analysis-common:10.5.0:sources`) and writes them as
Rust slices, in their Java order -- never transcribed by hand.

The data is the University of Massachusetts' KStem dictionary, under the
licence `LICENSE` already carries for it (BSD-style, see docs/licences.md).

Usage:

    python3 crates/lucene-analysis/tools/gen_kstem_data.py \\
        lucene-analysis-common-10.5.0-sources.jar \\
        crates/lucene-analysis/src/en/kstem_data.rs
"""

import re
import sys
import zipfile

BASE = "org/apache/lucene/analysis/en/"
STRING = re.compile(r'"((?:[^"\\]|\\.)*)"')


def array_body(src, decl):
    """The text between `decl ... = {` and its matching `};`."""
    start = src.index(decl)
    open_brace = src.index("{", start)
    depth, i = 0, open_brace
    while True:
        c = src[i]
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return src[open_brace + 1 : i]
        elif c == '"':
            i = src.index('"', i + 1)
            while src[i - 1] == "\\":
                i = src.index('"', i + 1)
        i += 1


def strip_comments(src):
    """`src` without `//` and `/* */` comments (string literals kept)."""
    out, i, n = [], 0, len(src)
    while i < n:
        c = src[i]
        if c == '"':
            j = i + 1
            while src[j] != '"':
                j += 2 if src[j] == "\\" else 1
            out.append(src[i : j + 1])
            i = j + 1
        elif src.startswith("//", i):
            i = src.find("\n", i)
            i = n if i < 0 else i
        elif src.startswith("/*", i):
            i = src.index("*/", i) + 2
        else:
            out.append(c)
            i += 1
    return "".join(out)


def strings(body):
    return [bytes(s, "utf-8").decode("unicode_escape") for s in STRING.findall(strip_comments(body))]


def pairs(body):
    groups = re.findall(r"\{([^{}]*)\}", strip_comments(body))
    result = []
    for g in groups:
        s = STRING.findall(g)
        if len(s) != 2:
            sys.exit(f"bad pair {g!r}")
        result.append((s[0], s[1]))
    return result


def rust_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def emit_list(out, name, doc, items):
    out.append(f"/// {doc}")
    out.append(f"pub(super) static {name}: &[&str] = &[")
    line = "   "
    for s in items:
        piece = " " + rust_str(s) + ","
        if len(line) + len(piece) > 99:
            out.append(line)
            line = "   "
        line += piece
    if line.strip():
        out.append(line)
    out.append("];")
    out.append("")


def emit_pairs(out, name, doc, items):
    out.append(f"/// {doc}")
    out.append(f"pub(super) static {name}: &[(&str, &str)] = &[")
    for a, b in items:
        out.append(f"    ({rust_str(a)}, {rust_str(b)}),")
    out.append("];")
    out.append("")


def main(jar, dest):
    z = zipfile.ZipFile(jar)
    read = lambda n: z.read(BASE + n).decode("utf-8")
    kstemmer = read("KStemmer.java")
    out = [
        "// @generated by crates/lucene-analysis/tools/gen_kstem_data.py from the",
        "// lucene-analysis-common 10.5.0 sources (KStemData1..8 and KStemmer's arrays).",
        "// DO NOT EDIT -- regenerate. The KStem dictionary is the University of",
        "// Massachusetts' (BSD-style licence, in LICENSE).",
        "",
    ]
    emit_list(out, "EXCEPTION_WORDS", "`KStemmer.exceptionWords`.",
              strings(array_body(kstemmer, "String[] exceptionWords")))
    emit_pairs(out, "DIRECT_CONFLATIONS", "`KStemmer.directConflations`.",
               pairs(array_body(kstemmer, "String[][] directConflations")))
    emit_pairs(out, "COUNTRY_NATIONALITY", "`KStemmer.countryNationality`.",
               pairs(array_body(kstemmer, "String[][] countryNationality")))
    head = []
    for i in range(1, 9):
        head.extend(strings(array_body(read(f"KStemData{i}.java"), "String[] data")))
    emit_list(out, "HEAD_WORDS", "`KStemData1.data` .. `KStemData8.data`, concatenated.", head)
    emit_list(out, "SUPPLEMENT_DICT", "`KStemmer.supplementDict`.",
              strings(array_body(kstemmer, "String[] supplementDict")))
    emit_list(out, "PROPER_NOUNS", "`KStemmer.properNouns`.",
              strings(array_body(kstemmer, "String[] properNouns")))
    with open(dest, "w", encoding="utf-8") as f:
        f.write("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1], sys.argv[2])
