#!/usr/bin/env bash
# Generate crates/lucene-analysis/src/snowball/algorithms/ from the Snowball
# sources Lucene 10.5.0's stemmers were generated from.
#
# Lucene's `org.tartarus.snowball.ext.*Stemmer` classes are the Java output of
# the Snowball compiler at commit SNOWBALL_COMMIT (Lucene's
# gradle/generation/snowball.gradle, `snowballStemmerCommit`; Snowball 2.2.0).
# This script builds that same compiler and runs its Rust backend (`-rust`)
# over the same `.sbl` sources, for the 30 languages Lucene ships (its
# `src/test/org/apache/lucene/analysis/snowball/languages.txt`). Nothing in
# algorithms/ is written by hand.
#
# Two mechanical rewrites of the backend's output:
# - `use snowball::SnowballEnv;` / `use snowball::Among;` name the snowball
#   crate's layout; here the runtime is `crate::snowball::program`.
# - `if !env.slice_from(s) { return false; }` (and `slice_del`) become
#   `env.slice_from(s);`: the runtime's slice operations cannot fail (Java's
#   `slice_from` is `void`, and the Java backend emits the bare call), so the
#   `return false` arm is dead code.
# - The runtime keeps Java's UTF-16 string (`SnowballEnv`'s module docs), so
#   `len`, emitted as `env.current.chars().count()`, is `env.length`, and the
#   one byte size the backend folds into a constant (`yiddish.sbl`'s
#   `sizeof '{Giml}{Yud}{Samekh}'`, 6 bytes) is its 3 UTF-16 units, as in
#   Lucene's Java (UNIT_FIXES; each must match exactly once).
# - Strings become UTF-16 (`snowball_utf16.py`): every literal a `&[u16]`
#   array, the two string variables `Vec<u16>`, and the `among` tables
#   re-sorted into UTF-16 order (the backend sorts a backward table by its
#   strings' reversed UTF-8 bytes, the runtime searches reversed UTF-16 units).
#   With the Lucene sources jar, every table is then checked equal to the
#   same table of Lucene's Java stemmer.
#
# Before generating, it re-runs the Java backend and checks that every Java
# stemmer it produces equals Lucene 10.5.0's (modulo Lucene's reformatting),
# so the Rust output is known to come from the compiler and sources Lucene
# used. Pass the Lucene sources jar to enable that check.
#
# The `.sbl` sources and the compiler are Snowball's, under the BSD 3-clause
# licence `LICENSE` already carries for Lucene's Snowball stemmers
# (docs/licences.md).
#
# Usage:
#   crates/lucene-analysis/tools/gen_snowball.sh [SNOWBALL_CHECKOUT] [LUCENE_ANALYSIS_COMMON_SOURCES_JAR]
#
# Without a checkout it fetches the commit from github.com/snowballstem/snowball.
set -euo pipefail

SNOWBALL_COMMIT=34f3612e5e8c48975243bc2e87561abdac5aa9bb
LANGUAGES=(Arabic Armenian Basque Catalan Danish Dutch English Estonian Finnish
  French German Greek Hindi Hungarian Indonesian Irish Italian Lithuanian Nepali
  Norwegian Porter Portuguese Romanian Russian Serbian Spanish Swedish Tamil
  Turkish Yiddish)

ROOT=$(cd "$(dirname "$0")/../../.." && pwd)
DEST="$ROOT/crates/lucene-analysis/src/snowball/algorithms"
WORK=$(mktemp -d)
trap 'rm -rf "$WORK"' EXIT

SRC="${1:-}"
if [ -z "$SRC" ]; then
  SRC="$WORK/snowball"
  git init -q "$SRC"
  git -C "$SRC" fetch -q --depth 1 https://github.com/snowballstem/snowball "$SNOWBALL_COMMIT"
  git -C "$SRC" checkout -q FETCH_HEAD
fi
if [ -d "$SRC/.git" ] && [ "$(git -C "$SRC" rev-parse HEAD)" != "$SNOWBALL_COMMIT" ]; then
  echo "gen_snowball: $SRC is not at $SNOWBALL_COMMIT" >&2
  exit 1
fi
make -s -C "$SRC" snowball >/dev/null

if [ -n "${2:-}" ]; then
  mkdir -p "$WORK/lucene" "$WORK/java"
  (cd "$WORK/lucene" && unzip -q "$2" 'org/tartarus/snowball/ext/*')
  norm() { grep -v '^\s*\(//\|\*\|/\*\)' "$1" | tr -d ' \t\n' | sed 's/finalstatic/staticfinal/g; s/,}/}/g'; }
  for l in "${LANGUAGES[@]}"; do
    lc=$(echo "$l" | tr 'A-Z' 'a-z')
    "$SRC/snowball" "$SRC/algorithms/$lc.sbl" -j -o "$WORK/java/${lc}Stemmer" \
      -p org.tartarus.snowball.SnowballStemmer
    sed "s/${lc}Stemmer/${l}Stemmer/g" "$WORK/java/${lc}Stemmer.java" > "$WORK/java/$l.java"
    if [ "$(norm "$WORK/java/$l.java")" != \
         "$(norm "$WORK/lucene/org/tartarus/snowball/ext/${l}Stemmer.java")" ]; then
      echo "gen_snowball: ${l}Stemmer differs from Lucene's" >&2
      exit 1
    fi
  done
  echo "gen_snowball: all ${#LANGUAGES[@]} Java stemmers equal Lucene 10.5.0's"
fi

# "language|generated text|replacement", each applied to exactly one line.
UNIT_FIXES=(
  'yiddish|return context.i_p1 <= (env.cursor + 6)|return context.i_p1 <= (env.cursor + 3)'
)

rm -rf "$DEST"
mkdir -p "$DEST"
{
  echo "//! The Snowball compiler's Rust output for every stemmer Lucene 10.5.0"
  echo "//! ships (\`org.tartarus.snowball.ext.*Stemmer\`), generated by"
  echo "//! \`tools/gen_snowball.sh\` from Snowball commit"
  echo "//! \`$SNOWBALL_COMMIT\`. Do not edit."
  echo
  echo "#![allow(clippy::all, clippy::pedantic, unused_labels, unreachable_code, rustdoc::bare_urls)]"
  echo
  for l in "${LANGUAGES[@]}"; do
    echo "pub mod $(echo "$l" | tr 'A-Z' 'a-z');"
  done
  echo
  echo "/// \`(Java class name without \`Stemmer\`, the generated \`stem\`)\`, in"
  echo "/// \`languages.txt\` order."
  echo "pub static STEMMERS: [(&str, fn(&mut super::program::SnowballEnv) -> bool); ${#LANGUAGES[@]}] = ["
  for l in "${LANGUAGES[@]}"; do
    echo "    (\"$l\", $(echo "$l" | tr 'A-Z' 'a-z')::stem),"
  done
  echo "];"
} > "$DEST/mod.rs"

for l in "${LANGUAGES[@]}"; do
  lc=$(echo "$l" | tr 'A-Z' 'a-z')
  "$SRC/snowball" "$SRC/algorithms/$lc.sbl" -rust -o "$WORK/$lc"
  sed -e 's/^use snowball::SnowballEnv;$/use super::super::program::SnowballEnv;/' \
      -e 's/^use snowball::Among;$/use super::super::program::Among;/' \
      "$WORK/$lc.rs" |
    perl -0pe 's/if !env\.(slice_from\("(?:[^"\\]|\\.)*"\)|slice_from\(&[\w.]+\)|slice_del\(\)) \{\n\s*return false;\n\s*\}/env.$1;/g' \
      > "$DEST/$lc.rs"
  if grep -q 'if !env\.slice_' "$DEST/$lc.rs"; then
    echo "gen_snowball: $lc.rs: a slice call was not rewritten" >&2
    exit 1
  fi
  perl -pi -e 's/\(env\.current\.chars\(\)\.count\(\) as i32\)/env.length/g' "$DEST/$lc.rs"
  if grep -q 'env\.current' "$DEST/$lc.rs"; then
    echo "gen_snowball: $lc.rs: a use of env.current was not rewritten" >&2
    exit 1
  fi
  java_src=()
  if [ -n "${2:-}" ]; then
    java_src=(--java "$WORK/lucene/org/tartarus/snowball/ext/${l}Stemmer.java")
  fi
  python3 "$(dirname "$0")/snowball_utf16.py" "$DEST/$lc.rs" "${java_src[@]}"
  for fix in "${UNIT_FIXES[@]}"; do
    IFS='|' read -r fl old new <<< "$fix"
    [ "$fl" = "$lc" ] || continue
    if [ "$(grep -cF -- "$old" "$DEST/$lc.rs")" != 1 ]; then
      echo "gen_snowball: $lc.rs: '$old' does not occur exactly once" >&2
      exit 1
    fi
    OLD="$old" NEW="$new" perl -pi -e 's/\Q$ENV{OLD}\E/$ENV{NEW}/' "$DEST/$lc.rs"
  done
done
echo "gen_snowball: wrote ${#LANGUAGES[@]} stemmers to $DEST"
