import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.CharacterCodingException;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.TreeSet;

/**
 * Generates {@code crates/lucene-analysis/src/hunspell/charsets.rs}: the JDK's decoding of every
 * single-byte charset a Hunspell {@code SET} line names in real dictionaries (beyond UTF-8 and
 * ISO-8859-1, which the port decodes directly, and ISO8859-14, which Lucene decodes itself), and
 * the names {@code Charset.forName} accepts, so {@code Dictionary.getDecoder} resolves names --
 * and refuses them -- as Lucene 10.5.0 does on the JDK.
 *
 * <p>Per charset: its 128 high bytes (every charset here is ASCII below 0x80, which the generator
 * checks), each the {@code char} the JDK's decoder yields, or {@code UNMAPPABLE} where it reports
 * an unmappable byte (Lucene's decoder only replaces malformed input, so such a byte fails the
 * load). Then every name and alias of every charset the JDK knows, lowercased: {@code
 * Charset.forName} matches case-insensitively, and a legal name outside that list is an {@code
 * UnsupportedCharsetException}. The output is identical under JDK 21 and JDK 25.
 *
 * <p>Usage: {@code java crates/lucene-analysis/tools/GenHunspellCharsets.java >
 * crates/lucene-analysis/src/hunspell/charsets.rs}
 */
public class GenHunspellCharsets {
  /** {@code (Rust name, JDK canonical name)}, in the order of the Rust enum. */
  static final String[][] CHARSETS = {
    {"Utf8", "UTF-8"},
    {"Iso8859_1", "ISO-8859-1"},
    {"Iso8859_2", "ISO-8859-2"},
    {"Iso8859_7", "ISO-8859-7"},
    {"Iso8859_13", "ISO-8859-13"},
    {"Iso8859_15", "ISO-8859-15"},
    {"Koi8R", "KOI8-R"},
    {"Windows1251", "windows-1251"},
    {"Tis620", "TIS-620"},
  };

  /** The tabled charsets: all but UTF-8 and ISO-8859-1. */
  static final int FIRST_TABLED = 2;

  static final char UNMAPPABLE = '�';

  public static void main(String[] args) throws Exception {
    StringBuilder out = new StringBuilder();
    out.append("//! The JDK's single-byte charsets a Hunspell `SET` names, and the charset\n");
    out.append("//! names `Charset.forName` accepts. Generated by\n");
    out.append("//! `crates/lucene-analysis/tools/GenHunspellCharsets.java`; do not edit.\n\n");
    out.append("/// A byte the JDK's decoder reports as unmappable.\n");
    out.append("pub(crate) const UNMAPPABLE: u16 = 0xFFFD;\n\n");
    for (int c = FIRST_TABLED; c < CHARSETS.length; c++) {
      Charset cs = Charset.forName(CHARSETS[c][1]);
      out.append("/// `").append(cs.name()).append("`: bytes `0x80..=0xFF`.\n");
      out.append("pub(crate) const ")
          .append(CHARSETS[c][0].toUpperCase(Locale.ROOT))
          .append(": [u16; 128] = [\n");
      for (int b = 0; b < 256; b++) {
        char ch = decode(cs, b);
        if (b < 0x80) {
          if (ch != b) throw new AssertionError(cs + " is not ASCII at " + b);
          continue;
        }
        if (ch == UNMAPPABLE) {
          if (decodeReplacing(cs, b) != UNMAPPABLE) throw new AssertionError(cs + " " + b);
        }
        if ((b - 0x80) % 12 == 0) out.append("   ");
        out.append(String.format(" 0x%04X,", (int) ch));
        if ((b - 0x80) % 12 == 11 || b == 255) out.append('\n');
      }
      out.append("];\n\n");
    }
    out.append("/// The tables, in `NAMES`' numbering from ").append(FIRST_TABLED).append(".\n");
    out.append("pub(crate) const TABLES: [&[u16; 128]; ")
        .append(CHARSETS.length - FIRST_TABLED)
        .append("] = [\n");
    for (int c = FIRST_TABLED; c < CHARSETS.length; c++) {
      out.append("    &").append(CHARSETS[c][0].toUpperCase(Locale.ROOT)).append(",\n");
    }
    out.append("];\n\n");
    out.append("/// Every name and alias `Charset.forName` resolves to each decoded\n");
    out.append("/// charset, lowercased, sorted.\n");
    out.append("pub(crate) const NAMES: [(&str, usize); ");
    List<String> named = new ArrayList<>();
    for (int c = 0; c < CHARSETS.length; c++) {
      Charset cs = Charset.forName(CHARSETS[c][1]);
      TreeSet<String> names = new TreeSet<>();
      names.add(cs.name().toLowerCase(Locale.ROOT));
      for (String a : cs.aliases()) names.add(a.toLowerCase(Locale.ROOT));
      for (String n : names) named.add(n + "\t" + c);
    }
    named.sort(null);
    out.append(named.size()).append("] = [\n");
    for (String n : named) {
      String[] f = n.split("\t");
      out.append("    (\"").append(f[0]).append("\", ").append(f[1]).append("),\n");
    }
    out.append("];\n\n");
    TreeSet<String> known = new TreeSet<>();
    for (Charset cs : Charset.availableCharsets().values()) {
      known.add(cs.name().toLowerCase(Locale.ROOT));
      for (String a : cs.aliases()) known.add(a.toLowerCase(Locale.ROOT));
    }
    out.append("/// Every charset name and alias the JDK knows, lowercased, sorted: a\n");
    out.append("/// legal name outside it is an `UnsupportedCharsetException`.\n");
    out.append("pub(crate) const JDK_NAMES: [&str; ").append(known.size()).append("] = [\n");
    for (String n : known) out.append("    \"").append(n).append("\",\n");
    out.append("];\n");
    System.out.print(out);
  }

  /** The JDK's decoding of byte {@code b}, {@code UNMAPPABLE} where it reports one. */
  static char decode(Charset cs, int b) {
    CharsetDecoder d =
        cs.newDecoder()
            .onMalformedInput(CodingErrorAction.REPORT)
            .onUnmappableCharacter(CodingErrorAction.REPORT);
    try {
      CharBuffer r = d.decode(ByteBuffer.wrap(new byte[] {(byte) b}));
      if (r.length() != 1) throw new AssertionError(cs + " decodes " + b + " to " + r.length());
      if (r.charAt(0) == UNMAPPABLE) throw new AssertionError(cs + " maps " + b + " to U+FFFD");
      return r.charAt(0);
    } catch (CharacterCodingException e) {
      return UNMAPPABLE;
    }
  }

  static char decodeReplacing(Charset cs, int b) {
    CharsetDecoder d =
        cs.newDecoder()
            .onMalformedInput(CodingErrorAction.REPLACE)
            .onUnmappableCharacter(CodingErrorAction.REPLACE);
    try {
      return d.decode(ByteBuffer.wrap(new byte[] {(byte) b})).charAt(0);
    } catch (CharacterCodingException e) {
      throw new AssertionError(e);
    }
  }
}
