/*
 * Prints crates/lucene-analysis/src/util/java_regex_props.rs: the Unicode data behind
 * java.util.regex's script, block and binary properties, as JDK 25 answers them -- each set is
 * the code points a one-character text matches the property's pattern against (Pattern itself is
 * the oracle), each script and block from Character.UnicodeScript.of / UnicodeBlock.of with the
 * names forName accepts. Unicode facts read through the JDK's API; no JDK code is copied. Run with
 * JDK 25:
 *
 *   java --add-opens java.base/java.lang=ALL-UNNAMED \
 *     crates/lucene-analysis/tools/GenJavaRegexProperties.java > crates/lucene-analysis/src/util/java_regex_props.rs
 */
import java.lang.reflect.Field;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.regex.Pattern;

public class GenJavaRegexProperties {
  /** Key, pattern: the key is what java_backtrack.rs looks the set up by. */
  static final String[][] SETS = {
    {"U:ALPHABETIC", "\\p{IsAlphabetic}"}, {"U:ASSIGNED", "\\p{IsAssigned}"}, {"U:CONTROL", "\\p{IsControl}"},
    {"U:EMOJI", "\\p{IsEmoji}"}, {"U:EMOJI_PRESENTATION", "\\p{IsEmoji_Presentation}"},
    {"U:EMOJI_MODIFIER", "\\p{IsEmoji_Modifier}"}, {"U:EMOJI_MODIFIER_BASE", "\\p{IsEmoji_Modifier_Base}"},
    {"U:EMOJI_COMPONENT", "\\p{IsEmoji_Component}"}, {"U:EXTENDED_PICTOGRAPHIC", "\\p{IsExtended_Pictographic}"},
    {"U:HEX_DIGIT", "\\p{IsHex_Digit}"}, {"U:IDEOGRAPHIC", "\\p{IsIdeographic}"}, {"U:JOIN_CONTROL", "\\p{IsJoin_Control}"},
    {"U:LETTER", "\\p{IsLetter}"}, {"U:LOWERCASE", "\\p{IsLowercase}"}, {"Ui:LOWERCASE", "(?i)\\p{IsLowercase}"},
    {"U:NONCHARACTER_CODE_POINT", "\\p{IsNoncharacter_Code_Point}"}, {"U:TITLECASE", "\\p{IsTitlecase}"},
    {"Ui:TITLECASE", "(?i)\\p{IsTitlecase}"}, {"U:PUNCTUATION", "\\p{IsPunctuation}"}, {"U:UPPERCASE", "\\p{IsUppercase}"},
    {"Ui:UPPERCASE", "(?i)\\p{IsUppercase}"}, {"U:WHITE_SPACE", "\\p{IsWhite_Space}"}, {"U:WORD", "\\p{IsWord}"},
    {"U:ALNUM", "\\p{IsAlnum}"}, {"U:BLANK", "\\p{IsBlank}"}, {"U:GRAPH", "\\p{IsGraph}"}, {"U:PRINT", "\\p{IsPrint}"},
    {"U:DIGIT", "\\p{IsDigit}"},
    {"J:javaLowerCase", "\\p{javaLowerCase}"}, {"Ji:javaLowerCase", "(?i)\\p{javaLowerCase}"},
    {"J:javaUpperCase", "\\p{javaUpperCase}"}, {"Ji:javaUpperCase", "(?i)\\p{javaUpperCase}"},
    {"J:javaTitleCase", "\\p{javaTitleCase}"}, {"Ji:javaTitleCase", "(?i)\\p{javaTitleCase}"},
    {"J:javaAlphabetic", "\\p{javaAlphabetic}"}, {"J:javaIdeographic", "\\p{javaIdeographic}"},
    {"J:javaDigit", "\\p{javaDigit}"}, {"J:javaDefined", "\\p{javaDefined}"}, {"J:javaLetter", "\\p{javaLetter}"},
    {"J:javaLetterOrDigit", "\\p{javaLetterOrDigit}"}, {"J:javaJavaIdentifierStart", "\\p{javaJavaIdentifierStart}"},
    {"J:javaJavaIdentifierPart", "\\p{javaJavaIdentifierPart}"},
    {"J:javaUnicodeIdentifierStart", "\\p{javaUnicodeIdentifierStart}"},
    {"J:javaUnicodeIdentifierPart", "\\p{javaUnicodeIdentifierPart}"},
    {"J:javaIdentifierIgnorable", "\\p{javaIdentifierIgnorable}"}, {"J:javaSpaceChar", "\\p{javaSpaceChar}"},
    {"J:javaWhitespace", "\\p{javaWhitespace}"}, {"J:javaISOControl", "\\p{javaISOControl}"},
    {"J:javaMirrored", "\\p{javaMirrored}"}, {"J:javaEmoji", "\\p{javaEmoji}"},
    {"J:javaEmojiPresentation", "\\p{javaEmojiPresentation}"}, {"J:javaEmojiModifier", "\\p{javaEmojiModifier}"},
    {"J:javaEmojiModifierBase", "\\p{javaEmojiModifierBase}"}, {"J:javaEmojiComponent", "\\p{javaEmojiComponent}"},
    {"J:javaExtendedPictographic", "\\p{javaExtendedPictographic}"},
    {"P:ALPHA", "(?U)\\p{Alpha}"}, {"P:LOWER", "(?U)\\p{Lower}"}, {"Pi:LOWER", "(?iU)\\p{Lower}"},
    {"P:UPPER", "(?U)\\p{Upper}"}, {"Pi:UPPER", "(?iU)\\p{Upper}"}, {"P:SPACE", "(?U)\\p{Space}"},
    {"P:PUNCT", "(?U)\\p{Punct}"}, {"P:XDIGIT", "(?U)\\p{XDigit}"}, {"P:ALNUM", "(?U)\\p{Alnum}"},
    {"P:CNTRL", "(?U)\\p{Cntrl}"}, {"P:DIGIT", "(?U)\\p{Digit}"}, {"P:BLANK", "(?U)\\p{Blank}"},
    {"P:GRAPH", "(?U)\\p{Graph}"}, {"P:PRINT", "(?U)\\p{Print}"},
    {"W", "(?U)\\w"}, {"D", "(?U)\\d"}, {"S", "(?U)\\s"},
  };

  static String ranges(Pattern p) {
    StringBuilder b = new StringBuilder();
    int start = -1;
    for (int c = 0; c <= 0x110000; c++) {
      boolean in = c <= 0x10FFFF && p.matcher(new String(Character.toChars(c))).matches();
      if (in && start < 0) start = c;
      if (!in && start >= 0) {
        b.append(String.format("(0x%X, 0x%X), ", start, c - 1));
        start = -1;
      }
    }
    return b.toString();
  }

  public static void main(String[] args) throws Exception {
    StringBuilder o = new StringBuilder();
    o.append("//! The Unicode data behind `java.util.regex`'s script, block and binary\n");
    o.append("//! properties, as JDK 25 answers them. Generated by\n");
    o.append("//! `tools/GenJavaRegexProperties.java`; do not edit.\n\n");
    // scripts
    Character.UnicodeScript[] scripts = Character.UnicodeScript.values();
    List<String> runs = new ArrayList<>();
    Character.UnicodeScript prev = null;
    for (int c = 0; c <= 0x10FFFF; c++) {
      Character.UnicodeScript s = Character.UnicodeScript.of(c);
      if (s != prev) {
        runs.add(String.format("(0x%X, %d)", c, s.ordinal()));
        prev = s;
      }
    }
    o.append("/// `Character.UnicodeScript.of`: (first code point, script) runs.\n");
    o.append("pub(crate) static SCRIPT_RUNS: [(u32, u8); ").append(runs.size()).append("] = [");
    o.append(String.join(", ", runs)).append("];\n\n");
    // forName: the enum name or its alias, case-insensitively
    Field aliases = Character.UnicodeScript.class.getDeclaredField("aliases");
    aliases.setAccessible(true);
    @SuppressWarnings("unchecked")
    Map<String, Character.UnicodeScript> amap = (Map<String, Character.UnicodeScript>) aliases.get(null);
    Map<String, Integer> names = new TreeMap<>();
    for (Character.UnicodeScript s : scripts) names.put(s.name(), s.ordinal());
    for (Map.Entry<String, Character.UnicodeScript> e : amap.entrySet()) names.put(e.getKey().toUpperCase(java.util.Locale.ENGLISH), e.getValue().ordinal());
    o.append("/// `UnicodeScript.forName`: every accepted name, upper-cased.\n");
    o.append("pub(crate) static SCRIPT_NAMES: [(&str, u8); ").append(names.size()).append("] = [");
    List<String> ns = new ArrayList<>();
    for (Map.Entry<String, Integer> e : names.entrySet()) ns.add("(\"" + e.getKey() + "\", " + e.getValue() + ")");
    o.append(String.join(", ", ns)).append("];\n\n");
    // blocks
    Field bmap = Character.UnicodeBlock.class.getDeclaredField("map");
    bmap.setAccessible(true);
    @SuppressWarnings("unchecked")
    Map<String, Character.UnicodeBlock> blocks = (Map<String, Character.UnicodeBlock>) bmap.get(null);
    Map<Character.UnicodeBlock, Integer> ids = new LinkedHashMap<>();
    List<String> bruns = new ArrayList<>();
    Object bprev = new Object();
    for (int c = 0; c <= 0x10FFFF; c++) {
      Character.UnicodeBlock b = Character.UnicodeBlock.of(c);
      if (b != bprev) {
        int id = b == null ? 65535 : ids.computeIfAbsent(b, k -> ids.size());
        bruns.add(String.format("(0x%X, %d)", c, id));
        bprev = b;
      }
    }
    o.append("/// `Character.UnicodeBlock.of`: (first code point, block) runs; 65535 is no block.\n");
    o.append("pub(crate) static BLOCK_RUNS: [(u32, u16); ").append(bruns.size()).append("] = [");
    o.append(String.join(", ", bruns)).append("];\n\n");
    Map<String, Integer> bnames = new TreeMap<>();
    for (Map.Entry<String, Character.UnicodeBlock> e : blocks.entrySet()) {
      Integer id = ids.get(e.getValue());
      if (id != null) bnames.put(e.getKey().toUpperCase(java.util.Locale.US), id);
    }
    o.append("/// `UnicodeBlock.forName`: every accepted name, upper-cased.\n");
    o.append("pub(crate) static BLOCK_NAMES: [(&str, u16); ").append(bnames.size()).append("] = [");
    List<String> bn = new ArrayList<>();
    for (Map.Entry<String, Integer> e : bnames.entrySet()) bn.add("(\"" + e.getKey() + "\", " + e.getValue() + ")");
    o.append(String.join(", ", bn)).append("];\n\n");
    // binary properties
    // A property this JDK's Pattern does not know is left out (the port
    // then refuses it as Java does).
    List<String> props = new ArrayList<>();
    for (String[] s : SETS) {
      Pattern p;
      try {
        p = Pattern.compile(s[1]);
      } catch (java.util.regex.PatternSyntaxException e) {
        continue;
      }
      props.add("(\"" + s[0] + "\", &[" + ranges(p) + "]),\n");
    }
    o.append("/// The binary properties and Unicode classes: (key, ranges).\n");
    o.append("pub(crate) static PROPERTIES: [(&str, &[(u32, u32)]); ").append(props.size()).append("] = [\n");
    for (String s : props) o.append(s);
    o.append("];\n");
    System.out.print(o);
  }
}
