import java.nio.ByteBuffer;
import java.nio.CharBuffer;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Random;
import java.util.TreeMap;

/**
 * Generates {@code crates/lucene-analysis/src/factory/xml_charsets.rs}: every single-byte charset
 * the JDK has, as an {@code InputStreamReader} decodes it ({@code CodingErrorAction.REPLACE}: an
 * unmappable byte is U+FFFD), for the hyphenation grammar's {@code encoding}
 * ({@code factory/xml_source.rs}). A charset is single-byte when each of the 256 bytes decodes to
 * one {@code char} and random byte strings decode byte by byte (the generator checks); the
 * multi-byte ones (CJK, ISO-2022, UTF-32, CESU-8) are left out. Each charset's 256 {@code char}s,
 * then every name and alias lowercased with its table. The mappings are the charsets' published
 * definitions, read through the JDK's public API; no JDK code is copied. The output is identical
 * under JDK 21 and JDK 25.
 *
 * <p>Usage: {@code java crates/lucene-analysis/tools/GenXmlCharsets.java >
 * crates/lucene-analysis/src/factory/xml_charsets.rs}
 */
public class GenXmlCharsets {
  /** The 256 chars {@code cs} decodes the bytes to, or null when it is not single-byte. */
  static char[] table(Charset cs) {
    CharsetDecoder d = cs.newDecoder().onMalformedInput(CodingErrorAction.REPLACE).onUnmappableCharacter(CodingErrorAction.REPLACE);
    char[] map = new char[256];
    try {
      for (int b = 0; b < 256; b++) {
        d.reset();
        CharBuffer out = d.decode(ByteBuffer.wrap(new byte[] {(byte) b}));
        if (out.length() != 1) return null;
        map[b] = out.get(0);
      }
      Random r = new Random(cs.name().hashCode());
      for (int t = 0; t < 500; t++) {
        byte[] x = new byte[1 + r.nextInt(32)];
        r.nextBytes(x);
        d.reset();
        CharBuffer out = d.decode(ByteBuffer.wrap(x));
        if (out.length() != x.length) return null;
        for (int i = 0; i < x.length; i++) if (out.get(i) != map[x[i] & 0xff]) return null;
      }
    } catch (Exception e) {
      return null;
    }
    return map;
  }

  public static void main(String[] args) {
    List<String> names = new ArrayList<>();
    List<char[]> tables = new ArrayList<>();
    TreeMap<String, Integer> aliases = new TreeMap<>();
    for (Charset cs : Charset.availableCharsets().values()) {
      char[] t = table(cs);
      if (t == null) continue;
      int id = tables.size();
      names.add(cs.name());
      tables.add(t);
      aliases.put(cs.name().toLowerCase(Locale.ROOT), id);
      for (String a : cs.aliases()) aliases.put(a.toLowerCase(Locale.ROOT), id);
    }
    StringBuilder o = new StringBuilder();
    o.append("//! The JDK's single-byte charsets, as an `InputStreamReader` decodes them\n");
    o.append("//! (an unmappable byte is U+FFFD). Generated by\n");
    o.append("//! `crates/lucene-analysis/tools/GenXmlCharsets.java`; do not edit.\n\n");
    o.append("/// Each charset's decoding of the bytes `0x00..=0xFF`.\n");
    o.append("pub(crate) static TABLES: [[u16; 256]; ").append(tables.size()).append("] = [\n");
    for (int k = 0; k < tables.size(); k++) {
      o.append("    // ").append(names.get(k)).append('\n').append("    [\n");
      char[] t = tables.get(k);
      for (int r = 0; r < 256; r += 16) {
        o.append("       ");
        for (int c = r; c < r + 16; c++) o.append(String.format(" 0x%04X,", (int) t[c]));
        o.append('\n');
      }
      o.append("    ],\n");
    }
    o.append("];\n\n");
    o.append("/// Every name and alias, lowercased (`Charset.forName` ignores case), and\n");
    o.append("/// its charset in [`TABLES`].\n");
    o.append("pub(crate) static NAMES: [(&str, u8); ").append(aliases.size()).append("] = [\n");
    StringBuilder line = new StringBuilder("   ");
    for (var e : aliases.entrySet()) {
      String l = " (\"" + e.getKey() + "\", " + e.getValue() + "),";
      if (line.length() + l.length() > 100) { o.append(line).append('\n'); line = new StringBuilder("   "); }
      line.append(l);
    }
    o.append(line).append("\n];\n");
    System.out.print(o);
  }
}
