//! Differential test against a real `Lucene99HnswVectorsFormat` segment: the
//! `.vec`/`.vemf` flat store and the `.vem`/`.vex` HNSW graph written by an
//! actual `IndexWriter` over 4000 documents and five vector fields (dense
//! FLOAT32, sparse FLOAT32, a sparse field small enough that Lucene skips
//! graph construction, BYTE, and a 5-document field). Regenerate with
//! `fixtures/src/GenVectors.java`.
//!
//! Four independent things are checked, in increasing order of how much they
//! prove:
//!
//! 1. **Metadata**: field numbers, encodings, similarity functions, counts,
//!    and per-level graph shape.
//! 2. **Vectors**: spot ordinals decoded bit-for-bit, and the sampled
//!    ordinal -> doc mapping (dense identity and the sparse
//!    `DirectMonotonicReader` path).
//! 3. **The graph itself**: per level, an order-sensitive hash over every
//!    node's neighbour list. A mis-decoded node offset, a dropped group-vint
//!    group or an off-by-one in the level index offsets all change it.
//! 4. **Search**: our searcher, run over *Lucene's own* graph, must reproduce
//!    Lucene's `KnnFloatVectorQuery` results -- the same doc ids in the same
//!    order, scores within 1e-6 (see `assert_hits_match` for why a tolerance
//!    is the only honest comparison) -- and our exhaustive scan must reproduce
//!    Lucene's brute-force top-k the same way.
//!
//! Then, separately, `rust_built_graph_recall_matches_lucene` builds a graph
//! *here* over the same vectors at the same `M`/`beamWidth`/seed and reports
//! its recall next to Lucene's on the same queries. That is the only number
//! that says the *construction* algorithm (level assignment, diversity rule,
//! entry-point descent) was ported and not merely the file format.
// Test-support code opts out of the arithmetic gate at the file boundary:
// the gate exists for values read off disk in production decode paths, not
// for a fixture builder's own index arithmetic. See
// `docs/arithmetic-gate.md`.
#![allow(clippy::arithmetic_side_effects)]

use std::cell::Cell;
use std::collections::HashMap;
use std::rc::Rc;

use lucene_codecs::field_infos::{VectorEncoding, VectorSimilarityFunction};
use lucene_codecs::hnsw::{self, HnswGraphBuilder, HnswGraphView, VectorScorer};
use lucene_codecs::hnsw_vectors::{self, HnswVectorsReader};
use lucene_codecs::vectors::{self, FlatVectorsReader};
use lucene_util::splittable_random::SplittableRandom;

fn dir() -> String {
    concat!(
        env!("CARGO_MANIFEST_DIR"),
        "/../../fixtures/data/vectors_index/"
    )
    .to_string()
}

struct Manifest {
    kv: HashMap<String, String>,
}

impl Manifest {
    fn load() -> Self {
        let text = std::fs::read_to_string(format!("{}manifest.properties", dir()))
            .expect("run fixtures generator first (GenVectors)");
        Manifest {
            kv: text
                .lines()
                .filter_map(|l| l.split_once('='))
                .map(|(k, v)| (k.to_string(), v.to_string()))
                .collect(),
        }
    }

    fn get(&self, key: &str) -> &str {
        self.kv
            .get(key)
            .unwrap_or_else(|| panic!("manifest key {key} missing"))
    }

    fn opt(&self, key: &str) -> Option<&str> {
        self.kv.get(key).map(|s| s.as_str())
    }

    fn int(&self, key: &str) -> i64 {
        self.get(key).parse().unwrap()
    }
}

fn read(name: &str) -> Vec<u8> {
    std::fs::read(format!("{}{name}", dir())).unwrap_or_else(|e| panic!("read {name}: {e}"))
}

fn segment_id(m: &Manifest) -> [u8; 16] {
    let hex = m.get("id_hex");
    let mut id = [0u8; 16];
    for (i, slot) in id.iter_mut().enumerate() {
        *slot = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).unwrap();
    }
    id
}

/// `doc:scorebits;doc:scorebits;...`
fn parse_hits(spec: &str) -> Vec<(i32, f32)> {
    if spec.is_empty() {
        return Vec::new();
    }
    spec.split(';')
        .map(|p| {
            let (d, s) = p.split_once(':').unwrap();
            (
                d.parse().unwrap(),
                f32::from_bits(s.parse::<i32>().unwrap() as u32),
            )
        })
        .collect()
}

/// Compares a top-k list against Lucene's: doc ids and their order must match
/// exactly; scores are compared with a tolerance.
///
/// The tolerance is not slack about correctness, it is the only honest way to
/// compare: Lucene ships **three** float kernels for these similarities
/// (`PanamaVectorUtilSupport`, and `DefaultVectorUtilSupport` with and without
/// `Constants.HAS_FAST_SCALAR_FMA`), and they disagree in the last ulp or two
/// because they sum in different orders and fuse differently. This fixture was
/// generated by the scalar+FMA one; a port cannot match all three, and this
/// port deliberately matches none of them exactly -- see `square_distance`'s
/// doc comment on the eight-lane split. What must match is the *ranking*.
fn assert_hits_match(got: &[(i32, f32)], want: &[(i32, f32)], what: &str) {
    let got_docs: Vec<i32> = got.iter().map(|(d, _)| *d).collect();
    let want_docs: Vec<i32> = want.iter().map(|(d, _)| *d).collect();
    assert_eq!(got_docs, want_docs, "{what}: doc ids");
    for ((_, g), (_, w)) in got.iter().zip(want) {
        assert!(
            (g - w).abs() <= 1e-6 * w.abs().max(1.0),
            "{what}: score {g} vs Lucene's {w}"
        );
    }
}

fn parse_similarity(name: &str) -> VectorSimilarityFunction {
    match name {
        "EUCLIDEAN" => VectorSimilarityFunction::Euclidean,
        "DOT_PRODUCT" => VectorSimilarityFunction::DotProduct,
        "COSINE" => VectorSimilarityFunction::Cosine,
        "MAXIMUM_INNER_PRODUCT" => VectorSimilarityFunction::MaximumInnerProduct,
        other => panic!("unknown similarity {other}"),
    }
}

struct Fixture {
    manifest: Manifest,
    vemf: Vec<u8>,
    vec: Vec<u8>,
    vem: Vec<u8>,
    vex: Vec<u8>,
    id: [u8; 16],
    suffix: String,
}

impl Fixture {
    fn load() -> Self {
        let manifest = Manifest::load();
        let id = segment_id(&manifest);
        let suffix = manifest.get("segment_suffix").to_string();
        Fixture {
            vemf: read(manifest.get("vemf_file")),
            vec: read(manifest.get("vec_file")),
            vem: read(manifest.get("vem_file")),
            vex: read(manifest.get("vex_file")),
            id,
            suffix,
            manifest,
        }
    }

    fn flat(&self) -> FlatVectorsReader<'_> {
        FlatVectorsReader::open(&self.vemf, &self.vec, &self.id, &self.suffix).unwrap()
    }

    fn hnsw(&self) -> HnswVectorsReader<'_> {
        HnswVectorsReader::open(&self.vem, &self.vex, &self.id, &self.suffix).unwrap()
    }
}

#[test]
fn flat_metadata_matches_lucene() {
    let f = Fixture::load();
    let m = &f.manifest;
    let reader = f.flat();
    assert_eq!(reader.fields().len(), m.int("field_count") as usize);
    for i in 0..m.int("field_count") {
        let key = format!("f{i}");
        let number = m.int(&format!("{key}.number")) as i32;
        let entry = reader
            .field(number)
            .unwrap_or_else(|| panic!("field {number} missing from .vemf"));
        assert_eq!(entry.dimension, m.int(&format!("{key}.dim")) as i32);
        assert_eq!(entry.size, m.int(&format!("{key}.count")) as i32);
        assert_eq!(
            entry.similarity,
            parse_similarity(m.get(&format!("{key}.similarity")))
        );
        let expected_encoding = match m.get(&format!("{key}.encoding")) {
            "FLOAT32" => VectorEncoding::Float32,
            "BYTE" => VectorEncoding::Byte,
            other => panic!("unexpected encoding {other}"),
        };
        assert_eq!(entry.encoding, expected_encoding);
        // A field every document has needs no ord->doc structures at all.
        let dense = entry.size == m.int("max_doc") as i32;
        assert_eq!(entry.ord_to_doc.is_dense(), dense, "{key} density");
    }
}

#[test]
fn vectors_and_ord_to_doc_match_lucene() {
    let f = Fixture::load();
    let m = &f.manifest;
    let reader = f.flat();
    for i in 0..m.int("field_count") {
        let key = format!("f{i}");
        let number = m.int(&format!("{key}.number")) as i32;
        let dim = m.int(&format!("{key}.dim")) as usize;
        let float = m.get(&format!("{key}.encoding")) == "FLOAT32";

        // Sampled ordinal -> doc, covering both the dense identity mapping and
        // the sparse `DirectMonotonicReader`.
        let ord_to_doc = m.get(&format!("{key}.ord_to_doc"));
        for pair in ord_to_doc.split(';') {
            let (ord, doc) = pair.split_once(':').unwrap();
            let (ord, doc): (i32, i32) = (ord.parse().unwrap(), doc.parse().unwrap());
            let got = if float {
                reader.float_vector_values(number).unwrap().ord_to_doc(ord)
            } else {
                reader.byte_vector_values(number).unwrap().ord_to_doc(ord)
            };
            assert_eq!(got.unwrap(), doc, "{key} ord {ord}");
        }

        // ... and the inverse direction, through the IndexedDISI bitset.
        if float {
            let values = reader.float_vector_values(number).unwrap();
            let mut cursor = values.doc_to_ord().unwrap();
            for pair in ord_to_doc.split(';') {
                let (ord, doc) = pair.split_once(':').unwrap();
                let (ord, doc): (i32, i32) = (ord.parse().unwrap(), doc.parse().unwrap());
                assert_eq!(cursor.ordinal(doc).unwrap(), Some(ord), "{key} doc {doc}");
            }
        }

        for (mkey, spec) in m.kv.iter() {
            let prefix = format!("{key}.spot.");
            let Some(ord) = mkey.strip_prefix(&prefix) else {
                continue;
            };
            let ord: i32 = ord.parse().unwrap();
            let expected: Vec<i32> = spec.split(',').map(|s| s.parse().unwrap()).collect();
            assert_eq!(expected.len(), dim);
            if float {
                let values = reader.float_vector_values(number).unwrap();
                let got = values.vector(ord).unwrap();
                let got_bits: Vec<i32> = got.iter().map(|v| v.to_bits() as i32).collect();
                assert_eq!(got_bits, expected, "{key} ord {ord}");
            } else {
                let values = reader.byte_vector_values(number).unwrap();
                let got = values.vector(ord).unwrap();
                let got_signed: Vec<i32> = got.iter().map(|b| *b as i8 as i32).collect();
                assert_eq!(got_signed, expected, "{key} ord {ord}");
            }
        }
    }
}

#[test]
fn graph_matches_lucene_arc_for_arc() {
    let f = Fixture::load();
    let m = &f.manifest;
    let reader = f.hnsw();
    assert_eq!(reader.version(), hnsw_vectors::VERSION_CURRENT);
    for i in 0..m.int("field_count") {
        let key = format!("f{i}");
        let number = m.int(&format!("{key}.number")) as i32;
        let num_levels = m.int(&format!("{key}.num_levels")) as i32;
        let entry = reader.field(number).unwrap();
        assert_eq!(entry.num_levels, num_levels, "{key} numLevels");
        let graph = reader.graph(number).unwrap();
        if num_levels == 0 {
            // Lucene skipped graph construction for this field; `.vem` records
            // numLevels = 0 and a zero-length `.vex` region.
            assert!(graph.is_none(), "{key} should have no graph");
            assert_eq!(entry.vector_index_length, 0);
            continue;
        }
        let graph = graph.unwrap();
        assert_eq!(graph.max_conn(), m.int(&format!("{key}.max_conn")) as i32);
        assert_eq!(
            graph.entry_node(),
            m.int(&format!("{key}.entry_node")) as i32
        );

        let mut neighbors = Vec::new();
        for level in 0..num_levels {
            let lk = format!("{key}.level{level}");
            let nodes = graph.sorted_nodes_on_level(level).unwrap();
            assert_eq!(
                nodes.len(),
                m.int(&format!("{lk}.node_count")) as usize,
                "{lk} node count"
            );
            if level > 0 {
                let expected: Vec<i32> = m
                    .get(&format!("{lk}.nodes"))
                    .split(',')
                    .map(|s| s.parse().unwrap())
                    .collect();
                assert_eq!(nodes, expected, "{lk} node ids");
            }
            let mut arc_total = 0i64;
            let mut hash = 0i64;
            let mut samples: HashMap<i32, Vec<i32>> = HashMap::new();
            for &node in &nodes {
                graph.neighbors_into(level, node, &mut neighbors).unwrap();
                hash = hash.wrapping_mul(31).wrapping_add(node as i64);
                for &n in &neighbors {
                    hash = hash.wrapping_mul(31).wrapping_add(n as i64);
                    arc_total += 1;
                }
                samples.insert(node, neighbors.clone());
            }
            // The readable half of the check, so a hash mismatch has something
            // to look at before the hash assertion fires.
            for entry in m.get(&format!("{lk}.sample")).split(';') {
                let (node, nbrs) = entry.split_once(':').unwrap();
                let node: i32 = node.parse().unwrap();
                let expected: Vec<i32> = if nbrs.is_empty() {
                    Vec::new()
                } else {
                    nbrs.split(',').map(|s| s.parse().unwrap()).collect()
                };
                assert_eq!(samples[&node], expected, "{lk} node {node} neighbours");
            }
            assert_eq!(arc_total, m.int(&format!("{lk}.arc_total")), "{lk} arcs");
            assert_eq!(hash, m.int(&format!("{lk}.arc_hash")), "{lk} arc hash");
        }
    }
}

/// The search half: our beam search over Lucene's own graph must return what
/// `KnnFloatVectorQuery`/`KnnByteVectorQuery` returned, and our exhaustive scan
/// what Lucene's brute force returned -- the same doc ids in the same order,
/// with scores within 1e-6 (see [`assert_hits_match`]).
#[test]
fn search_over_lucene_graph_reproduces_lucene_results() {
    let f = Fixture::load();
    let m = &f.manifest;
    let flat = f.flat();
    let hnsw_reader = f.hnsw();
    let k = 10usize;
    let mut checked = 0;
    for i in 0..m.int("field_count") {
        let key = format!("f{i}");
        let Some(count) = m.opt(&format!("q.{key}.count")) else {
            continue;
        };
        let number = m.int(&format!("{key}.number")) as i32;
        let float = m.get(&format!("{key}.encoding")) == "FLOAT32";
        let graph = hnsw_reader.graph(number).unwrap();
        for q in 0..count.parse::<i32>().unwrap() {
            let qk = format!("q.{key}.{q}");
            let expected_hnsw = parse_hits(m.get(&format!("{qk}.hnsw")));
            let expected_exact = parse_hits(m.get(&format!("{qk}.exact")));
            let (got_hnsw, got_exact) = if float {
                let values = flat.float_vector_values(number).unwrap();
                let query: Vec<f32> = m
                    .get(&format!("{qk}.vec"))
                    .split(',')
                    .map(|s| f32::from_bits(s.parse::<i32>().unwrap() as u32))
                    .collect();
                let mut scorer = values.scorer(&query).unwrap();
                let (hits, _) = hnsw_vectors::search(
                    &mut scorer,
                    graph.as_ref(),
                    k,
                    u64::MAX,
                    hnsw_vectors::SearchOptions::default(),
                )
                .unwrap();
                (
                    hits.into_iter()
                        .map(|(ord, s)| (values.ord_to_doc(ord).unwrap(), s))
                        .collect::<Vec<_>>(),
                    values.exhaustive_search(&query, k).unwrap(),
                )
            } else {
                let values = flat.byte_vector_values(number).unwrap();
                let query: Vec<u8> = m
                    .get(&format!("{qk}.vec"))
                    .split(',')
                    .map(|s| s.parse::<i32>().unwrap() as i8 as u8)
                    .collect();
                let mut scorer = values.scorer(&query).unwrap();
                let (hits, _) = hnsw_vectors::search(
                    &mut scorer,
                    graph.as_ref(),
                    k,
                    u64::MAX,
                    hnsw_vectors::SearchOptions::default(),
                )
                .unwrap();
                (
                    hits.into_iter()
                        .map(|(ord, s)| (values.ord_to_doc(ord).unwrap(), s))
                        .collect::<Vec<_>>(),
                    values.exhaustive_search(&query, k).unwrap(),
                )
            };
            assert_hits_match(&got_exact, &expected_exact, &format!("{qk} exact"));
            assert_hits_match(&got_hnsw, &expected_hnsw, &format!("{qk} hnsw"));
            checked += 1;
        }
    }
    assert!(checked >= 60, "expected several fields' worth of queries");
}

/// The construction half. Builds a graph here, over the fixture's own
/// vectors, at Lucene's `M`/`beamWidth`/seed -- then measures recall against
/// the exact top-k Lucene recorded, and prints it beside Lucene's own recall
/// on the same queries.
///
/// A recall number with no Java baseline proves nothing: a broken diversity
/// rule still gives high recall on easy data, and a *correct* implementation
/// still gives mediocre recall on 16-dimension uniform noise. The assertion
/// is therefore relative -- we must not be materially worse than Lucene -- not
/// an absolute floor.
#[test]
fn rust_built_graph_recall_matches_lucene() {
    let f = Fixture::load();
    let m = &f.manifest;
    let flat = f.flat();
    let key = "f0";
    let number = m.int(&format!("{key}.number")) as i32;
    let values = flat.float_vector_values(number).unwrap();
    let k = 10usize;

    let max_conn = m.int("default_max_conn") as i32;
    let beam_width = m.int("default_beam_width") as i32;
    let builder = HnswGraphBuilder::new(
        values.ord_scorer(),
        max_conn,
        beam_width,
        hnsw::DEFAULT_RAND_SEED,
    )
    .unwrap();
    let graph = builder.build(values.size()).unwrap();

    // The graph's *shape* should match Lucene's, because the level draws come
    // from the same bit-exact `SplittableRandom` stream.
    assert_eq!(
        graph.num_levels(),
        m.int(&format!("{key}.num_levels")) as i32,
        "level count"
    );
    assert_eq!(
        graph.entry_node(),
        m.int(&format!("{key}.entry_node")) as i32,
        "entry node"
    );
    for level in 0..graph.num_levels() {
        assert_eq!(
            graph.sorted_nodes_on_level(level).unwrap().len(),
            m.int(&format!("{key}.level{level}.node_count")) as usize,
            "level {level} node count"
        );
    }

    // The discriminating assertion. Level counts and the entry node above are
    // decided entirely by the `SplittableRandom` port, so they survive a wrong
    // diversity rule intact; and recall within a couple of points is not
    // sensitive to a `>` vs `>=` slip in `diversity_check`, a flipped sort
    // direction in a `NeighborArray`, or a dropped shift in
    // `NeighborArray::sort`. Comparing the two graphs' neighbour sets *is*.
    //
    // Sensitivity was checked by mutation, not assumed. Weakening
    // `diversity_check` so it accepts candidates it should prune takes this
    // agreement from 4273/4273 to **1/4273** -- while recall on this fixture
    // goes *up*, to 0.9350 against Lucene's 0.9250. So the recall assertion
    // below would have passed a broken diversity rule; this one would not.
    // That is the whole reason it exists.
    let lucene_graph = f.hnsw().graph(number).unwrap().unwrap();
    assert_eq!(lucene_graph.size(), graph.size());
    let mut ours = Vec::new();
    let mut theirs = Vec::new();
    let mut identical_total = 0usize;
    let mut node_total = 0usize;
    for level in 0..graph.num_levels() {
        let nodes = graph.sorted_nodes_on_level(level).unwrap();
        assert_eq!(nodes, lucene_graph.sorted_nodes_on_level(level).unwrap());
        let mut identical = 0usize;
        for &node in &nodes {
            graph.neighbors_into(level, node, &mut ours).unwrap();
            ours.sort_unstable();
            ours.dedup();
            lucene_graph
                .neighbors_into(level, node, &mut theirs)
                .unwrap();
            if ours == theirs {
                identical += 1;
            }
        }
        println!(
            "level {level}: {identical}/{} nodes have a neighbour set identical to Lucene's",
            nodes.len()
        );
        identical_total += identical;
        node_total += nodes.len();
    }
    let agreement = identical_total as f64 / node_total as f64;
    println!("graph agreement with Lucene: {identical_total}/{node_total} ({agreement:.4})");
    // Observed: 1.0000 -- every node on every level. The floor is below that
    // because exact agreement is not guaranteed in principle: the two engines'
    // float kernels differ by ~4e-8 (batch report, finding 15), which can
    // reorder two near-equal candidates and change which one the diversity rule
    // keeps. It is asserted across all levels together rather than per level so
    // a single flip on the 14-node top level cannot fail the build.
    assert!(
        agreement >= 0.95,
        "only {agreement:.4} of nodes match Lucene's neighbour set"
    );

    let queries: i32 = m.get(&format!("q.{key}.count")).parse().unwrap();
    let mut rust_hits = 0usize;
    let mut java_hits = 0usize;
    let mut total = 0usize;
    // How many distance computations the graph walk actually costs, versus the
    // `size()` an exhaustive scan costs. This is the number the whole format
    // exists to reduce, so it is asserted rather than only printed.
    let scored = Rc::new(Cell::new(0u64));
    for q in 0..queries {
        let qk = format!("q.{key}.{q}");
        let query: Vec<f32> = m
            .get(&format!("{qk}.vec"))
            .split(',')
            .map(|s| f32::from_bits(s.parse::<i32>().unwrap() as u32))
            .collect();
        let exact: Vec<i32> = parse_hits(m.get(&format!("{qk}.exact")))
            .into_iter()
            .map(|(d, _)| d)
            .collect();
        let java: Vec<i32> = parse_hits(m.get(&format!("{qk}.hnsw")))
            .into_iter()
            .map(|(d, _)| d)
            .collect();
        let mut scorer = CountingScorer {
            inner: values.scorer(&query).unwrap(),
            scored: scored.clone(),
        };
        let (ours, _) = hnsw_vectors::search(
            &mut scorer,
            Some(&graph),
            k,
            u64::MAX,
            hnsw_vectors::SearchOptions::default(),
        )
        .unwrap();
        for (ord, _) in &ours {
            if exact.contains(&values.ord_to_doc(*ord).unwrap()) {
                rust_hits += 1;
            }
        }
        for d in &java {
            if exact.contains(d) {
                java_hits += 1;
            }
        }
        total += exact.len();
    }
    let rust_recall = rust_hits as f64 / total as f64;
    let java_recall = java_hits as f64 / total as f64;
    let per_query = scored.get() as f64 / queries as f64;
    println!(
        "recall@{k} over {} vectors, M={max_conn} beamWidth={beam_width}: \
         rust-built graph {rust_recall:.4}, Lucene-built graph {java_recall:.4}; \
         {per_query:.0} distance computations/query vs {} exhaustive ({:.0}x fewer)",
        values.size(),
        values.size(),
        values.size() as f64 / per_query
    );
    assert!(
        per_query < values.size() as f64 / 4.0,
        "graph search scored {per_query} of {} vectors -- that is not a graph walk",
        values.size()
    );
    assert!(
        rust_recall >= java_recall - 0.02,
        "rust recall {rust_recall:.4} is materially below Lucene's {java_recall:.4}"
    );
}

/// A Rust-built graph, serialized here and read back through this port's own
/// `.vex` decoder, must be arc-for-arc what the in-memory graph held. This is
/// the only check that covers [`hnsw_vectors::write_hnsw_vectors`]'s
/// neighbour sorting, de-duplication and group-vint framing over a graph big
/// enough to have several levels.
#[test]
fn rust_written_graph_round_trips() {
    let f = Fixture::load();
    let m = &f.manifest;
    let flat = f.flat();
    let number = m.int("f1.number") as i32;
    let values = flat.float_vector_values(number).unwrap();
    let builder =
        HnswGraphBuilder::new(values.ord_scorer(), 16, 100, hnsw::DEFAULT_RAND_SEED).unwrap();
    let graph = builder.build(values.size()).unwrap();

    let (vex, vem) = hnsw_vectors::write_hnsw_vectors(
        &[hnsw_vectors::HnswVectorsField {
            field_number: number,
            encoding: VectorEncoding::Float32,
            similarity: values.similarity(),
            dimension: values.dimension() as i32,
            count: values.size(),
            graph: Some(&graph),
            m: 16,
        }],
        &f.id,
        &f.suffix,
    )
    .unwrap();
    let reader = HnswVectorsReader::open(&vem, &vex, &f.id, &f.suffix).unwrap();
    let off = reader.graph(number).unwrap().unwrap();
    assert_eq!(off.num_levels(), graph.num_levels());
    assert_eq!(off.entry_node(), graph.entry_node());
    assert_eq!(off.size(), graph.size());
    let mut want = Vec::new();
    let mut got = Vec::new();
    for level in 0..graph.num_levels() {
        assert_eq!(
            off.sorted_nodes_on_level(level).unwrap(),
            graph.sorted_nodes_on_level(level).unwrap()
        );
        for node in graph.sorted_nodes_on_level(level).unwrap() {
            graph.neighbors_into(level, node, &mut want).unwrap();
            want.sort_unstable();
            want.dedup();
            off.neighbors_into(level, node, &mut got).unwrap();
            assert_eq!(got, want, "level {level} node {node}");
        }
    }
}

/// The level distribution is `(int)(-ln(U) * ml)` over
/// `java.util.SplittableRandom(42)`. If that stream drifts, every graph this
/// port builds has a different shape than Lucene's for a reason that would
/// look like an algorithm difference.
#[test]
fn splittable_random_matches_java() {
    let m = Manifest::load();
    let expected: Vec<i64> = m
        .get("splittable_random_42")
        .split(',')
        .map(|s| s.parse().unwrap())
        .collect();
    let mut random = SplittableRandom::new(hnsw::DEFAULT_RAND_SEED);
    for (i, want) in expected.iter().enumerate() {
        let got = random.next_double().to_bits() as i64;
        assert_eq!(got, *want, "SplittableRandom(42).nextDouble() #{i}");
    }
}

/// Lucene skips graph construction for a field whose expected visited-node
/// count already covers the field; the fixture has two such fields, and the
/// constants that decide it must agree.
#[test]
fn tiny_segment_threshold_matches_lucene() {
    let m = Manifest::load();
    assert_eq!(
        hnsw::HNSW_GRAPH_THRESHOLD,
        m.int("hnsw_graph_threshold") as i32
    );
    assert_eq!(hnsw::DEFAULT_MAX_CONN, m.int("default_max_conn") as i32);
    assert_eq!(hnsw::DEFAULT_BEAM_WIDTH, m.int("default_beam_width") as i32);
    for i in 0..m.int("field_count") {
        let key = format!("f{i}");
        let count = m.int(&format!("{key}.count")) as i32;
        let has_graph = m.int(&format!("{key}.num_levels")) > 0;
        assert_eq!(
            hnsw::should_create_graph(hnsw::HNSW_GRAPH_THRESHOLD, count),
            has_graph,
            "{key}: {count} vectors"
        );
    }
}

/// The flat writer's bytes must be readable by this port's reader over a
/// non-trivial mixture (dense + sparse + byte), and every vector and doc id
/// must survive. The *cross-engine* half of this -- real Lucene reading these
/// bytes -- is `fixtures/src/VerifyVectors.java`, wired into
/// `scripts/verify-write-path.sh`.
#[test]
fn flat_writer_round_trips_dense_sparse_and_byte() {
    let id = *b"rustwrittenvec01";
    let max_doc = 300i32;
    let dense: Vec<f32> = (0..max_doc * 4).map(|i| i as f32 * 0.25 - 3.0).collect();
    let sparse_docs: Vec<i32> = (0..max_doc).filter(|d| d % 7 == 2).collect();
    let sparse: Vec<f32> = (0..sparse_docs.len() * 3)
        .map(|i| (i as f32).sin())
        .collect();
    let byte_docs: Vec<i32> = (0..max_doc).filter(|d| d % 2 == 0).collect();
    let bytes: Vec<u8> = (0..byte_docs.len() * 5).map(|i| (i % 256) as u8).collect();

    let fields = vec![
        vectors::FlatVectorsField {
            field_number: 0,
            similarity: VectorSimilarityFunction::Euclidean,
            dimension: 4,
            docs: (0..max_doc).collect(),
            values: vectors::FieldVectorData::Float32(dense.clone()),
        },
        vectors::FlatVectorsField {
            field_number: 3,
            similarity: VectorSimilarityFunction::Cosine,
            dimension: 3,
            docs: sparse_docs.clone(),
            values: vectors::FieldVectorData::Float32(sparse.clone()),
        },
        vectors::FlatVectorsField {
            field_number: 5,
            similarity: VectorSimilarityFunction::DotProduct,
            dimension: 5,
            docs: byte_docs.clone(),
            values: vectors::FieldVectorData::Byte(bytes.clone()),
        },
    ];
    let (vec_bytes, vemf_bytes) =
        vectors::write_flat_vectors(&fields, max_doc, &id, "Suffix_0").unwrap();
    let reader = FlatVectorsReader::open(&vemf_bytes, &vec_bytes, &id, "Suffix_0").unwrap();

    let d = reader.float_vector_values(0).unwrap();
    assert!(reader.field(0).unwrap().ord_to_doc.is_dense());
    for ord in 0..d.size() {
        assert_eq!(d.ord_to_doc(ord).unwrap(), ord);
        assert_eq!(d.vector(ord).unwrap(), &dense[ord as usize * 4..][..4]);
    }

    let s = reader.float_vector_values(3).unwrap();
    assert!(!reader.field(3).unwrap().ord_to_doc.is_dense());
    let mut cursor = s.doc_to_ord().unwrap();
    for (ord, doc) in sparse_docs.iter().enumerate() {
        assert_eq!(s.ord_to_doc(ord as i32).unwrap(), *doc);
        assert_eq!(cursor.ordinal(*doc).unwrap(), Some(ord as i32));
        assert_eq!(s.vector(ord as i32).unwrap(), &sparse[ord * 3..][..3]);
    }

    let b = reader.byte_vector_values(5).unwrap();
    for (ord, doc) in byte_docs.iter().enumerate() {
        assert_eq!(b.ord_to_doc(ord as i32).unwrap(), *doc);
        assert_eq!(b.vector(ord as i32).unwrap(), &bytes[ord * 5..][..5]);
    }

    // `alignOutput`: FLOAT32 regions land on a 64-byte boundary, BYTE on 4.
    assert_eq!(reader.field(0).unwrap().vector_data_offset % 64, 0);
    assert_eq!(reader.field(3).unwrap().vector_data_offset % 64, 0);
    assert_eq!(reader.field(5).unwrap().vector_data_offset % 4, 0);
}

/// Wraps a scorer to count distance computations -- the quantity the whole
/// graph exists to reduce.
struct CountingScorer<S> {
    inner: S,
    scored: Rc<Cell<u64>>,
}

impl<S: VectorScorer> VectorScorer for CountingScorer<S> {
    fn score(&mut self, node: i32) -> lucene_codecs::vectors::Result<f32> {
        self.scored.set(self.scored.get() + 1);
        self.inner.score(node)
    }

    fn max_ord(&self) -> i32 {
        self.inner.max_ord()
    }
}
