import org.apache.lucene.document.Document;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.StringField;
import org.apache.lucene.document.TextField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.FieldInfos;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.MultiTerms;
import org.apache.lucene.index.NoMergePolicy;
import org.apache.lucene.index.PostingsEnum;
import org.apache.lucene.index.Term;
import org.apache.lucene.index.Terms;
import org.apache.lucene.index.TermsEnum;
import org.apache.lucene.search.DocIdSetIterator;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import org.apache.lucene.util.BytesRef;
import org.apache.lucene.util.Version;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * {@code multi_terms/}: ground truth for {@code crates/lucene-search/src/multi_terms.rs} --
 * {@code MultiTerms.getTerms(reader, field)}, its {@code MultiTermsEnum} (every term, {@code
 * docFreq}, {@code totalTermFreq}, {@code seekCeil}) and {@code MultiPostingsEnum} ({@code
 * nextDoc}/{@code freq}, {@code advance}), and the indexed field names ({@code MultiFields}).
 *
 * <p>Four segments, each its own commit: a text field {@code body} (freqs) in all, a {@code
 * StringField} {@code tag} (docs only) in all but the third, and a document deleted from the
 * first -- postings do not filter deletions, and neither do the statistics.
 */
public class GenMultiTerms {
  static final String[][][] SEGMENTS = {
    {{"the quick fox", "red"}, {"the lazy dog dog", "blue"}, {"quick quick quick", "red"}},
    {{"a fox and a dog", "green"}, {"zebra", "red"}},
    {{"the end", null}, {"fox fox", null}},
    {{"lazy zebra", "blue"}, {"the the the the", "amber"}},
  };

  public static void main(String[] args) throws Exception {
    Path out = Path.of(args[0]).resolve("multi_terms");
    Path indexDir = out.resolve("index");
    if (Files.exists(indexDir)) {
      try (var files = Files.list(indexDir)) {
        for (Path f : (Iterable<Path>) files::iterator) Files.delete(f);
      }
    }
    Files.createDirectories(indexDir);
    try (Directory d = FSDirectory.open(indexDir)) {
      IndexWriterConfig cfg = new IndexWriterConfig();
      cfg.setMergePolicy(NoMergePolicy.INSTANCE);
      cfg.setUseCompoundFile(false);
      try (IndexWriter w = new IndexWriter(d, cfg)) {
        int id = 0;
        for (String[][] segment : SEGMENTS) {
          for (String[] doc : segment) {
            Document document = new Document();
            document.add(new StringField("id", "d" + id++, Field.Store.YES));
            document.add(new TextField("body", doc[0], Field.Store.NO));
            if (doc[1] != null) document.add(new StringField("tag", doc[1], Field.Store.NO));
            w.addDocument(document);
          }
          w.commit();
        }
        w.deleteDocuments(new Term("id", "d1"));
        w.commit();
      }
      StringBuilder sb = new StringBuilder();
      sb.append("# Generated by fixtures/src/GenMultiTerms.java against Lucene ")
          .append(Version.LATEST)
          .append('\n');
      try (DirectoryReader r = DirectoryReader.open(d)) {
        List<String> fields = new ArrayList<>(FieldInfos.getIndexedFields(r));
        java.util.Collections.sort(fields);
        sb.append("fields=").append(String.join(",", fields)).append('\n');
        for (String field : new String[] {"body", "tag", "id", "absent"}) {
          Terms terms = MultiTerms.getTerms(r, field);
          String p = field + ".";
          if (terms == null) {
            sb.append(p).append("terms=null\n");
            continue;
          }
          sb.append(p).append("sum_total_term_freq=").append(terms.getSumTotalTermFreq()).append('\n');
          sb.append(p).append("sum_doc_freq=").append(terms.getSumDocFreq()).append('\n');
          sb.append(p).append("doc_count=").append(terms.getDocCount()).append('\n');
          sb.append(p).append("min=").append(terms.getMin().utf8ToString()).append('\n');
          sb.append(p).append("max=").append(terms.getMax().utf8ToString()).append('\n');
          TermsEnum te = terms.iterator();
          List<String> all = new ArrayList<>();
          BytesRef t;
          while ((t = te.next()) != null) {
            StringBuilder e = new StringBuilder();
            e.append(t.utf8ToString()).append(':').append(te.docFreq()).append(':')
                .append(te.totalTermFreq()).append(':');
            PostingsEnum pe = te.postings(null, PostingsEnum.FREQS);
            List<String> docs = new ArrayList<>();
            int doc;
            while ((doc = pe.nextDoc()) != DocIdSetIterator.NO_MORE_DOCS) {
              docs.add(doc + "/" + pe.freq());
            }
            e.append(String.join(" ", docs));
            all.add(e.toString());
          }
          sb.append(p).append("terms=").append(String.join(",", all)).append('\n');
          List<String> seeks = new ArrayList<>();
          for (String target : new String[] {"", "a", "fox", "fp", "lazz", "the", "zz", "blue", "c"}) {
            TermsEnum s = terms.iterator();
            TermsEnum.SeekStatus status = s.seekCeil(new BytesRef(target));
            seeks.add(
                target + ">" + status + ">" + (status == TermsEnum.SeekStatus.END
                    ? "" : s.term().utf8ToString() + "/" + s.docFreq()));
          }
          sb.append(p).append("seek_ceil=").append(String.join(",", seeks)).append('\n');
        }
        // `advance` over the postings of body:fox, which spans three segments.
        TermsEnum te = MultiTerms.getTerms(r, "body").iterator();
        te.seekExact(new BytesRef("fox"));
        List<String> adv = new ArrayList<>();
        for (int target : new int[] {1, 4, 5, 8, 20}) {
          PostingsEnum pe = te.postings(null, PostingsEnum.FREQS);
          int doc = pe.advance(target);
          adv.add(target + ">" + (doc == DocIdSetIterator.NO_MORE_DOCS ? "end" : doc + "/" + pe.freq()));
        }
        sb.append("body.fox.advance=").append(String.join(",", adv)).append('\n');
      }
      Files.writeString(out.resolve("manifest.properties"), sb.toString(), StandardCharsets.UTF_8);
    }
  }
}
