import org.apache.lucene.codecs.Codec;
import org.apache.lucene.document.Document;
import org.apache.lucene.document.LongPoint;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.StoredField;
import org.apache.lucene.document.StringField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.FilterMergePolicy;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.KeepOnlyLastCommitDeletionPolicy;
import org.apache.lucene.index.PersistentSnapshotDeletionPolicy;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.LogByteSizeMergePolicy;
import org.apache.lucene.index.LogDocMergePolicy;
import org.apache.lucene.index.LogMergePolicy;
import org.apache.lucene.index.MergePolicy;
import org.apache.lucene.index.MergeTrigger;
import org.apache.lucene.index.IndexCommit;
import org.apache.lucene.index.NoDeletionPolicy;
import org.apache.lucene.index.NoMergePolicy;
import org.apache.lucene.index.OneMergeWrappingMergePolicy;
import org.apache.lucene.index.SegmentCommitInfo;
import org.apache.lucene.index.SegmentInfo;
import org.apache.lucene.index.SegmentInfos;
import org.apache.lucene.index.SerialMergeScheduler;
import org.apache.lucene.index.Term;
import org.apache.lucene.index.LeafReaderContext;
import org.apache.lucene.index.TemporalMergePolicy;
import org.apache.lucene.index.TieredMergePolicy;
import org.apache.lucene.store.ByteBuffersDirectory;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import org.apache.lucene.store.IOContext;
import org.apache.lucene.store.IndexInput;
import org.apache.lucene.store.IndexOutput;
import org.apache.lucene.util.InfoStream;
import org.apache.lucene.util.StringHelper;
import org.apache.lucene.util.Version;

import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Cross-engine ground truth for the pluggable merge policies of {@code
 * crates/lucene-index/src/merge_policy/}: {@link LogByteSizeMergePolicy}, {@link
 * LogDocMergePolicy}, {@link TemporalMergePolicy}, {@link FilterMergePolicy}, {@link
 * OneMergeWrappingMergePolicy} and {@link TieredMergePolicy} through the {@code MergePolicy}
 * entry points {@code GenMergePolicy} does not cover ({@code findFullFlushMerges}, {@code
 * useCompoundFile}, {@code segmentsToMerge} "original" flags, a running forced merge).
 *
 * <p>Two outputs:
 *
 * <ul>
 *   <li>{@code merge_policies/merge_policies.manifest.properties}: a table of {@code (policy,
 *       entry point, segments, merging set, segmentsToMerge) -> merges} decided by real Lucene
 *       over {@link SegmentCommitInfo}s whose {@code sizeInBytes()} is real (one file of the
 *       stated length each), exactly as {@code GenMergePolicy} builds them. Deterministic.
 *   <li>{@code merge_policies/temporal_index/}: a real index, one segment per flush, each holding
 *       {@code LongPoint("ts")} values of one time window (some compound), and the merges {@link
 *       TemporalMergePolicy} picks for it reading the date ranges out of the segments' own points
 *       -- the Rust test reads the same segments through its own points reader.
 * </ul>
 *
 * <p>{@code TemporalMergePolicy} reads the clock. Every timestamp here is either far in the future
 * (age 0: the base window) or decades in the past (the window grows to its cap), so the answer does
 * not depend on when this runs. Its forced entry points iterate an identity {@code HashMap}; the
 * scenarios keep each window within {@code maxThreshold} or give distinct delete ratios, so the
 * merged groups do not depend on that order either, and the forced groups are printed sorted.
 */
public class GenMergePolicies {

  private record Seg(String name, int maxDoc, int delCount, long bytes, boolean cfs) {}

  private record Scenario(
      String name,
      String policy,
      String op,
      List<Seg> segments,
      Set<String> merging,
      Map<String, Boolean> toMerge,
      Map<String, long[]> ranges) {}

  // Far future (2200-01-01) and far past (1975-01-01), in milliseconds.
  static final long FUTURE = 7_258_118_400_000L;
  static final long PAST = 157_766_400_000L;
  static final long HOUR = 3_600_000L;

  public static void main(String[] args) throws Exception {
    Path out = Path.of(args[0]).resolve("merge_policies");
    Files.createDirectories(out);

    List<Scenario> scenarios = scenarios();
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
        .append(Version.LATEST)
        .append('\n');
    sb.append("# Ground truth for crates/lucene-index/src/merge_policy/{log,temporal,filter,api}.rs.\n");
    sb.append("# policy = kind;key=value;...   op = findMerges | findFullFlushMerges |\n");
    sb.append("#   findForcedMerges:N | findForcedDeletesMerges | useCompoundFile:SEG\n");
    sb.append("# segments = name:maxDoc:delCount:bytes:cfs;...  merging = name,...\n");
    sb.append("# toMerge = name:original,...   ranges = name:minMs:maxMs;...\n");
    sb.append("# expected = null | (empty: an empty specification) | group|group  or true/false\n");
    sb.append("scenarios=").append(scenarios.size()).append('\n');
    for (int i = 0; i < scenarios.size(); i++) {
      Scenario s = scenarios.get(i);
      String p = "scenario." + i + ".";
      sb.append(p).append("name=").append(s.name).append('\n');
      sb.append(p).append("policy=").append(s.policy).append('\n');
      sb.append(p).append("op=").append(s.op).append('\n');
      List<String> segs = new ArrayList<>();
      for (Seg seg : s.segments) {
        segs.add(
            seg.name + ":" + seg.maxDoc + ":" + seg.delCount + ":" + seg.bytes + ":" + seg.cfs);
      }
      sb.append(p).append("segments=").append(String.join(";", segs)).append('\n');
      List<String> merging = new ArrayList<>(s.merging);
      Collections.sort(merging);
      sb.append(p).append("merging=").append(String.join(",", merging)).append('\n');
      List<String> toMerge = new ArrayList<>();
      if (s.toMerge != null) {
        for (Map.Entry<String, Boolean> e : s.toMerge.entrySet()) {
          toMerge.add(e.getKey() + ":" + e.getValue());
        }
      }
      sb.append(p).append("toMerge=").append(String.join(",", toMerge)).append('\n');
      List<String> ranges = new ArrayList<>();
      if (s.ranges != null) {
        for (Map.Entry<String, long[]> e : s.ranges.entrySet()) {
          ranges.add(e.getKey() + ":" + e.getValue()[0] + ":" + e.getValue()[1]);
        }
      }
      sb.append(p).append("ranges=").append(String.join(";", ranges)).append('\n');
      sb.append(p).append("expected=").append(run(s)).append('\n');
    }
    Files.writeString(
        out.resolve("merge_policies.manifest.properties"), sb.toString(), StandardCharsets.UTF_8);

    temporalIndex(out.resolve("temporal_index"));
    snapshotIndex(out);
    writerRuns(out);
    writerDeletes(out);
    commitsIndex(out);
  }

  // ------------------------------------------------- policies inside a writer

  static String leafDocs(IndexWriter w) throws IOException {
    List<String> l = new ArrayList<>();
    try (DirectoryReader r = DirectoryReader.open(w)) {
      for (LeafReaderContext ctx : r.leaves()) l.add(Integer.toString(ctx.reader().maxDoc()));
    }
    return String.join(",", l);
  }

  /**
   * {@code merge_policies/writer_runs.properties}: a real {@link IndexWriter} (serial merges, no
   * compound files) under {@code LogDocMergePolicy}, one commit per batch of {@code 1 + i % 4}
   * documents, then {@code forceMerge(2)} and {@code forceMerge(1)}: every segment's {@code maxDoc},
   * in order, after each step. Doc counts only, so the answer does not depend on how either engine
   * sizes its files.
   */
  static void writerRuns(Path out) throws Exception {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
        .append(Version.LATEST)
        .append('\n');
    sb.append("# LogDocMergePolicy inside IndexWriter; see writerRuns().\n");
    String[][] runs = {
      {"logdoc_mf3", "3", "1"}, {"logdoc_mf4", "4", "2"}, {"logdoc_mf10", "10", "1000"},
    };
    int commits = 20;
    sb.append("commits=").append(commits).append('\n');
    sb.append("runs=");
    for (int i = 0; i < runs.length; i++) sb.append(i == 0 ? "" : ",").append(runs[i][0]);
    sb.append('\n');
    for (String[] run : runs) {
      try (Directory d = new ByteBuffersDirectory()) {
        LogDocMergePolicy p = new LogDocMergePolicy();
        p.setMergeFactor(Integer.parseInt(run[1]));
        p.setMinMergeDocs(Integer.parseInt(run[2]));
        p.setNoCFSRatio(0.0);
        IndexWriterConfig cfg = new IndexWriterConfig();
        cfg.setMergePolicy(p);
        cfg.setMergeScheduler(new SerialMergeScheduler());
        cfg.setUseCompoundFile(false);
        String k = "run." + run[0] + ".";
        sb.append(k).append("mergeFactor=").append(run[1]).append('\n');
        sb.append(k).append("minMergeDocs=").append(run[2]).append('\n');
        try (IndexWriter w = new IndexWriter(d, cfg)) {
          int id = 0;
          for (int c = 0; c < commits; c++) {
            for (int j = 0; j < 1 + c % 4; j++) addId(w, Integer.toString(id++));
            w.commit();
            sb.append(k).append("commit.").append(c).append('=').append(leafDocs(w)).append('\n');
          }
          w.forceMerge(2);
          sb.append(k).append("force2=").append(leafDocs(w)).append('\n');
          w.forceMerge(1);
          sb.append(k).append("force1=").append(leafDocs(w)).append('\n');
        }
      }
    }
    Files.writeString(out.resolve("writer_runs.properties"), sb.toString(), StandardCharsets.UTF_8);
  }

  /** Every segment of the latest commit as {@code maxDoc/delCount}, in segment order. */
  static String committedLayout(Directory d) throws IOException {
    List<String> l = new ArrayList<>();
    for (SegmentCommitInfo sci : SegmentInfos.readLatestCommit(d)) {
      l.add(sci.info.maxDoc() + "/" + sci.getDelCount());
    }
    return String.join(",", l);
  }

  /**
   * {@code merge_policies/writer_deletes.properties}: {@code forceMergeDeletes} under {@code
   * LogDocMergePolicy} (mergeFactor 10, so no merge runs on its own). Six commits of five
   * documents with an indexed {@code id}, then the ids in {@code deletes} are deleted by term and
   * committed, then {@code forceMergeDeletes()} and a commit: the layout ({@code maxDoc/delCount}
   * per segment, in order) after the adds, after the deletes and after the forced merge. The
   * deleted ids leave segments 0, 1, 3 and 5 with deletes, so the policy specifies the runs
   * [0,1], [3] and [5], and where each merged segment lands is part of the answer.
   */
  static void writerDeletes(Path out) throws Exception {
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
        .append(Version.LATEST)
        .append('\n');
    sb.append("# forceMergeDeletes under LogDocMergePolicy; see writerDeletes().\n");
    int commits = 6;
    int perCommit = 5;
    int[] deletes = {1, 2, 7, 8, 16, 27};
    sb.append("mergeFactor=10\nminMergeDocs=1\n");
    sb.append("commits=").append(commits).append('\n');
    sb.append("perCommit=").append(perCommit).append('\n');
    StringBuilder del = new StringBuilder();
    for (int i = 0; i < deletes.length; i++) del.append(i == 0 ? "" : ",").append(deletes[i]);
    sb.append("deletes=").append(del).append('\n');
    try (Directory d = new ByteBuffersDirectory()) {
      LogDocMergePolicy p = new LogDocMergePolicy();
      p.setMergeFactor(10);
      p.setMinMergeDocs(1);
      p.setNoCFSRatio(0.0);
      IndexWriterConfig cfg = new IndexWriterConfig();
      cfg.setMergePolicy(p);
      cfg.setMergeScheduler(new SerialMergeScheduler());
      cfg.setUseCompoundFile(false);
      try (IndexWriter w = new IndexWriter(d, cfg)) {
        int id = 0;
        for (int c = 0; c < commits; c++) {
          for (int j = 0; j < perCommit; j++) {
            Document doc = new Document();
            doc.add(new StringField("id", Integer.toString(id++), Field.Store.YES));
            w.addDocument(doc);
          }
          w.commit();
        }
        sb.append("added=").append(committedLayout(d)).append('\n');
        for (int x : deletes) w.deleteDocuments(new Term("id", Integer.toString(x)));
        w.commit();
        sb.append("deleted=").append(committedLayout(d)).append('\n');
        w.forceMergeDeletes();
        w.commit();
        sb.append("forceMergeDeletes=").append(committedLayout(d)).append('\n');
      }
    }
    Files.writeString(
        out.resolve("writer_deletes.properties"), sb.toString(), StandardCharsets.UTF_8);
  }

  /**
   * {@code merge_policies/commits_index/} and {@code commits.properties}: three commits kept by
   * {@link NoDeletionPolicy} -- two documents; a third document and a delete, with user data; a
   * fourth document with other user data -- and what {@code DirectoryReader.listCommits} says of
   * each (generation, segments file, segment count, the sorted file set, user data) plus {@code
   * maxDoc}/{@code numDocs} of {@code DirectoryReader.open(commit)}.
   */
  static void commitsIndex(Path out) throws Exception {
    Path dir = out.resolve("commits_index");
    clean(dir);
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
        .append(Version.LATEST)
        .append('\n');
    sb.append("# DirectoryReader.listCommits over commits_index; see commitsIndex().\n");
    try (Directory d = FSDirectory.open(dir)) {
      IndexWriterConfig cfg = new IndexWriterConfig();
      cfg.setIndexDeletionPolicy(NoDeletionPolicy.INSTANCE);
      cfg.setMergePolicy(NoMergePolicy.INSTANCE);
      cfg.setUseCompoundFile(false);
      try (IndexWriter w = new IndexWriter(d, cfg)) {
        for (String id : new String[] {"a", "b"}) {
          Document doc = new Document();
          doc.add(new StringField("id", id, Field.Store.YES));
          w.addDocument(doc);
        }
        w.commit();
        Document doc = new Document();
        doc.add(new StringField("id", "c", Field.Store.YES));
        w.addDocument(doc);
        w.deleteDocuments(new Term("id", "a"));
        w.setLiveCommitData(Map.of("step", "two", "note", "delete").entrySet());
        w.commit();
        doc = new Document();
        doc.add(new StringField("id", "d", Field.Store.YES));
        w.addDocument(doc);
        w.setLiveCommitData(Map.of("step", "three").entrySet());
        w.commit();
      }
      List<IndexCommit> commits = DirectoryReader.listCommits(d);
      sb.append("count=").append(commits.size()).append('\n');
      for (int i = 0; i < commits.size(); i++) {
        IndexCommit c = commits.get(i);
        String k = "commit." + i + ".";
        sb.append(k).append("generation=").append(c.getGeneration()).append('\n');
        sb.append(k).append("segments_file=").append(c.getSegmentsFileName()).append('\n');
        sb.append(k).append("segment_count=").append(c.getSegmentCount()).append('\n');
        List<String> files = new ArrayList<>(c.getFileNames());
        Collections.sort(files);
        sb.append(k).append("files=").append(String.join(",", files)).append('\n');
        List<String> ud = new ArrayList<>();
        for (Map.Entry<String, String> e : c.getUserData().entrySet()) {
          ud.add(e.getKey() + ":" + e.getValue());
        }
        Collections.sort(ud);
        sb.append(k).append("user_data=").append(String.join(";", ud)).append('\n');
        try (DirectoryReader r = DirectoryReader.open(c)) {
          sb.append(k).append("max_doc=").append(r.maxDoc()).append('\n');
          sb.append(k).append("num_docs=").append(r.numDocs()).append('\n');
        }
      }
    }
    Files.writeString(out.resolve("commits.properties"), sb.toString(), StandardCharsets.UTF_8);
  }

  // ------------------------------------------------ persistent snapshot policy

  static void clean(Path dir) throws IOException {
    if (Files.exists(dir)) {
      try (var files = Files.list(dir)) {
        for (Path f : (Iterable<Path>) files::iterator) Files.delete(f);
      }
    }
    Files.createDirectories(dir);
  }

  /** Commit points and snapshot files only: the part of a listing both engines name alike. */
  static String listing(Directory d) throws IOException {
    List<String> l = new ArrayList<>();
    for (String f : d.listAll()) {
      if (f.startsWith("segments_") || f.startsWith("snapshots_")) l.add(f);
    }
    Collections.sort(l);
    return String.join(",", l);
  }

  static String hex(Directory d, String name) throws IOException {
    try (IndexInput in = d.openInput(name, IOContext.READONCE)) {
      byte[] b = new byte[(int) in.length()];
      in.readBytes(b, 0, b.length);
      StringBuilder sb = new StringBuilder();
      for (byte x : b) sb.append(String.format("%02x", x & 0xff));
      return sb.toString();
    }
  }

  static void addId(IndexWriter w, String id) throws IOException {
    Document doc = new Document();
    doc.add(new StoredField("id", id));
    w.addDocument(doc);
  }

  static IndexWriterConfig snapshotConfig(PersistentSnapshotDeletionPolicy p) {
    IndexWriterConfig cfg = new IndexWriterConfig();
    cfg.setIndexDeletionPolicy(p);
    cfg.setMergePolicy(NoMergePolicy.INSTANCE);
    cfg.setUseCompoundFile(false);
    return cfg;
  }

  /**
   * {@code merge_policies/snapshots_index/}: three commits under a {@link
   * PersistentSnapshotDeletionPolicy} over {@link KeepOnlyLastCommitDeletionPolicy}, generation 1
   * snapshotted once and generation 2 twice, so all three survive and {@code snapshots_N} holds
   * both counts. {@code snapshots.properties} records the listing, the snapshot file's bytes, and
   * what a second writer does on a copy: open (onInit), release generation 1, {@code
   * deleteUnusedFiles}, one more commit.
   */
  static void snapshotIndex(Path out) throws Exception {
    Path dir = out.resolve("snapshots_index");
    clean(dir);
    StringBuilder sb = new StringBuilder();
    sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
        .append(Version.LATEST)
        .append('\n');
    sb.append("# PersistentSnapshotDeletionPolicy over snapshots_index; see snapshotIndex().\n");
    try (Directory d = FSDirectory.open(dir)) {
      PersistentSnapshotDeletionPolicy p =
          new PersistentSnapshotDeletionPolicy(
              new KeepOnlyLastCommitDeletionPolicy(), d, IndexWriterConfig.OpenMode.CREATE);
      try (IndexWriter w = new IndexWriter(d, snapshotConfig(p))) {
        addId(w, "a");
        w.commit();
        p.snapshot();
        addId(w, "b");
        w.commit();
        p.snapshot();
        p.snapshot();
        addId(w, "c");
        w.commit();
      }
      sb.append("written.files=").append(listing(d)).append('\n');
      sb.append("written.snapshots_file=").append(p.getLastSaveFile()).append('\n');
      sb.append("written.snapshots_bytes=").append(hex(d, p.getLastSaveFile())).append('\n');
      sb.append("written.snapshot_count=").append(p.getSnapshotCount()).append('\n');
    }
    Path work = Files.createTempDirectory("gen-snapshots-replay");
    try {
      try (var files = Files.list(dir)) {
        for (Path f : (Iterable<Path>) files::iterator) {
          if (!f.getFileName().toString().equals("write.lock")) {
            Files.copy(f, work.resolve(f.getFileName()));
          }
        }
      }
      try (Directory d = FSDirectory.open(work)) {
        PersistentSnapshotDeletionPolicy p =
            new PersistentSnapshotDeletionPolicy(
                new KeepOnlyLastCommitDeletionPolicy(), d, IndexWriterConfig.OpenMode.APPEND);
        IndexWriterConfig cfg = snapshotConfig(p);
        cfg.setOpenMode(IndexWriterConfig.OpenMode.APPEND);
        try (IndexWriter w = new IndexWriter(d, cfg)) {
          sb.append("open.files=").append(listing(d)).append('\n');
          List<String> gens = new ArrayList<>();
          for (var c : p.getSnapshots()) gens.add(Long.toString(c.getGeneration()));
          Collections.sort(gens);
          sb.append("open.snapshot_gens=").append(String.join(",", gens)).append('\n');
          sb.append("open.snapshot_count=").append(p.getSnapshotCount()).append('\n');
          p.release(1);
          sb.append("release.snapshots_file=").append(p.getLastSaveFile()).append('\n');
          sb.append("release.snapshots_bytes=").append(hex(d, p.getLastSaveFile())).append('\n');
          w.deleteUnusedFiles();
          sb.append("release.files=").append(listing(d)).append('\n');
          addId(w, "d");
          w.commit();
          sb.append("commit.files=").append(listing(d)).append('\n');
        }
      }
    } finally {
      try (var files = Files.list(work)) {
        for (Path f : (Iterable<Path>) files::iterator) Files.delete(f);
      }
      Files.delete(work);
    }
    Files.writeString(out.resolve("snapshots.properties"), sb.toString(), StandardCharsets.UTF_8);
  }

  // ---------------------------------------------------------------- policies

  static MergePolicy build(String spec, Map<String, long[]> ranges, Map<String, SegmentCommitInfo> byName)
      throws Exception {
    String[] parts = spec.split(";");
    Map<String, String> kv = new HashMap<>();
    for (int i = 1; i < parts.length; i++) {
      String[] e = parts[i].split("=", 2);
      kv.put(e[0], e[1]);
    }
    switch (parts[0]) {
      case "logbyte":
        {
          LogByteSizeMergePolicy p = new LogByteSizeMergePolicy();
          log(p, kv);
          if (kv.containsKey("minBytes")) p.setMinMergeMB(mb(kv.get("minBytes")));
          if (kv.containsKey("maxBytes")) p.setMaxMergeMB(mb(kv.get("maxBytes")));
          if (kv.containsKey("maxForcedBytes"))
            p.setMaxMergeMBForForcedMerge(mb(kv.get("maxForcedBytes")));
          return p;
        }
      case "logdoc":
        {
          LogDocMergePolicy p = new LogDocMergePolicy();
          log(p, kv);
          if (kv.containsKey("minDocs")) p.setMinMergeDocs(Integer.parseInt(kv.get("minDocs")));
          return p;
        }
      case "tiered":
        {
          TieredMergePolicy p = new TieredMergePolicy();
          if (kv.containsKey("maxMergedBytes"))
            p.setMaxMergedSegmentMB(mb(kv.get("maxMergedBytes")));
          if (kv.containsKey("floorBytes")) p.setFloorSegmentMB(mb(kv.get("floorBytes")));
          if (kv.containsKey("segsPerTier"))
            p.setSegmentsPerTier(Double.parseDouble(kv.get("segsPerTier")));
          if (kv.containsKey("noCFSRatio"))
            p.setNoCFSRatio(Double.parseDouble(kv.get("noCFSRatio")));
          if (kv.containsKey("maxCFSBytes")) p.setMaxCFSSegmentSizeMB(mb(kv.get("maxCFSBytes")));
          return p;
        }
      case "filter":
        {
          // A FilterMergePolicy over a LogDocMergePolicy built from the rest of the spec.
          LogDocMergePolicy inner = new LogDocMergePolicy();
          log(inner, kv);
          if (kv.containsKey("minDocs")) inner.setMinMergeDocs(Integer.parseInt(kv.get("minDocs")));
          return new FilterMergePolicy(inner);
        }
      case "wrapreverse":
        {
          // OneMergeWrappingMergePolicy reversing each merge's segment order.
          LogDocMergePolicy inner = new LogDocMergePolicy();
          log(inner, kv);
          if (kv.containsKey("minDocs")) inner.setMinMergeDocs(Integer.parseInt(kv.get("minDocs")));
          return new OneMergeWrappingMergePolicy(
              inner,
              m -> {
                List<SegmentCommitInfo> l = new ArrayList<>(m.segments);
                Collections.reverse(l);
                return new MergePolicy.OneMerge(l);
              });
        }
      case "temporal":
        {
          TemporalMergePolicy p = new TemporalMergePolicy().setTemporalField("ts");
          // minThreshold first: it may only shrink below the default maxThreshold.
          if (kv.containsKey("minThreshold"))
            p.setMinThreshold(Integer.parseInt(kv.get("minThreshold")));
          if (kv.containsKey("maxThreshold"))
            p.setMaxThreshold(Integer.parseInt(kv.get("maxThreshold")));
          if (kv.containsKey("baseTime")) p.setBaseTimeInSeconds(Long.parseLong(kv.get("baseTime")));
          if (kv.containsKey("maxWindow"))
            p.setMaxWindowSizeSeconds(Long.parseLong(kv.get("maxWindow")));
          if (kv.containsKey("maxAge")) p.setMaxAgeSeconds(Long.parseLong(kv.get("maxAge")));
          if (kv.containsKey("ratio")) p.setCompactionRatio(Double.parseDouble(kv.get("ratio")));
          if (kv.containsKey("forceDeletesPct"))
            p.setForceMergeDeletesPctAllowed(Double.parseDouble(kv.get("forceDeletesPct")));
          if ("false".equals(kv.get("exponential"))) p.disableExponentialBuckets();
          if (ranges != null) {
            // Package-private: TemporalMergePolicy.setSegmentDateRangeOverrides(Map).
            Class<?> rangeClass =
                Class.forName("org.apache.lucene.index.TemporalMergePolicy$SegmentDateRange");
            Constructor<?> ctor = rangeClass.getDeclaredConstructor(long.class, long.class);
            ctor.setAccessible(true);
            Map<SegmentCommitInfo, Object> overrides = new HashMap<>();
            for (Map.Entry<String, long[]> e : ranges.entrySet()) {
              overrides.put(byName.get(e.getKey()), ctor.newInstance(e.getValue()[0], e.getValue()[1]));
            }
            Method m =
                TemporalMergePolicy.class.getDeclaredMethod("setSegmentDateRangeOverrides", Map.class);
            m.setAccessible(true);
            m.invoke(p, overrides);
          }
          return p;
        }
      default:
        throw new IllegalArgumentException(parts[0]);
    }
  }

  static void log(LogMergePolicy p, Map<String, String> kv) {
    if (kv.containsKey("mergeFactor")) p.setMergeFactor(Integer.parseInt(kv.get("mergeFactor")));
    if (kv.containsKey("maxMergeDocs")) p.setMaxMergeDocs(Integer.parseInt(kv.get("maxMergeDocs")));
    if (kv.containsKey("calibrate"))
      p.setCalibrateSizeByDeletes(Boolean.parseBoolean(kv.get("calibrate")));
    if (kv.containsKey("tsc")) p.setTargetSearchConcurrency(Integer.parseInt(kv.get("tsc")));
    if (kv.containsKey("noCFSRatio")) p.setNoCFSRatio(Double.parseDouble(kv.get("noCFSRatio")));
  }

  static double mb(String bytes) {
    return Long.parseLong(bytes) / (double) (1024 * 1024);
  }

  static String run(Scenario s) throws Exception {
    try (Directory dir = new ByteBuffersDirectory()) {
      SegmentInfos infos = new SegmentInfos(Version.LATEST.major);
      Map<String, SegmentCommitInfo> byName = new LinkedHashMap<>();
      for (Seg seg : s.segments) {
        SegmentCommitInfo sci = commitInfo(dir, seg);
        infos.add(sci);
        byName.put(seg.name, sci);
      }
      Set<SegmentCommitInfo> merging = new LinkedHashSet<>();
      for (String n : s.merging) merging.add(byName.get(n));
      MergePolicy.MergeContext ctx = context(merging);
      MergePolicy policy = build(s.policy, s.ranges, byName);
      String op = s.op;
      if (op.startsWith("useCompoundFile:")) {
        return Boolean.toString(
            policy.useCompoundFile(infos, byName.get(op.substring(16)), ctx));
      }
      MergePolicy.MergeSpecification spec;
      boolean sortGroups = false;
      if (op.equals("findMerges")) {
        spec = policy.findMerges(MergeTrigger.EXPLICIT, infos, ctx);
      } else if (op.equals("findFullFlushMerges")) {
        spec = policy.findFullFlushMerges(MergeTrigger.FULL_FLUSH, infos, ctx);
      } else if (op.startsWith("findForcedMerges:")) {
        Map<SegmentCommitInfo, Boolean> toMerge = new HashMap<>();
        for (Map.Entry<String, Boolean> e : s.toMerge.entrySet()) {
          toMerge.put(byName.get(e.getKey()), e.getValue());
        }
        spec = policy.findForcedMerges(infos, Integer.parseInt(op.substring(17)), toMerge, ctx);
        sortGroups = s.policy.startsWith("temporal");
      } else if (op.equals("findForcedDeletesMerges")) {
        spec = policy.findForcedDeletesMerges(infos, ctx);
      } else {
        throw new IllegalArgumentException(op);
      }
      return render(spec, sortGroups);
    }
  }

  static String render(MergePolicy.MergeSpecification spec, boolean sortGroups) {
    if (spec == null) return "null";
    List<String> groups = new ArrayList<>();
    for (MergePolicy.OneMerge m : spec.merges) {
      List<String> names = new ArrayList<>();
      for (SegmentCommitInfo sci : m.segments) names.add(sci.info.name);
      if (sortGroups) Collections.sort(names);
      groups.add(String.join(",", names));
    }
    if (sortGroups) Collections.sort(groups);
    return String.join("|", groups);
  }

  static MergePolicy.MergeContext context(Set<SegmentCommitInfo> merging) {
    return new MergePolicy.MergeContext() {
      @Override
      public int numDeletesToMerge(SegmentCommitInfo info) {
        return info.getDelCount();
      }

      @Override
      public int numDeletedDocs(SegmentCommitInfo info) {
        return info.getDelCount();
      }

      @Override
      public InfoStream getInfoStream() {
        return InfoStream.NO_OUTPUT;
      }

      @Override
      public Set<SegmentCommitInfo> getMergingSegments() {
        return Collections.unmodifiableSet(merging);
      }
    };
  }

  /** As in GenMergePolicy: {@code sizeInBytes()} is the length of one real file. */
  static SegmentCommitInfo commitInfo(Directory dir, Seg seg) throws IOException {
    String fileName = seg.name + ".dat";
    try (IndexOutput o = dir.createOutput(fileName, IOContext.DEFAULT)) {
      byte[] chunk = new byte[1024];
      long remaining = seg.bytes;
      while (remaining > 0) {
        int n = (int) Math.min(chunk.length, remaining);
        o.writeBytes(chunk, 0, n);
        remaining -= n;
      }
    }
    byte[] id = new byte[StringHelper.ID_LENGTH];
    for (int i = 0; i < id.length; i++) {
      id[i] = (byte) (seg.name.hashCode() >>> (i % 4) * 8);
    }
    SegmentInfo info =
        new SegmentInfo(
            dir,
            Version.LATEST,
            Version.LATEST,
            seg.name,
            seg.maxDoc,
            seg.cfs,
            false,
            Codec.getDefault(),
            Map.of(),
            id,
            Map.of(),
            null);
    info.setFiles(Set.of(fileName));
    return new SegmentCommitInfo(info, seg.delCount, 0, -1, -1, -1, id);
  }

  // --------------------------------------------------------------- scenarios

  static List<Seg> uniform(String prefix, int n, int maxDoc, int del, long bytes) {
    List<Seg> l = new ArrayList<>();
    for (int i = 0; i < n; i++) {
      l.add(new Seg(String.format("%s%02d", prefix, i), maxDoc, del, bytes, false));
    }
    return l;
  }

  static List<Seg> sizes(String prefix, long... bytes) {
    List<Seg> l = new ArrayList<>();
    for (int i = 0; i < bytes.length; i++) {
      l.add(new Seg(String.format("%s%02d", prefix, i), (int) Math.max(1, bytes[i] / 100), 0, bytes[i], false));
    }
    return l;
  }

  static List<Seg> docs(String prefix, int... maxDocs) {
    List<Seg> l = new ArrayList<>();
    for (int i = 0; i < maxDocs.length; i++) {
      l.add(new Seg(String.format("%s%02d", prefix, i), maxDocs[i], 0, maxDocs[i] * 10L, false));
    }
    return l;
  }

  static Map<String, Boolean> all(List<Seg> segs, boolean original) {
    Map<String, Boolean> m = new LinkedHashMap<>();
    for (Seg s : segs) m.put(s.name, original);
    return m;
  }

  static Set<String> set(String... names) {
    return new LinkedHashSet<>(List.of(names));
  }

  static Scenario sc(String name, String policy, String op, List<Seg> segs) {
    return new Scenario(name, policy, op, segs, Set.of(), all(segs, true), null);
  }

  static Scenario sc(String name, String policy, String op, List<Seg> segs, Set<String> merging) {
    return new Scenario(name, policy, op, segs, merging, all(segs, true), null);
  }

  static List<Scenario> scenarios() {
    List<Scenario> s = new ArrayList<>();
    long kb = 1024;

    // ---- LogByteSizeMergePolicy ------------------------------------------------
    String lb = "logbyte;mergeFactor=4;minBytes=" + (8 * kb) + ";maxBytes=" + (512 * kb);
    s.add(sc("logbyte_equal_levels", lb, "findMerges", sizes("_e", 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb)));
    s.add(sc("logbyte_mixed_levels", lb, "findMerges", sizes("_m", 400 * kb, 100 * kb, 100 * kb, 90 * kb, 110 * kb, 30 * kb, 25 * kb, 20 * kb, 22 * kb, 21 * kb, 2 * kb, 1 * kb)));
    s.add(sc("logbyte_below_floor_packs_more", lb, "findMerges", sizes("_f", 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb, 1 * kb)));
    s.add(sc("logbyte_too_large_skipped", lb, "findMerges", sizes("_t", 600 * kb, 600 * kb, 600 * kb, 600 * kb, 10 * kb, 10 * kb, 10 * kb, 10 * kb)));
    s.add(sc("logbyte_merge_capped_by_max", "logbyte;mergeFactor=4;minBytes=1024;maxBytes=" + (100 * kb), "findMerges", sizes("_c", 40 * kb, 40 * kb, 40 * kb, 40 * kb, 40 * kb)));
    s.add(sc("logbyte_merging_blocks_window", lb, "findMerges", sizes("_w", 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb, 20 * kb), set("_w01")));
    List<Seg> deleted = new ArrayList<>();
    for (int i = 0; i < 8; i++) deleted.add(new Seg(String.format("_d%02d", i), 100, i * 12, 20 * kb, false));
    s.add(sc("logbyte_calibrated_by_deletes", lb, "findMerges", deleted));
    s.add(sc("logbyte_not_calibrated", lb + ";calibrate=false", "findMerges", deleted));
    s.add(sc("logbyte_forced_one", lb, "findForcedMerges:1", sizes("_o", 50 * kb, 40 * kb, 30 * kb, 20 * kb, 10 * kb, 5 * kb)));
    s.add(sc("logbyte_forced_three", lb, "findForcedMerges:3", sizes("_o", 50 * kb, 40 * kb, 30 * kb, 20 * kb, 10 * kb, 5 * kb)));
    s.add(sc("logbyte_forced_many_full_merges", "logbyte;mergeFactor=3", "findForcedMerges:2", sizes("_g", 9 * kb, 8 * kb, 7 * kb, 6 * kb, 5 * kb, 4 * kb, 3 * kb, 2 * kb, 1 * kb, 1 * kb)));
    s.add(sc("logbyte_forced_size_limit", lb + ";maxForcedBytes=" + (60 * kb), "findForcedMerges:1", sizes("_l", 10 * kb, 10 * kb, 100 * kb, 10 * kb, 10 * kb, 10 * kb, 100 * kb, 10 * kb)));
    s.add(sc("logbyte_forced_already_merged", lb, "findForcedMerges:1", sizes("_a", 10 * kb)));
    List<Seg> oneDeleted = List.of(new Seg("_x00", 100, 10, 10 * kb, false));
    s.add(sc("logbyte_forced_single_with_deletes", lb, "findForcedMerges:1", oneDeleted));
    List<Seg> part = sizes("_p", 10 * kb, 10 * kb, 10 * kb, 10 * kb, 10 * kb);
    Map<String, Boolean> partMap = new LinkedHashMap<>();
    partMap.put("_p01", true);
    partMap.put("_p02", true);
    s.add(new Scenario("logbyte_forced_subset", lb, "findForcedMerges:1", part, Set.of(), partMap, null));
    List<Seg> fd = new ArrayList<>();
    int[] dels = {0, 5, 3, 0, 0, 7, 1, 2, 4, 6, 1, 0, 9};
    for (int i = 0; i < dels.length; i++) fd.add(new Seg(String.format("_r%02d", i), 100, dels[i], 10 * kb, false));
    s.add(sc("logbyte_forced_deletes_runs", "logbyte;mergeFactor=3", "findForcedDeletesMerges", fd));
    s.add(sc("logbyte_forced_deletes_none", lb, "findForcedDeletesMerges", sizes("_n", kb, kb)));
    s.add(sc("logbyte_full_flush", lb, "findFullFlushMerges", sizes("_ff", 2 * kb, 2 * kb, 2 * kb, 2 * kb, 30 * kb, 30 * kb, 30 * kb, 30 * kb)));
    List<Seg> cfs = new ArrayList<>(sizes("_u", 100 * kb, 5 * kb, 5 * kb));
    s.add(sc("logbyte_use_cfs_small", lb, "useCompoundFile:_u01", cfs));
    s.add(sc("logbyte_use_cfs_large", lb, "useCompoundFile:_u00", cfs));
    s.add(sc("logbyte_tsc_caps_docs", lb + ";tsc=3", "findMerges", uniform("_s", 8, 100, 0, 20 * kb)));

    // ---- LogDocMergePolicy ------------------------------------------------------
    String ld = "logdoc;mergeFactor=3;minDocs=50";
    s.add(sc("logdoc_levels", ld, "findMerges", docs("_q", 1000, 900, 950, 300, 310, 290, 30, 20, 25, 10, 5)));
    s.add(sc("logdoc_below_floor", ld, "findMerges", docs("_b", 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5)));
    s.add(sc("logdoc_max_merge_docs", ld + ";maxMergeDocs=250", "findMerges", docs("_k", 100, 100, 100, 100, 100, 100, 400, 90)));
    s.add(sc("logdoc_forced_max_docs_limit", ld + ";maxMergeDocs=150", "findForcedMerges:1", docs("_z", 100, 30, 30, 200, 30, 30, 30, 30)));
    s.add(sc("logdoc_forced_partial_least_cost", "logdoc;mergeFactor=10", "findForcedMerges:3", docs("_y", 500, 400, 10, 12, 300, 11, 9)));
    s.add(sc("logdoc_default_everything_below_floor", "logdoc", "findMerges", docs("_h", 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100)));

    // ---- FilterMergePolicy / OneMergeWrappingMergePolicy ------------------------
    s.add(sc("filter_delegates_find_merges", "filter;mergeFactor=3;minDocs=50", "findMerges", docs("_q", 1000, 900, 950, 300, 310, 290, 30, 20, 25, 10, 5)));
    s.add(sc("filter_delegates_forced_deletes", "filter;mergeFactor=3", "findForcedDeletesMerges", fd));
    s.add(sc("wrap_reverses_merges", "wrapreverse;mergeFactor=3;minDocs=50", "findMerges", docs("_q", 1000, 900, 950, 300, 310, 290, 30, 20, 25, 10, 5)));
    s.add(sc("wrap_reverses_forced", "wrapreverse;mergeFactor=3", "findForcedMerges:1", docs("_v", 10, 20, 30, 40)));
    s.add(sc("wrap_full_flush", "wrapreverse;mergeFactor=3;minDocs=50", "findFullFlushMerges", docs("_ff", 1, 2, 3, 100, 100, 100)));

    // ---- TieredMergePolicy through the MergePolicy entry points -----------------
    String tp = "tiered;maxMergedBytes=" + (1024 * kb) + ";floorBytes=" + (16 * kb) + ";segsPerTier=4";
    s.add(sc("tiered_full_flush_small_only", tp, "findFullFlushMerges", sizes("_t", 4 * kb, 4 * kb, 4 * kb, 4 * kb, 4 * kb, 40 * kb, 40 * kb, 40 * kb, 40 * kb, 40 * kb)));
    s.add(sc("tiered_full_flush_none", tp, "findFullFlushMerges", sizes("_t", 100 * kb, 100 * kb, 100 * kb, 100 * kb, 100 * kb)));
    s.add(sc("tiered_use_cfs_default_ratio", tp, "useCompoundFile:_c01", sizes("_c", 900 * kb, 50 * kb, 50 * kb)));
    s.add(sc("tiered_use_cfs_over_ratio", tp, "useCompoundFile:_c00", sizes("_c", 900 * kb, 50 * kb, 50 * kb)));
    s.add(sc("tiered_use_cfs_ratio_one", tp + ";noCFSRatio=1.0", "useCompoundFile:_c00", sizes("_c", 900 * kb, 50 * kb, 50 * kb)));
    s.add(sc("tiered_use_cfs_max_size", tp + ";noCFSRatio=1.0;maxCFSBytes=" + (100 * kb), "useCompoundFile:_c00", sizes("_c", 900 * kb, 50 * kb, 50 * kb)));
    List<Seg> tpart = sizes("_s", 50 * kb, 40 * kb, 30 * kb, 20 * kb, 10 * kb);
    Map<String, Boolean> tpartMap = new LinkedHashMap<>();
    tpartMap.put("_s02", true);
    tpartMap.put("_s03", true);
    tpartMap.put("_s04", true);
    s.add(new Scenario("tiered_forced_subset", tp, "findForcedMerges:1", tpart, Set.of(), tpartMap, null));
    s.add(new Scenario("tiered_forced_running", tp, "findForcedMerges:1", tpart, set("_s03"), tpartMap, null));
    Map<String, Boolean> notOriginal = all(tpart, false);
    notOriginal.put("_s04", true);
    s.add(new Scenario("tiered_forced_unlimited_not_original", tp, "findForcedMerges:" + Integer.MAX_VALUE, tpart, Set.of(), notOriginal, null));
    List<Seg> one = List.of(new Seg("_one", 10, 0, 10 * kb, true));
    s.add(new Scenario("tiered_forced_single_compound", tp, "findForcedMerges:1", one, Set.of(), Map.of(), null));
    s.add(sc("tiered_forced_single_in_set", tp, "findForcedMerges:1", one));

    // ---- TemporalMergePolicy (date ranges from overrides) -----------------------
    // Future timestamps: age 0, every window is the base window (1h).
    List<Seg> tsegs = new ArrayList<>();
    Map<String, long[]> tr = new LinkedHashMap<>();
    int[] tdocs = {10, 12, 9, 11, 50, 10, 10, 10, 10, 100, 3};
    long[] toff = {0, 1, 2, 3, 4, 5, HOUR + 1, HOUR + 2, HOUR + 3, 2 * HOUR + 7, 2 * HOUR + 9};
    for (int i = 0; i < tdocs.length; i++) {
      String n = String.format("_tm%02d", i);
      tsegs.add(new Seg(n, tdocs[i], 0, 10 * kb, false));
      tr.put(n, new long[] {FUTURE + toff[i] - 10, FUTURE + toff[i]});
    }
    s.add(new Scenario("temporal_windows", "temporal;exponential=false", "findMerges", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_windows_exponential_age0", "temporal", "findMerges", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_ratio_one", "temporal;exponential=false;ratio=1.0;minThreshold=2;maxThreshold=3", "findMerges", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_high_ratio", "temporal;exponential=false;ratio=5.0", "findMerges", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_merging_excluded", "temporal;exponential=false", "findMerges", tsegs, set("_tm01", "_tm02"), Map.of(), tr));
    // Far past: exponential windows grow to maxWindow; maxAge drops old segments.
    List<Seg> psegs = new ArrayList<>();
    Map<String, long[]> pr = new LinkedHashMap<>();
    for (int i = 0; i < 9; i++) {
      String n = String.format("_tp%02d", i);
      psegs.add(new Seg(n, 10 + i, 0, 10 * kb, false));
      long max = PAST + i * 40L * 24 * HOUR;
      pr.put(n, new long[] {max - HOUR, max});
    }
    s.add(new Scenario("temporal_past_capped_windows", "temporal;maxWindow=" + (100L * 24 * 3600), "findMerges", psegs, Set.of(), Map.of(), pr));
    s.add(new Scenario("temporal_past_too_old", "temporal;maxAge=" + (365L * 24 * 3600), "findMerges", psegs, Set.of(), Map.of(), pr));
    // Forced: every window merges to one segment (windows within maxThreshold).
    s.add(new Scenario("temporal_forced_one", "temporal;exponential=false", "findForcedMerges:1", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_forced_many", "temporal;exponential=false", "findForcedMerges:20", tsegs, Set.of(), Map.of(), tr));
    s.add(new Scenario("temporal_forced_running", "temporal;exponential=false", "findForcedMerges:1", tsegs, set("_tm00"), Map.of(), tr));
    // Forced deletes: distinct ratios, so Java's sort decides the order.
    List<Seg> dsegs = new ArrayList<>();
    int[] ddel = {5, 50, 30, 0, 20, 60, 1, 40, 45, 35, 25};
    for (int i = 0; i < ddel.length; i++) {
      dsegs.add(new Seg(String.format("_tm%02d", i), 100, ddel[i], 10 * kb, false));
    }
    s.add(new Scenario("temporal_forced_deletes", "temporal;exponential=false;maxThreshold=4", "findForcedDeletesMerges", dsegs, Set.of(), Map.of(), tr));
    return s;
  }

  // ------------------------------------------------------ real temporal index

  /**
   * One segment per flush, each with LongPoint("ts") values inside one hour of the far future
   * (milliseconds), plus a seconds-unit segment and a segment without the field; the policy reads
   * the ranges from the points itself.
   */
  static void temporalIndex(Path dir) throws Exception {
    if (Files.exists(dir)) {
      try (var files = Files.list(dir)) {
        for (Path f : (Iterable<Path>) files::iterator) Files.delete(f);
      }
    }
    Files.createDirectories(dir);
    try (Directory d = FSDirectory.open(dir)) {
      IndexWriterConfig cfg = new IndexWriterConfig();
      cfg.setMergePolicy(NoMergePolicy.INSTANCE);
      cfg.setUseCompoundFile(false);
      try (IndexWriter w = new IndexWriter(d, cfg)) {
        // hour 0: 5 segments; hour 1: 3 segments; hour 3: 4 segments, one in seconds.
        long[][] segs = {
          {FUTURE, FUTURE + 10}, {FUTURE + 20, FUTURE + 30, FUTURE + 31}, {FUTURE + 40},
          {FUTURE + 50, FUTURE + 55}, {FUTURE + 60, FUTURE + 61, FUTURE + 62, FUTURE + 63},
          {FUTURE + HOUR + 1}, {FUTURE + HOUR + 2, FUTURE + HOUR + 3}, {FUTURE + HOUR + 9},
          {FUTURE + 3 * HOUR}, {FUTURE + 3 * HOUR + 5}, {FUTURE + 3 * HOUR + 6},
        };
        for (int i = 0; i < segs.length; i++) {
          // Alternate compound segments, so the date range is read through .cfs too.
          w.getConfig().setUseCompoundFile(i % 3 == 1);
          for (long ts : segs[i]) {
            Document doc = new Document();
            doc.add(new LongPoint("ts", ts));
            doc.add(new StoredField("v", ts));
            w.addDocument(doc);
          }
          w.flush();
        }
        // Seconds since the epoch, same window as hour 3.
        Document doc = new Document();
        doc.add(new LongPoint("ts", (FUTURE + 3 * HOUR + 7) / 1000));
        w.addDocument(doc);
        w.flush();
        // No temporal field at all: never bucketed.
        doc = new Document();
        doc.add(new StoredField("v", 1L));
        w.addDocument(doc);
        w.flush();
        w.commit();
      }
      SegmentInfos infos = SegmentInfos.readLatestCommit(d);
      StringBuilder sb = new StringBuilder();
      sb.append("# Generated by fixtures/src/GenMergePolicies.java against Lucene ")
          .append(Version.LATEST)
          .append('\n');
      sb.append("# TemporalMergePolicy over this index, date ranges read from the segments.\n");
      sb.append("segments=");
      List<String> names = new ArrayList<>();
      for (SegmentCommitInfo sci : infos) names.add(sci.info.name + ":" + sci.info.maxDoc());
      sb.append(String.join(",", names)).append('\n');
      String[][] cases = {
        {"natural", "temporal;exponential=false", "findMerges"},
        {"natural_min3", "temporal;exponential=false;minThreshold=3", "findMerges"},
        {"natural_exponential", "temporal", "findMerges"},
        {"forced_one", "temporal;exponential=false", "findForcedMerges:1"},
      };
      Set<SegmentCommitInfo> none = Set.of();
      for (String[] c : cases) {
        MergePolicy p = build(c[1], null, null);
        MergePolicy.MergeSpecification spec;
        boolean sort = false;
        if (c[2].equals("findMerges")) {
          spec = p.findMerges(MergeTrigger.EXPLICIT, infos, context(none));
        } else {
          Map<SegmentCommitInfo, Boolean> toMerge = new HashMap<>();
          for (SegmentCommitInfo sci : infos) toMerge.put(sci, true);
          spec = p.findForcedMerges(infos, 1, toMerge, context(none));
          sort = true;
        }
        sb.append("case.").append(c[0]).append(".policy=").append(c[1]).append('\n');
        sb.append("case.").append(c[0]).append(".op=").append(c[2]).append('\n');
        sb.append("case.").append(c[0]).append(".expected=").append(render(spec, sort)).append('\n');
      }
      Files.writeString(dir.resolve("manifest.properties"), sb.toString(), StandardCharsets.UTF_8);
    }
  }
}
