import org.apache.lucene.document.Document;
import org.apache.lucene.document.DoublePoint;
import org.apache.lucene.document.Field;
import org.apache.lucene.document.FloatPoint;
import org.apache.lucene.document.IntPoint;
import org.apache.lucene.document.LongPoint;
import org.apache.lucene.document.NumericDocValuesField;
import org.apache.lucene.document.StringField;
import org.apache.lucene.index.DirectoryReader;
import org.apache.lucene.index.IndexReader;
import org.apache.lucene.index.IndexWriter;
import org.apache.lucene.index.IndexWriterConfig;
import org.apache.lucene.index.LeafReaderContext;
import org.apache.lucene.index.NoMergePolicy;
import org.apache.lucene.index.SegmentOrder;
import org.apache.lucene.index.SegmentReader;
import org.apache.lucene.search.Sort;
import org.apache.lucene.search.SortField;
import org.apache.lucene.store.Directory;
import org.apache.lucene.store.FSDirectory;
import org.apache.lucene.util.Version;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * {@code segment_order/}: ground truth for {@code crates/lucene-search/src/segment_order.rs}
 * ({@code SegmentOrder.fromSort(sort).reorder(reader)}).
 *
 * <p>An index of five segments, each committed on its own, over one value per document (or none):
 *
 * <pre>
 *   _0: 50, 60        _1: 10, 20, (none)   _2: 100
 *   _3: (none), (none)                     _4: 30, 40, -5
 * </pre>
 *
 * Each value is indexed five ways: {@code dv_skip} (a {@code NumericDocValuesField} with a skip
 * index -- the {@code DocValuesSkipper} path), and as points {@code long_pts}/{@code int_pts}/
 * {@code float_pts}/{@code double_pts} (the {@code PointValues} path). {@code manifest.properties}
 * records, for each sort (field, type, reverse, missing value or none), the segment names of the
 * reordered reader's leaves in order.
 */
public class GenSegmentOrder {
  static final long[][] SEGMENTS = {
    {50, 60}, {10, 20, Long.MIN_VALUE}, {100}, {Long.MIN_VALUE, Long.MIN_VALUE}, {30, 40, -5},
  };

  public static void main(String[] args) throws Exception {
    Path out = Path.of(args[0]).resolve("segment_order");
    Path indexDir = out.resolve("index");
    if (Files.exists(indexDir)) {
      try (var files = Files.list(indexDir)) {
        for (Path f : (Iterable<Path>) files::iterator) Files.delete(f);
      }
    }
    Files.createDirectories(indexDir);
    try (Directory d = FSDirectory.open(indexDir)) {
      IndexWriterConfig cfg = new IndexWriterConfig();
      cfg.setMergePolicy(NoMergePolicy.INSTANCE);
      cfg.setUseCompoundFile(false);
      try (IndexWriter w = new IndexWriter(d, cfg)) {
        int id = 0;
        for (long[] segment : SEGMENTS) {
          for (long v : segment) {
            Document doc = new Document();
            doc.add(new StringField("id", Integer.toString(id++), Field.Store.YES));
            if (v != Long.MIN_VALUE) {
              doc.add(NumericDocValuesField.indexedField("dv_skip", v));
              doc.add(new LongPoint("long_pts", v));
              doc.add(new IntPoint("int_pts", (int) v));
              doc.add(new FloatPoint("float_pts", v + 0.5f));
              doc.add(new DoublePoint("double_pts", v + 0.25));
            }
            w.addDocument(doc);
          }
          w.commit();
        }
      }
      StringBuilder sb = new StringBuilder();
      sb.append("# Generated by fixtures/src/GenSegmentOrder.java against Lucene ")
          .append(Version.LATEST)
          .append('\n');
      sb.append("# sort.N = field;TYPE;reverse;missing (a comparable long, or - for none)\n");
      sb.append("# order.N = the reordered reader's segment names\n");
      List<String[]> sorts = new ArrayList<>();
      for (String reverse : new String[] {"false", "true"}) {
        sorts.add(new String[] {"dv_skip", "LONG", reverse, "-"});
        sorts.add(new String[] {"dv_skip", "LONG", reverse, "0"});
        sorts.add(new String[] {"dv_skip", "LONG", reverse, "1000"});
        sorts.add(new String[] {"dv_skip", "LONG", reverse, "-1000"});
        sorts.add(new String[] {"long_pts", "LONG", reverse, "-"});
        sorts.add(new String[] {"long_pts", "LONG", reverse, "1000"});
        sorts.add(new String[] {"long_pts", "LONG", reverse, "-1000"});
        sorts.add(new String[] {"int_pts", "INT", reverse, "-"});
        sorts.add(new String[] {"int_pts", "INT", reverse, "1000"});
        sorts.add(new String[] {"float_pts", "FLOAT", reverse, "-"});
        sorts.add(new String[] {"float_pts", "FLOAT", reverse, "1000.5"});
        sorts.add(new String[] {"double_pts", "DOUBLE", reverse, "-"});
        sorts.add(new String[] {"double_pts", "DOUBLE", reverse, "-1000.25"});
        sorts.add(new String[] {"absent", "LONG", reverse, "-"});
        sorts.add(new String[] {"id", "STRING", reverse, "-"});
      }
      try (DirectoryReader r = DirectoryReader.open(d)) {
        sb.append("count=").append(sorts.size()).append('\n');
        for (int i = 0; i < sorts.size(); i++) {
          String[] s = sorts.get(i);
          SortField sf = sortField(s);
          IndexReader reordered = SegmentOrder.fromSort(new Sort(sf)).reorder(r);
          List<String> names = new ArrayList<>();
          for (LeafReaderContext ctx : reordered.leaves()) {
            names.add(((SegmentReader) ctx.reader()).getSegmentName());
          }
          sb.append("sort.").append(i).append('=').append(s[0]).append(';').append(s[1])
              .append(';').append(s[2]).append(';').append(comparableMissing(s)).append('\n');
          sb.append("order.").append(i).append('=').append(String.join(",", names)).append('\n');
        }
      }
      Files.writeString(
          out.resolve("manifest.properties"), sb.toString(), StandardCharsets.UTF_8);
    }
  }

  static SortField sortField(String[] s) {
    boolean reverse = Boolean.parseBoolean(s[2]);
    SortField sf;
    switch (s[1]) {
      case "LONG" -> {
        sf = new SortField(s[0], SortField.Type.LONG, reverse);
        if (!s[3].equals("-")) sf.setMissingValue(Long.parseLong(s[3]));
      }
      case "INT" -> {
        sf = new SortField(s[0], SortField.Type.INT, reverse);
        if (!s[3].equals("-")) sf.setMissingValue(Integer.parseInt(s[3]));
      }
      case "FLOAT" -> {
        sf = new SortField(s[0], SortField.Type.FLOAT, reverse);
        if (!s[3].equals("-")) sf.setMissingValue(Float.parseFloat(s[3]));
      }
      case "DOUBLE" -> {
        sf = new SortField(s[0], SortField.Type.DOUBLE, reverse);
        if (!s[3].equals("-")) sf.setMissingValue(Double.parseDouble(s[3]));
      }
      default -> sf = new SortField(s[0], SortField.Type.STRING, reverse);
    }
    return sf;
  }

  /** The missing value as the comparable long {@code SegmentOrder} works in, or {@code -}. */
  static String comparableMissing(String[] s) {
    if (s[3].equals("-")) return "-";
    return switch (s[1]) {
      case "FLOAT" ->
          Long.toString(
              org.apache.lucene.util.NumericUtils.floatToSortableInt(Float.parseFloat(s[3])));
      case "DOUBLE" ->
          Long.toString(
              org.apache.lucene.util.NumericUtils.doubleToSortableLong(Double.parseDouble(s[3])));
      default -> s[3];
    };
  }
}
